magfest/ubersystem

uber/config.py
uber/site_sections/summary.py
uber/templates/summary/index.html

Per registration's request, the summary page now lists all badges in the system we've promised to attendees. It does this by counting all badges of a type as long as it is New or Complete status.

Add "Badge counts by type" to Summary

---

uber/site_sections/registration.py
uber/templates/registration/form.html

Volunteers are using the badge status dropdown to bypass important system checks, so we're making it readonly for anyone who is not a department head of Registration.

Make Badge Status read-only during the event

---

uber/site_sections/emails.py
uber/templates/emails/emails_by_kickin.html

Our swadges team needs to get the emails of everyone who's kicked in at least at the Supporter level. This report lets you choose the kick-in level you get the emails of, plus has an optional option to only pull emails from attendees who agreed to receive marketing emails.

Add Emails By Kickin level report

---

uber/config.py
uber/site_sections/preregistration.py
uber/templates/emails/mivs/videoless_studio.txt

- use c.EVENT_YEAR for everything instead of c.YEAR
- calc c.EVENT_YEAR in the right order in order to use it
semi-high priority because confirmation emails should contain the year, but, I don't think we should interrupt the launch for this.

fix year config line 

---

uber/configspec.ini
uber/templates/guest_checklist/band_merch_deadline.html
uber/templates/guest_checklist/guest_merch_deadline.html
uber/templates/guest_checklist/merch_deadline.html

Fixes the following error we're seeing on servers that don't have rock island enabled:
```
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 631, in respond
self._do_respond(path_info)
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 400, in with_timing
return func(*args, **kwargs) …
```

Fixes c.ROCK_ISLAND default settings

---

tests/uber/models/test_merch.py
uber/models/attendee.py
uber/site_sections/signups.py

If one's shirt size was marked, shirt_info_marked was only truthy if either the person in question wasn't staff or if their second_shirt was set -- this meant that for events without 2 shirts, staffers would never be able to move past the 'shirt' step. This fixes that by checking the event's config, much like the shirt template does.
This should fix #3170.

Stop always requiring second_shirt for staff

---

uber/templates/emails/reg_workflow/attendee_confirmation.html

As reported by a MAGStock attendee, the confirmation email is confusing, because it includes addons (like food) in the list with donation swag. It looks like food is received as part of the kickin level rather than being an additional cost.

Fixes swag list confusion

---

uber/config.py

The server would attempt to redefine c.ROCK_ISLAND_GROUPS even if the list was empty, resulting in a 500 error. Checking for truthiness wasn't sufficient, presumably since the list technically has an item in it.

Fix bug when no rock island groups are configured

---

requirements.txt

Residue requires at least 2017.2 but we were pinning to an older version. It doesn't seem to affect anything right now, but better to update it.

Update pytz to not conflict with residue

---

INSTALL.manually.md

Users need to install libcap-dev to follow the alternate manual installation instructions. Additionally, sideboard requires Python3 now.

Add missing info to sqlite instructions

---

requirements.txt

Celery 4.1.1 depends on kombu 4.2.0, which fixes hung connections.
See related celery issue:  https://github.com/celery/celery/issues/4296

Fixes #3197: Updates to celery 4.1.1

---

uber/templates/registration/form.html

Partially fixes https://github.com/magfest/ubersystem/issues/3136 - specifically, it allows payment methods to be displayed/edited in the full attendee view. Previously, these were only able to be set on the "Recent At-the-Door Registrations" page.
Use case: Someone registered last month, didn't pay, and showed up at-event needing to pay. Their account is no longer in the "recent registrations" page, so the staffer pulls up their main info page, and enters in their payment. With this new form, they can also set the payment type.
Not done here, but on my todo: Add a "last 4 digits of CC" field to model/attendee, so that Stripe refunds can be more easily done. (That field will also be exposed here, as well as on the "recent regs" page)
(Changing back to "Payment Method" removes the …

Add dropdown for payment_method in attendee form

---

uber/templates/static_views/dealer_reg_not_open.html

Found in https://github.com/MidwestFurryFandom/mff-rams-plugin/pull/55 -- the date in this template will print in a strange format without the jinja2 tag.

Format dealer start date properly

---

development-defaults.ini
uber/configspec.ini

Without these, a default initialization (during `./env/bin/sep reset_uber_db`) produces:
```
config: panels_room config problem: Ignoring 'PANELS_1' because it was not also found in [[event_location]] section.
config: panels_room config problem: Ignoring 'PANELS_2' because it was not also found in [[event_location]] section.
config: panels_room config problem: Ignoring 'PANELS_3' because it was not also found in [[event_location]] section.
config: panels_room config problem: Ignoring 'PANELS_4' because it was not also found in [[event_location]] section.
config: panels_room config problem: Ignoring 'CONCERTS' because it was not also found in [[event_location]] section.
config: panels_room config problem: Ignoring 'CHIPTUNES' because it was not also found in [[event_location]] section. …
```

Add defaults to event_location in development-defaults.ini

---

uber/api.py

This change updated the API Version to 1.0, since we made a breaking change to the API Authentication and code written for the 0.1 version is universally broken.
This change also updated the variable YEAR to EVENT_YEAR, tracking an earlier change to the config object.  It both returns the new variable as EVENT_YEAR and returns the legacy variable as YEAR for compatibility with APIs that rewrite their auth code.

Update API Version and fix config.info call

---

requirements.txt
uber/site_sections/schedule.py
uber/templates/schedule_common.html

Allows admins to export the current version of the schedule into an iCal file, suitable for/tested with Google Calendar and iCloud Calendar. Admins may filter the schedule by location before exporting to get just a few locations in the file.

Add iCal file export

---

tests/uber/test_utils.py
uber/utils.py

This is kind of an emergency patch, so I am going to merge it now.

Fixes the convert_to_absolute_url() function to accept absolute urls and root relative urls

---

uber/api.py

The fields `BADGE_PRICE`, `BADGES_SOLD`, and `REMAINING_BADGES` are currently openly exposed on `/uber/registration/stats`. This was historically for MAGBot, as well as part of [MAGFest's Website](http://super.magfest.org).
Once MAGBot and the MAGFest website no longer rely on `/uber/registration/stats` it should be removed.

Add fields from registration/stats to secure with API

---

uber/config.py

This adds a 0.5 shift weight option to uber.
Further work would be ideal to set 1.0 as the default weight in the frontend, however I don't understand how the initial defaults are set in the session data.

Add 0.5 shift weight

---

uber/templates/emails/dealers/application.html

Using the text from MAGDEV-253, we add a block telling dealers to seriously, really, do not buy a badge.

Tell dealers not to buy their own badges

---

alembic/versions/9d90d3d538c6_add_volunteer_waiver_agreement.py
uber/automated_emails.py
uber/configspec.ini
uber/custom_tags.py
uber/models/attendee.py
uber/site_sections/signups.py
uber/templates/emails/signups/volunteer_agreement.txt
uber/templates/signups/volunteer_agreement.html
uber/templates/signups/volunteer_agreement_item.html

Also adds a reminder email reminder to STOPs workflow
Backstory: Magwest is in California which has more legal regulations than you can shake a stick at.   So, our Cali lawyers were pretty adamant about us having an explicit agreement that volunteers agreed to spelling out some legalese.
Last year, this was something we had volunteers sign physically on a piece of paper, but the legal crew was OK with this being a part of the volunteer checklist.
---
Tech notes:
All of this is controlled by a new config option, c.VOLUNTEER_AGREEMENT_ENABLED.  By default, this feature is disabled except by events that explicitly turn it on (i.e. MAGwest).
Though the waiver text is currently MAGWest-specific, I felt it was a better idea to include it here instead of in the magwest plugin because other …

Add volunteer agreement item to volunteer checklist

---

uber/configspec.ini

I realized our default settings were not optimal because we had to override them everywhere.
See https://github.com/magfest/production-config/pull/450

Sets better volunteer checklist defaults

---

tests/uber/models/test_attendee.py
uber/models/attendee.py
uber/site_sections/groups.py

Fixes MAGDEV-254.
One of the entire points of base_badge_price was to allow us to store what the badge WOULD have cost if it were a regular attendee badge... a purpose we completely undermined by putting discounted and overridden prices in the calculation we used for base_badge_price. Most noticeably, this led us to charging dealers whose apps had been rejected only the dealer price, not the attendee price at the time they applied. We've instead moved ALL discounts and overrides to calculate_badge_cost, so they get applied to any price except the "base" price.
Thank goodness for unit tests.

Make base_badge_price actually store correct price

---

uber/configspec.ini
uber/server.py
uber/site_sections/accounts.py
uber/utils.py

This will allow us to set `c.PATH = ""` and clean up the URLs returned to users for the new deployment. It shouldn't affect any of our legacy deployments.

Adds cherrypy mount path config setting to distinguish the cherrypy mount point from the URL path

---

uber/models/email.py
uber/templates/macros.html

Only uses fixed-width font when looking at an unrendered template. Always shows whitespace how the recepient will see it.

Better email preview rendering.

---

tests/uber/conftest.py
tests/uber/site_sections/test_guest_admin.py
tests/uber/test_schedule.py
uber/models/__init__.py

This should radically improve performance under heavy load.
**Note**: the page load times below are representative instances of the typical page load times for the given request. I repeated the requests many times, and chose examples that were near the median value of the sample set.
* 12 new sessions
* Page loads in ~0.2 secs
```
NEW SESSION: <sqlalchemy.orm.session.Session object at 0x7f2508224828>
NEW SESSION: <sqlalchemy.orm.session.Session object at 0x7f252864ceb8>
CLOSING SESSION: <sqlalchemy.orm.session.Session object at 0x7f252864ceb8>
NEW SESSION: <sqlalchemy.orm.session.Session object at 0x7f252864c358>
NEW SESSION: <sqlalchemy.orm.session.Session object at 0x7f25280afba8>
NEW SESSION: <sqlalchemy.orm.session.Session object at 0x7f25082c7cf8>
CLOSING SESSION: …
```

Adds database session caching

---

alembic/versions/651b1ea070d4_creates_index_on_attendee_badge_status_.py
test-defaults.ini
tests/uber/models/test_config.py
uber/config.py
uber/configspec.ini
uber/custom_tags.py
uber/models/attendee.py

The `BADGES_SOLD` estimate is hidden behind a `badges_sold_estimate_enabled` feature flag. This pull request also removes `HARDCORE_OPTIMIZATIONS_ENABLED` in favor of the new estimate.
I am going to merge this now, because I need to deploy it on the load testing system. However, @kitsuta and @EliAndrewC, I would love a pull request review!
Please hit me up with any questions or concerns, and I'll be happy to revise or revert things 😄

Adds efficient estimation for BADGES_SOLD

---

uber/templates/regform.html

This adds a different CSS class to each merch tier icon, so we can easily target them to add retina icons.

Support for retina merch tier icons on the prereg page

---

uber/config.py

We use `CAN_SUBMIT_MIVS_ROUND_TWO` to control whether or not the "Game Build Information" form is available to studios. However, the property was `True` even if round two hadn't started yet, causing the form to appear too early. This fixes that.
Note that anyone with indie admin access will still be able to see the form, just to give our admins more flexibility.

Stop non-MIVS admins submitting game info BEFORE round two

---

uber/decorators.py
uber/site_sections/preregistration.py

Steps to reproduce bug:
1. Fill out prereg form for a single attendee badge
2. From the overview page, click "Edit" to change the badge details
3. Change the badge from a single attendee to a group badge and click "Update"
4. **NOTE**: On the overview page, both the original single attendee badge and the new group badge will both be listed
5. Pay for the badges
6. The following error will be raised:
```
File "/srv/reggie/plugins/uber/uber/decorators.py", line 356, in charge
return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken)
File "/srv/reggie/plugins/uber/uber/site_sections/preregistration.py", line 385, in prereg_payment
session.commit()  # paranoia: really make sure we lock in marking taking payments in the database
File …
```

Fixes bug where an unpaid prereg is switched from a group badge to a single badge or vice-versa

---

tests/uber/test_barcode.py
uber/api.py
uber/barcode/__init__.py
uber/server.py
uber/templates/api/reference.html

This pull request changes the API so it uses HTTP status codes where appropriate (404 Not Found, 403 Forbidden, 500 Server Error).
Furthermore, this pull request normalizes the format of returned errors. Previously, some methods would return 200 OK with an embedded error message in the result object:
```
200 OK
{
"id": null,
"jsonrpc": "2.0",
"result": [
{
"error": "No attendee found with Badge #217"
}
]
}
```
```
404 Not Found
{
"id": null,
"jsonrpc": "2.0",
"error": {
"code": -32603,
"message": "No attendee found with Badge #217"
}
}
```

Normalizes API error format and uses HTTP status codes where appropriate

---

uber/site_sections/preregistration.py

Steps to reproduce:
1. Fill out prereg form for a **single attendee**
2. From overview page, click "Edit"
3. Change reg to **group**, click update
4. From overview page, click "Edit"
3. Change reg back to **single attendee**, click update
5. On overview page, not the **Total Cost** is incorrect

Fixes prereg total cost calculation if attendee removes themselves from group

---

uber/templates/preregistration/badge_refund.html
uber/templates/static_views/styles/main.css

Implements the following:
If refunds are not enabled, hide the button altogether
If refunds _will be_ enabled, hide the button until they become available
If refunds _were_ enabled, but are _no longer_ available, the button should be disabled with an explanation why
Also fixes the Bootstrap tooltip for Safari users.

Hide self-service refund button under certain conditions

---

uber/models/attendee.py

What's happening is that our CRUD model stuff is considering `age_discountable_badge_types` a regular attribute, so it's trying to set it as a property.

Adds underscore to age_discountable_badge_types so it isn't considered a model attribute

---

uber/site_sections/hotel_assignments.py

also filters out refunded badges

Uses non-blank email instead of non-blank first_name for hotel info criteria

---

.gitignore
uber/static/analytics/analytics.css
uber/static/analytics/attendance.js
uber/templates/graphs/index.html

Allows the attendance graph to resize between 480px - 1024px. Wraps graph in scrolling element.

Makes attendance graph responsive

---

requirements.txt

Looks like cherrypy moved around some of it's internals. Here's the error we're receiving on new deployments:
```
File "/root/.pythonstartup.py", line 24, in <module>
import sideboard
File "/home/vagrant/reggie-formula/reggie_install/sideboard/__init__.py", line 9, in <module>
import sideboard.server
File "/home/vagrant/reggie-formula/reggie_install/sideboard/server.py", line 11, in <module>
from sideboard.jsonrpc import _make_jsonrpc_handler
File "/home/vagrant/reggie-formula/reggie_install/sideboard/jsonrpc.py", line 6, in <module>
from cherrypy.lib.jsontools import json_decode
ImportError: cannot import name 'json_decode'
```
For breaking changes, see here and possibly elsewhere: https://github.com/cherrypy/cherrypy/commit/5f8d4358cfc7580bdb22e471dd1e4 …

Pins cherrypy to v17.3.0 – v18.* has breaking changes

---

uber/templates/preregistration/group_members.html

Fixes https://jira.magfest.net/browse/MAGDEV-231. We still keep the link to the group leader's badge because I'm pretty sure that's they only way they can get to it -- in any case, we generally assume the group leader is the one on this page.

Only allow access to group leader's badge from group page

---

alembic/versions/bf427bc2a7f2_add_new_mivs_game_scoring_columns.py
uber/models/mivs.py
uber/site_sections/mivs_judging.py
uber/templates/mivs_admin/game_results.html
uber/templates/mivs_admin/index.html
uber/templates/mivs_judging/game_review.html
uber/templates/mivs_judging/index.html
uber/templates/static_views/mivs_scoring.html

Fixes https://jira.magfest.net/browse/MAGDEV-295.
The new judging page has a Scoring section:
The scoring explanation is a static_views page, so formatting is limited. It pops up in a new window, so in fullscreen Chrome it ends up looking like this:
The scoring breakdown is shown to judges on their games page alongside the averaged score:
Finally, the three scores are also on the game results page:

Add new MIVS scoring categories

---

uber/templates/mits_applications/index.html

A template mistake would have prevented any MITS team from actually adding any games. This fixes that so testing can commence.

Allow MITS teams without games to add a game

---

uber/models/mits.py

We don't actually make sure that MITS teams upload image files to their pictures table, so some teams were breaking their own applications by accident. This should allow us to fail more gracefully.

Gracefully handle non-image images for MITS

---

uber/models/mits.py
uber/site_sections/mits_applications.py
uber/templates/mits_admin/index.html
uber/templates/mits_applications/index.html

Fixes https://jira.magfest.net/browse/MAGDEV-341. Also fixes a bug I ran into where the MITS admin index page would break if a studio didn't have any primary contacts. Also also fixes the panel and showcase columns, which were getting automatically set to False when they should start out as None.

Make all MITS application steps clearly opt-outable

---

alembic/versions/da22d6a6407c_add_fields_for_mivs_checklist.py
uber/automated_emails.py
uber/config.py
uber/configspec.ini
uber/custom_tags.py
uber/menu.py
uber/models/mivs.py
uber/site_sections/guest_admin.py
uber/site_sections/guests.py
uber/site_sections/mivs_admin.py
uber/site_sections/mivs_applications.py
uber/templates/emails/mivs/mivs_checklist_new_item.txt
uber/templates/emails/mivs/mivs_checklist_open.txt
uber/templates/emails/mivs/mivs_checklist_reminder.txt
uber/templates/guest_admin/mivs_info.html
uber/templates/guests/index.html
uber/templates/guests/mivs_core_hours.html
uber/templates/guests/mivs_discussion.html
uber/templates/guests/mivs_hotel_space.html
uber/templates/guests/mivs_selling_at_event.html

Based off the Guest Groups checklists, this is a fully-custom checklist for MIVS Studios to fill out. Fixes https://jira.magfest.net/browse/MAGDEV-298. Requires a [mivs_checklist] section in our config to match the code.
Two of the steps described in https://jira.magfest.net/browse/MAGDEV-298 are not in this, as the MIVS team isn't ready to set them up yet -- those will be in another PR.
We also need the email templates for the three types of emails added here: mivs_checklist_open.txt, mivs_checklist_new_item.txt, and mivs_checklist_reminder.txt. They can be changed to HTML if desired. That should be done in this PR.
This is also dependent on https://jira.magfest.net/browse/MAGDEV-330, so I can actually test the emails coded.

Add a pre-event checklist for MIVS Studios

---

uber/models/attendee.py
uber/site_sections/preregistration.py
uber/templates/preregistration/badge_refund.html

Fixes https://jira.magfest.net/browse/MAGDEV-352. Also deletes any shifts assigned to a staffer when they abandon their badge. Also also adds a check to prevent abandoning a badge that's been picked up.

Allow staffers to abandon their badge

---

uber/site_sections/mivs_admin.py

Whoops! Fixes https://jira.magfest.net/browse/MAGDEV-363.

Export MIVS checklist completion as separate rows

---

uber/models/attendee.py
uber/templates/summary/food_restrictions.html

Fixes https://jira.magfest.net/browse/MAGDEV-358.
We used to collect vegetarian and vegan information from attendees separately. In cases where an attendee checked both boxes, we would forcibly remove the "Vegetarian" option from reports, much like we add the "No Pork" option to anyone who is vegetarian or vegan.
At some point in the past, we changed it so c.VEGAN was the only option (now called "Vegetarian/Vegan"), but during the refactor we must have changed all instances of `c.VEGETARIAN` to `c.VEGAN`, leading to this completely pointless line that removes the "Vegan" option from... anyone who has checked the "Vegan" option.

Stop removing everyone's FoodRestriction setting if it is vegan

---

uber/models/attendee.py

Fixes https://jira.magfest.net/browse/MAGDEV-350. It seems we were intentionally removing public shifts from volunteers who were assigned to more departments than the maximum, but this was unintuitive. We still change some behavior based on the max departments, but we only do so if the volunteer hasn't requested 'Anywhere' in their department requests.

Always let volunteers see public shifts if they want to

---

uber/site_sections/mits_applications.py

I found that the issue was that we were checking for the logged-in team but then not actually logging them in!  So the waiver form would pull up, but then when you tried to submit the waiver it would fail.  We weren't testing it far enough to the point of submitting.
I'm going to merge this in and deploy right away because Janus just sent out a bunch of emails telling people to retry.

emergency fix for the MITS waiver

---

uber/config.py
uber/configspec.ini
uber/decorators.py
uber/models/group.py
uber/models/guests.py
uber/models/mits.py
uber/models/mivs.py
uber/models/panels.py
uber/site_sections/summary.py
uber/templates/export/index.html
uber/templates/summary/guidebook_exports.html

Fixes https://jira.magfest.net/browse/MAGDEV-309. Many of our exports have to be hardcoded just because our models don't necessarily mirror how we want to display information in Guidebook, so this is about the most flexible/easily extendable way we can do this now. In the future, if we want to add a new model, we simply have to add it to the list in config.py, define the appropriate properties on that model, and in some cases update the export page handler to select the right models for us.

Add extendable Guidebook export using Guidebook's "custom list" template

---

development-defaults.ini
test-defaults.ini

**WARNING**: I'm not sure if this is overridden in production's config (as I think I don't have access to prod's config? I don't know how deployment works, hah). When merging this, please check to make sure it isn't.
Background: the at-door payment line is sometimes 15-30 minutes long, and pre-reg is usually instant or a couple minutes. I get really sad whenever someone waits 30 minutes to use the at-door table, when they could have just immediately picked up their badge in the prereg line.

Add prereg line message to at-door registration

---

uber/templates/emails/mivs/accepted/2019_DecemberUpdate.txt

The `primary_contact` property no longer exists, so we need to use the new property for emails `primary_contact_first_names`.

Use new primary_contact_first_names property

---

alembic/versions/72f97bdad2fa_add_mits_panel_application_table.py
alembic/versions/b574c0577253_add_separate_mits_showcase_scheduling_.py

See my comment at https://github.com/magfest/ubersystem/issues/3412#issuecomment-450712780 for a full explanation of this bug.
This fix is to adjust the ``down_revision`` values so that they cause the migrations to be executed in the proper order.

fixes #3412

---

uber/automated_emails.py
uber/site_sections/summary.py
uber/templates/guest_admin/index.html
uber/templates/summary/volunteer_hours_overview.html

Fixes https://jira.magfest.net/browse/MAGDEV-404, and addresses several other related requests for data, by allowing admins to view all volunteers based on a few filters. We then use the DataTables Button extension to export only the filtered data.
Also fixes https://github.com/magfest/ubersystem/issues/3372, albeit in a bit of a lazy way.

Add Volunteer Hours Overview page with dynamic filtering and export

---

uber/templates/regform.html

Fixes https://jira.magfest.net/browse/MAGDEV-406.
Prereg pages (specifically `['/preregistration/form', '/preregistration/post_form', '/preregistration/register_group_member']`) now show a message explaining that kick-in tiers are no longer available:
Since this isn't the first time attendees have confused the 'extra donation' box with kick-ins, I've also added that bold note under the box on every attendee-facing page, including the at-door page.
I also went ahead and fixed https://jira.magfest.net/browse/MAGDEV-369 while I was at it -- the shirt tier now has a message about its deadline just like the supporter tier.

Tell attendees explicitly that kick-ins are no longer available

---

alembic/versions/6c5cf22429e2_add_mivs_judge_status_and_game_.py

This is what's causing our migrations to give an error when we deploy via magbot.  I've tested this fix locally on Vagrant as well as onsite, so I'm gonna merge this in and deploy.

final fix to db migration order

---

uber/server.py

It might have been better to do this in nginx, but I'm more familiar with Python and time's a factor.  At least I left good docs!

redirect /uber/x to /x automatically

---

uber/templates/attractions/events.html

We need to be in at-con mode to check staff in, but it's not reasonable to require a badge number from attendees until the event is actually scheduled to start -- they can't necessarily get their badge until around then.

Allow attendees to sign up for attractions until c.EPOCH

---

development-defaults.ini
uber/site_sections/registration.py

This was confusing attendees more than it was helping. I thought I'd already done this when reg decided to stop using it, but apparently not!

Remove "taking an unassigned group badge" from at-door payment methods

---

uber/models/attendee.py

The effect of this line was that, if we were in at-con mode, attendees could suddenly sign up for any shift not restricted to a role. This has caused problems.

Stop making non-public shifts public in at-con mode

---

uber/model_checks.py
uber/models/tracking.py

This is a quick-and-dirty fix, and in the long run we'll probably need something better.
We pin some of our dependencies to an exact version, and others we merely specify a minimum version.  SQLAlchemy is one of the ones that we DON'T pin to an exact version - perhaps we should.  Because it looks like there was recently a small change to their class hierarchy.  Their API didn't change, but anyone relying on certain ``isinstance`` behaviors (as we are) would have been bitten.
In particular, our ``Model.to_dict()`` methods include all of our columns by default but exclude ``AssociationProxy`` objects:
https://github.com/magfest/sideboard/blob/master/sideboard/lib/sa/_crud.py#L1279
It looks like SQLAlchemy has recently changed how association proxies work such that association lists are no …

fixed dev environment

---

uber/models/attendee.py

The legal_last_name function was actually returning nothing if legal_name was one word. This should fix it appropriately.

Actually return last name if legal name is one word

---

uber/templates/regform.html

This just means it's easier to keep things standard on the reg form.

Force swag icons to be 50px wide regardless of source image size

---

uber/templates/regform.html

The prereg form was telling people both the shirt and supporter deadlines, even if they were the same. This re-implements https://github.com/magfest/magstock/commit/28913c1855dcf66e462fe1593117a7e779068acd by adding some conditionals to the text we print. Note that you can set the shirt deadline to be blank if you want only the supporter deadline to be printed.

Mention shirt and supporter deadlines only when appropriate

---

alembic/versions/4c9ae1c0db43_set_guestgroup_event_id_to_null_when_.py
uber/models/guests.py
uber/models/panels.py

Fixes https://jira.magfest.net/browse/MAGDEV-451 -- confusingly, we actually override SQLAlchemy's default behavior for cascading, so by default our object relationships cascade deletes. Yikes (TM)

Stop deleting GuestGroups when an associated Event is deleted

---

uber/models/promo_code.py

Fixes https://jira.magfest.net/browse/MAGDEV-453. We were naively replacing the expiration datetime's time, which works for initially setting the expiration date, but when we saved an 11:59pm PDT datetime to the database it was saving as a 6:59am time the next day in UTC... which we were then naively replacing, thus effectively moving the expiration date forward every time we saved the PromoCode. Now we first convert it back to the local timezone if necessary.

Account for timezones when adjusting promo code expiration dates

---

uber/site_sections/preregistration.py

Fixes https://jira.magfest.net/browse/MAGDEV-500. This bug has been in the code base for, quite possibly, the entire time we've had groups. We've just always happened to have a dealer badge price that could modulo into the attendee group price correctly.

Compare new group badges' cost to the correct base price

---

uber/configspec.ini
uber/models/group.py
uber/site_sections/preregistration.py
uber/templates/groupform.html
uber/templates/preregistration/group_members.html

Fixes https://jira.magfest.net/browse/MAGDEV-491. We now use max_dealers as the actual maximum number of badges, unless it is not set, in which case we default to letting them have the number of tables they order plus 1. The dealer application page handles both cases.
This also improves the UI around dealers self-purchasing badges. If a dealer was maxed out on badges, the form would still offer to let them purchase badges, but would not let them select a number.
Now, if a dealer is either at their maximum badge count or does not have `can_add` set, they see:
If `can_add` is set and they have badges remaining that they can purchase, they see:

Use the max_dealers property if it is set

---

uber/configspec.ini
uber/site_sections/registration.py
uber/templates/registration/check_in_form_base.html

This is mainly to fix https://jira.magfest.net/browse/MAGDEV-170 -- page handlers cannot be overridden in plugins, and we can't mark booleans without the page handler being aware of them -- but I made it a feature flag because many events under a certain size dole out merch at check-in.

Add config flag for marking merch pickup at check-in

---

uber/templates/registration/new_base.html

No MAGFest event needs or can use this, so we now hide it using a close approximation of events that would want it (those that personalize badges onsite)

Stop showing Badge Printed Name during At-Door Checkin

---

uber/api.py

took 1 minute to get it to clone the repo, then another 30 to re-clone it twice while discovering how to fork it so I can actually upload and do a pull request.  Please let me know if I need to change how I do this for general process or convenience or whatever.

added public_id to returned fields in API AttendeeLookup class

---

alembic/versions/8f8419ebcf27_replace_second_shirt_column_with_more_.py
tests/uber/models/test_merch.py
uber/configspec.ini
uber/models/attendee.py
uber/site_sections/signups.py
uber/site_sections/summary.py
uber/templates/emails/shifts/schedule.html
uber/templates/signups/shirt_size.html

The way we handled staff and event shirts was not flexible enough for MAGWest's purposes. I've replaced our `second_shirt` column with `num_event_shirts`, which allows events to add configuration for any number of shirts along with c.SHIRTS_PER_STAFFER. For example, an event can now have three shirts per staffer and let them replace either one or two (or none) of them, using just config. Or, in MAGWest's case, an event can have just 1 shirt per staffer but still allow them to select between that shirt and an event shirt.
We do still assume that staffers (and not volunteers) are the only ones who get this selection, but this can be overridden using two properties (which you'll see shortly with MAGWest). The template for selecting shirt type/size is also still using Super MAGFest text, …

Retool how Staff and Event shirts interact to allow more flexibility

---

alembic/versions/4c9ae1c0db43_set_guestgroup_event_id_to_null_when_.py
alembic/versions/6c5cf22429e2_add_mivs_judge_status_and_game_.py
uber/templates/base.html
uber/templates/fields/attendee.html
uber/templates/preregistration/confirm.html
uber/templates/preregistration/register_group_member.html
uber/templates/registration/form.html

Fixes https://jira.magfest.net/browse/MAGDEV-534. Also (hopefully) fixes any other 'reset' bug for this form, except for `got_swadge` (which is supposedly not meant to be permanent so I'm not adding new code) and any columns that come from event plugins (we'll need to fix those in their respective plugins).
To explain what's going on: checkboxes always pass either a string, or no value at all -- we tell our page handler to process them by telling it which fields are boolean, so it can interpret a value as "Yes" and a lack of value as "No." However, we were telling it to check every boolean column that an Attendee object could have, and many of those values were not actually represented on our admin form. Now they are.

Stop resetting ANY boolean values on the admin reg form

---

uber/templates/fields/attendee.html
uber/templates/preregistration/confirm.html

Same as https://github.com/magfest/ubersystem/pull/3474, but for the non-restricted booleans that would be reset on someone's confirmation page.

Stop resetting boolean values on confirmation page

---

uber/config.py
uber/configspec.ini

Fixes https://jira.magfest.net/browse/MAGDEV-540. Now events can set shared_kickin_stocks to False to sell tiers individually.

Add 'Shared Kickin Stocks' config option for selling out kick-ins

---

uber/configspec.ini
uber/site_sections/summary.py

We want to change the number of blank staff badges that get added to the personalized export -- this adds a config option so we can.

Add blank_staff_badges config for personalized_badges_zip

---

uber/api.py
uber/site_sections/staffing_admin.py
uber/templates/staffing_admin/import_shifts.html

This is key in executing https://jira.magfest.net/browse/MAGDEV-545 -- before, you could only import departments with their roles if you ALSO imported all their shifts, which obviously would be undesirable in a lot of cases. This also adds a bulk import feature to make it easier on us. The bulk import will either transfer roles to departments with the same name, or create a new department if one doesn't exist (it will not import shifts, as doing so causes a 504 timeout). You can also now choose to create a new department when importing individual departments.
What we'll want to do for Super 2020 is to remove all the 'default' departments (in fact, I'll be filing another PR soon to remove the config that populates those departments, as they just cause confusion) and use the bulk import …

Add ability to import departments without shifts

---

uber/site_sections/staffing_admin.py
uber/templates/staffing_admin/import_shifts.html

The real reason the bulk import didn't seem to be working is that the way I'd coded the page, the parameters for the API token and server would only exist if an import had previously been done (as it places those values in the URL). This updates those fields automatically so that the bulk import actually works.

Fix bug where bulk import wasn't working under certain circumstances

---

uber/site_sections/panels.py
uber/templates/panels/index.html

This is the last thing we need for Super 2020 panels launch! This text was provided by legal and comes in the form of the two checkboxes at the bottom here:

Add data privacy and CoC agreement to panel application

---

uber/templates/mivs/game_build_info.html
uber/templates/mivs/index.html
uber/templates/mivs/studio.html

Updates the help text for "link to game" and removes a reference to round one deadlines that we didn't catch earlier. Also, the game submission button will now appear for MIVS admins, whereas before it would only appear after the actual MIVS state date. Fixes https://jira.magfest.net/browse/MAGDEV-557.

Minor text fixes for MIVS 2020

---

alembic/versions/2cd71c52889e_remove_access_column_from_admin_accounts.py

When upping a fresh vagrant environment, I ran into an issue with this migration - it depends on a MIVS migration rather than the migration that adds the ``access_group`` table, so I changed this to use the correct ordering.

fixed migration order

---

uber/automated_emails.py
uber/config.py
uber/configspec.ini
uber/templates/emails/mivs/game_submitted.txt
uber/templates/emails/mivs/results_almost_ready.txt
uber/templates/emails/mivs/studio_registered.txt
uber/templates/mivs_admin/game_results.html

The old link redirects to a 404 on our website, and since I had to edit the Game Submitted email anyway I updated it here.

Add new FAQ link to and remove reference to Round Two from MIVS emails

---

alembic/versions/2cd71c52889e_remove_access_column_from_admin_accounts.py

Reverts magfest/ubersystem#3507.
I can't deploy to any servers right now because of this change, and I need to update the kick-in tiers ASAP.

Revert "fixed migration order"

---

uber/templates/emails/shifts/schedule.html

MAGWest emails won't run without this template fix, which is already in master.

Fix email template for West

---

tests/uber/conftest.py
tests/uber/models/test_attendee.py
tests/uber/models/test_badge_funcs.py
tests/uber/models/test_config.py

Our unit tests still don't work, but it's good to try to keep them updated a little bit.

Remove references to Supporter badge in unit tests

---

uber/site_sections/staffing_admin.py

There was a merge conflict and staffing_admin.py ended up without an import for our ajax decorator, which it needs for the server to run.

Import @ajax for staffing_admin

---

uber/automated_emails.py

We discovered two important things today:
1. Two lambda functions taken together are always truthy
2. The pending emails page does not always correctly report how many emails it has or wants to send out, which can trick testers into thinking emails are working correctly when they are not.
This gets around the first point by making two lambda functions into one.

Stop sending emails to everyone on the planet

---

uber/automated_emails.py

We can't turn off emails that are automatically approved, so just to be safe we're going to require approval for these emails again.

Set all vendor emails to need approval

---

uber/models/attendee.py

We don't actually charge PAID_BY_GROUP attendees for their badge, but our receipt item breakdown was including a line item for the badge's cost. This fixes that.

Don't generate a badge receipt item for paid by group badges

---

uber/models/attendee.py
uber/site_sections/preregistration.py
uber/templates/dealer_admin/form.html
uber/templates/fields/group.html
uber/templates/preregistration/form.html
uber/templates/preregistration/group_members.html
uber/utils.py

Also fixes a UX bug where your group buyer badge would turn back into an attendee badge if you got any validation errors. Unfortunately, I was not able to fix a bug where the attendee's personal badge wasn't being recorded as a receipt item -- instead, we're relying on amount_paid_override to keep the system from asking attendees for money it shouldn't ask them for.

Fix 500 error when buying two promo code groups

---

uber/site_sections/promo_codes.py
uber/site_sections/reg_admin.py
uber/templates/fields/attendee.html
uber/templates/promo_codes/index.html

Fixes https://jira.magfest.net/browse/MAGDEV-591 and fixes https://jira.magfest.net/browse/MAGDEV-513 by adding new views to the promo code page to filter out group codes and show only overused codes. Also adds the ability to remove promo codes from attendees if the current admin has access to reg_admin

Add new views to promo code page and allow removing codes from attendees

---

uber/model_checks.py
uber/templates/fields/group.html

Attempts to fix https://jira.magfest.net/browse/MAGDEV-554 and some related bugs. Admins were unable to actually update dealer addresses, and some attendees somehow entered an invalid region/state when applying as a dealer. This fixes the former and adds a model check to try to capture the latter.

Fix Dealer address bugs

---

uber/site_sections/hotel_reports.py

We have a hotel cutoff date for people who are preregistering, but comped attendees don't have control over when their badges are added to the system, so we want the flexibility to include them in the export even if they were added 'late' (especially this year). Altering the export is easier and safer than trying to hand-edit people's registered dates.

Include comped attendees in hotel export regardless of reg date

---

uber/models/guests.py

This makes it so we only check off the 'badges' step in guest checklists if all badges in the guest's group are not unassigned AND not placeholder.

Take placeholder badges into account for guest groups

---

uber/site_sections/preregistration.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-600. Yet another instance of a variable being over-set by our modular fields... I should probably do an audit of these or just rename them all or something.

Pass through promo code correctly on prereg form

---

uber/config.py
uber/models/admin.py
uber/site_sections/accounts.py
uber/site_sections/schedule.py
uber/templates/emails/accounts/new_account.txt

Fixes https://jira.magfest.net/browse/MAGDEV-594. Due to how we were retrieving accounts' access sets, we were using the currently-logged-in admin's access set in the new account email, rather than the new account's access set.

Stop using new accounts' creator's access set in new account email

---

README.md

A discussion about licensing of the project made us realize that we weren't actually putting the license front and center, so this fixes that!

Add license badge to main README

---

uber/automated_emails.py

Fixes https://jira.magfest.net/browse/MAGDEV-640 by changing the guest badge confirmation email to only send to people with Guest badges who either do not have a group or whose group has a GuestGroup of type c.GUEST.

Send guest badge confirmation email only to guests

---

uber/templates/guest_admin/index.html

You have the ability to 'unmark' a guest group as a band or guest, but you can't undo that, which is likely what led to https://jira.magfest.net/browse/MAGDEV-639. This removes that button so we don't accidentally 'lose' any more band or guest groups, since restoring their guest-group-ness currently requires developer intervention.

Remove ability to unmark guest groups as guest groups

---

uber/templates/emails/mivs/video_fixed.txt

https://jira.magfest.net/browse/MAGDEV-646. A MIVS email was trying to access a config variable that we'd removed earlier.

Fix MIVS game fixed email

---

uber/api.py

Fixes https://jira.magfest.net/browse/MAGDEV-627. We hadn't updated the API account-based access when we changed the access groups to be multi-choice.

Fix 500 API error

---

uber/site_sections/dealer_admin.py

Reg/Marketplace has decided that dealers should get a group discount because applying and registering in a group are mutually exclusive. This applies that discount.

Apply group discount to declined dealers

---

uber/site_sections/dealer_admin.py

While testing the prior PR I realized that attendees don't actually get set to invalid status, which appears to be because they aren't actually added to the session (only the replacement attendee is). This should fix that.

Actually update existing attendees when converting dealer badges

---

uber/site_sections/dealer_admin.py

Reverts magfest/ubersystem#3569 -- this just broke the conversion script more. I'll have to fix this locally instead of via the web editor.

Revert "Actually update existing attendees when converting dealer badges"

---

uber/site_sections/accounts.py

The query is causing the homepage to 504 timeout on production, so we're going to disable it until we can fix that.

Emergency disable query for homepage

---

uber/decorators.py
uber/models/__init__.py
uber/templates/base.html
uber/templates/fields/attendee.html

The creator property I added would fail if an admin wasn't logged in at the time of badge creation, causing _any_ badge purchase to fail. This fixes that, fixes some JS issues, and lets admins see badges despite the broken viewable_attendees function.

Emergency fix for preregistration

---

uber/models/attendee.py

Fixes https://jira.magfest.net/browse/MAGDEV-673, which was happening if you tried to add more than one badge to a group at a time. Relationships in SQLAlchemy are weird.

Fix 500 error on creating multiple badges

---

uber/custom_tags.py
uber/site_sections/registration.py

Our form_link custom tags were still using the old link for attendees, and the page parameter wasn't filling in properly. Also, saving the attendee would return an error.

Fix lingering errors with attendee form

---

uber/site_sections/dept_checklist.py

Apparently the method to get an attendee object I was using only works if you have already viewed an attendee checklist page first, which meant this was passing my tests earlier. I think this method is the correct one?

Fix department checklist hotel approval page render

---

uber/models/__init__.py

The relationship for GuestGroups to Groups is actually called 'guest' but I misnamed it in a few references because I forgot. This broke updating attendees in some cases.

Use correct name for guest group relationship

---

uber/api.py

I previously added EVENT_TIMEZONE to the list returned by config.info.  Upon trying to actually use it, the JSON encoder returns an error because this is a TZINFO object and it doesn't know how to handle it.  This change adds code to convert this to a string equivalent before JSON encoding.

Fix API config.info timezone

---

uber/model_checks.py

Attendees stopped being able to register as groups because we added a badge-type-based check, which would break on our special "pseudo group" and "pseudo dealer" badge types. This fixes that, and attempts to guard against similar bugs in our model checks.

Stop model checks from breaking on special prereg badge types

---

uber/configspec.ini
uber/static/angular-apps/signups/possible.html
uber/static/angular-apps/signups/taken.html
uber/templates/fields/attendee.html
uber/templates/staffing/shifts.html
uber/templates/static_views/howToStaff.html

Fixes https://jira.magfest.net/browse/MAGDEV-671 by making the URL for staffer comps configurable. The default is the old internal URL.

Add VOLUNTEER_PERKS_URL

---

uber/templates/macros.html

Fixes part of https://jira.magfest.net/browse/MAGDEV-706 -- in certain circumstances our checkbox macro would always pass through a hidden input with the values "true" or "false," which isn't handled correctly by most of our page handlers.

Fix 500 error with read-only checkboxes

---

uber/automated_emails.py
uber/models/mivs.py
uber/templates/mivs_admin/index.html

Fixes https://jira.magfest.net/browse/MAGDEV-708. I had the polarity reversed on this automated email, so it was waiting until three days _after_ a studio's confirmation deadline before telling them to confirm their game before the deadline. Also adds the confirmation deadline to the list of indie games for better visibility.

Send MIVS reminder email 3 days BEFORE deadline

---

uber/config.py
uber/configspec.ini
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-710 by altering how prereg_shirt_opts works. We can now populate it with only the shirt sizes we want to offer on the prereg page, which lets us preserve existing special shirt sizes without continuing to offer them.
If someone has a special shirt size that's no longer available, they'll see this message:

Add separate list of shirt sizes available for preorder

---

uber/templates/dept_checklist/hotel_eligible.html

Tuber doesn't have a page for the "hotel eligible" checklist step, but we don't want it to show the old hotel system, which would have the wrong information. This is just a placeholder for when we add the page to Tuber later.

Add placeholder code for linking to Tuber in dept head checklist

---

uber/models/mits.py

Fixes https://jira.magfest.net/browse/MAGDEV-687. For some reason using c.PATH now generates broken urls, so these URLs need to be relative instead.

Fix MITS file URLs

---

uber/automated_emails.py

The new email was one indent too far, which caused it to be registered more than once, which apparently prevents the server from starting. Whoops.

Fix MIVS Versus email

---

uber/config.py
uber/decorators.py
uber/site_sections/schedule.py

Fixes https://jira.magfest.net/browse/MAGDEV-733 by adding a new decorator that makes our previously-public schedule pages show only if hide_schedule is turned off or you are currently logged in as an admin with read access to the requested page.

Use c.HIDE_SCHEDULE for public schedule pages

---

alembic/versions/ad26fcaafb78_replace_w9_upload_with_checkbox.py
uber/configspec.ini
uber/model_checks.py
uber/models/guests.py
uber/site_sections/group_admin.py
uber/site_sections/guest_reports.py
uber/site_sections/guests.py
uber/templates/band_admin/checklist_info.html
uber/templates/guest_admin/checklist_info.html
uber/templates/guest_checklist/taxes_deadline.html
uber/templates/guest_reports/rock_island.html
uber/templates/mivs_admin/checklist_info.html

Fixes https://jira.magfest.net/browse/MAGDEV-645. Requires secure_document_url to be set in secret config. Also fixes several other bugs I found while testing this, including one that prevented changing guest group metadata.

Use secure document portals for guest W9s

---

uber/templates/emails/shifts/dept_checklist.txt

Fixes https://jira.magfest.net/browse/MAGDEV-736. All department head checklist items use the same base template and pull from config. We added text that only applies to one of the steps without realizing this, so now we hide that text for steps it doesn't apply to.

Hide approval for setup/teardown on irrelevant emails

---

uber/config.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-729. I had the if-else chain backwards, so that if we sold out of a kick-in tier everything under it would become unavailable. We want to lock off tiers ABOVE the tier that sold out.

Fix non-shared kick-in stocks

---

alembic/versions/53b71e7c45b5_add_fields_for_mivs_show_info_checklist_.py
uber/model_checks.py
uber/models/mivs.py
uber/site_sections/guests.py
uber/site_sections/mivs.py
uber/templates/dept_checklist/placeholders.html
uber/templates/guests/mivs_handbook.html
uber/templates/guests/mivs_show_info.html
uber/templates/mivs/show_info.html

This fixes https://jira.magfest.net/browse/MAGDEV-628 -- we actually already had a page that combined the info MIVS studios need to update for their games and studio, so we used that instead of the pre-acceptance game and studio editing pages. To enable the step we'll simply need to add it to config.
Also includes a file I missed in the last pull request.

Add "Show Info" step to MIVS Checklist

---

uber/config.py

Fixes https://jira.magfest.net/browse/MAGDEV-746 by updating how it checks for panels_admin access.

Fix panel POC dropdown

---

uber/site_sections/guest_reports.py

Fixes https://jira.magfest.net/browse/MAGDEV-374 by adding a 'guest type' column to the checklist info CSV. The CSV also already outputs only guest groups that the admin has access to.

Add guest type to guest checklist CSV

---

uber/config.py
uber/site_sections/accounts.py

We were using two separate, slightly different chunks of complex code to introspect the application and build a list of site sections and pages. We were also not caching the site map, causing it to take multiple seconds to load.
This combines the two methods into one cached property that returns all the data structures we need to build both the Site Map and the list of pages and sections for the Access Groups page. This is safe to make fully cached, since the app's structure does not change dynamically.

Refactor site map and access groups page list

---

uber/config.py

We had partly configured our system to show kick-in stocks separately, but I missed an important part of that -- how we count the kick-in stocks! This should re-enable our t-shirt and supporter tiers. Fixes https://jira.magfest.net/browse/MAGDEV-752.

Actually use non-shared kickin stocks

---

uber/site_sections/mivs.py

MIVS studios need to edit their screenshots while completing their checklist, but the system was redirecting them to the studio login page, which isn't editable after the deadline. We now automatically log in a studio once they load their show_info page -- this isn't perfect, because passing around a direct link will still end up redirecting them, but it's 80% of what we need.

Automatically log in MIVS studios completing their checklist

---

uber/api.py

I don't know off the top of my head if this is needed to actually use the new API class, but at the very least it should put it on our API help page.

Actually register new ScheduleLookup API

---

uber/site_sections/group_admin.py
uber/site_sections/registration.py
uber/templates/base.html
uber/templates/fields/group.html
uber/templates/group_admin/dealers.html

Part of fixing https://jira.magfest.net/browse/MAGDEV-660 -- deleting declined dealers was causing issues, so now we just hide them on the Dealers tab instead. Also adds a button to show them, some frontend fixes for the decline function not firing properly, and some quality of life updates to fix things I noticed while testing my changes.

Hide declined dealers by default

---

uber/site_sections/dealer_admin.py
uber/templates/dealer_admin/waitlist.html

I forgot to test the mass version of declining and converting dealers -- it was redirecting to the wrong page and the warning said we would delete dealers.

Fix the mass decline-and-convert function

---

uber/decorators.py
uber/site_sections/schedule_reports.py

I thought we had an issue to track this but I can't find it. Our guidebook exports require a selected model, which means you need to use a page to choose which export to get, but the direct links were being displayed on the sitemap. This fixes that.

Remove POST-only Guidebook exports from sitemap

---

uber/custom_tags.py
uber/templates/registration/attendee_shifts.html

Fixes https://jira.magfest.net/browse/MAGDEV-726. Also adds a `new_window` parameter to our form_link custom tag so you can selectively make form links open in a new window.

Update links to jobs in attendee_shifts

---

uber/models/__init__.py
uber/site_sections/group_admin.py

Fixes https://jira.magfest.net/browse/MAGDEV-778. We were checking for an admin's permission to create badges whenever we used assign_badges, but that's used in prereg functions too... like groups buying more badges. Whoops.

Only check if admins can create group badges on admin page

---

uber/site_sections/registration.py

I'd made a change a while back to support processing fees through the at-door registration page, but what we need instead is a link to send attendees. We shouldn't redirect them to an admin-only page when they're done paying.

Make arbitrary charges return to the form by default

---

uber/config.py
uber/configspec.ini
uber/decorators.py
uber/site_sections/preregistration.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-761. Fixes https://jira.magfest.net/browse/MAGDEV-765. We now use the stocks system, which counts actual badges promised, to limit sales -- this works better for selling out on-site, and will also work for selling out during prereg. Probably.

Replace max_badges with attendee_badge stocks

---

uber/site_sections/preregistration.py

Having a free preregistration without a promo code is practically impossible, but we should still make it work just in case.

Make free preregistrations work without a promo code

---

uber/site_sections/preregistration.py
uber/templates/fields/attendee.html
uber/templates/preregistration/register_group_member.html

Fixes https://jira.magfest.net/browse/MAGDEV-789. When someone would claim an unassigned group badge, even if that badge was 'staffing' the form would default to an unchecked staffing checkbox. People should never be able to opt out of staffing when claiming a Contractor or Staff badge in a group, so we hide the checkbox and force staffing to be true.

Preserve unassigned group badges' staffing status

---

uber/templates/accounts/bulk.html

Our Javascript for /accounts/bulk was apparently depending on a class I removed from checkboxes because it seemed pointless. Whoops.

Add 'cbox' class back to /accounts/bulk

---

uber/configspec.ini
uber/models/__init__.py
uber/site_sections/accounts.py
uber/templates/accounts/attendees.html
uber/templates/accounts/homepage.html
uber/templates/base.html

Fixes https://jira.magfest.net/browse/MAGDEV-793. This was initially going to just be an at-the-con flag, but then I realized that would mean no one without registration access could see non-volunteers during the event. Instead I replaced the old giant load with a set of buttons to load attendees by type.
(buttons are hidden if you do not have access to view that type of attendee)

Stop loading viewable attendees on the homepage by default

---

uber/templates/attractions/events.html
uber/templates/base.html

Fixes https://jira.magfest.net/browse/MAGDEV-803 -- $.val() parses a field's value as an integer if it can, which was removing leading zeroes from zipcodes, causing it to not match the attendee. Also fixes an as-of-yet-uncaught bug where the badge-number attraction sign-up field was being hidden from attendees.

Capture leading 0 in attraction sign-ups

---

uber/model_checks.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-509. We send some emails, including a confirmation email, while at-con so it doesn't make sense to stop requiring a valid email address. Also fixes/works around a bug where the email confirmation box wasn't being validated if the attendee didn't type anything in it

Require email during and after the event

---

uber/site_sections/preregistration.py
uber/templates/preregistration/index.html

Now that group_name has been defined as a property, we can't use it here to add on an extra attribute to the attendee or it will throw a 500 error.

Use a property name besides 'group_name'

---

uber/templates/fields/attendee.html

I was seeing this on the admin form:
I assumed it was a bug, but it turned out that the labeling was just confusing, so I adjusted the label.

updated staff merch label on admin form

---

uber/templates/registration/check_in_form_base.html

The badge number form field on the check-in form wasn't autofocusing consistently, because the ``autofocus`` element only works if there's not already something selected.  I also made the Enter key attempt to check-in the form.

fixed focus and enter key behavior on check-in form

---

uber/config.py
uber/site_sections/registration.py

A previous PR at https://github.com/magfest/ubersystem/pull/3671 changed where we set our onsite station number, but there were 2 old references to that page.  I updated those references.
I also fixed a bug where it was counting unpaid badges as having been promised.  Vicki and I discussed this in Google Hangouts and I let the ``#reg-heads`` channel know about it.

minor tweaks to onsite workflow

---

uber/site_sections/attractions.py

We have a button that says "Sign up without badge #" which is visible before the event begins, but then on the backend we check for ``c.AT_THE_CON``, which gets set to True the day before.
This fix makes things consistent and allows signups tonight.

allow attraction signups without a badge before the event begins

---

uber/templates/fields/attendee.html

It's very difficult to create a new attendee if we don't render the emergency contact info fields but DO require emergency contact info.

Show emergency contact info on reg form for new attendees

---

uber/site_sections/attractions.py
uber/templates/attractions/features.html

Previously the features would display in an arbitrary order.  Now it's less arbitrary.  This was done at the suggestion of the autographs department.

attraction features now sort according to the start time of their first event

---

uber/models/attendee.py
uber/site_sections/registration.py
uber/templates/registration/form.html

Fixes https://github.com/magfest/ubersystem/issues/3703. Normally we zero out a badge number if an attendee doesn't need one. This doesn't make sense for at-the-con, when we may need to assign badge numbers ahead of time. So if we're at the con, we don't zero out the number. We also don't auto-assign badge numbers -- we throw an error if you try to check in someone without one. Also also, we no longer make "save and check-in" the default action when you press enter on the form.

Allow adding numbers to attendees during at-con mode

---

uber/config.py
uber/utils.py

Fixes https://jira.magfest.net/browse/MAGDEV-809 by making the 'default' view be "All" departments. This isn't ideal, since there's something wrong with that page, but it's better than someone not being able to use the link at all.

Stop redirecting to the first assigned dept for dept views

---

uber/site_sections/registration.py
uber/templates/registration/attendee_shifts.html

There were three issues here:
1) The jquery filter was being run before the DOM elements were loaded, so I put it inside of a ``$(function () { })`` block.  This is the reason why the JSON was being displayed.
2) The ``loadForm`` function doesn't exist on the "old-school" shifts page, so I added an if-check for that.
3) Because of this, the other forms on that page would show a success message but not update their contents, so I've fixed this to basically do a page refresh with the success message.

MAGDEV-766: fixed nonshift hour form

---

alembic/versions/07f752ec9b7c_rename_amount_paid_and_amount_refunded_.py
alembic/versions/2cd71c52889e_remove_access_column_from_admin_accounts.py
alembic/versions/c36659e7f238_add_rehearsal_checklist_step_for_bands.py
alembic/versions/e372e4daf771_add_many_to_many_tables_for_stripe_.py

The uber plugin's migrations have more heads than a goddamn hydra, and some of them break each other if not applied in the necessary order. These changes made `alembic update heads` work in one shot for me.

Populate depends_on so `alembic update heads` works from scratch

---

uber/automated_emails.py

We used to closed group registration way before we closed normal prereg, like a week before the event starts.  So our automated emails about "last chance to claim badges" assumes that there's no way we'd already be in at-the-con mode.  This fixes that.

allow last chance email to go out

---

uber/site_sections/attractions_admin.py

There's JavaScript on the attractions check-in page to convert encrypted barcodes into badge numbers, but for some reason it's not working. We now all process encrypted barcodes in the check-in page handler so we can still use the barcodes.

Allow attraction check-ins with encrypted badge numbers

---

uber/models/tracking.py

If you try to update an attraction time when attendees are signed up, it throws a 500 error. We can't figure out why that error is happening in the middle of the event, so now we bypass the error instead.

Work around 500 error on attractions

---

uber/site_sections/registration.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-815. We stop basing it on department and instead use the reg_admin and security_admin site sections to control access, which is more consistent with how the rest of the system works.

Update who can change badge status at the con

---

uber/models/attendee.py
uber/site_sections/registration.py

In order to provide better flexibility and clarity for Watched attendees, we change the "can't checkin" message to display either:
1. A message saying the attendee must talk to security, if the attendee has a matching watchlist entry OR they have no special regdesk instructions.
2. The special regdesk instructions, if the attendee does not have a matching watchlist entry but does have special regdesk instructions.
3. Both, if the attendee has both a matching watchlist entry and special regdesk instructions.
We also now always show watched attendees in search.

Update check-in message for attendees in Watched status

---

uber/templates/attractions_admin/checkin.html

We still were having trouble scanning the encrypted badge number barcodes, we're hoping this will solve it.
Note that this means all interpretation is done on the server, so the text you submit won't look like a barcode. See below.

Remove clientside barcode interpretation

---

uber/site_sections/attractions.py
uber/templates/attractions_macros.html

It seems we weren't doing anything to process encrypted barcodes for attendees' badge numbers during attraction signups -- now we do.

Process encrypted badge numbers for attraction sign-ups

---

uber/templates/registration/index_base.html

We're not totally sure people will be checking their emails enough to get a warning about the number of badges left in time, so now we also display a warning on the search page. We only display it for reg admins because it requires polling the database for number of attendee badges.

Add badges left warnings for reg admins

---

uber/tasks/registration.py

We had the 'to' and 'from' parameters reversed, so we were trying to send *from* multiple addresses instead of to them. Whoops!

Fix badge warning email sender

---

uber/automated_emails.py

There were still some tabs in the email file, which prevented the server for running. Also, any email that we intend to send in post-con mode needs `allow_post_con` to be set.

Make MIVS email not crash the server and also sendable post-con

---

uber/models/attendee.py
uber/site_sections/budget.py
uber/templates/budget/cost_breakdown.html

Receipt items turned out to not be quite what we want because of the unexpected ways attendees can switch out payments (e.g. pay $10 for a donation, then reduce it to $0 but add a kick-in level and pay the difference), so we're adding a 'snapshot' style report that breaks the costs down as the system understands them at report run.

Add itemized cost breakdown report

---

alembic/versions/0b4ad67a27be_add_purchased_items_for_cost_tracking.py
uber/models/attendee.py
uber/site_sections/budget.py
uber/templates/budget/cost_breakdown.html

Attendees' costs were always calculated on the fly, which made a report on all attendees' costs effectively impossible. Now we record these costs via a JSONB column that we can pull much more efficiently.

Add cost breakdown to Attendee table for better performance

---

alembic/versions/07f752ec9b7c_rename_amount_paid_and_amount_refunded_.py
alembic/versions/2cd71c52889e_remove_access_column_from_admin_accounts.py
alembic/versions/c36659e7f238_add_rehearsal_checklist_step_for_bands.py
alembic/versions/e372e4daf771_add_many_to_many_tables_for_stripe_.py

Reverts magfest/ubersystem#3707.
I can't run migrations on the prod database, and this PR is the most likely culprit.

Revert "Populate depends_on so `alembic update heads` works from scratch"

---

uber/models/attendee.py
uber/templates/budget/cost_breakdown.html

Our payment_method field used to just be for at-door attendees, but we now would prefer it to be accurate for everyone. This adds the relevant presave adjustment. This also fixes a bug on the cost breakdown page.

Update payment method for preregistered attendees

---

uber/models/attendee.py
uber/site_sections/budget.py
uber/templates/budget/attendee_cost_breakdown.html
uber/templates/budget/group_cost_breakdown.html
uber/templates/budget/index.html
uber/templates/fields/attendee.html

Splits the attendee and group cost breakdowns so they'll load more consistently. Also makes the budget/index tables exportable, and restricts receipt items loaded to just be the refunds (which are the only thing to come out of receipt items we can actually use). Finally, tweaks the presave adjustment for purchased items and adds a null option to the payment method dropdown since payment_method is a nullable column.
Oh yea, I also finally fixed the report for self-service refunds.

Update cost reports and payment method dropdown

---

uber/site_sections/reg_reports.py

Strangely, there doesn't actually seem to be an issue filed for this. Nevertheless, our badges sold graph was wildly inaccurate this year thanks to this oversight, so it's time to fix it.

Add promo code group attendees to badges sold graph

---

uber/models/attendee.py

Partially fixes https://jira.magfest.net/browse/MAGDEV-813. Now if you resave the attendee, the system will reset them off "on hold" status.

Unset watched status for attendees whose entries are inactive

---

uber/models/email.py
uber/site_sections/email_admin.py
uber/templates/email_admin/pending_examples.html

Fixes https://jira.magfest.net/browse/MAGDEV-835.
Admins can now approve, unapprove, and update email dates using the pending_examples page.
I also altered the message on the pending_examples page for when the system can't render any examples. Sadly, fixing the email example generation is out of scope for this PR as it's actually a core problem with how we select emails for sending.

Add email date changes to admin interface

---

uber/models/attendee.py

We found that the volunteers owed refunds page was listing someone who had not paid us anything as needing a refund, because they were in a paid group. This only looks at attendees' groups if they're "paid by group."

Don't count attendees with paid group if they're not paid-by-group

---

alembic/versions/b9aa7cc0b9ae_add_emergency_procedures_step_to_.py
alembic/versions/e822b20093c1_add_name_in_credits_field_for_volunteers.py
alembic/versions/fa3b09b82899_add_walk_on_volunteer_boolean.py
uber/configspec.ini
uber/models/attendee.py
uber/site_sections/staffing_reports.py
uber/templates/fields/attendee.html
uber/templates/preregistration/confirm.html
uber/templates/registration/form.html
uber/templates/staffing/credits.html
uber/templates/staffing/credits_item.html
uber/templates/staffing/emergency_procedures.html
uber/templates/staffing/emergency_procedures_item.html
uber/templates/staffing/food_item.html
uber/templates/staffing/placeholder_item.html
uber/templates/staffing/shirt_item.html
uber/templates/staffing/volunteer_agreement_item.html

Several changes to the volunteer checklist were made for Super in the magprime plugin, but putting them there was messy (and is causing problems for MAGStock). Moving them and their migrations to the main plugin.

Move volunteer checklist changes to main plugin

---

development-defaults.ini

You can't remove enums in default config, so the donation tier descriptions in this file were being applied to all events, including ones that shouldn't have them. This was causing a 500 error on startup.

Remove default donation tiers

---

development-defaults.ini

Effectively reverts the change in https://github.com/magfest/ubersystem/pull/3753 -- we need to at some point figure out how to merge this version and that version so that new deployments work without existing deployments breaking.
This should also fix the 500 error we're getting on MAGWest right now when you try to view attendees.

Restore development-defaults.ini

---

uber/templates/staffing/hotel_item.html
uber/templates/staffing/placeholder_item.html
uber/templates/staffing/shirt_item.html

Part of fixing https://jira.magfest.net/browse/MAGDEV-879 -- tweaks the wording and hides the hotel step if hotels_enabled is false.

Update volunteer checklist for virtual events

---

.gitignore
alembic/versions/f2ee72f8a1aa_convert_shift_and_max_consecutive_.py
uber/api.py
uber/automated_emails.py
uber/config.py
uber/model_checks.py
uber/models/__init__.py
uber/models/attendee.py
uber/models/department.py
uber/site_sections/dept_admin.py
uber/site_sections/hotel_reports.py
uber/site_sections/registration.py
uber/site_sections/shifts_admin.py
uber/site_sections/staffing_admin.py
uber/site_sections/staffing_reports.py
uber/static/angular-apps/signups/possible.html
uber/static/angular-apps/signups/taken.html
uber/templates/dept_admin/form.html
uber/templates/dept_admin/index.html
uber/templates/dept_checklist/no_shows.html
uber/templates/emails/shifts/shifts_worked.html
uber/templates/registration/attendee_shifts.html
uber/templates/shifts_admin/form.html
uber/templates/staffing_reports/consecutive_threshold.html
uber/templates/staffing_reports/ratings.html

Fixes https://jira.magfest.net/browse/MAGDEV-928 by tracking shifts per minute instead of per hour. This puts some extra load on some of our shift calculations -- particularly some of our reports -- but hopefully it won't actually be noticeable.
Because the old dropdowns for start times and duration options no longer makes sense at a minute level of granularity, I replaced them -- the start time uses the same datetimepicker used in our Attraction module:
And entering duration is done using dual inputs for hours and minutes:
It's somewhat difficult to see in the datetimepicker popup, but invalid times and dates are disabled based on the type of shift being edited.
In other sections of the app, e.g., entering non-shift hours, we just use floats in an hour input.

Make shift schedule use minutes instead of hours

---

uber/models/attendee.py

Fixes an issue where the link to shifts isn't showing up in West 2020.

Make shifts available if hotels are disabled

---

uber/models/__init__.py

Fixes https://jira.magfest.net/browse/MAGDEV-942. Each minute of a job was being counted as an hour -- I've checked the code and it's safe to just change the default minute_increment.

Fix job.timespan() calls

---

.gitignore
uber/templates/emails/shifts/shifts_worked.html

We don't need this right now since MAGWest overrides this template, but we'll need the same changes for Super anyway.

Update base shifts worked email

---

uber/config.py
uber/configspec.ini
uber/decorators.py
uber/models/__init__.py
uber/models/admin.py
uber/models/attendee.py
uber/site_sections/shifts_admin.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-599. Since the attendee form is a 'universal' pop-up, the access an admin has depends not on what site section they're in but on what site sections they access vs what sections the attendee would be viewable in. This is a first pass and focuses only on the attendee form.
The attendee form viewed with "Limited" read access:
The same form viewed with "Contact" read access:

Implement limited and contact access levels

---

uber/models/attendee.py

Fixes https://jira.magfest.net/browse/MAGDEV-964, which was caused by a false negative when checking admin access during attendee creation.

Always get actual write/read access

---

alembic/versions/4036e1fdb9ee_add_stage_two_mits_team_fields.py

We had the alembic migration set up wrong for a MITS column, so the bug is just now cropping up on servers. This will fix the error after you downgrade and re-upgrade alembic versions.

Fix 500 error for new MITS applications

---

uber/static/theme/prereg.css

We use PNG files for most of our assets nowadays, including the tile background.

Use PNG for tile backgrounds

---

uber/model_checks.py
uber/site_sections/preregistration.py

If an attendee cancelled payment we were trying to delete their account even if they didn't have one, which was throwing an error. This should fix that.

Fix error on payment cancellation

---

uber/site_sections/badge_printing.py
uber/templates/fields/attendee.html

The badge buttons we don't use anymore were showing up if you clicked on the Attendee registration type, this should stop that. Also hides a spurious link on the sitemap.

Fix prereg badge buttons

---

uber/decorators.py
uber/models/__init__.py

We were erroneously checking if admins had access to an attendee even if that attendee was new -- this fixes that and adds an extra check to prevent the 500 error even if we run into something like this again.

Allow non-registration admins to create attendees

---

uber/model_checks.py

We were erroneously preventing any actual promo codes from being used, assuming they were all agent codes instead.

Let people use promo codes as promo codes

---

uber/templates/staffing/shirt_item.html

We re-ordered these steps again so we have to edit their prerequisites.

Enable shirt step before food restrictions are filled out

---

uber/templates/fields/attendee.html
uber/templates/staffing/shirt_size.html

Staff who didn't have event shirts were still getting the option to select an event shirt size in some cases. This should fix that.

Fix check for staff getting event shirts

---

uber/templates/dept_checklist/placeholders.html

On the placeholders report, an invalid parameter was accidentally included in the URL to open an attendee form. Now department heads should be able to view their placeholder attendees.

Fix placeholders report attendee links

---

uber/site_sections/merch_reports.py
uber/templates/merch_reports/shirt_counts.html

Attendees whose 'registered' date was greater than 50 weeks ago were breaking our shirt sales by week report -- this should fix that.

Fix shirt report for very old attendees

---

uber/automated_emails.py

This will let us merge https://github.com/magfest/ubersystem/pull/3857 without breaking emails.

Update reference to MIVS tournament email

---

uber/models/attendee.py

Uses the gets_emails property to ensure that badges inside declined or cancelled dealer groups never receive emails about their registration in any circumstance.

Prevent emails to cancelled or declined dealers

---

uber/models/tracking.py

The tracking database code is so naive that admins changing badge numbers on purpose is marked as an automatic badge shift, even if the shift custom badge setting is False. This makes it at least smart enough to not scare people reviewing the tracking table into thinking that have shift_custom_badges set wrong.

Don't mark actions as badge shifts if badge shifting is turned off

---

uber/config.py
uber/templates/fields/attendee.html

Fixes https://jira.magfest.net/browse/MAGDEV-1024 -- now attendees with kick-in levels will still be able to upgrade even if their current kick-in level is sold out.

Always show kick-in buttons for attendees with kick-ins

---

uber/templates/staffing/shifts.html

We were accessing the wrong property for events in the shift signup calendar, so the "Are you sure" popup was always listing the current time instead of the shift time. This fixes that.

Fix shift time in confirmation pop-up

---

uber/templates/registration/index_base.html

We're trying out a new group_name property this year, so it'd be helpful if registration staff could actually see that name in the list. Note that the group_name property itself is actually defined inside the magprime plugin, but printing an undefined variable in a template shouldn't cause major issues.

Add group_name to registration index

---

uber/config.py
uber/model_checks.py

The old override to create custom badges after the deadline was hacky and relied on specific department names. We now use the new permissions system to do the same thing.

Fix custom badge override for Reg and STOPS

---

uber/templates/staffing/shifts.html

Shows the long day-of-week (e.g., "Wednesday") on the right-hand side of the day headers in the list view, under the `staffing/shifts` page.

shifts: Add day-of-week to list-view day header.

---

uber/models/department.py

Fixes a bug where "Email all members" on a department's page would give you a list of emails that included invalid and deferred badges.

Only email staffers with badges or shifts

---

uber/models/tracking.py
uber/site_sections/registration.py

Fixes https://jira.magfest.net/browse/MAGDEV-1035, mostly.
The tracking table links each entry to other models by way of a `links` list and automatically builds this list by looking at foreign keys for the instance it is tracking. However, since added the `creator` field to Attendees and Groups, admins would be linked to every single attendee and group they ever made, and all THOSE attendee/groups' changes would be linked to that admin.
Creators of attendees/groups are now excluded from the `links` list, but there's already thousands upon thousands of rows in the tracking table with erroneous links. There's no clean way to fix the data, so we are now also filtering out tracking results for any attendees that are linked to the admin attendee (other linked models' changes are still …

Fix tracking links and get around bad tracking

---

uber/decorators.py
uber/reports.py
uber/site_sections/badge_exports.py

Alters the printed badge export to include attendee IDs, so that if for some reason in the future we need to set the system back to the time we sent the badge data to the printer we can do that easier. Also fixes a bug where the extra badges might overlap existing badges, and adds YYYYMMDD to the filename of all CSV and XLSX exports.

Make printed badge export more useful

---

uber/models/__init__.py
uber/models/attendee.py
uber/site_sections/devtools.py
uber/site_sections/reg_admin.py
uber/site_sections/registration.py
uber/templates/registration/index_base.html

Fixes https://jira.magfest.net/browse/MAGDEV-1064. You can now search attendees by several attributes, and reg admins can export search results into a CSV file. It is also possible to include both AND and OR conditions in a search.
To search by attributes, use `attribute_name:search_text`. Most attributes will be either `true` or `false`, e.g., `staffing:true` or `placeholder:false`, but badge type, badge status, paid status, and amount_extra (the column for kick-ins) are all searchable by labels, e.g., `badge_type:staff`, `paid:yes`, or `badge_status:deferred`. These labels will correspond to the text associated with that attribute in the system, e.g., all the labels for badge type can be viewed in the badge type dropdown box. `amount_extra` can also be searched by dollar value, e.g., …

Improve attendee search and add export for searched attendees

---

alembic/versions/26bc228319d2_add_columns_for_attractions_requiring_.py
uber/models/attraction.py
uber/site_sections/attractions.py
uber/site_sections/attractions_admin.py
uber/templates/attractions/attractions_common.html
uber/templates/attractions/events.html
uber/templates/attractions_admin/event.html
uber/templates/attractions_admin/feature.html
uber/templates/attractions_admin/form.html
uber/templates/attractions_macros.html

Fixes https://jira.magfest.net/browse/MAGDEV-1058. Fixes https://jira.magfest.net/browse/MAGDEV-1057.
Attractions can now always be signed up for without a badge number unless a feature is set otherwise. You can also set an Attraction to require badge numbers to change the default when creating features.
Events can now also be set to have signups open or closed (AKA, "read-only"). To make managing this easier, there's a new set of buttons on the features overview that allows you to close or open signups for all events per location, per day.

Add badge_num_required and signups_open to Attractions

---

uber/configspec.ini
uber/models/attendee.py
uber/site_sections/attractions.py
uber/site_sections/preregistration.py
uber/templates/fields/attendee.html
uber/templates/preregistration/attendee_donation_form.html
uber/templates/preregistration/badge_refund.html
uber/templates/preregistration/badge_updated.html
uber/templates/preregistration/confirm.html
uber/templates/preregistration/defer_badge.html

Adds a workflow for deferring your own badge to the next year if self_service_deferrals_open is set to True. We'll collect a shipping fee and mailing address for attendees with kick-ins, if a shipping fee is set.
Also improves the extra payment page so you can avoid the often erroneous "thanks for kicking in" message by providing a "payment_label" to the page handler. Also adds a notice to confirmation pages for deferred badges, and slightly improves the logic for refunding/abandoning your badge.

Add ability to let attendees self-defer badges

---

uber/site_sections/registration.py

We were running our model checks on checked-in attendees correctly when checked in through the check-in box, but NOT when checked in through the admin form. This fixes that.

Correctly check checked-in attendees on admin form

---

uber/templates/staffing/printable_schedule.html

Stops showing minutes on the printable schedule when we mean hours.

Fix hours count on printable schedule

---

requirements.txt

Reverts magfest/ubersystem#3917
Right now our distro can't find this package. We'll want this fixed but I need to run at least one deploy now and not later.

Revert "Bump celery from 4.1.1 to 5.2.2"

---

requirements.txt

Reverts magfest/ubersystem#3922
Pip can't find this version of Pillow, so we need to roll back for now.

Revert "Bump pillow from 8.3.2 to 9.0.0"

---

uber/templates/staffing/emergency_procedures_item.html
uber/templates/staffing/food_item.html
uber/templates/staffing/hotel_item.html

Fixes https://jira.magfest.net/browse/MAGDEV-1089. Every year we reorder the volunteer checklist, and every year that creates bugs where you can't fill out the checklist in order. Now the majority of steps are available once you fill out your information. The exceptions are the emergency procedures step, which requires the volunteer agreement to be signed, and the shifts step, which requires everything else to be completed.

Open most volunteer checklist steps at once

---

uber/site_sections/staffing.py

Part of fixing https://jira.magfest.net/browse/MAGDEV-1088. This makes the error a little more clear, and also restores backward compatibility with agreement pages that only use one checkbox.

Update volunteer agreement error message

---

uber/configspec.ini
uber/templates/panel_app_form.html
uber/templates/panels/index.html

Part of fixing https://jira.magfest.net/browse/MAGDEV-1092. Fixes the covid policy link and adds an overrideable email for techops.

Fix panels app links

---

uber/config.py
uber/configspec.ini
uber/model_checks.py
uber/models/attendee.py
uber/templates/fields/attendee.html

Both West and Super use child badges with a discount, so this moves the code from the magprime plugin to the base plugin. Fixes https://jira.magfest.net/browse/MAGDEV-1105.

Add child badges to base system

---

requirements.txt

Reverts magfest/ubersystem#3928.
Pillow dropped support for Python 3.8 so we can't use the new version unless/until we upgrade our Python install.

Revert "Bump pillow from 8.3.2 to 9.0.1"

---

uber/configspec.ini
uber/templates/panels/index.html

Panels wants changes before they open applications this year, but there's actually no way to prevent applications from being open when the server is online except by setting a deadline. This fixes that.

Add panels start date

---

uber/model_checks.py

An old merge created a second version of our prereg checks for promo codes, which in turn broke promo codes for any already-existing attendees. Yikes:tm:

Remove extra, broken promo code model check

---

alembic/versions/a4a79802ba51_allow_api_and_print_jobs_to_not_have_.py
uber/models/admin.py
uber/models/api.py
uber/models/badge_printing.py

Fixes a bug in both API jobs and Print jobs that prevented any admin associated with them from being deleted.

Allow admins who created API jobs to be deleted

---

uber/utils.py

While updating the panel application I ran into a bug where the required field check was letting through a null value because it was interpreting it as the literal string "None."

Fix required checks for dropdown fields

---

alembic/versions/04826cecc42d_add_panel_interest_checkbox_for_.py
uber/config.py
uber/models/__init__.py
uber/models/attendee.py
uber/models/panels.py
uber/site_sections/schedule.py
uber/templates/fields/attendee.html
uber/templates/panel_app_form.html
uber/templates/panels_admin/index.html
uber/templates/preregistration/form.html
uber/templates/preregistration/transfer_badge.html
uber/templates/registration/form.html
uber/templates/registration/register.html

Adds panel tracks to the guidebook exports, adds the 'department' column to the panel list view, changes the wording for the Department dropdown on the panel application, and adds a 'panel interest' checkbox for preregistration.

Update panel tracks and add interest checkbox

---

uber/templates/emails/accounts/new_account.txt

Having the / after login caused fun problems where people logging in would be redirected to accounts/accounts/login.

Remove trailing slash from accounts link

---

uber/automated_emails.py

We actually don't have a reliable way to specify deferred attendees only, which is something we should fix later before we import them. For now, we'll add more conditions to the email so we don't email every dealer and MIVS judge.

Narrow down targets for deferred attendee email

---

uber/models/commerce.py
uber/site_sections/preregistration.py
uber/templates/preregistration/confirm.html
uber/utils.py

Our experience both with staff reg launch and at MFF have shown us that the current admin intervention required for 'dangling' payments is going to end with one of the reg heads driving down to my house to murder me in my sleep. Luckily I accidentally read some documentation for once and now attendees can resume their own payments!

Add ability to resume payment

---

uber/models/attendee.py
uber/receipt_items.py

This is for dealers, not attendee groups. We were giving someone a badge discount even if they were being covered by their group, so e.g. if they preordered merch they'd get $10 off that merch.

Fix group discount calculation

---

uber/site_sections/dept_checklist.py
uber/site_sections/shifts_admin.py

We now handle missing dept head checklist config much more gracefully, allowing people to still view the staffers page even with the dept head checklist turned off.

Stop requiring dept head checklist config

---

uber/site_sections/preregistration.py

Fixes a bug that has apparently been around for a while where if you click "Edit" on the prereg index page you would lose your promo code.

Don't clear promo code when editing prereg

---

tests/uber/models/test_promo_code.py
uber/models/commerce.py
uber/models/promo_code.py
uber/site_sections/preregistration.py
uber/templates/fields/attendee.html
uber/templates/preregistration/form.html
uber/templates/preregistration/group_promo_codes.html
uber/templates/promo_codes/index.html
uber/templates/registration/promo_code_group_form.html
uber/utils.py

Fixes several issues that are generating support tickets post-launch:
- An empty Superstar donation no longer breaks the upgrade process
- Fixed issue where attendees weren't receiving badge upgrades if the upgrade process did not fully complete, including loading the page after payment
- Receipt items are now only added to the attendee if the upgrade process is not interrupted by, for example, an empty Superstar donation breaking the upgrade process
- Pending badges (and imported and invalid badges) no longer 'use up' group promo codes
- Transaction amounts for multiple badges no longer apply the full payment amount to both attendees' receipts

Post Prereg Fixes

---

uber/models/__init__.py

We can't check the stripe intent amount against the receipt's current amount owed because we don't want to save anything to the session until after everything is done. Oh well.

Remove erroneous sanity check

---

uber/api.py

It would be nice for the covid verification system to be able to pull the current covid_ready status out of uber.

Allow pulling covid_ready status via API

---

uber/templates/fields/attendee.html

We're showing an "Add" or "Upgrade" button next to attendees' merch even though all our merch is sold out, and it's confusing attendees. This should fix that.

Hide kick-in upgrade button better

---

uber/configspec.ini
uber/site_sections/accounts.py
uber/site_sections/mivs_admin.py
uber/templates/emails/mivs/judge_disqualified.txt
uber/templates/mivs_admin/edit_judge.html
uber/templates/mivs_judging/index.html

There was no way to mark a judge as not qualifying for a comped badge if they didn't complete all their reviews in time. Now there is!
Marking a judge as disqualified with the new "Disqualify for (year)" button will also set their badge as needing to pay (if it was comped beforehand) and sends them an email informing them of the disqualification.

Allow MIVS admins to disqualify judges

---

uber/config.py

We need to stop counting merch for refunded, invalid, and imported badges.

Release merch from invalid badges

---

uber/site_sections/statistics.py

The summary page shows a different count than we were actually using, which is confusing.

Reflect kick-in count in summary page

---

uber/models/group.py

Fixes https://jira.magfest.net/browse/MAGDEV-1166. Makes an exception for MIVS groups because there's no reason to keep them from adding badges. Also lets dealer groups buy more badges.

Stop guest groups from buying badges

---

uber/site_sections/preregistration.py

Fixes a bug where a comped group (i.e. one without a receipt) couldn't actually buy extra badges.

Let groups without receipts buy badges

---

uber/templates/schedule/edit.html

The schedule page has been showing twice as many slots as it should since at least 2017. How did we miss this??

Fix a 5-year-old bug in the schedule page

---

uber/model_checks.py
uber/templates/panel_app_form.html
uber/templates/panels/guest.html
uber/templates/panels/index.html

Instead of "When are you available" we now ask guests to list when they're unavailable, just like we do with attendees.

Use unavailability instead of availability for guests

---

uber/model_checks.py
uber/templates/guests_macros.html

Now only full admins can add customized badges. Also allows contractors to not have to put in a MAGBuddy

Lock down new customized badges more

---

uber/templates/guest_checklist/merch_deadline.html
uber/templates/guest_checklist/rock_island_merch_deadline.html

Requested via Slack. This removes references to having a merch table and auto-selects Rock Island from the merch preferences.

Customize Rock Island groups' checklist

---

uber/models/__init__.py
uber/site_sections/staffing.py
uber/templates/staffing/shifts.html

We keep having confusion because the system auto-hides non-role shifts that overlap with role shifts, but it doesn't actually say that anywhere. Now it explains this and lets you view ALL shifts, regardless of required role.

Allow volunteers to show un-role shifts

---

uber/site_sections/marketplace.py
uber/tasks/attractions.py
uber/tasks/panels.py
uber/tasks/registration.py

Apparently, when you call a celery task function with no other modifiers, you attempt to run that function inside the current process. We basically never want this, and I am like 14% sure this is what's breaking some of our automated emails, so this switches everything to use send_email.delay() -- "delay" makes it send a message to the actual email task.

Send all emails to the email task

---

uber/config.py

We were only showing pages on the site map if you also had access to the page's overall section, which kind of defeats the point. This fixes that.

Show all accessible pages on the site map

---

uber/tasks/email.py

I suspect that people are getting double-emailed because the automated email task isn't actually finishing before it's kicked off again, causing race conditions or whatever. Hopefully this helps. I created an exception for dev boxes to ease development.

Send automated emails a little less often

---

uber/automated_emails.py
uber/templates/emails/mivs/checklist_new_item.txt

I had built in a way to generate emails for every checklist item, but it's better if the MIVS folks have more control so we don't need those automatically generated ones anymore.

Remove extra MIVS checklist notifications

---

uber/tasks/mivs.py

TIL that MIVS studios' status never changes! We'll deal with that later -- filtering based on who has a guest group is better for our purposes anyway.

Change MIVS reminder filter

---

uber/models/group.py

It's silly to require dealers to add 5 badges at a time, so this fixes that.

Let dealers add one badge at a time

---

alembic/versions/fa2deb095760_add_column_to_track_email_sending.py
uber/configspec.ini
uber/model_checks.py
uber/models/attendee.py
uber/site_sections/guests.py
uber/site_sections/preregistration.py
uber/templates/emails/guests/charity_notification.txt
uber/templates/fields/attendee.html

Catching up on various issues raised on Slack the past couple weeks, including:
- An issue with permissions seeing volunteers
- A problem where people would unset their own volunteer agreement and emergency procedures agreement when updating their own info
- A request to add an email notification when a guest indicates they have something to donate to charity
- An issue where minors could not ever join promo code groups

Implement various fixes/requests post-MFF

---

uber/models/email.py

If you restarted the server while the email task was running, some emails would get stuck in the "currently sending" state -- this should knock them back out of it whenever the email task starts.

Unset currently_sending when reconciling email fixtures

---

uber/models/attendee.py
uber/models/group.py

We now account for promo codes when calculating attendee badge cost changes. Also fixes a bug where dealers with non-purchased badges (i.e., attendees that weren't paid by group) would be charged for the non-purchased badges whenever they were saved.

Fix issues with auto-updating receipts

---

uber/site_sections/marketplace.py
uber/tasks/attractions.py
uber/tasks/registration.py

Emails sent from tasks were failing because they were being encoded in UTF-8, then JSONized. This fixes the encoding issue.

Fix encoding issue with emails sent from tasks

---

uber/templates/emails/mivs/checklist_reminder.txt

All our page handlers are formatted mivs_[checklist key], e.g., mivs_core_hours or mivs_discussion. I forgot to mirror that in the checklist reminder emails, whoops.

Append mivs_ to checklist links

---

uber/model_checks.py

Pointed out via Slack. Boy, our validations for job creation are really lacking.

Stop job creation with negative hours

---

uber/tasks/email.py

We keep having the system randomly stop sending email categories... we'll need a new approach.

Stop locking emails during sending

---

uber/tasks/email.py

I accidentally commented out too much code in an earlier change. This will make the system stop listing some emails as 1 million+ waiting to send.

Reset email approval counts when sending automated emails

---

uber/api.py

Due to an oversight in this API call, you could get an absurd amount of data on each department's attendees. This fixes that and adds a 'full' parameter if you want extra attendee info, in line with our other API calls.

Stop leaking ALL THE DATA in dept.members

---

uber/templates/accounts/homepage.html

MIVS judges could access the attendee form and make badges. This is a quick fix to stop that.

Only show homepage to real admins

---

uber/models/admin.py

This is a quick workaround for a somewhat odd problem in how we calculate our guest group accesses -- we made a checklist type that doesn't really fit into our admin accesses, so now we give people with guest_admin access to any checklists without corresponding site sections.

Allow guest admins to see ALL guests

---

uber/site_sections/dept_checklist.py
uber/templates/dept_checklist/item.html
uber/templates/dept_checklist/overview.html

Also adds a note to the overview page reminding you to click the item title, since I constantly forget how to get to the item overview page myself. Fixes https://jira.magfest.net/browse/MAGDEV-1017.

Add CSV of dept head checklist items

---

uber/templates/attractions/events.html
uber/templates/attractions_macros.html

Discussed in Slack -- attendees were getting confused because we have public attractions that require a badge number before the event, so they've been emailing us asking what their badge number is. This will hopefully make things a little clearer.

Improve UX for attractions requiring badge number

---

uber/site_sections/preregistration.py
uber/templates/static_views/post_con.html

Weird that we weren't already doing this. Other events can now override the template as normal instead of changing the code. Fixes https://jira.magfest.net/browse/MAGDEV-1118.
We don't need this right now so I'll just include it in the next update to the super2023 branch.

Render an overridable template for post-con

---

uber/models/__init__.py
uber/site_sections/art_show_applications.py
uber/site_sections/badge_printing.py
uber/site_sections/marketplace.py
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py
uber/site_sections/registration.py
uber/templates/reg_admin/receipt_items.html

We're having issues with some workflows because the system will only create a model receipt when an attendee saves their info. This adds a button to create either a "Default" receipt (one with all the default costs calculated) or a blank receipt.

Add a way for admins to manually create receipts

---

uber/site_sections/hotel_reports.py

Prevents a 500 error when maps aren't enabled, and excludes unassigned badges from the report.

Fixes for hotel audit

---

uber/site_sections/hotel_reports.py

Hopefully the last fix needed for this. I really would've expected the uszipcode library to just handle these.

Handle long zipcodes in hotel audit report

---

uber/automated_emails.py
uber/templates/email_admin/pending.html

This adds a column to the Pending Emails page with links directly to the templates used to generate each email.

Adding links to email templates from Pending Emails page

---

uber/jinja.py

It looks like the email template path evaluation is cached, but not invalidated when the searchpath is changed. This will blow away the cache any time a plugin is loaded.

Fixing email template cache invalidation

---

uber/site_sections/devtools.py

Apparently when I wrote the code to convert labels to the column's integer values, I assumed it would automatically apply to CSV imports. It does not.

Convert CSV import labels

---

docker-compose.yml
make_config.py
uber-wrapper.sh

This adds `UBERSYSTEM_GIT_CONFIG` and `UBERSYSTEM_GIT_CONFIG_PATHS` environment variables that allow pulling configuration from a git repo in the same format used by the MAGFest terraform scripts.

Adding option to pull config into dev environment

---

uber/templates/emails/shifts/shifts_worked.html

I changed "January" to "end of the month" which is probably more in line with what we'd use for all three events.

Update for shifts email

---

uber/automated_emails.py

Since the URLs for emails were only being set on initialization, they didn't always match the email body, which is re-calculated on access. It might be worth figuring out later why the email body sometimes changes after init, but for now this Probably™ won't cause issues.

Fix email template URLs

---

uber/configspec.ini
uber/templates/emails/mivs/judge_badge_info.txt
uber/templates/emails/placeholders/guest.txt
uber/templates/emails/placeholders/panelist.txt
uber/templates/emails/placeholders/regular.txt
uber/templates/emails/placeholders/volunteer.txt

Replaces it with a configurable string, since that seems useful anyway.

Remove "proof of vaccination" from emails

---

uber/models/attendee.py
uber/templates/preregistration/index.html

- Fixes a case where people were counted as getting shirts even if SHIRTS_PER_STAFFER was 0
- Changes "membership" to "registration" on the prereg index page.

Fixes for MAGStock launch

---

uber/site_sections/preregistration.py

Although this should technically never happen, we managed to glitch our way into having a pending payment without a stripe intent and it failed silently for the user. This will at least make it fail less silently.

Stop silent error when resuming payment intent

---

uber/site_sections/preregistration.py
uber/site_sections/registration.py
uber/templates/preregistration/index.html
uber/utils.py

Adjusts the "too much" error message to give the correct amount ($9,999, not $999,999!), fixes an issue where attendees' receipts weren't always being refreshed properly, and displays correct prices for attendees with age discounts.

Fix minor bugs in payment system

---

uber/tasks/email.py

This should hopefully fix the intermittent bug people were seeing where their "amount paid" was listed as $0.

Refresh receipts before sending emails

---

uber/amazon_ses.py
uber/tasks/email.py

This addresses two issues:
1. When I added handling for email error exceptions (https://github.com/magfest/ubersystem/commit/10d87e2d5dcfb612358326cd0f02885795269788), I accidentally erased the email system logging an email error returned from the sendEmail function (https://github.com/magfest/ubersystem/blob/33fb5b8b97c55b2115bda1d499b4c6fd03731f92/uber/amazon_ses.py#L25). Honestly we theoretically don't need the try/except here, but I must have added it for a reason so I'm not going to change it.
2. We need more information about our email sending because something's going wrong with some emails, so we now log emails before attempting to send them. This is logged at the ERROR level because we can't figure out how to change our logging level. The corresponding response logging has been …

Improve email logging

---

uber/amazon_ses.py
uber/tasks/email.py

We were getting confused about email sending because the system records the email as sent even if there was a problem sending it. We still record emails if email sending is turned off in development environments, but otherwise emails now don't get recorded unless they actually get sent.
Also sets email-related logs to INFO level since we don't need the extra data anymore.

Only record emails if there are no errors

---

uber/templates/fields/attendee.html

This field was hidden if you did not have job_interests defined, so it wasn't showing up for West.

Show "want to help" if there are public depts

---

uber/config.py
uber/models/promo_code.py
uber/site_sections/statistics.py

We were only counting group codes that had been claimed because they had attendees associated with them, but the badges_sold graph is about sales, not registrations. We now count promo code groups when they're bought and don't count people with claimed pc group badges. Also fixes BADGES_SOLD to filter out unpaid promo codes.

Fix daily badges sold statistic for PC groups

---

uber/site_sections/statistics.py

This Should™ fix the 500 error on Stock while preserving the correct dates for attendee registrations and promo code group registrations.

Account for mismatching keys in group and attendee queries

---

uber/models/__init__.py

The "available" property on our Stripe account is how much money Stripe is ready to deposit into our bank account, which will often be $0 (like, say, after Stripe has deposited money in our bank account). Refunds are actually levied against both current and future funds, which seem to be captured in the "instant_available" property.

Use the correct Stripe property to check for refund availability

---

uber-wrapper.sh

Apparently the format of the SRV record can be slightly different in some cases. This should return just the precise answer to the query.

Fixing SRV record parsing

---

uber/models/tracking.py

Our tracking DB tracks every change to every model, but locking emails via the DB means generating approximately 8 bajillion DB entries. This should stop that.

Don't log email locking changes

---

uber/tasks/email.py

I think swapping to having automated_emails as the outer loop should limit the number of DB writes, and possibly make unapproved_count more accurate.

Swapping loop order to reduce DB writes

---

uber/templates/attractions_macros.html
uber/templates/detailed_travel_plans_form.html
uber/templates/shifts_admin/form.html

Our datetimepicker plugin was converting all times to the browser's local timezone, but we always want times to be in the event's timezone. This forces all times passed to datetimepicker to be timezone-naive so it stops converting them to the browser's timezone.
This specifically fixes an issue where a department head could not create a West loadout shift before 7pm (the minimum should be 4pm).

Fix timezone conversion issue with datetimepicker

---

uber/site_sections/devtools.py
uber/tasks/__init__.py
uber/tasks/health.py

This adds a public endpoint at `/uber/devtools/health` that quickly tests the session store, database, and task broker. It returns 200 if they all work, and times out or gives a 500 error otherwise. It returns a json object that gives some stats:
```json
{
"server_current_timestamp": 1684306723,
"session_read_count": 1,
"session_commit_time": 0.0003650000003290188,
"db_read_time": 0.001840582999648177,
"db_status": "Pool size: 5  Connections in pool: 0 Current Overflow: -4 Current Checked out connections: 1",
"task_run_time": 6.971455335999963,
"task_response_correct": true,
"task_payload": 392,
"task_response": 392
}
```
Adding this endpoint will allow us to make the load balancer in front of uber a lot more graceful, as at the moment it has a bad habit of sending traffic to dead ubers.

Added health check endpoint

---

uber/site_sections/preregistration.py

This should help properly generate receipts for new group members. It doesn't really explain why only buying dinner tickets was broken, but at least this seems to make it work?

Fix receipt generation for group members

---

uber/config.py
uber/models/__init__.py
uber/site_sections/staffing.py
uber/templates/shifts_admin/index.html

Fixes the following issues, reported via Slack:
- Certain admin views were displaying only the hour start time and not the minute for shifts, e.g., an 11:15am shift was shown as starting at 11am
- If you had access to setup and teardown shifts, your shift signup view started on the first shift setup day but would not show you the full length of the event

Fixes for shifts views

---

uber/templates/staffing/printable_schedule.html

Adds minutes to the start time displayed on the printable schedule. Also prints the hours for setup/teardown shifts.

Improve printable schedule

---

uber/automated_emails.py
uber/configspec.ini
uber/models/panels.py

Fixes https://jira.magfest.net/browse/MAGDEV-1244, although it is a little weird that the guest submitter is made the POC... in any case, we can (probably) safely assume that applications with a POC assigned should not be waitlisted. Also sets panels_confirm_deadline to be off by default to avoid confusing behavior.

Stop waitlisting panels with confirmed POC

---

uber/models/tracking.py

It appears diff will always be a dict rather than a str.

Fix email tracking exclusions

---

uber/templates/fields/attendee.html

That way contractors can't set themselves to attendees when they claim their badge.

Make volunteering checkbox read-only for staff/contractors

---

uber/tasks/email.py

Adding more logging to the automated email task to help track performance

Email logging

---

uber/tasks/email.py

Only update the last_send_time if we are in danger of approaching the expiration time, rather than on every potential send.

Don't update the last_send_time as often

---

uber/templates/fields/attendee.html

If an attendee doesn't have emergency contact info or an onsite contact, we now show these fields so that admins can set them and thus save the form without validation errors.

Show emergency contact info if it is not set

---

uber/configspec.ini
uber/models/attendee.py
uber/models/group.py
uber/receipt_items.py
uber/site_sections/budget.py

The SQL I wrote to check if group attendees were valid/had badges was causing too much trouble, so instead we now directly update attendees' badge status based on their group status.
Also fixes an error in the badge cost summary report.

Remove circular joins on has_badge

---

alembic/versions/4acd51ac5462_add_signed_documents.py
alembic/versions/551b8ff65d33_add_last_email_send_time_for_signed_.py
alembic/versions/a4a79802ba51_allow_api_and_print_jobs_to_not_have_.py
alembic/versions/a5d2a3700b1a_overhaul_payments_and_payment_tracking.py
alembic/versions/af64b33e950a_initial_migration.py

The use of the `alembic history` command made this slightly less painful.
Protocol is to manually remove all revisions from the database except the event plugin revision (1368bafd0eb2 for magprime, e86fcf34f217 for MFF), stamp to the latest revisions for the main plugin (c31a2e5b6fbd), and hope nothing breaks

Reorder Alembic migrations

---

uber/forms/attendee.py
uber/site_sections/preregistration.py
uber/templates/preregistration/additional_info.html
uber/templates/preregistration/stripeForm.html

The badge_printed_name field may be optional at some events, and there was a mismatched ID in the additionalinfo form.

Fixing form validation bugs

---

uber/automated_emails.py

One more attempt at fixing the email template links. This should be precisely the same method used by the actual sender.

Fixing email paths in links to templates

---

uber/configspec.ini
uber/site_sections/preregistration.py
uber/static/js/window-hash-tabload.js
uber/templates/preregistration/confirm.html

Fixes a bug found in dealer reg where you could not edit your # of badges. Also adds the ability to send notification emails to the dealers department.

Additional fixes for dealer reg

---

uber/site_sections/preregistration.py
uber/site_sections/registration.py

This should fix returning "reg is closed" errors based on time.

Returning errors generated by check_if_can_reg

---

uber/models/__init__.py
uber/models/art_show.py
uber/models/attendee.py
uber/models/group.py
uber/site_sections/budget.py
uber/tasks/email.py

We want to do a joinedload to optimize accessing models' receipt properties, so we now explicitly define a relationship instead of creating a dictionary on property access.

Convert active_receipt to a relationship

---

uber/site_sections/group_admin.py
uber/templates/group_admin/dealers.html

We need to see more than 1000 groups (ahhh), so this uses joinedloads to fix the page load time so we can also remove the row limit.

Fix groups list performance and remove row limit

---

uber/utils.py

We want to do some of our imports using the local IP for a server, but we need to use the HTTP protocol for this and not HTTPS. This lets you specify the http protocol in the server hostname -- if you don't specify, it still defaults to https.

Allow using HTTP for API if specified

---

uber/automated_emails.py
uber/models/email.py
uber/site_sections/email_admin.py
uber/templates/email_admin/pending.html
uber/templates/emails/placeholders/imported_volunteer.txt
uber/templates/emails/shifts/reminder.txt

We now reconcile email fixtures whenever someone loads the pending email page. Also makes sure that fixtures' template paths get updated during the reconciliation process.

FIX. EMAILS.

---

uber/config.py
uber/site_sections/budget.py
uber/site_sections/hotel_reports.py
uber/site_sections/reg_reports.py

I _think_ the use of the attendees_with_badges() shortcut prior to any join is the root of the issues we've been having. Also fixes an issue where the hotel export excluded unapproved dealers but included deferred badges, both of which were incorrect.

Stop with_badge filtering before joins

---

uber/payments.py
uber/site_sections/art_show_applications.py
uber/site_sections/marketplace.py
uber/site_sections/preregistration.py

The auto_update_receipt function now only looks at parameters that have changed, which should fix several bugs (most importantly, the current bug where PC group owners get asked for $10 every time they save their badge). Also actually creates receipt items in several places where those were missing, including promo code groups and dealer groups.

Improve receipt auto-updater and fix receipt items

---

uber/models/__init__.py
uber/site_sections/preregistration.py

I had added logic to stop two people using the same single code, but it turns out that when looking up a universal promo code for two people in the same cart the system would always assign them the same individual code. Now that also accounts for already-used codes.

Stop universal promo code double-claiming

---

uber/models/commerce.py
uber/site_sections/art_show_applications.py
uber/site_sections/preregistration.py

Fixes a bug where declined payments were marked as paid since they technically had a charge on them.

Only mark payment intents as paid if they were successful

---

uber/site_sections/group_admin.py

You can now actually add group badges. Additionally, they will be the badge type and ribbon you select rather than always matching the leader's badge type and ribbon. Also fixes a typo in setting up the leader of a new group.

Fix issues with assigning extra group badges

---

uber/models/email.py

We have a way to ignore currently_sending if it's been stuck for too long, but it wasn't working because any currently_sending email category was fully excluded from the list. This should fix that and prevent emails from getting indefinitely blocked.

Include currently_sending emails in active emails

---

uber/models/attendee.py
uber/site_sections/hotel_reports.py

We need a way to mark some staff as not eligible for both staff rooming and the attendee lottery. This makes it so that if we set hotel_eligible to False, it doesn't then reset to True just because someone has a staff badge. This also checks for hotel_eligible for staffers during the attendee hotel export.

Allow hotel_eligible to stay False for staffers

---

uber/model_checks.py
uber/models/__init__.py
uber/models/attendee.py
uber/models/commerce.py
uber/models/group.py
uber/payments.py
uber/receipt_items.py
uber/site_sections/art_show_applications.py
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py
uber/site_sections/registration.py
uber/tasks/email.py
uber/tasks/registration.py
uber/templates/art_show_applications/confirmation.html
uber/templates/art_show_applications/edit.html
uber/templates/art_show_applications/index.html
uber/templates/base.html
uber/templates/confirm_tabs.html
uber/templates/emails/reg_workflow/pending_badges.html
uber/templates/marketplace/edit.html
uber/templates/marketplace/index.html
uber/templates/preregistration/attendee_card.html
uber/templates/preregistration/homepage.html
uber/templates/preregistration/preregbase.html
uber/templates/preregistration/stripeForm.html
uber/utils.py

Fixes validations so that people trying to update attendees under 18 aren't told to select an adult badge. Also pulls in fixes from MFF for receipt management, particularly refunds. Also also re-enables automatic pending badge deletion.

Fixes for refunds and validations

---

uber/site_sections/statistics.py

Currently days without group registrations are getting added with a date of None, which trips up this function.

Fixing badge graph

---

uber/model_checks.py
uber/models/__init__.py
uber/models/attendee.py
uber/payments.py
uber/receipt_items.py
uber/site_sections/art_show_applications.py
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py
uber/templates/art_show_admin/pieces.html
uber/templates/art_show_applications/art_show_form.html
uber/templates/art_show_applications/confirmation.html
uber/templates/art_show_applications/edit.html
uber/templates/art_show_applications/index.html
uber/templates/art_show_applications/new_attendee_fields.html
uber/templates/art_show_common/art_pieces_form.html
uber/templates/base.html
uber/templates/email_admin/pending_examples.html
uber/templates/email_admin/sent.html
uber/templates/group_admin/form.html
uber/templates/group_admin/index.html
uber/templates/preregistration/group_members.html
uber/templates/preregistration/stripeForm.html

While working on MFF I noticed that we'd introduced a bug in our custom price receipt updates, this should fix that. Also includes a bunch of changes for art show that we won't use.

Fix override price calculations

---

alembic/versions/ceb6dd682832_add_processing_fee_column_to_receipt_.py
uber/config.py
uber/models/commerce.py
uber/payments.py
uber/site_sections/reg_admin.py
uber/templates/reg_admin/receipt_items.html

You can now exclude processing fees for full refunds and for refunds where you undo an item, which is like 99.9999% of cases where we want to exclude processing fees in a refund.

Allow refunds to exclude processing fees

---

uber/models/commerce.py
uber/models/promo_code.py
uber/payments.py
uber/site_sections/api.py
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py
uber/tasks/registration.py
uber/templates/art_show_admin/history.html
uber/templates/email_admin/index.html
uber/templates/guests_macros.html
uber/templates/marketplace_admin/history.html
uber/templates/model_history_base.html
uber/templates/preregistration/group_promo_codes.html
uber/templates/reg_admin/receipt_items.html
uber/templates/registration/feed.html
uber/templates/registration/promo_code_group_form.html

Allows you to fully refund badges that are in promo code groups, including with and without processing fees. Also fixes history tab styling and accounts for refunded promo codes.
The rules for promo code usage are:
- Badges that pending, invalid, imported, and "invalid group" don’t count against promo code usage -- they are effectively the same as that badge not having the promo code attached.
- If a badge status is Refunded, the promo code is still used and shows up with a “Refunded” tag on group leader’s page and also the admin page.
- All other badge statuses are counted as a valid use and have no special display logic.

Updates to receipt refunds plus adding refunding of group badges

---

uber/models/department.py
uber/templates/dept_admin/form.html
uber/templates/dept_admin/index.html
uber/templates/dept_admin/new.html
uber/templates/dept_checklist/index.html
uber/templates/forms/attendee.html
uber/templates/shifts_admin/index.html
uber/templates/shifts_admin/main_menu.html
uber/templates/staffing/hotel_item.html

We're making all setup and teardown shifts available by default without needing approval. Also updates the "creating shifts" step to explain roles a bit better, and updates the department head checklist page to correctly display checkboxes.

Remove setup/teardown approval options

---

uber/models/attendee.py
uber/templates/emails/shifts/dept_checklist.txt
uber/templates/forms/attendee.html

Our emails for the department head checklist were listing ASSIGNED departments, not departments you actually needed to fill out the checklist for. This adds a property that lets you easily generate a list of department names for any property (in this case, "can admin checklist") so that we can display that in our emails.
Also uses the readable_join custom tag, which I didn't know existed, to fix minor issues with displaying the "can't transfer their badge" message on the attendee admin form.

Improve display of list of departments for dept heads

---

uber/automated_emails.py
uber/model_checks.py
uber/site_sections/group_admin.py
uber/utils.py

Fixes several bugs where running into a validation error with the group leader's info while creating a group would crash the page. Also stops requiring a phone number for staff who are placeholder badges (whoops).

Fix admin group validations

---

uber/templates/forms/group/admin_table_info.html
uber/templates/forms/group/table_info.html

I'd rearranged the way we build admin forms but my changes broke the admin form for dealers. This fixes that somewhat clumsily by copying the logic I need from admin_group_info into admin_table_info.

Fix 500 error on dealer admin form

---

uber/forms/attendee.py
uber/templates/forms/attendee/admin_staffing_info.html
uber/templates/forms/macros.html

Also fixes a bug where if you passed `readonly` to a checkbox form macro, it would always disable the checkbox.

Allow super admins to manually set staff crash space

---

uber/forms/__init__.py

It turns out there's an oversight in WTForms where if you render a BooleanField with a hidden input, it will render the value as "False," and then when you process the submitted form it will count "False" as true because it is a string. This adds custom preprocessing to prevent that.

Fix hidden boolean fields

---

uber/models/__init__.py
uber/models/art_show.py
uber/models/attendee.py
uber/models/group.py
uber/payments.py
uber/site_sections/dealer_admin.py
uber/site_sections/mivs.py
uber/templates/preregistration/index.html

There's a lot of cases where we need the default cost of a new object -- this should hopefully fix all those cases. Also fixes a 500 error for preregistration and removes c.AT_DOOR_PENDING_STATUS since that shouldn't have gotten in there.

Use calc_default_cost() where appropriate

---

uber/site_sections/staffing.py
uber/templates/staffing/shifts.html

This was a request from Nova at MFF. It adds a button for volunteers to download their shift schedule in a convenient ical format.
Not sure if that's the best place for a download button, but the ical download seems to work correctly in staging2023.

Adding ical download for shift schedule

---

uber/site_sections/preregistration.py
uber/templates/preregistration/additional_info.html
uber/templates/preregistration/dealer_registration.html
uber/templates/preregistration/form.html

When I updated group badge claiming I accidentally made it so that if you accessed the page without the attendee ID, it would generate a new registration for you and then refuse to save it. It also wanted to direct you to prereg -- this fixes both issues.

Fix group badge claiming via generic link

---

uber/templates/emails/dealers/badge_converted.html

This should make the badge_converted email say the right thing if the group is being declined or the waitlist is being closed.

Improve the way we handle converting dealer badges

---

uber/model_checks.py
uber/site_sections/dealer_admin.py
uber/tasks/registration.py
uber/templates/emails/daily_checks/pending.html
uber/templates/emails/dealers/badge_converted.html
uber/templates/preregistration/disclaimers.html
uber/templates/shifts_admin/index.html

Includes the following fixes:
- Group leaders no longer get deleted along with their group during dealer badge conversion 😬
- The "select a child badge" validation should no longer erroneously trip for people claiming group badges
- The pending badge report email now only sends if there are pending badges created by admins (vs pending badges of people who didn't finish registering, which happens basically constantly). Also fixes a typo in the email.
- The duplicate registration check should now only send once a day even if there are multiple email tasks running
- The "Event" button on the admin shift schedule now actually shows the last day of the event

Fixes for dealer badge conversion, email reports, and admin shift schedule

---

uber/configspec.ini
uber/receipt_items.py
uber/site_sections/dealer_admin.py
uber/site_sections/group_admin.py
uber/tasks/groups.py

Our old way of doing this was tricky -- dealers would get a declined email AFTER they were told their badges were converted. It also meant that if a dealer was declined by mistake, their badges would be converted instantly, a difficult process to reverse.
Now we run a nightly task that converts badges. Dealer groups are either left around (for MFF) or deleted (for MAGFest) based on the new delete_declined_groups config option.

Automatically convert declined dealer badges

---

uber/models/__init__.py

I forgot to exclude attendee accounts from searches for IDs, so they would always turn up nothing. This fixes that.

Fix searching by ID

---

uber/config.py
uber/site_sections/statistics.py
uber/templates/statistics/index.html

Fixes https://jira.magfest.net/browse/MAGDEV-1293 by adding paid promo codes to the attendee badge count. Also revamps the registration stats on the main stats page to reorganize and better explain what different stats actually mean.

Overhaul stats page and improve cap count

---

uber/site_sections/accounts.py

Fixes https://jira.magfest.net/browse/MAGDEV-1286 by checking explicitly for the case where an account is updated with none of the checkboxes checked.

Allow unsetting of all admin accesses from an account

---

uber/models/group.py

I had to add support for dealer groups with no tables to MFF, and since we haven't used paid groups in years I thought it would be safe to just include any group with a cost. However, it's very common for admins to accidentally add a group of free badges as a group of paid badges, and you can't undo that once you've done it without filling in a bunch of junk dealer data. I'll have to add another way for MFF to have dealer groups without paid tables.

Support paid attendee non-dealer groups

---

uber/models/attendee.py
uber/payments.py

Fixes https://jira.magfest.net/browse/MAGDEV-1280 by preventing credit receipt items from being closed. Also removes the ability to try to 'revert' changes to the # of badges, promo code, or DOB as these are all broken or impossible to make work properly.

Allow deleting credit items

---

uber/site_sections/registration.py
uber/templates/forms/macros.html
uber/templates/registration/attendee_data.html
uber/templates/registration/form.html

Deleting an attendee while on the group admin form led to a 500 error as it was loading the wrong page handler. Also adds an AJAXified version of delete_attendee so the attendee modal can simply close without needing a redirect. Also fixes an issue I found where loading the attendee modal would trounce on existing form validations on the page.

Fix issues with attendee modal on group form

---

uber/configspec.ini
uber/models/attendee.py
uber/site_sections/preregistration.py
uber/templates/forms/attendee/other_info.html
uber/templates/preregistration/transfer_badge.html

Updates the transfer badge form to the new form system. Also adds the onsite_contact fields to the nontransferable field list. Fixes https://jira.magfest.net/browse/MAGDEV-1298 while ensuring that receipts are transferred to the new badge.

Fix transferring badges

---

uber/config.py
uber/custom_tags.py
uber/models/commerce.py
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py
uber/site_sections/registration.py
uber/templates/check_in.html
uber/templates/forms/attendee/check_in_form.html
uber/templates/preregistration/at_door_confirmation.html
uber/templates/preregistration/index_payment_form.html
uber/templates/preregistration/stripeForm.html
uber/templates/registration/check_in_cart_form.html
uber/templates/registration/check_in_form_base.html
uber/templates/registration/minor_check_form.html

Updates the 'at-door confirmation' page to work without attendee accounts so that MAGFest can also use the prereg page during the event. Also fixes some bugs with the check in modal Stripe form not working with Bootstrap 5 and not marking people as paid correctly. Also fixes https://jira.magfest.net/browse/MAGDEV-1211 by forcing focus on the badge input field -- validations were already made to work correctly earlier for MFF.

Update at-con workflow to work with prereg page

---

uber/site_sections/barcode.py

Fixes https://jira.magfest.net/browse/MAGDEV-1208 and likely other permissions issues regarding scanning badges by letting any admin call the get_badge_num_from_barcode page handler.

Allow any admin to decrypt barcodes

---

uber/models/attendee.py
uber/site_sections/dealer_admin.py
uber/site_sections/group_admin.py
uber/templates/emails/dealers/badge_converted.html

Updates the dealer conversion email to account for when we close the waitlist. Also lists the badge price and the number of other people who got converted to help make the process clearer for dealers.

Update dealer conversion for waitlist closing

---

uber/models/__init__.py
uber/site_sections/preregistration.py
uber/templates/forms/attendee/badge_extras.html
uber/templates/preregistration/claim_badge.html
uber/templates/static_views/prereg_soldout.html

Fixes https://jira.magfest.net/browse/MAGDEV-1297 by adding a single-page registration form to claim a group badge. It rejects any promo code that isn't attached to a group, any code that is already used, and any group code for a 'full' group. Also adjusts the behavior of the new badge payment page so that, if you select extras while claiming a group code, you're brought directly to that page instead of the confirmation page.

Add group promo code claim page

---

uber/models/__init__.py
uber/site_sections/dept_admin.py
uber/site_sections/preregistration.py
uber/site_sections/reg_reports.py

Also lowers the pagination number for the receipt discrepancies page, and adds "has shifts" to the department volunteer export.

Fix duplicate key error for cancelled prereg payments

---

uber/automated_emails.py
uber/models/email.py
uber/site_sections/email_admin.py
uber/templates/email_admin/pending_examples.html

Also improves several things about email fixtures, including:
- Letting you actually override the email dates (I think this never worked and it became more obvious once we started reconciling fixtures on page load)
- Adding hacky support for actually keeping email date updates between server restarts
- Skipping a lengthy DB call for reconcile_fixtures when it's used while loading the pending emails page
- Only reloading templates if they're not already set in a fixture -- this should be okay because Jinja can only consume new templates on a server restart anyway, and we check the fixture (which starts blank) rather than the DB

Add support for plugin overrides of email fixtures

---

alembic/versions/9168e926974e_add_tracking_fixture_changes_to_.py
uber/automated_emails.py
uber/models/email.py
uber/site_sections/email_admin.py
uber/templates/email_admin/pending_examples.html

The previous change made it so that code updates to email dates NEVER worked. We now track which dates have been changed to avoid that. We also show admins a list of changes on each email and allow them to revert those changes back to the default.

Allow updating email dates through code

---

uber/models/email.py

The pending emails page errors out, but only for West, in a way that makes no sense. Still, it indicates an error that could happen in some circumstances, so I'm hoping this fixes it.

Try to resolve duplicate key errors

---

uber/site_sections/registration.py
uber/site_sections/security_admin.py
uber/templates/accounts/index.html
uber/templates/base.html
uber/templates/forms/macros.html
uber/templates/registration/banned.html
uber/templates/registration/duplicate.html
uber/templates/registration/form.html

Fixes https://jira.magfest.net/browse/MAGDEV-468 by extending our validations to allow warnings, which will mark validations as having passed and therefore let the user continue submitting the form after they read the warning. Also fixes our error messaging system to be able to handle string errors, a problem that plagued us continuously last year by silencing various errors from the server (including CSRF token errors).

Add in-page warnings for duplicate and banned attendees

---

uber/automated_emails.py

We don't write "staff import" in the notes for admins/initial badges, which means they never get a direct link to their badge. This fixes that.

Send staff badge claim email to admins, too

---

uber/site_sections/devtools.py

Currently we end up in a loop of killing container instances if celery is not enabled. This isn't a health issue with the instance,  so we should check for that and report health anyways.

Don't kill instance if celery is disabled

---

uber/payments.py
uber/site_sections/preregistration.py

We were merging the prereg cart with the attendees we just made when we loaded this page, which was silently deleting all their department requests. I have no idea how long this was broken.
Also fixes a silent 500 error when trying to log data for Stripe requests.

Stop unsetting volunteer interests on paid_preregistrations

---

uber/models/attendee.py
uber/templates/staffing_reports/ratings.html

This page was showing the total hours for a job (the job's actual length multiplied by how many slots the job had), which is not what we want in this context. Also fixes references to "location_label," which was removed from jobs long ago as part of moving departments into the DB

Fix display bugs on ratings overview page

---

uber/forms/attendee.py
uber/models/email.py
uber/payments.py
uber/templates/forms/group.html

Fixes a bug where you couldn't change the send dates of an email that already had them because it couldn't save the original value in a JSON column. Also includes a few minor updates: the promo code field is now labelled "Group or Promo Code" if groups are enabled, and a bug with debug logging transaction is also fixed.

Fix updating before/after dates on pending emails

---

uber/config.py
uber/models/panels.py
uber/templates/group_admin/form.html

You can now set both hours and minutes for any date under [dates], which will let Super MAGFest dealer apps be open for half an hour. Also fixes a bug where submitting a panel app would throw a 500 error for certain event configs, and fixes the "unassign" button on the group admin form to use the right page handler.

Add ability to read minutes for date configs

---

uber/automated_emails.py

Our process for setting up the first admins in the system meant that, if I was too slow giving people admin accounts, they got the generic placeholder claim email. This is confusing, so now we don't send anyone the generic claim email if their badge was created before either dealer launch or prereg, whichever came first. This technically creates a hole in the claim email system but hopefully we aren't creating a ton of random badges before dealer/prereg launch.

Don't send generic claim email to first admins

---

alembic/versions/7c43e4352bb0_add_expiration_date_to_watchlist_entries.py
uber/forms/__init__.py
uber/forms/security.py
uber/migration.py
uber/model_checks.py
uber/models/admin.py
uber/site_sections/preregistration.py
uber/site_sections/security_admin.py
uber/tasks/__init__.py
uber/tasks/security.py
uber/templates/registration/attendee_watchlist.html
uber/templates/security_admin/index.html
uber/templates/security_admin/watchlist_form.html

Fixes https://jira.magfest.net/browse/MAGDEV-1210. Watchlist entries past their expiration date are set inactive every 12 hours. Matched attendees for expired entries do NOT automatically get cleared for attending, but they are listed on the watchlist page so admins can easily clear them manually.
Also converts the watchlist form to the new form system, and shows the watchlist creation and last updated date on the form. The last updated date is also shown on the index page.

Add expiration date for watchlist entries

---

uber/models/department.py

It turns out the code adds assigned departments through a relationship that had been marked as viewonly. This removes the viewonly marker, which is the quick fix.
The real fix is to adjust how we edit relationships like this -- the heavy abstraction of routing everything through the set_relation_ids functions means that it's difficult to tell which relationships can be made viewonly and which can't. We already have to define setter functions anyway, we might as well require that you specify what class and relationship should be used.

Make assigned departments editable again

---

uber/models/__init__.py
uber/site_sections/accounts.py
uber/site_sections/mivs_admin.py
uber/site_sections/preregistration.py
uber/site_sections/saml.py
uber/utils.py

Fixes creating MIVS judges. Also refactors creating a new hash into a utility function, since the encoding/decoding involved makes it complicated enough to warrant its own function. I'm hoping this will also fix whatever bug sometimes causes people's admin passwords to not work, but I have no way to reproduce that so we'll see.

Refactor password hashing

---

uber/config.py
uber/decorators.py

We already have a c.PATH used in absolute URLs, this extra c.PATH wasn't working correctly and was only used in one place.

Remove c.PATH property for getting site section

---

uber/automated_emails.py
uber/templates/emails/placeholders/band.txt

Plugs one of the holes in our 'badge claim' email system by adding an email for guests in Band groups.

Add band claim email

---

uber/config.py

Fixes an issue where we were double-counting claimed promo codes in our badge counts.

Fix promo group code counting

---

uber/automated_emails.py

When we got rid of Sideboard, we changed the template structure of Uber enough that it broke the links we were building to go to email templates. This fixes that.

Fix email template links

---

uber/forms/attendee.py
uber/templates/forms/attendee/personal_info.html

I accidentally removed this during the forms rewrite last year, which caused issues with dozens of attendees having invalid email addresses. This adds it back.
Technically, the confirmation box appears when you claim your placeholder badge but it's not required to have any data in it. This is due to the core workflow with placeholder handling that we need to deal with later. Everything else should be working correctly.

Add email address confirmation input

---

uber/forms/attendee.py
uber/templates/forms/attendee/personal_info.html

Makes the confirm email input optional for events, controlled by the prereg_confirm_email_enabled flag.

Use prereg_confirm_email_enabled flag

---

uber/config.py
uber/templates/forms/attendee/badge_extras.html

In some cases, SHIRT_OPTS and STAFF_SHIRT_OPTS would be erroneously considered different from each other due to sorting. Additionally, in cases where the staff shirt and shirt opts were the same but all staff get a shirt, the form would hide the shirt size option. This fixes both issues.

Fix form bugs with staff shirts

---

uber/config.py
uber/configspec.ini
uber/templates/preregistration/group_members.html

We were using the configurable editable_status list to control whether or not dealers could cancel their own applications, but Super needs them controlled separately. Now you can let dealers edit their application, but not let them cancel it.

Add cancellable status list for dealers

---

uber/automated_emails.py

The email template path is actually different in the main plugin vs the root repo, so we need to account for that difference when building links to GitHub.

Also fix template URLs for plugins

---

uber/automated_emails.py

Stops the generic placeholder emails from being sent to people who qualified for the staff import emails. Also sets them to need approval so we can make sure in the future they only start going out after we're ready for badges to be claimed.

Fix generic placeholder emails

---

uber/templates/preregistration/new_badge_payment.html

This should fix the 500 error about a missing csrf token when clicking the "Undo Extras" button.

Fix 'reset receipt' link

---

uber/site_sections/statistics.py

Someone at MAGStock has no age group label for some reason, causing the summary page to throw a 500 error. This should work around the issue.

Fix statistics summary 500 error

---

uber/automated_emails.py
uber/tasks/email.py

People with just regular attendee badges were tripping the volunteer_placeholder email check because it didn't check a.staffing. They then (correctly) didn't actually get sent the volunteer email because they were not volunteering. Now the volunteer_placeholder function includes a.staffing so people can actually qualify for the generic placeholder.
Also fixes an issue where deferred attendees would also qualify for the generic placeholder because I was checking the truthiness of the function itself instead of calling it.

Fix the generic placeholder email for attendees

---

uber/models/attendee.py
uber/templates/group_admin/dealers.html

Found this while working on something else -- if you had a group badge with an add-on, "amount unpaid" would actually remove your badge cost from your receipt total. Now it will not.

Fix amount_unpaid for group badges with receipts

---

uber/site_sections/other_reports.py

The old XML report is now a CSV that you can actually use.

Update food eligible report

---

uber/model_checks.py
uber/site_sections/panels.py
uber/templates/panels_admin/index.html

This was broken when I fixed the poc_id being set for guest panels. We now only check the panels deadline on the default panel submission page.

Allow guests to submit panels after deadline

---

uber/models/__init__.py
uber/site_sections/mivs.py
uber/templates/mivs/index.html
uber/templates/mivs/login_explanation.html

We haven't had an actual MIVS studio login for at least five years, which is as far back as I can check. Now we redirect to this explanation page instead of the blank studio page, which was confusing people.

Replace missing login page for MIVS

---

uber/automated_emails.py
uber/templates/emails/mivs/game_reminder.txt

There's a reminder for incomplete games, but no reminder for MIVS studios that didn't even start a game. This adds one.

Add reminder for gameless MIVS studios

---

uber/automated_emails.py
uber/receipt_items.py
uber/site_sections/dealer_admin.py
uber/templates/emails/dealers/claim_badge.html

Fixes a couple bugs when calculating the receipt changes for dealers being converted to individual badges. Also adds an optional reminder email to poke dealers before the prereg hotel cut-off date.

Fix dealer conversion and add reminder email

---

uber/configspec.ini
uber/model_checks.py
uber/payments.py
uber/site_sections/mits.py
uber/templates/forms/attendee/admin_badge_extras.html
uber/templates/forms/attendee/badge_extras.html
uber/templates/mivs_judging/game_review.html

Several minor fixes that came up during staff badge launch, most notably a 500 error for MITS, a couple error debug logs left in, and the staff shirt size not being optional.

Staff badge launch fixes

---

uber/configspec.ini
uber/site_sections/preregistration.py
uber/site_sections/reg_admin.py

Adds a new exclude_fees_from_refunds option (default true) that allows you to control if self-service refunds exclude processing fees or not. This option is disabled for anyone not using Stripe, since we rely on Stripe's API to calculate the processing fee for transactions.

Enable self-service refunds excluding fees

---

uber/config.py
uber/configspec.ini
uber/menu.py
uber/models/__init__.py
uber/models/attendee.py
uber/site_sections/group_admin.py
uber/site_sections/registration.py
uber/templates/forms/attendee/admin_badge_flags.html
uber/templates/registration/pending_badges.html

Fixes https://magfest.atlassian.net/browse/MAGDEV-1331 by adding a new setting that makes ALL non-registration-admin badges pending. Also updates under what circumstances you can change the badge status to both accommodate this change (so you can't just immediately set the badge status from Pending to New) and to better manage how we handle badges on the watchlist.

Update how pending badges work

---

uber/models/__init__.py
uber/models/attendee.py
uber/models/guests.py
uber/site_sections/guest_reports.py
uber/site_sections/panels_admin.py
uber/templates/group_admin/guests.html
uber/templates/guest_admin/checklist_info.html
uber/templates/guest_checklist/band_panel_deadline.html
uber/templates/guest_checklist/guest_panel_deadline.html
uber/templates/guest_checklist/panel_deadline.html
uber/templates/panels/guest.html

We had very old data in the panel-related info of the guest checklist CSV. Also, panel_applications means applications ASSIGNED to someone as POC and not applications they have submitted. I added a new relationship for submitted apps and changed the guest plugin to rely on those, which should fix various display errors on the checklist.

Fix how guest panels are handled

---

alembic/versions/128e7228f182_add_ability_to_opt_out_of_free_shirts.py
uber/configspec.ini
uber/models/attendee.py
uber/site_sections/staffing.py
uber/templates/staffing/shirt_item.html
uber/templates/staffing/shirt_size.html

Fixes https://magfest.atlassian.net/browse/MAGDEV-1335.

Allow opt-out of free shirts

---

uber/decorators.py
uber/site_sections/reg_reports.py

This switches to using generators when rendering Jinja templates with the `@render` decorator. With that pages can be streamed to the client by setting the `response.stream` property to `True` on the exposed pageview function.
For now I'm just enabling this on the Attendee Receipt Discrepancies page until more get tested.

Add Streaming Responses

---

uber/decorators.py

This removes the explicit call to expunge_all prior to returning the page generator. Instead we rely on the SessionManager to call session.close() during `__exit__` which should also handle expunging objects.

Fixing detached db objects

---

uber/site_sections/reg_reports.py

This re-wraps the query to avoid a cartesian join, speeding up the discrepancies page from ~90 seconds to ~100ms

Speeding up attendee_receipt_discrepancies

---

uber/templates/api/index.html
uber/templates/attractions_admin/checkin.html
uber/templates/attractions_admin/event.html
uber/templates/attractions_admin/form.html
uber/templates/attractions_admin/index.html
uber/templates/dept_admin/form.html
uber/templates/dept_admin/index.html
uber/templates/dept_admin/requests.html
uber/templates/dept_checklist/overview.html
uber/templates/group_admin/guests.html
uber/templates/group_admin/mivs.html
uber/templates/guest_reports/rock_island.html
uber/templates/promo_codes/generate_promo_codes.html
uber/templates/registration/attendee_shifts.html
uber/templates/shifts_admin/job_renderer.html
uber/templates/shifts_admin/signups.html
uber/templates/shifts_admin/unfilled_shifts.html

Fixes the department management page in particular to use the new Bootstrap button classes instead of the old ones. Also does a quick find-replace for all btn-xs and btn-plain classes, which are deprecated.

Fix broken button classes

---

uber/site_sections/panels.py

If a guest submitted a panel with any other panelists listed, a variable collision removed the 'submitter' panelist object we create to tie the panel to the guest group. Fixes https://magfest.atlassian.net/browse/MAGDEV-1332.

Fix guest-submitted panel apps

---

uber/config.py
uber/models/__init__.py
uber/models/commerce.py
uber/site_sections/staffing.py
uber/templates/base.html
uber/templates/signup_base.html
uber/templates/staffing/credits.html
uber/templates/staffing/emergency_procedures.html
uber/templates/staffing/food_restrictions.html
uber/templates/staffing/hotel.html
uber/templates/staffing/index.html
uber/templates/staffing/onsite_jobs.html
uber/templates/staffing/shifts.html
uber/templates/staffing/shirt_size.html
uber/templates/staffing/volunteer.html
uber/templates/staffing/volunteer_agreement.html

Fixes https://magfest.atlassian.net/browse/MAGDEV-1198, including:
- Swapping the existing calendar widget for one that doesn't have nested scrolling, improving experience on mobile devices
- Adding a "details" box when you click on an event in the calendar view, allowing you to use the calendar view on mobile without text spilling out everywhere
- Showing which department each shift is in and how many slots it has filled out of its total, and allowing you to highlight empty shifts
- A ton of other improvements, including making sure you never need to refresh the page (this is to prevent your view getting reset -- everything is purely clientside so saving its state is pretty difficult) and allowing you to filter by department

Completely overhaul signups view

---

uber/site_sections/staffing.py
uber/templates/staffing/shifts.html

This should (hopefully) dramatically improve the performance of the signups calendar by rewriting the call for assigned shifts so it stops generating so many DB queries.
There's less that we can immediately do about the call for available jobs, since there's so much processing that happens to figure out what jobs you can actually sign up for. We'll want to tackle that later, but in the meantime, we've added caching to the page so that switching to List view no longer re-fetches jobs from the server (thank you Hayley!).
We also now update the "you are signed up for X hours" text when you sign up for and drop a shift, so people don't have to refresh the page to see their current hours total.

Improve performance of signups calendar

---

uber/site_sections/staffing.py
uber/templates/staffing/shifts.html

Fixes https://magfest.atlassian.net/browse/MAGDEV-1218.

Add setup/teardown night warning to shifts

---

uber/menu.py
uber/models/mits.py
uber/models/mivs.py
uber/tasks/panels.py
uber/templates/schedule_reports/index.html

Adds a bunch of fixes/updates to the new schedule changes list:
- No longer exports header/thumbnail for MIVS and MITS if there isn't a designated header/thumbnail
- Displays old session names if the name changed, as that's how we would find the session to change in Guidebook
- Changes the email address the at-con update notifications get sent to
- Fixes linebreaks in data so that they render correctly on the page
- Adds a link to the changes list to the top bar menu (under "Schedule")
- Only shows the "View" link next to items if it goes to a public page or if you have access
Unfortunately, while Guidebook only accepts XLS files and not XLSX files, our xlsxwriter library will not output XLS files. We could output CSV files instead but that invites encoding errors if anyone opens the file …

Update schedule changes list based on review

---

uber/templates/attractions_admin/form.html
uber/templates/base.html

We might want to put the link to an attraction on the schedule without actually making it public. This change adds a "Copy Link" button to each feature to help with that.

Add ability to copy link to attraction features

---

uber/configspec.ini
uber/models/panels.py
uber/tasks/panels.py
uber/templates/emails/guidebook_deletes.txt
uber/templates/emails/guidebook_updates.txt
uber/templates/schedule_reports/index.html

Adds a report for deleted items that were synced to Guidebook. Also fixes a bug with the AJAX on the schedule changes page, and fixes an issue where panel updates were changing their respective events but NOT making those event changes show on the schedule changes page.

Add more improvements to Guidebook syncing

---

uber/config.py
uber/configspec.ini
uber/forms/attendee.py
uber/templates/forms/attendee/personal_info.html
uber/utils.py

lets try this again with a new branch name....
Sets collect birthdays to true
Restores ability to have age categories
Sets up some sane (?) defaults in age categories

Fix Age Config Defaults and Operation

---

uber/api.py
uber/models/department.py
uber/templates/shifts_admin/job_renderer.html
uber/utils.py

Updates how we export and import attendees' departments:
- Stops importing department requests, which are not useful to import year to year -- either someone was accepted to a department or they weren't
- Excludes assigned departments if someone did not sign up for shifts in that department, unless they are a POC/checklist admin/department head or unless the department is marked as shiftless -- this should help cull the dozens of extra staffers in departments like registration
- Imports staffers with their roles in their respective departments (https://magfest.atlassian.net/browse/MAGDEV-426)
Not fully tested yet, will be testing this on the staging servers.

Update department and roles importing

---

uber/site_sections/dealer_admin.py
uber/templates/forms/group/table_info.html

Fixes https://magfest.atlassian.net/browse/MAGDEV-1400. If you wanted to send a custom message when waitlisting or declining a dealer, you couldn't decline a dealer without converting their badges. It also wasn't clear what converting actually did, since the link explaining it doesn't show up until someone is declined. This adds a new decline button and a link to the converted badge explanation, and also makes some feedback better when you don't reject + convert.

Add 'decline' button for dealer custom messages

---

uber/models/attendee.py
uber/templates/staffing/shifts_item.html

We weren't actually enforcing the shifts_created date properly. Our event plugins also had very similar override templates for the shifts_item, so this combines them into one.

Fix shifts item on volunteer checklist

---

uber/models/attendee.py
uber/templates/staffing/shifts_item.html

We weren't actually enforcing the shifts_created date properly. Our event plugins also had very similar override templates for the shifts_item, so this combines them into one.

Fix shifts item on volunteer checklist (West and Stock)

---

uber/config.py
uber/configspec.ini
uber/forms/hotel_lottery.py
uber/model_checks.py
uber/models/hotel.py
uber/site_sections/hotel_lottery.py
uber/templates/confirm_tabs.html
uber/templates/emails/hotel/entry_details.html
uber/templates/emails/hotel/hotel_lottery_entry.html
uber/templates/hotel_lottery/contact_info_form.html
uber/templates/hotel_lottery/index.html
uber/templates/hotel_lottery/lottery_tos.html
uber/templates/hotel_lottery/room_lottery_form.html
uber/templates/hotel_lottery/suite_lottery_form.html
uber/templates/hotel_lottery/terms.html
uber/templates/hotel_lottery_admin/form.html
uber/templates/preregistration/confirm.html
uber/templates/registration/menu.html

Includes several changes to the hotel lottery entry system -- several of these are actually requested by MFF but made sense to do in this fork first:
- Make the hotel lottery entry system work when attendee accounts are turned off
- Allow switching between Suite and Room hotel entry types
- Limit characters for hotel room group names
- Move name/phone entry to first step so that it is required for ALL entrants, including room group members
- Add link to the hotel lottery entry on /registration/form
- Update validation wording based on feedback
- Warn before closing your hotel lottery form if you've made changes

Update hotel lottery form for MAGFest

---

uber/site_sections/tabletop_checkins.py

Fixes the tabletop checkin query that got missed due to branch ordering when rewriting that section of the site.

Fix Tabletop Query to new Badge Info

---

uber/config.py
uber/configspec.ini
uber/forms/panels.py
uber/models/mits.py
uber/models/showcase.py
uber/validations/panels.py

Restricts panel name length, updates the title and subtitle for MIVS/MITS guidebook exports, and cleans up an orphaned set of form options.

Update panel application and guidebook exports

---

alembic/versions/b561dae06c39_add_check_in_and_check_out_times_and_.py
uber/config.py
uber/configspec.ini
uber/model_checks.py
uber/models/guests.py
uber/site_sections/guest_reports.py
uber/site_sections/guests.py
uber/templates/guest_checklist/merch_deadline.html
uber/templates/guest_reports/rock_island.html
uber/templates/guests_macros.html

Adds an explicit dropdown for check-in and check-out times, removes the Quantity field for inventory items, and replaces the per-inventory-item Sample Tracks field with a per-guest Sample Tracks field.
Hopefully the nginx limit on our servers is 100MB because that's what I went with for upload limit size. If it's smaller, people uploading a lot of tracks will run into an ugly error message. We should in the future figure out a better way to handle file uploads and downloads in a consistent fashion.

Update Rock Island checklist step for 2025

---

uber/automated_emails.py

We ended up with some placeholders not yet sent by the time we went to at-con, so they want them to go out late.

Enable all placeholder emails at the con

---

uber/templates/dept_admin/form.html
uber/templates/dept_admin/index.html
uber/templates/forms/department/department_info.html

what it sayeth on the tin. Display is now integers, can remove that if other screens shouldnt have it, but the form value w/ kwargs needs the // integer division only operator.

make consecutive hours whole minutes
