- uber/automated_emails.py
- uber/configspec.ini
- uber/templates/emails/guests/guest_checklist_announce.html
- uber/templates/emails/guests/guest_checklist_reminder.html
Fixes https://jira.magfest.net/browse/MAGDEV-325.
> Update signature line for guest checklist emails

- uber/templates/dept_checklist/hotel_setup.html
New link for the 2019 version of the form
> Update supermag 2019 hotel dept head checklist

- uber/templates/dept_checklist/logistics.html
updating the checklist to include this year's Super MAGFest logistics form.
> 2019 logistics form

- uber/configspec.ini
- uber/decorators.py
- uber/server.py
- we're seeing errors related to facebook passing in fbclid randomly
WIP: NOT TESTED.  it should work, I just don't have a valid dev environment at the moment, so leaving this up to the experts to merge or use if you guys want.
could probably use a unit test for scrub_kwargs_for_junk()
> filter incoming kwargs for junk params

- uber/models/mits.py
- uber/site_sections/mits_admin.py
- uber/templates/mits_admin/badges.html
- uber/templates/mits_admin/teams_and_badges.html
Fixes https://jira.magfest.net/browse/MAGDEV-321. The report in question is organized by team -- hopefully this is desirable. It looks like this:
> Add Indie Dev ribbon to new MITS badges and report of said MITS badges

- uber/templates/dept_checklist/treasury.html
Specifically, made sure that known name actually meant nicknames/slack names. Also added highlighting in the instruction about it as an example.
> Updated and clarified some language.

- uber/site_sections/summary.py
We already got this information for Super 2019, but it was a pain to gather. Implement it for future years.
Tested locally, seems to work fine - it uses the same group-by-time mechanism as `graphs.py` - note that sqlite *does not* support date_trunc, so neither this nor `graphs.py` works in sqlite.
> Add summary/checkins_by_hour csv export

- uber/templates/preregistration/check_if_preregistered.html
Fixes https://jira.magfest.net/browse/MAGDEV-354.
> Adjust check-if-preregistered page wording

- uber/templates/signups/shirt_item.html
> Fix shirt step to check `attendee` instead of `self`

- uber/automated_emails.py
- uber/menu.py
https://github.com/magfest/ubersystem/pull/3371 broke emails, but because I was working on my own branch I didn't realize it. This fixes the error, plus an error in creating the MIVS menu item from https://github.com/magfest/ubersystem/pull/3373.
> Fix emails broken by MIVS changes

- uber/site_sections/hotel_assignments.py
Fixes https://jira.magfest.net/browse/MAGDEV-284.
> Add room emails to Mark Center and Gaylord CSVs

- uber/site_sections/mits_admin.py
Fixes https://jira.magfest.net/browse/MAGDEV-367.
> Account for teams without showcase requests in MITS showcase export

- uber/models/mivs.py
- uber/site_sections/mivs_admin.py
Fixes https://jira.magfest.net/browse/MAGDEV-372. Note that you need to open the file in something that's not Excel for it to be a comma-separated list.
> Add CSV export of email addresses for the MIVS discussion group

- uber/templates/jobs/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-256.
Looks like this:
> Make filled shifts darker on the shift calendar

- uber/automated_emails.py
- uber/models/mivs.py
- uber/templates/emails/mivs/mivs_checklist_reminder.txt
Fixes https://jira.magfest.net/browse/MAGDEV-365.
> Add list of items due soon to MIVS checklist reminders

- uber/models/group.py
Fixes https://jira.magfest.net/browse/MAGDEV-381.
> Use IndieStudio email is a group has an IndieStudio

- uber/site_sections/hotel_assignments.py
Fixes https://jira.magfest.net/browse/MAGDEV-382.
> Add simplified hotel export for emails, with preferred names

- alembic/versions/d1ae7f4f7767_add_electronic_waiver_to_mits.py
- uber/automated_emails.py
- uber/models/mits.py
- uber/site_sections/mits_admin.py
- uber/site_sections/mits_applications.py
- uber/templates/emails/mits/mits_waiver.txt
- uber/templates/mits_admin/accepted.html
- uber/templates/mits_applications/index.html
- uber/templates/mits_applications/waiver.html
Fixes https://jira.magfest.net/browse/MAGDEV-320.
> Add MITS waiver for accepted teams to sign electronically

- uber/site_sections/mits_applications.py
- uber/templates/mits_applications/accepted_teams.html
Fixes https://jira.magfest.net/browse/MAGDEV-311.
Looks like this:
Not sure if we want to include any other info or tweak the display at all. This is just what I came up with.
> Add page listing accepted MITS teams

- uber/site_sections/departments.py
(From devops channel):
Is there a way to get a report of staffers who have signed up for more than the consecutive number of hours in a row limit? Usecase is it was set to 0, we just set it to 12, and want to see if anyone is over the limit.
> Add consecutive hour shift violation report

- uber/site_sections/departments.py
I accidentally used `>=` instead of `>` in two places - this included shifts in the report that were exactly on-the-limit, whereas they should be okay (and not included).
Also, it's using `session.query(Attendee).filter(Attendee.staffing == True).all()` instead of `session.query(Attendee).all()`, hopefully this improves performance a bit.
> Fix overworked_attendees report and clean it up a bit

- uber/templates/emails/shifts/reminder.txt
Adds a sentence about when we count shifts for volunteer perks.
> Add perks deadline to volunteer shift reminder

- uber/site_sections/hotel_assignments.py
Fixes https://jira.magfest.net/browse/MAGDEV-386. Hopefully.
> Update hotels export for Gaylord

- uber/site_sections/graphs.py
- uber/site_sections/summary.py
sqlite does not support `date_trunc` :'(
> Use compatible datetime functions for sqlite

- uber/site_sections/departments.py
This is just a minor thing, but it's nice to have
> Report times in local time, not UTC.

- uber/automated_emails.py
- uber/models/mits.py
- uber/templates/emails/dealers/badge_converted.html
- uber/templates/emails/mits/mits_faq.html
- uber/templates/emails/mits/mits_parking.txt
- uber/templates/emails/mits/mits_tax_form.txt
- uber/templates/mits_applications/waiver.html
Fixes https://jira.magfest.net/browse/MAGDEV-399. Fixes https://jira.magfest.net/browse/MAGDEV-387.
> Add MITS automated emails for the tax form and parking info

- uber/site_sections/accounts.py
Reg was like "hey, where's that dang page again?"
turns out finding URLs is way easier when things are site mapped :P
> Add @site_mappable to accounts/bulk

- uber/site_sections/attractions_admin.py
Fixes https://jira.magfest.net/browse/MAGDEV-275.
> Add badge name and number to Attraction export

- uber/templates/summary/volunteer_hours_overview.html
> Fix copy-paste errors in the new volunteer hours report

- uber/models/tabletop.py
- uber/site_sections/tabletop_checkins.py
- uber/static/angular-apps/tabletop_checkins/game_list.html
- uber/templates/tabletop_checkins/checkout_history.html
Fixes https://jira.magfest.net/browse/MAGDEV-401.
Looks like:
> Add checkout history for tabletop games

- uber/api.py
Fixes https://jira.magfest.net/browse/MAGDEV-407. I also added an API call for MIVS teams, though I belatedly realized that using the group name is probably better for TOPS after all -- we don't have a team's presence/non-presence at MAGFest actually mapped to a single column. :(
> Add attendees' groups' name to their full API lookup

- uber/automated_emails.py
- uber/templates/emails/shifts/shifts_worked.html
Fixes https://jira.magfest.net/browse/MAGDEV-402.
The email looks like this:
@outlaw-josiah Two things I wasn't sure about -- what should the subject line be? I just made up "Please review your worked shifts for MAGFest!" Also, if a shift is unmarked, should we tell the volunteer that ("Not specified" in the screenshot above) or just say it's not been worked ("No")?
> Add post-con email asking volunteers to review their worked hours

- uber/automated_emails.py
> Allow email to be sent post-con

- uber/automated_emails.py
> Allow shift review email to actually be sent post-con

- alembic/versions/523e3d243395_add_promo_code_groups_to_prereg.py
- alembic/versions/e0c620d341cb_add_cost_tracking_and_registered_date_.py
- uber/automated_emails.py
- uber/config.py
- uber/configspec.ini
- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/promo_code.py
- uber/site_sections/preregistration.py
- uber/templates/attractions/manage.html
- uber/templates/confirm_tabs.html
- uber/templates/emails/reg_workflow/promo_code_group_confirmation.html
- uber/templates/emails/reg_workflow/promo_code_invite.txt
- uber/templates/groupform.html
- uber/templates/preregistration/add_promo_codes.html
- uber/templates/preregistration/banned.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/duplicate.html
- uber/templates/preregistration/group_promo_codes.html
- uber/templates/preregistration/hotel.html
- uber/templates/preregistration/index.html
- uber/templates/regform.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-421.
> Add promo code groups

- uber/configspec.ini
- uber/templates/base.html
Fixes https://jira.magfest.net/browse/MAGDEV-435.
> Add Uber Guide to the top right admin menu

- uber/config.py
- uber/templates/preregistration/disclaimers.html
- uber/templates/regform.html
Update for https://jira.magfest.net/browse/MAGDEV-430
> Improve disclaimer styling and pii_consent checkbox location

- uber/site_sections/preregistration.py
Fixes https://jira.magfest.net/browse/MAGDEV-445. Whoops.
> Don't try to pull the promo code's group name if it doesn't have a group

- uber/config.py
- uber/configspec.ini
- uber/models/attendee.py
- uber/templates/panel_applications/index.html
- uber/templates/preregistration/disclaimers.html
- uber/templates/regform.html
- uber/templates/static_views/stafferComps.html
Adds a bunch of small fixes related to implementing West pre-reg (https://jira.magfest.net/browse/MAGDEV-446)
> Fixes for west prereg

- uber/config.py
- uber/templates/preregistration/disclaimers.html
- uber/templates/preregistration/preregbase.html
> Fix bugs and text for MAGWest prereg launch

- uber/menu.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/groups.py
- uber/site_sections/preregistration.py
- uber/templates/groups/promo_code_group_form.html
- uber/templates/groups/promo_code_groups.html
- uber/templates/registration/form.html
- uber/templates/registration/index_base.html
Fixes https://jira.magfest.net/browse/MAGDEV-439.
> Add admin-side support for Promo Code Groups

- uber/menu.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/groups.py
- uber/site_sections/preregistration.py
- uber/templates/groups/promo_code_group_form.html
- uber/templates/groups/promo_code_groups.html
- uber/templates/registration/form.html
- uber/templates/registration/index_base.html
Reverts magfest/ubersystem#3459 -- I'll fix that 500 error properly before merging this.
> Revert "Revert "Add admin-side support for Promo Code Groups""

- uber/site_sections/preregistration.py
> Stop setting badges to zero for dealer applications

- uber/templates/groups/form.html
- uber/templates/guest_admin/index.html
- uber/templates/panel_app_management/app.html
- uber/templates/panel_app_management/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-456 by adding a column for guest type to the panels list, and a link to the guest group on the admin view of a panel application.
> Add guest group information to panel list and form

- uber/templates/fields/attendee.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/register_group_member.html
- uber/templates/preregistration/transfer_badge.html
- uber/templates/registration/form.html
Fixes https://github.com/magfest/ubersystem/issues/3472. Fixes https://jira.magfest.net/browse/MAGDEV-440. Also fixes some bugs I found with the new modular fields and enables the email confirmation field for ALL new attendees and not just the ones on the prereg form.
> Stop always resetting badges to Attendee badges + misc template fixes

- uber/automated_emails.py
This will be reverted once the email gets sent out.
> Temporarily expand the window for the hotel room space email for West

- uber/api.py
added new API lookup method intended to be used as a login method that checks against the Magfest attendee records.
Was unable to test before submitting pull request, please deploy to Staging only so I can see if it crashes anything!
> Login method for API

- uber/automated_emails.py
Reverts magfest/ubersystem#3476, as intended.
> Revert "Temporarily expand the window for the hotel room space email for West"

- uber/site_sections/registration.py
- uber/templates/fields/attendee.html
- uber/templates/preregistration/form.html
- uber/templates/registration/register.html
Our at-door reg page never got updated for the modular forms. Whoops! Also fixes a minor bug where people registering might get no banner message, and presold one-day badges were being hidden if it wasn't currently the day on the badge.
> Fix At-Door registration page

- uber/templates/fields/group.html
- uber/templates/groups/form.html
- uber/templates/preregistration/form.html
Various fixes for Super dealer applications.
> Fix dealer application form

- uber/config.py
Fixes https://jira.magfest.net/browse/MAGDEV-543.
> Add missing datetime.date import

- uber/automated_emails.py
- uber/site_sections/preregistration.py
I'll get everything updated properly someday, I swear.
> Fix capitalization for email subject lines

- uber/models/__init__.py
- uber/site_sections/staffing_admin.py
Somehow I didn't test the very last change I made. I'd also never tested creating a new database from scratch, so this fixes the bug involved in that as well.
> Fix last-minute bulk import bug and new admin creation

- uber/models/mivs.py
- uber/site_sections/mivs.py
- uber/templates/mivs/developer.html
- uber/templates/mivs/developer_agreements.html
- uber/templates/mivs/studio.html
We need the MIVS presenters to check some boxes! Text provided by legal.
> Add legal fields for MIVS presenters

- alembic/versions/8888a0f4c1ef_add_code_of_conduct_and_data_policy_.py
A file that got missed from https://github.com/magfest/ubersystem/pull/3503.
> Include the database migration this time

- uber/model_checks.py
This series of pull-requests is an illustrative example of why you never work on the weekend, kids.
> Add serverside validation checks for MIVS developers

- uber/automated_emails.py
- uber/templates/emails/placeholders/imported_volunteer.txt
Fixes https://jira.magfest.net/browse/MAGDEV-565.
> Update imported staff email

- uber/templates/emails/shifts/reminder.txt
Fixes https://jira.magfest.net/browse/MAGDEV-567.
> Remove Super-specific text from shifts reminder

- uber/model_checks.py
If we aren't collecting the full address, we don't set the country, so we need to account for that!
> check for collecting full address for zip verify

- uber/api.py
- uber/site_sections/reg_admin.py
- uber/site_sections/staffing_admin.py
- uber/utils.py
While working on figuring out how to best import staff from prior years, I ended up doing a lot of cleanup of the attendee and department imports. This also fixes a bug where using the API reference page always returned a forbidden error.
> Use same utility functions for attendee and department imports

- uber/model_checks.py
updated check to mirror the one coded for amount_extra
> Fix Extra Donation bug

- uber/configspec.ini
Default to just "MAGFest, Inc"
> Remove old Affiliates list

- uber/api.py
- uber/config.py
- uber/custom_tags.py
- uber/decorators.py
- uber/model_checks.py
- uber/models/__init__.py
- uber/models/admin.py
- uber/site_sections/accounts.py
- uber/site_sections/api.py
- uber/site_sections/dept_admin.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/templates/emails/accounts/new_account.txt
- uber/utils.py
I missed a spot! ... or several!
> Fix various admin code errors found in Super

- uber/configspec.ini
- uber/templates/fields/attendee.html
Fixes https://jira.magfest.net/browse/MAGDEV-572.
> Update prereg page text based on lawyer input

- uber/templates/fields/group.html
add missing 'to', clarify restriction
> Fix additional group badges text

- uber/models/attendee.py
- uber/site_sections/hotel_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-563. The hotel_reports file was missing some necessary imports, though I have no idea how they ended up inside the attendee.py model file.
> Add missing imports for hotel requested info export

- uber/model_checks.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/preregistration.py
- uber/site_sections/registration.py
- uber/templates/fields/attendee.html
- uber/templates/registration/promo_code_group_form.html
- uber/templates/registration/promo_code_groups.html
Fixes https://jira.magfest.net/browse/MAGDEV-581.
> Gives admins ability to create and add to promo code groups

- uber/models/__init__.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/fields/attendee.html
- uber/templates/reg_admin/receipt_items.html
- uber/templates/registration/history.html
- uber/templates/registration/menu.html
Fixes https://jira.magfest.net/browse/MAGDEV-589. The UX of the receipt item management page was somewhat tricky to design, but hopefully will work okay.
> Add receipt item management for admins

- uber/models/attendee.py
- uber/site_sections/preregistration.py
- uber/templates/preregistration/badge_updated.html
Fixes https://jira.magfest.net/browse/MAGDEV-571.
> Allow attendees in promo code groups to transfer or abandon their badge

- uber/model_checks.py
- uber/models/mivs.py
Fixes https://jira.magfest.net/browse/MAGDEV-561. Also fixes https://jira.magfest.net/browse/MAGDEV-562.
> Require showtime and liability agreements from MIVS studios

- uber/templates/guest_checklist/autograph_deadline.html
- uber/templates/guest_checklist/guest_badges_deadline.html
- uber/templates/guest_checklist/guest_charity_deadline.html
- uber/templates/guest_checklist/guest_panel_deadline.html
- uber/templates/guest_checklist/merch_deadline.html
- uber/templates/guest_checklist/travel_plans_deadline.html
- uber/templates/preregistration/group_members.html
Fixes https://jira.magfest.net/browse/MAGDEV-597.
> Update text on guest checklist

- uber/site_sections/hotel_reports.py
We found out at the last minute that the new format for the hotel export caused a 504 error, and had to make an emergency commit (https://github.com/magfest/ubersystem/commit/d64bde9e23ec25b57d4eeae1790331b5c85332c4) to get the export out in time. We still want that format though, so this is a version of the export that has the right format and didn't cause 504 error on my local system (I added 10k placeholder attendees to test).
Also fixes a bug that caused 'late' comped badges to not actually be included in the export. Whoops.
> Fix performance issues for Hotel Export

- uber/templates/emails/guests/guest_checklist_announce.html
- uber/templates/emails/guests/guest_checklist_reminder.html
- uber/templates/emails/placeholders/guest.txt
Fixes https://jira.magfest.net/browse/MAGDEV-603. https://jira.magfest.net/browse/MAGDEV-604. https://jira.magfest.net/browse/MAGDEV-605. https://jira.magfest.net/browse/MAGDEV-606.
> Update Guest Checklist email text

- uber/templates/guest_checklist/merch_deadline.html
Fixes https://jira.magfest.net/browse/MAGDEV-611.
> Add region_opts to Guest Group merch page

- uber/templates/guest_checklist/band_merch_deadline.html
- uber/templates/guest_checklist/guest_merch_deadline.html
- uber/templates/guest_checklist/merch_deadline.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-616.
> Update text for band merch deadline

- alembic/versions/c36659e7f238_add_rehearsal_checklist_step_for_bands.py
- uber/config.py
- uber/configspec.ini
- uber/models/guests.py
- uber/site_sections/guests.py
- uber/templates/guest_checklist/rehearsal_deadline.html
- uber/templates/guests/rehearsal.html
Fixes https://jira.magfest.net/browse/MAGDEV-288.
> Add rehearsal deadline for bands

- uber/models/guests.py
- uber/templates/guest_checklist/merch_deadline.html
Also adds text to clarify which parts of the Rock Island page need to be filled out.
> Fix Rock Island address and guest checklist URLs

- uber/templates/emails/guests/band_merch_reminder.txt
Fixes https://jira.magfest.net/browse/MAGDEV-619.
> Update Band merch reminder text

- uber/templates/emails/mivs/judging/judge_welcome.txt
- uber/templates/guest_checklist/bio_deadline.html
Fixes https://jira.magfest.net/browse/MAGDEV-620. Also updates the text on the new MIVS email.
> Fix bug hiding bio pic upload

- uber/models/attendee.py
- uber/site_sections/preregistration.py
- uber/templates/preregistration/badge_refund.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-613 and fixes self-service refunds. Fixes https://jira.magfest.net/browse/MAGDEV-595. Fixes https://jira.magfest.net/browse/MAGDEV-576.
> Fix issues with payments and receipt items

- uber/templates/emails/dealers/approved.html
> Make dealer app loss upon non-payment clearer

- uber/templates/dept_checklist/hotel_requests.html
- uber/templates/dept_checklist/hotel_setup.html
- uber/templates/dept_checklist/logistics.html
- uber/templates/shifts_admin/form.html
- uber/templates/shifts_admin/index.html
Fixes part of https://jira.magfest.net/browse/MAGDEV-637. Requires https://github.com/magfest/infrastructure/pull/175.
> Update text for department head checklist items

- uber/templates/dept_checklist/treasury.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-637.
> Update treasury to use just google form

- uber/configspec.ini
- uber/templates/dept_checklist/hotel_requests.html
- uber/templates/staffing/hotel_item.html
This pull request will collect the changes to uber needed to outsource the hotel roommate request/matching system. The current workflow is planned as follows:
Checklist item for hotel request replaced with link to external hotel system with embedded attendee ID for auth.
External system verifies ID against uber via API.
External system collects requests from staff members, approvals from Department Heads (via department head checklist item), and adjustments from stops.
External system exports CSV files in format compatible with uber's import tool to back-populate request, assignments, and approvals.
> Getting things ready for outsourced hotel request system

- uber/config.py
- uber/models/__init__.py
- uber/site_sections/shifts_admin.py
- uber/templates/shifts_admin/staffers.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-633. Also removes an exploit where admins could see all staffers by manually editing the department_id in the URL to "All," and fixes the 404 error people were getting in certain circumstances.
> Improve access to staffers page

- uber/custom_tags.py
- uber/decorators.py
- uber/menu.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/accounts.py
- uber/site_sections/registration.py
- uber/site_sections/shifts_admin.py
- uber/static/angular-apps/hotel/attendee.html
- uber/static/angular-apps/hotel/schedule.html
- uber/static/angular-apps/tabletop_checkins/app.js
- uber/templates/accounts/index.html
- uber/templates/barcode/index.html
- uber/templates/base.html
- uber/templates/budget/mpoints.html
- uber/templates/dealer_admin/deletion_confirmation.html
- uber/templates/dealer_admin/form.html
- uber/templates/emails/reg_workflow/attendee_watchlist.txt
- uber/templates/group_form_base.html
- uber/templates/mivs_admin/studios.html
- uber/templates/panel_macros.html
- uber/templates/panels_admin/app.html
- uber/templates/promo_codes/index.html
- uber/templates/registration/attendee_data.html
- uber/templates/registration/reg_take_report.html
- uber/templates/staffing_reports/departments.html
Fixes https://jira.magfest.net/browse/MAGDEV-669 (which, surprisingly, was two bugs). Also adds more comprehensive use of the new attendee modal, as well as page logging. Also fixes https://jira.magfest.net/browse/MAGDEV-655.
> Fix 504 error and other attendee-viewing issues

- uber/custom_tags.py
I changed this file right before committing and uploading for https://github.com/magfest/ubersystem/pull/3579, and the change I made didn't get included in the commit for some reason.
> Actually fix custom tags

- uber/models/attendee.py
- uber/site_sections/staffing.py
- uber/templates/staffing/hotel_item.html
- uber/templates/staffing/index.html
- uber/templates/staffing/shirt_size.html
While working on updates to Super's volunteer checklist, I found a few bugs and other things that needed to be changed in the core plugin. Goes with https://github.com/magfest/magprime/pull/305.
> Miscellaneous fixes for volunteer checklist

- uber/templates/emails/shifts/reminder.txt
- uber/templates/emails/shifts/schedule.html
- uber/templates/emails/shifts/shifts_worked.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-644.
> Update text for volunteer checklist emails

- uber/site_sections/dept_checklist.py
- uber/templates/dept_checklist/guidebook_schedule.html
- uber/templates/dept_checklist/printed_signs.html
Also adds a custom page for the printed signs step. Fixes https://jira.magfest.net/browse/MAGDEV-668.
> Add guidebook schedule dept head checklist step

- uber/site_sections/mits.py
- uber/templates/mits/index.html
- uber/templates/mits/schedule.html
- uber/templates/mits/team.html
Fixes https://jira.magfest.net/browse/MAGDEV-621.
> Add MITS showcase consent and info usage text

- uber/site_sections/other_reports.py
- uber/templates/other_reports/guest_donations.html
Fixes https://jira.magfest.net/browse/MAGDEV-692.
> Add report of guest groups' donations for charity

- uber/models/mivs.py
- uber/site_sections/guests.py
- uber/templates/guests/mivs_hotel_space.html
Fixes https://jira.magfest.net/browse/MAGDEV-682.
> Update MIVS checklist deadlines and hotel step

- uber/templates/guests/index.html
- uber/templates/guests/mivs_hotel_space.html
- uber/templates/mivs_admin/index.html
Also adds the new hotel link and fixes a minor bug in the MIVS admin overview page.
> Sort MIVS checklist by deadline

- uber/templates/fields/attendee.html
Fixes https://jira.magfest.net/browse/MAGDEV-672. There was a bug preventing this set of fields from working as intended, but on closer review they were also not set up correctly in some instances. They now behave as intuitively as I could think of.
> Fix behavior of badge num fields

- uber/models/attendee.py
- uber/site_sections/staffing.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-663.
> Add volunteer checklist step for a name in credits

- uber/templates/staffing/index.html
- uber/templates/staffing/shirt_item.html
We have contractors filling out their checklist already, so we need this right now.
> Remove shirt item and add message for contractors

- uber/templates/emails/mivs/2020/strong_versus_2020.txt
This caused a 500 error! Whoops!
> Primary contact field was missing an s

- uber/automated_emails.py
- uber/models/attendee.py
Fixes https://jira.magfest.net/browse/MAGDEV-666.
> Adjust contractor badge treatment

- uber/reports.py
- uber/site_sections/badge_exports.py
Forgot this! Part of https://jira.magfest.net/browse/MAGDEV-666.
> Include contractor badges in staff badge export

- uber/api.py
Reverts magfest/ubersystem#3606. This PR broke the build; we'll have to fix it and re-merge it later.
> Revert "Added attendee update and hotel assigment management methods to API"

- uber/templates/emails/shifts/dept_checklist.txt
Fixes https://jira.magfest.net/browse/MAGDEV-725.
> Update hotel approval dept checklist email

- uber/templates/registration/attendee_data.html
Fixes https://jira.magfest.net/browse/MAGDEV-730.
> Add setup/teardown approval fields to attendee form

- uber/templates/guest_checklist/band_merch_deadline.html
Fixes https://jira.magfest.net/browse/MAGDEV-641.
> Update performer checklist text

- uber/model_checks.py
- uber/models/attendee.py
- uber/site_sections/band_admin.py
- uber/site_sections/group_admin.py
- uber/site_sections/guest_admin.py
- uber/templates/fields/attendee.html
- uber/templates/fields/group.html
- uber/templates/group_admin/form.html
Fixes https://jira.magfest.net/browse/MAGDEV-724.
> Fix universal group form errors

- uber/api.py
The server wouldn't start due to a syntax error. Whoops.
> Add missing comma and re-merge attendee_api branch

- uber/models/mivs.py
- uber/site_sections/mivs_admin.py
- uber/site_sections/mivs_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-630. Also splits the reports for MIVS out from the MIVS Admin section for easier navigation.
> Add timestamp and studio names to MIVS discussion report

- uber/models/group.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/group_admin/nav_menu.html
- uber/templates/reg_admin/receipt_items.html
Fixes https://jira.magfest.net/browse/MAGDEV-742. It turns out the badges themselves were being made, just not the group receipt item. Also adapts the receipt item review page to use in groups, which hadn't been implemented yet.
> Add receipt items correctly when adding group members

- uber/models/panels.py
Fixes https://jira.magfest.net/browse/MAGDEV-743 by fixing the SQLAlchemy cascade on the relationship.
> Stop cascading Event deletions to panel applications

- uber/model_checks.py
- uber/templates/panels_admin/form.html
Fixes https://jira.magfest.net/browse/MAGDEV-713.
> Add unavailability field to admin panel form

- uber/tasks/registration.py
- uber/templates/emails/daily_checks/pending.html
Fixes https://jira.magfest.net/browse/MAGDEV-690 by sending a nightly email if there are pending badges.
> Notify STOPS/Reg about pending badges

- uber/templates/guests/mivs_selling_at_event.html
Per request via email, we're updating the tax info form to be this year's form.
> Update MIVS selling form link

- uber/site_sections/guests.py
- uber/templates/guests/mivs_selling_at_event.html
Fixes https://jira.magfest.net/browse/MAGDEV-758.
> Update MIVS selling checklist item

- uber/templates/guests/mivs_handbook.html
Fixes https://jira.magfest.net/browse/MAGDEV-756.
> Update MIVS handbook link

- uber/api.py
Also reorders the uber.models imports to be alphabetical.
> Add mktime import for ScheduleLookup

- uber/site_sections/dealer_reports.py
- uber/templates/dealer_admin/waitlist.html
Fixes https://jira.magfest.net/browse/MAGDEV-757.
> Add waitlisted seller report

- uber/site_sections/registration.py
Fixes https://jira.magfest.net/browse/MAGDEV-745 by updating the page handler to use the new field name.
> Update omit badge # name on old form

- uber/automated_emails.py
- uber/config.py
- uber/configspec.ini
- uber/models/attendee.py
- uber/site_sections/dept_checklist.py
- uber/templates/emails/hotel/hotel_hours.txt
- uber/templates/emails/hotel/hotel_reminder.txt
- uber/templates/emails/hotel/hotel_rooms.txt
- uber/templates/emails/shifts/shifts_worked.html
- uber/templates/staffing/food_item.html
- uber/templates/staffing/hotel.html
- uber/templates/staffing/printable_schedule.html
- uber/templates/staffing/shirt_item.html
- uber/templates/static_views/stafferComps.html
We had an odd setup for our food hours, and we couldn't turn off shirts if we wanted. This updates how we handle perks to be a bit more consistent.
> Update variables tracking staff perks

- uber/models/attendee.py
- uber/models/department.py
- uber/templates/static_views/visibility.html
Fixes https://jira.magfest.net/browse/MAGDEV-716.
> Change 'public' shifts to not care about requested departments

- uber/models/__init__.py
- uber/site_sections/preregistration.py
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-481. This should also fix https://jira.magfest.net/browse/MAGDEV-596, which is too difficult to reliably reproduce but thereotically is just a slightly different form of the underlying bug.
> Fix prereg promo-code collisions

- uber/site_sections/preregistration.py
> Allow people to prereg without a promo code

- uber/configspec.ini
- uber/site_sections/staffing.py
- uber/templates/staffing/shifts.html
Fixes https://jira.magfest.net/browse/MAGDEV-782.
> Add and enforce a drop_shifts_deadline

- uber/configspec.ini
- uber/templates/guests/mivs_handbook.html
- uber/templates/guests/mivs_training.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-785.
> Make MIVS URLs configurable

- uber/site_sections/registration.py
- uber/templates/registration/form.html
- uber/templates/registration/index_base.html
Fixes https://jira.magfest.net/browse/MAGDEV-790 by adding a form on /registration/index to record an at-door station number. If a number isn't recorded or is set to 0, the payment buttons are hidden on both the index page and the attendee form.
> Add ability to set at-door station

- uber/templates/accounts/bulk.html
Fixes https://jira.magfest.net/browse/MAGDEV-800.
> Use new access groups on /accounts/bulk

- uber/site_sections/registration.py
Fixes https://jira.magfest.net/browse/MAGDEV-794, maybe.
> Joinload promo codes on promo code groups page

- uber/site_sections/registration.py
- uber/templates/registration/promo_code_groups.html
These changes were the best performance I could get out of the Promo Code Groups page for now. Hopefully they're sufficient for the real site.
> Avoid list comprehension at all costs

- uber/site_sections/dealer_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-759.
> Add at-con report of vendor info

- uber/site_sections/registration.py
- uber/templates/registration/promo_code_groups.html
Fixes https://jira.magfest.net/browse/MAGDEV-794 -- for real this time!
> Use group_by for efficient counting

- uber/models/__init__.py
- uber/templates/staffing_reports/volunteer_hours_overview.html
Fixes https://jira.magfest.net/browse/MAGDEV-784. Also hopefully includes a performance improvement for the volunteer hours overview page.
> Add email to volunteer hours report

- uber/models/__init__.py
Fixes https://jira.magfest.net/browse/MAGDEV-788 by checking for promo code group name and id in calculating search results.
> added promo code group names to search criteria

- uber/configspec.ini
- uber/tasks/registration.py
- uber/templates/emails/badges_sold_alert.txt
Fixes https://jira.magfest.net/browse/MAGDEV-766.
> Email alerts to reg and sysadmin for badges sold

- uber/templates/registration/check_in_form_base.html
Fixes https://jira.magfest.net/browse/MAGDEV-417 -- we actually were already showing special regdesk instructions on the check-in screen if there were any, so I moved it up per request and made it more visually distinctive.
> Better emphasize special regdesk instructions

- uber/models/attendee.py
- uber/templates/accounts/attendees.html
- uber/templates/fields/attendee.html
- uber/templates/registration/check_in_form_base.html
- uber/templates/registration/form.html
- uber/templates/registration/index_base.html
Implements fixes for various thing our registration crew found while testing the at-con staging server.
> At-con registration fixes

- uber/models/__init__.py
Fixes https://jira.magfest.net/browse/MAGDEV-805. It turns out I'd just totally broken the function and didn't realize because it exits early if you're a full registration admin. Whoops!
> Make viewable_attendees() work for non-reg-admins

- uber/models/__init__.py
- uber/templates/staffing_reports/volunteer_hours_overview.html
Fixes https://jira.magfest.net/browse/MAGDEV-806.
> Use assignments instead of requests on hours overview

- uber/templates/fields/attendee.html
> Fix emergency contact on attendee-facing pages

- uber/templates/staffing_reports/volunteer_hours_overview.html
We'd added a column but I forget to update which columns the javascript looks at, which meant this whole page wasn't working right at all. Whoops!
> Fix volunteer hours overview

- uber/static/angular-apps/signups/app.js
This is the typo fix referred to at https://github.com/magfest/ubersystem/issues/1721
Although this page is not currently used it still seemed worth fixing the typo so we can close out #1721
> fixes #1721

- uber/site_sections/staffing.py
- uber/templates/staffing/printable.html
This turned out to not be a pain.
> allow editing of dietary restrictions onsite

- uber/api.py
Case sensitivity is causing lots of problems cause of emails with random capital letters and stuff like that.
> Fix login API method to not be case sensitive

- uber/templates/registration/attendee_data.html
Fixes https://jira.magfest.net/browse/MAGDEV-780.
> Account for missing 'return to' field on attendee modal

- uber/models/attendee.py
- uber/site_sections/mivs_admin.py
- uber/site_sections/schedule.py
- uber/site_sections/staffing_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-824.
> Include attendees in promo code groups on refund pages

- uber/automated_emails.py
> Don't send shift review email to contractors

- uber/templates/emails/shifts/shifts_worked.html
Fixes typos and adds an extra note about contacting STOPS. Fixes https://jira.magfest.net/browse/MAGDEV-833.
> Update shifts worked email

- uber/site_sections/budget.py
- uber/templates/budget/attendee_donation_breakdown.html
Fixes https://jira.magfest.net/browse/MAGDEV-837.
> Add report for attendees who donated or kicked-in money

- uber/site_sections/reg_reports.py
- uber/templates/budget/attendee_donation_breakdown.html
- uber/templates/reg_reports/comped_badges.html
- uber/templates/reg_reports/comped_badges_group.html
- uber/templates/reg_reports/comped_badges_other.html
- uber/templates/reg_reports/comped_badges_promo.html
Fixes https://jira.magfest.net/browse/MAGDEV-741. Also updates the donation breakdown to filter out attends with unpaid amounts.
> Add comped badge report

- uber/site_sections/reg_reports.py
- uber/templates/reg_reports/comped_badges.html
- uber/templates/reg_reports/comped_badges_other.html
- uber/templates/reg_reports/comped_badges_promo.html
- uber/templates/reg_reports/comped_badges_staff.html
Various improvements to the new comped badge report that I thought of slightly belatedly.
> Update comped badge report

- alembic/versions/a9b36ffb5ff7_refactor_receiptitem_table_to_record_.py
- uber/configspec.ini
- uber/decorators.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/models/group.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/templates/reg_admin/receipt_items.html
Fixes https://jira.magfest.net/browse/MAGDEV-847.
> Refactor receipt items to use snapshots

- uber/models/attendee.py
- uber/site_sections/merch_reports.py
- uber/site_sections/registration.py
- uber/templates/merch_reports/owed_merch.html
Fixes https://jira.magfest.net/browse/MAGDEV-853.
> Add report of people owed merch

- uber/models/__init__.py
I'll leave comments inline explaining what I did.  One of the blocks might need to be refactored slightly.
> fixes to get stock2020 deployed

- uber/models/__init__.py
- uber/models/admin.py
This appears to work, at least in existing dev environments.
> Fix test admin accounts' access

- uber/site_sections/devtools.py
The import still worked, but it was redirecting to the wrong page after, throwing the error "TypeError: index() takes 1 positional argument but 3 were given."
> Fix CSV import 500 error

- uber/site_sections/devtools.py
- uber/templates/devtools/csv_import.html
We forgot to add handling for JSONB columns, causing imports of them to fail and exports to provide bad data. This fixes both issues.
> Fix JSONB exports and imports

- uber/templates/staffing/emergency_procedures_item.html
- uber/templates/staffing/food_item.html
- uber/templates/staffing/placeholder_item.html
- uber/templates/staffing/volunteer_agreement_item.html
> Use correct notation for jinja2 variables

- uber/templates/dept_checklist/form.html
- uber/templates/dept_checklist/hotel_requests.html
- uber/utils.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-878.
> Add "full description" option for dept head checklists

- uber/models/attendee.py
Fixes https://jira.magfest.net/browse/MAGDEV-914
> Fix 500 error for merch shirt edge cases

- uber/site_sections/email_admin.py
- uber/templates/email_admin/pending_examples.html
Fixes https://jira.magfest.net/browse/MAGDEV-856. Also fixes an issue where the dates on emails couldn't be in the future.
> Randomly sort example emails

- alembic/versions/4036e1fdb9ee_add_stage_two_mits_team_fields.py
- alembic/versions/5ceaec4834aa_associate_mits_docs_and_pictures_with_.py
- alembic/versions/af733a3c421c_add_stage_two_mits_game_fields.py
- uber/config.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/__init__.py
- uber/models/mits.py
- uber/site_sections/mits.py
- uber/templates/mits/game.html
- uber/templates/mits/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-849 by implementing the first form changes required for MITS. We'll likely need another pass on this as we get feedback from the MITS team, but this implements everything that's currently been specified.
Note that we'll need to reorder either the Stripe migration or this set of migrations, depending on which PR is merged first.
> Begin retooling MITS application for 2020

- uber/config.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-931 -- we need an easier way to turn off dept head checklist items.
> Allow removal of dept head checklist items

- uber/config.py
Fixes https://jira.magfest.net/browse/MAGDEV-895.
> Remove 2.5 shift weight option

- uber/models/attendee.py
Fixes https://jira.magfest.net/browse/MAGDEV-689. Doesn't apply to any of our events right now, but since we're changing a database default value this is a good time to fix it.
> Track whether staff have selected event shirts

- uber/automated_emails.py
- uber/model_checks.py
- uber/templates/fields/attendee.html
We need to turn a few things off on the attendee form and change the wording slightly. Part of fixing https://jira.magfest.net/browse/MAGDEV-935. Fixes https://jira.magfest.net/browse/MAGDEV-934.
> Update attendee form for West's virtual event

- uber/templates/emails/placeholders/volunteer.txt
Fixes https://jira.magfest.net/browse/MAGDEV-941. Super's going to need this too; we'll just change it back later.
> Update volunteer placeholder email

- bower.json
- uber/amazon_ses.py
- uber/configspec.ini
- uber/tasks/email.py
Fixes https://jira.magfest.net/browse/MAGDEV-933. ...pretty sure.
> Update to modern SDK for AWS

- uber/models/attendee.py
Fixes https://jira.magfest.net/browse/MAGDEV-951.
> Fix 500 error on prereg page

- uber/configspec.ini
- uber/models/__init__.py
- uber/templates/fields/attendee.html
Part of https://jira.magfest.net/browse/MAGDEV-956. Also fixes some errors if you weren't logged in as an administrator.
> Update prereg confirmation page

- uber/templates/emails/shifts/shifts_worked.html
Partially reverts https://github.com/magfest/ubersystem/pull/3774/.
> Fix base shifts worked email

- uber/templates/emails/placeholders/volunteer.txt
Reverts magfest/ubersystem#3770 as we're going back to an in-person event.
> Revert "Update volunteer placeholder email"

- uber/templates/emails/mivs/results_almost_ready.txt
- uber/templates/emails/mivs/studio_registered.txt
Fixes https://jira.magfest.net/browse/MAGDEV-971.
> Update MIVS link in emails

- uber/site_sections/api.py
Fixes https://jira.magfest.net/browse/MAGDEV-975.
> Fix 404 error for Stripe webhook endpoint

- README.md
- STRIPE.md
- uber/configspec.ini
- uber/site_sections/api.py
- uber/site_sections/preregistration.py
- uber/tasks/registration.py
- uber/templates/preregistration/index.html
- uber/utils.py
Fixes Stripe verification and cleans up the prereg payment workflow, plus adds instructions for setting up Stripe webhooks.
> Finish Stripe API upgrade for prereg payments

- uber/models/__init__.py
Should (hopefully) fix a 500 error admins are seeing.
> Fix typo in checking attendee creation

- uber/site_sections/panels.py
- uber/templates/panels/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-990.
> Add COVID language to panels app

- uber/models/__init__.py
- uber/site_sections/preregistration.py
- uber/templates/art_show_applications/index.html
- uber/templates/marketplace/index.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/preregbase.html
I missed several spots to check if `ATTENDEE_ACCOUNTS_ENABLED` was enabled, this should hopefully cover it.
> Make attendee accounts actually turn off

- uber/configspec.ini
- uber/site_sections/preregistration.py
- uber/templates/fields/attendee.html
- uber/templates/fields/group.html
- uber/templates/preregistration/form.html
- uber/templates/static_views/dealer_reg_closed.html
- uber/templates/static_views/dealer_reg_not_open.html
Adds a way to make dealer reg invite-only, and hides the amount extra and donation forms for dealers when applying.
> Additional updates to dealer registration

- alembic/versions/70920586fdee_add_tabletop_checkbox_to_panel_.py
- uber/models/panels.py
- uber/templates/panel_app_form.html
Fixes https://jira.magfest.net/browse/MAGDEV-993.
> Add checkbox for tabletop panels

- uber/site_sections/dealer_reports.py
- uber/site_sections/dept_checklist.py
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-995.
> Add seller report with links to group forms

- uber/templates/fields/attendee.html
This will support extra rows for season level (AKA super supporter) merch.
> Add row for season level upgrades

- uber/automated_emails.py
- uber/menu.py
Fixes https://jira.magfest.net/browse/MAGDEV-983.
> Update volunter claim email subject

- uber/model_checks.py
- uber/templates/preregistration/confirm.html
Fixes https://jira.magfest.net/browse/MAGDEV-997.
> Flag pending badges for attendees

- uber/site_sections/art_show_applications.py
- uber/site_sections/marketplace.py
- uber/site_sections/preregistration.py
Some of our charge descriptions didn't include the attendee name. This should fix that.
> Add attendee name to extra charge descriptions

- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-1001.
> Mark pending attendees as paid

- uber/config.py
- uber/decorators.py
- uber/site_sections/accounts.py
- uber/site_sections/api.py
- uber/site_sections/attractions_admin.py
- uber/site_sections/dept_admin.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/templates/accounts/sitemap.html
Fixes https://jira.magfest.net/browse/MAGDEV-1002 by adding a not_site_mappable attribute to hide certain pages from the site map. Also removes spurious links to index pages that don't exist, and improves the site map a bit by collapsing any site sections that only have an index page and nothing else.
> Improve site map

- alembic/versions/a3e65433bd72_add_staff_shirt_size_selection.py
- development-defaults.ini
- uber/config.py
- uber/configspec.ini
- uber/models/attendee.py
- uber/site_sections/merch_admin.py
- uber/site_sections/merch_reports.py
- uber/site_sections/staffing.py
- uber/templates/fields/attendee.html
- uber/templates/merch_admin/index.html
- uber/templates/staffing/shirt_size.html
Fixes https://jira.magfest.net/browse/MAGDEV-996.
> Add separate sizing for staff shirts

- uber/templates/staffing/hotel_item.html
- uber/templates/staffing/shifts.html
Fixes https://jira.magfest.net/browse/MAGDEV-1028.
> Update volunteer checklist, part 2

- uber/site_sections/dept_checklist.py
- uber/templates/dept_checklist/form.html
- uber/templates/dept_checklist/office_supplies.html
- uber/templates/dept_checklist/ppe_requests.html
- uber/templates/dept_checklist/printed_signs.html
Fixes https://jira.magfest.net/browse/MAGDEV-1029.
> Update dept head checklist for Super 2022

- uber/templates/dept_checklist/hotel_setup.html
- uber/templates/dept_checklist/logistics.html
- uber/templates/dept_checklist/office_supplies.html
- uber/templates/dept_checklist/ppe_requests.html
- uber/templates/dept_checklist/tech_requirements.html
- uber/templates/dept_checklist/treasury.html
- uber/templates/staffing/hotel_item.html
Also opens the external hotel URL in a new window.
> Open dept checklist forms in new window

- uber/site_sections/staffing.py
> Fix staff-shirt-only size marking for real this time

- uber/templates/fields/attendee.html
Hopefully this is the last of the bugs.
> Fix lingering issues with staff vs event shirt sizes

- uber/site_sections/merch_reports.py
There was an off-by-one error in the last fix. This should do it.
> Fix shirt report fix

- uber/templates/merch_reports/shirt_counts.html
> Fix typo in shirt sales report

- uber/templates/emails/shifts/dept_checklist.txt
Slightly changes the wording for the automated emails that get sent out for each dept head checklist step. Part of fixing https://jira.magfest.net/browse/MAGDEV-1036.
> Update dept checklist step email template

- uber/site_sections/panels_admin.py
- uber/templates/panels_admin/index.html
Also adds a tabletop column to the Everything export. Fixes https://jira.magfest.net/browse/MAGDEV-1034.
> Add tabletop column to panels view

- uber/models/__init__.py
- uber/site_sections/mits_admin.py
- uber/site_sections/panels_admin.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/payment_pending_attendees.html
Fixes https://jira.magfest.net/browse/MAGDEV-1023.
> Create report for payment pending attendees

- uber/models/attendee.py
- uber/site_sections/reg_admin.py
- uber/templates/fields/attendee.html
- uber/templates/reg_admin/attendees_who_owe_money.html
- uber/templates/reg_admin/payment_pending_attendees.html
Fixes https://jira.magfest.net/browse/MAGDEV-1025 (and expands it to all types of unpaid attendees). Also updates the payment pending attendees report to open links in a new window.
> Create report for attendees who owe money

- uber/models/attendee.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/payment_pending_attendees.html
Some improvements to the recently-added reports about pending and unpaid attendees.
> Improve pending reports

- uber/reports.py
Also filters out any attendees who won't have badges for the event, including refunded and deferred attendees.
> Add placeholder flag to printed badge report

- uber/models/__init__.py
- uber/models/attendee.py
- uber/reports.py
- uber/templates/dept_admin/form.html
Fixes https://jira.magfest.net/browse/MAGDEV-1045. An attempt was made at a more holistic solution, but for now we'll have to settle for them not showing up on the one page.
> Hide attendees without badges from dept page

- uber/site_sections/mivs_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-1050.
> Fix discussion email export, probably

- uber/templates/band_admin/checklist_info.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-1048.
> Add autograph info to band info page

- alembic/versions/cc0f9e9861cd_add_member_info_to_guestgroup_bio_table.py
- uber/models/guests.py
- uber/templates/guest_checklist/bio_deadline.html
Fixes https://jira.magfest.net/browse/MAGDEV-1042.
> Add group member info box to guest groups

- uber/templates/guest_checklist/band_merch_deadline.html
- uber/templates/guest_checklist/guest_merch_deadline.html
- uber/templates/guest_checklist/merch_deadline.html
Unifies the merch description for bands and guests, and fixes https://jira.magfest.net/browse/MAGDEV-1054.
> Update band+guest merch step

- uber/templates/emails/mivs/At-Con/LoadIn.txt
updating with 2022 information
> Update LoadIn.txt email

- uber/templates/emails/mivs/At-Con/LoadIn.txt
https://github.com/magfest/ubersystem/pull/3886 introduced hidden unicode characters that I couldn't get rid of through the GitHub web editor. This actually removes them.
> Remove hidden unicode characters from MIVS email

- uber/site_sections/registration.py
- uber/templates/registration/check_in_form_base.html
Required for https://github.com/magfest/magprime/pull/377.
> Enable macros and model checks for checking attendees in

- requirements.txt
- uber/site_sections/statistics.py
- uber/templates/statistics/map.html
Fixes https://jira.magfest.net/browse/MAGDEV-1056.
This also upgrades our uszipcode package, which we seemed to need to make it save its SQLite to a different place, which we seemed to need to make it work at all.
> Add CSV export for listing states attendees are from

- requirements.txt
- uber/site_sections/statistics.py
- uber/templates/statistics/map.html
Reverts magfest/ubersystem#3892
> Revert "Add CSV export for listing states attendees are from"

- requirements.txt
- uber/site_sections/statistics.py
- uber/templates/statistics/map.html
Reverts magfest/ubersystem#3893
> Revert "Revert "Add CSV export for listing states attendees are from""

- uber/site_sections/badge_exports.py
> Fix bug with badge export

- uber/site_sections/badge_exports.py
Fixes the DB query so that this actually works.
> Actually prevent overlap for badge exports

- uber/site_sections/reg_admin.py
Fix for a bug reported via Slack.
> Fix refund items not being removed

- uber/models/attendee.py
- uber/site_sections/registration.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-1066.
> Allow boolean values on check-in to be overridden

- uber/models/__init__.py
- uber/models/attendee.py
Fixes searches that checks your terms for special condition (e.g., searching by first/last name if you had exactly two words). Also fixes a misnamed classproperty.
> Fix search when using special conditions

- uber/templates/registration/recent.html
This is not a particularly often-used page, but I need it to at least report the registered date in local time.
> Update recent registrations list page

- uber/models/__init__.py
- uber/templates/fields/attendee.html
Allows searching for attributes not explicitly listed in the attendee properties.
> Fix 500 error when searching for unknown attributes

- uber/api.py
Fixes https://jira.magfest.net/browse/MAGDEV-1068
> Update search API to handle error messages from session.search

- uber/site_sections/merch_admin.py
- uber/templates/merch_admin/arbitrary_charge_form.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-1055.
> Fix arbitrary sales charge form

- uber/templates/preregistration/defer_badge.html
Now people can ship their kick-in merch to the US!
> Fix address field while deferring badge

- uber/templates/preregistration/confirm.html
Also adds text about paying a shipping fee for merch, when appropriate (roughly).
> Fix checking for amount unpaid vs amount pending

- uber/site_sections/registration.py
- uber/templates/registration/index_base.html
Now that we have attribute search, we also want an easy way to see how many attendees the search turned up.
> Show count of searched attendees

- uber/site_sections/statistics.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-1080.
> Add error handling for Search Engine

- uber/site_sections/staffing.py
Part of fixing https://jira.magfest.net/browse/MAGDEV-1081.
> Update volunteer agreement handling

- uber/site_sections/dept_checklist.py
- uber/templates/fields/attendee.html
- uber/templates/staffing/hotel.html
- uber/templates/staffing/hotel_item.html
Part of fixing https://jira.magfest.net/browse/MAGDEV-1090.
> Fix Uber hotel requests

- uber/site_sections/panels.py
- uber/templates/emails/dealers/payment_confirmation.html
- uber/templates/emails/mivs/judge_badge_info.txt
- uber/templates/emails/placeholders/guest.txt
- uber/templates/emails/placeholders/panelist.txt
- uber/templates/emails/placeholders/regular.txt
- uber/templates/emails/placeholders/volunteer.txt
- uber/templates/emails/reg_workflow/attendee_confirmation.html
- uber/templates/emails/reg_workflow/attendee_qrcode.html
- uber/templates/emails/reg_workflow/group_confirmation.html
- uber/templates/emails/reg_workflow/promo_code_group_confirmation.html
Fixes up some text to be configurable and adds even more reminders for bringing your vaccination.
> Add event-nonspecific COVID text

- uber/templates/emails/hotel/hotel_reminder.txt
- uber/templates/emails/hotel/hotel_rooms.txt
- uber/templates/emails/shifts/dept_checklist.txt
- uber/templates/emails/shifts/reminder.txt
- uber/templates/staffing/hotel.html
Partly fixes https://jira.magfest.net/browse/MAGDEV-1094.
> Update volunteer emails

- uber/templates/emails/shifts/dept_checklist.txt
> Fix 500 error in checklist email

- uber/configspec.ini
- uber/templates/emails/shifts/dept_checklist.txt
Also updates a comment on the shirts_per_staffer variable.
> Fix spacing issues with dept checklist email

- uber/config.py
Fixes https://jira.magfest.net/browse/MAGDEV-1046. Not really sure what we were doing before this.
> Let guest, band, and mivs admins see group_admin

- uber/templates/landing/index.html
- uber/templates/macros.html
A couple templates were broken in the last changes.
> Fix template errors

- uber/templates/emails/guests/band_bio_reminder.txt
Change language to social media
> Update Band Bio reminder

- uber/site_sections/guests.py
Taking out the info deadline for guests caused some problems, so this fixes that. Part of fixing https://jira.magfest.net/browse/MAGDEV-1115.
> Allow guests to complete their checklist without info

- uber/templates/emails/hotel/room_assignment.txt
> Update room assignment email text

- uber/templates/emails/hotel/room_assignment.txt
> Add "night" to email

- uber/model_checks.py
I had tested existing attendees but not new oneeees
> Fix error preventing people from registering

- uber/templates/preregistration/form.html
Moves the giant block of disclaimers everyone will ignore into a big popup of disclaimers everyone will click through without reading
> Pop up disclaimers during prereg

- uber/site_sections/preregistration.py
- uber/templates/preregistration/form.html
I have no idea how I missed changing the buttons to not submit the form, I distinctly remember doing that.
Also fixes some 500 errors when viewing dealer applicatons.
> Fix disclaimer modal popup

- uber/templates/emails/dealers/application.html
- uber/templates/emails/dealers/approved.html
- uber/templates/fields/group.html
Fixes issues in dealer emails.
> Update dealer cost properties

- alembic/versions/d606c3cb6b17_add_group_email_and_phone_fields.py
- uber/model_checks.py
- uber/models/group.py
- uber/site_sections/preregistration.py
- uber/templates/fields/attendee.html
- uber/templates/fields/group.html
This is in case we decide we don't want to collect the comptroller information separately.
> Add email address and phone number fields to dealers

- alembic/versions/f9a54abc8ebf_update_panels_application_and_add_auto_.py
- development-defaults.ini
- test-defaults.ini
- uber/automated_emails.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/panels.py
- uber/site_sections/panels.py
- uber/site_sections/panels_admin.py
- uber/tasks/__init__.py
- uber/tasks/panels.py
- uber/templates/emails/panels/panel_accept_reminder.txt
- uber/templates/emails/panels/panel_app_accepted.txt
- uber/templates/emails/panels/panel_app_declined.txt
- uber/templates/emails/panels/panel_app_scheduled.txt
- uber/templates/emails/panels/panel_app_waitlisted.txt
- uber/templates/emails/placeholders/panelist.txt
- uber/templates/panel_app_form.html
- uber/templates/panels/confirm_panel.html
- uber/templates/panels_admin/app.html
- uber/templates/panels_admin/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-1117 by adding several new fields and a new confirmation system for panelists that closely mirrors the one for MIVS. Also removes the old deprecated "PEGLEGS" signature.
> Update Panels applications for Super

- uber/model_checks.py
- uber/utils.py
Also removes a couple extra debug log statements.
> Fix admin account creation

- uber/site_sections/preregistration.py
This doesn't properly fix this issue, but at least it will fix MAGWest's website
> Set post-con message to MAGFest info

- uber/site_sections/mivs_reports.py
- uber/utils.py
Also makes XLSX exports more robust in general so that if I set up a bad report in the future, it will just look dumb instead of throwing a 500 error
> Fix MIVS judges report

- uber/automated_emails.py
- uber/config.py
- uber/configspec.ini
- uber/templates/emails/placeholders/deferred.html
- uber/templates/emails/reg_workflow/attendee_confirmation.html
- uber/templates/emails/reg_workflow/group_donation.txt
- uber/templates/fields/attendee.html
Also fixes a couple minor things with the registration form.
> Update emails and add deferred attendee email

- alembic/versions/28bf25495d40_add_onsite_contact_field.py
- uber/model_checks.py
- uber/models/attendee.py
- uber/templates/emails/reg_workflow/reg_notes.html
- uber/templates/fields/attendee.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/register_group_member.html
- uber/templates/preregistration/transfer_badge.html
- uber/templates/registration/attendee_data.html
- uber/templates/registration/form.html
- uber/templates/registration/register.html
Super last-minute addition in the name of health and safety!
> Add onsite contact field

- uber/receipt_items.py
> Stop charging for an extra group badge

- uber/site_sections/preregistration.py
- uber/templates/fields/attendee.html
- uber/utils.py
We weren't actually adding any codes (!) and the receipt transaction was being recorded incorrectly.
> Fix adding codes to promo code groups

- uber/models/commerce.py
IIii was afraid this would happeeeen I hate everythiiiing
> Quick hopeful fix for receipt share issue

- uber/models/commerce.py
I can't figure out SQLAlchemy tonight, but hopefully I won't need to.
> At least fix the property

- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/badge_printing.py
- uber/site_sections/marketplace.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/templates/marketplace/edit.html
- uber/templates/preregistration/group_members.html
- uber/templates/reg_admin/receipt_items.html
- uber/utils.py
Updates the remaining code, at least for taking payments, to use the new system. Also refactors stuff a liiittle bit.
> More receipt updates

- uber/site_sections/registration.py
- uber/templates/registration/promo_code_group_form.html
You can now delete promo codes from groups and some extra info has been added for ease of use.
> Improve promo code group page

- uber/templates/registration/attendee_data.html
- uber/templates/registration/promo_code_groups.html
I had taken it out during the refactor because I thought I'd be replacing it, but I forgot to put it back when I changed my mind, whoops.
Also includes another improvement for promo code groups.
> Add payment status back to attendee modal

- alembic/versions/f2929b710d19_add_settable_transferrable_property.py
- uber/models/attendee.py
- uber/site_sections/reg_admin.py
- uber/templates/fields/attendee.html
- uber/templates/reg_admin/import_attendees.html
- uber/templates/registration/form.html
- uber/utils.py
Lets us mark deferred badges as transferable, and improves badge importing for ease of use.
> Pre-hotel lock updates

- uber/templates/emails/mivs/judge_badge_info.txt
new survey link for judge badge email for MIVS
Also, please remove the override email template (and parent mivs folder?):
https://github.com/magfest/magprime/blob/master/magprime/templates/emails/mivs/judge_badge_info.txt
> Mivs update judge email

- uber/automated_emails.py
- uber/configspec.ini
- uber/models/attendee.py
Also fixes some issues with the shirt step.
> Split shifts created and checklist open dates

- uber/site_sections/dealer_reports.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/attendees_who_owe_money.html
Hopefully I will have to do less cherry-picking from now on.
> Sync up with MFF

- uber/templates/emails/shifts/dept_checklist.txt
We had hardcoded stops@magwest somehow. Also adds the configuration name just for fun.
> Fix department checklist email

- uber/configspec.ini
- uber/models/guests.py
- uber/site_sections/group_admin.py
- uber/templates/fields/attendee.html
- uber/templates/group_admin/checklist_info.html
- uber/templates/group_admin/guests.html
- uber/templates/group_admin/mivs.html
- uber/templates/group_admin/nav_menu.html
- uber/templates/guest_checklist/merch_deadline.html
- uber/templates/guests/agreement.html
- uber/templates/guests/autograph.html
- uber/templates/guests/bio.html
- uber/templates/guests/charity.html
- uber/templates/guests/index.html
- uber/templates/guests/interview.html
- uber/templates/guests/mc.html
- uber/templates/guests/merch.html
- uber/templates/guests/panel.html
- uber/templates/guests/rehearsal.html
- uber/templates/guests/stage_plot.html
- uber/templates/guests/taxes.html
- uber/templates/guests/travel_plans.html
Fixes https://jira.magfest.net/browse/MAGDEV-1170. Also fixes up the guest checklist to work with checklist names with spaces in them. Also adds an "Add New Group" button that creates a new group from an attendee, with the attendee as the group leader.
> Add Rock Island checklist type

- uber/models/__init__.py
I mixed up which way the alligator was facing.
> Switch <= and >= operators

- uber/templates/guests/mivs_hotel_space.html
Updated mivs indie checklist hotel block link for 2023
> update new mivs hotel block link for 2023

- .dockerignore
- .github/workflows/ci-docker.yaml
- Dockerfile
- docker-compose.yml
- sideboard-development.ini.template
- uber-development.ini.template
- uber-wrapper.sh
Adds a github action to automatically build a docker container
> Adding docker build

- uber/config.py
- uber/configspec.ini
I got bored so I added this. Also moves the Tuber URL out of [secrets] since it doesn't belong there.
I can't shake the feeling that maybe I should require you to prepend the env vars with something... that'd be some pretty long var names though.
> Add support for setting secrets with env vars

- alembic/versions/cd2578936cb0_add_detailed_travel_plans_for_guest_.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/guests.py
- uber/site_sections/guest_reports.py
- uber/site_sections/guests.py
- uber/templates/detailed_travel_plans_form.html
- uber/templates/guest_checklist/travel_plans_deadline.html
- uber/templates/guests_macros.html
Fixes https://jira.magfest.net/browse/MAGDEV-1174. Also adds regular travel info to the checklist CSV (it was missing for some reason) and adds a new report just for the detailed travel info
> Add new detailed travel info for guests

- uber/site_sections/dealer_admin.py
- uber/site_sections/preregistration.py
Fixes the "Decline and Convert" button.
> Fix converting declined dealers

- uber/automated_emails.py
- uber/templates/emails/shifts/shifts_created.txt
> Add shift announcement email

- uber/templates/registration/attendee_data.html
Fixes https://jira.magfest.net/browse/MAGDEV-1175.
> Add zip code/address fields to attendee popup

- uber/site_sections/guest_reports.py
Fixes https://jira.magfest.net/browse/MAGDEV-1173. I expect Autographs will want more info in this report, but I don't know what...
> Add autographs report

- uber/templates/fields/attendee.html
Fixes https://jira.magfest.net/browse/MAGDEV-1176.
> Stop unsetting staffing when Contractor is selected

- uber/models/attendee.py
- uber/templates/group_admin/form.html
- uber/templates/registration/attendee_data.html
- uber/templates/registration/form.html
People deleting custom badges after the printed badge deadline causes problems every year -- this finally does something about it.
> Prevent deleting badges after the custom badge deadline

- uber/automated_emails.py
- uber/models/mivs.py
- uber/site_sections/email_admin.py
- uber/tasks/mivs.py
- uber/templates/emails/mivs/checklist_reminder.txt
Using the email fixture system caused a lot of weird, buggy emails. This switches checklist reminders to use a task that runs every six hours instead. Hopefully it worrrks
> Overhaul MIVS checklist reminders

- uber/model_checks.py
Fixes an oversight in the code.
> Only let minors use promo codes if their group is free

- uber/models/panels.py
Saw this error when doing stuff with automated emails. I wonder what email it's blocking?
> Fix "after_confirm_deadline" property for panel apps

- uber/site_sections/dealer_reports.py
- uber/site_sections/group_admin.py
- uber/site_sections/preregistration.py
We weren't processing ANY of these fields correctly so they just weren't getting updated. Also updates dealer reports to use the group's phone/email, and lets dealers update their own group phone/email.
> Let admins update group address, phone, and email

- uber/decorators.py
- uber/models/attendee.py
- uber/site_sections/staffing.py
- uber/templates/staffing/credits_item.html
- uber/templates/staffing/food_item.html
- uber/templates/staffing/hotel_item.html
- uber/templates/staffing/printable.html
- uber/templates/staffing/shifts.html
- uber/templates/staffing/shirt_item.html
Reconfigures the workflow for volunteers during the event, allowing them to sign the volunteer agreement and acknowledge emergency procedures. Fixes https://jira.magfest.net/browse/MAGDEV-1180.
> Make volunteer checklist work during the event

- uber/site_sections/registration.py
Fixes https://jira.magfest.net/browse/MAGDEV-1179. This code didn't make any logical sense being where it was, so easier to just take it out entirely.
> Fix 500 error when giving attendees groups

- uber/model_checks.py
- uber/site_sections/shifts_admin.py
Fixes https://jira.magfest.net/browse/MAGDEV-1141.
> Improve job validations

- uber/api.py
Requested via Slack for the super dope mega radical check-in system Rob is writing
> Add shift slot data to JobLookup API

- uber/site_sections/registration.py
Either I deleted these lines and forgot or something happened recently that made these necessary... hopefully this won't be a Problem(tm) going forward.
> Fix creating new attendees

- uber/site_sections/dealer_reports.py
> Add new comptroller info to export

- uber/model_checks.py
Adds the same override that people with Staff badges have.
> Allow under-18 contractors to volunteer

- uber/site_sections/dealer_reports.py
> Split group address in comptroller report

- uber/site_sections/dealer_reports.py
- uber/tasks/email.py
I forgot I switched to a feature branch already, whoops
> Update super2023 with changes from master

- uber/site_sections/dealer_reports.py
> Don't strip leading 0s in dealer zip-codes

- uber/api.py
- uber/templates/accounts/homepage.html
Most of these were actually already in super2023, the only new thing is "Don't strip leading 0s in dealer zip-codes"
> Merge updates to Super 2023

- uber/models/__init__.py
- uber/models/admin.py
- uber/models/guests.py
- uber/templates/guest_reports/rock_island.html
Various fixes for Rock Island reports, including broken links and RI access not actually working right.
> Rock Island fixes

- uber/models/__init__.py
- uber/models/admin.py
- uber/models/guests.py
- uber/site_sections/dealer_admin.py
- uber/templates/guest_reports/rock_island.html
Includes the update to API calls to only return valid attendees.
> Update Super 2023 from master

- uber/site_sections/merch_reports.py
Also adds 'extra merch' to both the merch owed page and the CSV file. Fixes https://jira.magfest.net/browse/MAGDEV-1189.
> Add CSV for merch owed overview

- uber/site_sections/registration.py
None of this code was changed recently... I suspect we upgraded SQLAlchemy at some point and it changed how it handled sessions a bit.
> Fix save and return to search for new attendees

- uber/site_sections/hotel_reports.py
Requested via Slack -- we've done this manually before but there's no reason to keep doing it that way.
> Add hotel audit report

- alembic/versions/a4a79802ba51_allow_api_and_print_jobs_to_not_have_.py
- make_config.py
- requirements.txt
- uber-wrapper.sh
- uber/configspec.ini
- uber/site_sections/hotel_reports.py
This allows all uber/sideboard configuration to be pushed into the docker container via an UBERSYSTEM_CONFIG environment variable.
> Adding environment-based configuration

- uber/templates/emails/mivs/game_accepted_from_waitlist.txt
it now matches accepted email information
> updating waitlist email

- uber/model_checks.py
- uber/site_sections/accounts.py
- uber/templates/accounts/index.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-1226. Also makes the account form partially ajaxified so errors are less obnoxious. Also removes a couple debug logs.
> Don't preselect first attendee for admin account

- uber/templates/emails/placeholders/imported_volunteer.txt
This is my first pull request for these emails, I tried to make it sound more like the Super/West badge claim emails, since this seems to be an older template. Please let me know if I'm doing this wrong (also I might need to re-do this one because we don't know the Covid policy yet).
> Update Badge Claim Email

- .gitignore
- docker-compose.override.yml.template
- docker-compose.yml
Removes the default UBERSYSTEM_GIT environment variables, as having them in the main YAML file means that your local changes are blown away on every container restart. Also adds a template for docker-compose.override.yml and instructions on how to set up local Docker containers for multiple events.
> Add process for local dev with Docker

- uber/templates/fields/attendee.html
- uber/templates/macros.html
- uber/templates/preregistration/form.html
Required for https://github.com/magfest/magstock/pull/161. Also makes the disclaimers stop popping up if you're editing a prereg.
> Enable event plugins to add upgrades

- uber/configspec.ini
We don't really use these config options anymore, so it'd be nice if we didn't have to keep setting them.
> Set default takedown config

- uber/config.py
- uber/templates/fields/attendee.html
We don't have a date deadline for merch for West, but not including a supporter deadline is causing a 500 error.
> Stop requiring supporter deadline

- uber/configspec.ini
- uber/templates/preregistration/paid_preregistrations.html
- Sets shared kickin stocks to be false by default
- Fixes a typo
> Even more MAGstock fixes

- uber/site_sections/preregistration.py
- uber/site_sections/registration.py
- uber/templates/fields/attendee.html
- uber/templates/preregistration/index.html
- uber/templates/preregistration/upgrade_modal.html
- uber/utils.py
- Adds a default value for cost change dicts
- Stops resetting data on form submission failure
- Changes "Badge names" to "Custom names"
- Adds badge price to prereg index page
- Fixes scoping issue with upgrade JS
> Hopefully final fixes for Stock launch

- uber/server.py
2019 was almost 4 years ago. Also, this was causing a confusing issue with our dept checklist URL config.
> Remove very old redirects

- uber/models/__init__.py
- uber/models/commerce.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
Fixes https://jira.magfest.net/browse/MAGDEV-1240. Also auto-cancels pending transactions if we can't retrieve them from Stripe. Also updates pending transaction balance if necessary.
> Add better error detection/handling for Stripe requests

- uber/site_sections/schedule.py
Fixes https://jira.magfest.net/browse/MAGDEV-774
> Print panel tech needs in event timezone

- requirements.txt
Our current version of celery is exhibiting https://github.com/celery/celery/issues/6414
Now that health checks are enforced I'm seeing the following TB in the logs and the ELB is killing things pretty often:
```
File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
self._do_respond(path_info)
File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
File "/app/env/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
File "/app/env/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
File …
```
> Upgrading celery

- uber/site_sections/devtools.py
I'm going to comment out the celery check for now since it's failing too often. I'll debug why celery is unhappy and add this back later.
> Skipping celery check since it's failing a lot

- uber/models/__init__.py
This seems to be unnecessary..?
> Disabling checking balance for refunds

- uber/models/__init__.py
- uber/models/commerce.py
- uber/receipt_items.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/receipt_items.html
- uber/utils.py
Removes the refund transaction button to fix https://jira.magfest.net/browse/MAGDEV-1248. Also to facilitate this, refreshing a transaction from stripe will automatically add a refund item to the receipt. Also also, fixes it so that upgrades that attendees buy during prereg can be reverted, and adds several fixes to actually refunding and reverting or comping items.
> Implement various fixes for receipts

- uber/templates/staffing/printable_schedule.html
Add the day of the week to each shift time in the printable schedule
> Update printable_schedule.html with day of week

- uber/site_sections/email_admin.py
This should fix issues with admins trying to resend emails to attendees.
> Make resend_email work for all admins

- requirements.txt
- uber/config.py
- uber/configspec.ini
- uber/server.py
Add support for logging errors on the backend to sentry
> Adding sentry hooks

- uber/configspec.ini
- uber/server.py
This will push timing info about all web requests to sentry if it's enabled.
> Adding sentry performance tracking

- requirements.txt
- uber/config.py
- uber/forms/__init__.py
- uber/forms/group.py
- uber/tasks/__init__.py
- uber/templates/base.html
- uber/templates/email_admin/pending_examples.html
- uber/templates/forms/dealer_contact_intro.html
- uber/templates/forms/macros.html
- uber/templates/forms/other_info.html
- uber/templates/forms/personal_info.html
- uber/templates/landing/index.html
- uber/templates/preregistration/dealer_registration.html
- uber/templates/preregistration/index_payment_form.html
- uber/templates/preregistration/preregbase.html
- uber/validations/attendee.py
Resync code from MFF and fixes several dealer reg bugs I didn't catch due to differing config. Also fixes the landing page and stops the masthead from saying "Midwest Furfest".
> Pull in MFF fixes and fix dealer reg bugs

- alembic/versions/1fcbcf875d8e_add_new_fields_to_panel_applications.py
- uber/automated_emails.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/panels.py
- uber/site_sections/panels.py
- uber/templates/base.html
- uber/templates/emails/panels/application.html
- uber/templates/emails/panels/panel_app_accepted.txt
- uber/templates/emails/panels/panel_app_scheduled.txt
- uber/templates/landing/index.html
- uber/templates/macros.html
- uber/templates/mits_base.html
- uber/templates/mivs_base.html
- uber/templates/other_panelists_form.html
- uber/templates/panel_app_form_new.html
- uber/templates/panel_macros.html
- uber/templates/panels/confirm_panel.html
- uber/templates/panels/guest.html
- uber/templates/panels/index.html
- uber/templates/panels_admin/app.html
- uber/templates/panels_admin/form.html
- uber/templates/panels_admin/index.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/preregbase.html
Fixes https://jira.magfest.net/browse/MAGDEV-1242 by adding several new fields and updating emails to panelists.
> Update panel application for Super 2024

- uber/config.py
- uber/forms/__init__.py
- uber/models/attendee.py
- uber/site_sections/accounts.py
- uber/templates/accounts/access_groups.html
- uber/templates/accounts/index.html
- uber/templates/art_show_admin/form.html
- uber/templates/art_show_common/art_pieces_form.html
- uber/templates/attractions/events.html
- uber/templates/attractions_admin/event.html
- uber/templates/attractions_admin/form.html
- uber/templates/attractions_macros.html
- uber/templates/marketplace_admin/form.html
- uber/templates/panels_admin/panel_feedback.html
- uber/templates/promo_codes/generate_promo_codes.html
- uber/templates/promo_codes/index.html
- uber/templates/registration/index_base.html
- uber/templates/registration/promo_code_group_form.html
Fixes some issues with updating admin accounts, and updates the look of the admin accounts page to better fit Bootstrap 5. Also fixes an issue with getting attendee age groups. Also also makes some mass updates throughout the admin section to get more Bootstrap 5 stuff working.
> Fix updating admin accounts

- uber/site_sections/preregistration.py
> Fix uber.validations import error

- alembic/versions/1fcbcf875d8e_add_new_fields_to_panel_applications.py
- uber/model_checks.py
- uber/models/panels.py
- uber/templates/emails/panels/application.html
- uber/templates/panel_app_form.html
- uber/templates/panel_app_form_new.html
- uber/templates/panel_macros.html
- uber/templates/panels/index.html
- uber/utils.py
Requested via Slack -- we now no longer default to any panel department or type, and we don't use a checkbox for the public display name.
> Extra updates for panels for Super 2024

- uber/automated_emails.py
- uber/templates/emails/mits/mits_feedback.txt
- uber/templates/emails/mits/mits_initial_panel_info.txt
- uber/templates/mits/waiver.html
> Update MITS emails and waiver text

- uber/config.py
- uber/custom_tags.py
- uber/forms/attendee.py
- uber/model_checks.py
- uber/models/attendee.py
- uber/templates/forms/attendee/badge_extras.html
- uber/templates/forms/attendee/personal_info.html
- uber/templates/forms/macros.html
Updates a bunch of code to improve the card select macro, add validations for staff shirt size, and use the new form system properly with the DONATION_DESCRIPTIONS config.
Also moves badge_printed_name to be under the PersonalInfo form -- none of the events that use Uber actually have customized items based on your purchases so it no longer made sense to have logic surrounding that.
> Update form system for MAGFest staff reg

- uber/automated_emails.py
- uber/config.py
- uber/decorators.py
- uber/forms/__init__.py
- uber/forms/attendee.py
- uber/forms/group.py
- uber/forms/widgets.py
- uber/jinja.py
- uber/receipt_items.py
- uber/site_sections/preregistration.py
- uber/templates/forms/attendee/badge_extras.html
- uber/templates/forms/macros.html
- uber/templates/macros.html
- uber/templates/preregistration/upgrade_modal.html
Includes a bunch of fixes to make staff reg and upgrading work for 2023, including:
- Fixing how we load plugin templates to fix a bug where including the same template twice gave you different versions of the template
- Refactors to support a new widget in the magprime plugin (see https://github.com/magfest/magprime/pull/445)
- Setting up the upgrade modal to work with the amount_extra and extra_donation fields
> Updates for 2023 staff registration

- uber/forms/__init__.py
- uber/forms/attendee.py
Also adds support for dynamic choices in fields, so when a public department is added it actually gets populated in people's forms instead of requiring a server restart.
> Fix "where do you want to volunteer" field

- .github/workflows/ci-docker.yaml
This adds back the job that builds the base ubersystem image.
> Restoring local docker build

- uber/config.py
- uber/forms/__init__.py
- uber/forms/attendee.py
- uber/model_checks.py
- uber/site_sections/group_admin.py
- uber/site_sections/landing.py
- uber/site_sections/preregistration.py
- uber/templates/forms/attendee/badge_extras.html
- uber/templates/forms/attendee/other_info.html
- uber/templates/forms/macros.html
- uber/templates/forms/prereg_fields.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/index_payment_form.html
- uber/templates/preregistration/stripeForm.html
Also includes a refactor that's designed to allow us to include forms from different form modules so we can load group info on the prereg page.
> Add group and child badge selections to prereg

- uber/automated_emails.py
- uber/configspec.ini
- uber/templates/emails/dealers/badge_converted.html
- uber/templates/emails/dealers/payment_confirmation.html
- uber/templates/emails/reg_workflow/group_confirmation.html
- uber/templates/emails/reg_workflow/group_donation.txt
- uber/templates/emails/reg_workflow/group_preassign_reminder.txt
- uber/templates/emails/reg_workflow/promo_code_group_confirmation.html
- uber/templates/emails/reg_workflow/reg_notes.html
> Update registration emails for Super 2024

- uber/templates/emails/dealers/payment_confirmation.html
- uber/templates/emails/panels/application.html
- uber/templates/emails/placeholders/reminder.txt
- uber/templates/emails/reg_workflow/group_confirmation.html
- uber/templates/emails/reg_workflow/promo_code_group_confirmation.html
We have one last update to make after this but it's for the precon FAQ so it's not prereg-critical.
> More updates for registration emails for Super

- uber/forms/attendee.py
Changed my mind about requiring this field as I realized that it won't list all the departments. Also removes coercing to int because department IDs aren't ints, duh.
> Fix requested depts field

- uber/site_sections/preregistration.py
- uber/tasks/email.py
- uber/templates/art_show_applications/edit.html
- uber/templates/preregistration/add_promo_codes.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/group_promo_codes.html
- uber/templates/registration/register.html
Fixes several bugs with emailing promo codes to people, claiming codes from that email, and buying more codes.
> Add fixes for promo code groups

- uber/models/__init__.py
- uber/models/mivs.py
- uber/templates/mivs/index.html
- uber/templates/mivs_admin/assign_judges.html
Fixes an issue that was blocking MIVS judges from being able to review games. Also fixes an issue found earlier where creating a MIVS judge wouldn't fully work the first time.
> MIVS judge and game code fixes

- alembic/versions/1dc129c4c4f0_add_guest_hospitality_checklist_step.py
- uber/config.py
- uber/models/guests.py
- uber/site_sections/guests.py
- uber/site_sections/reg_admin.py
- uber/templates/emails/guests/guest_checklist_announce.html
- uber/templates/emails/guests/guest_checklist_reminder.html
- uber/templates/guest_checklist/guest_bio_deadline.html
- uber/templates/guest_checklist/guest_panel_deadline.html
- uber/templates/guest_checklist/guest_taxes_deadline.html
- uber/templates/guest_checklist/hospitality_deadline.html
- uber/templates/guest_checklist/taxes_deadline.html
- uber/templates/guests/hospitality.html
Adds a new hospitality survey step and adjusts the wording on several steps. Also updates emails to use the taxes deadline, which is the most likely deadline to be the last.
> Update Guest Checklist for Super 2024

- uber/models/legal.py
- uber/payments.py
- uber/site_sections/dealer_admin.py
- uber/site_sections/group_admin.py
- uber/site_sections/preregistration.py
- uber/tasks/groups.py
- uber/templates/emails/dealers/badge_converted.html
- uber/templates/forms/group.html
- uber/templates/group_admin/form.html
- uber/templates/guests/mivs_hotel_space.html
- uber/utils.py
MIVS groups were unable to pay because their email is a list of emails, which the TransactionRequest class wasn't equipped to handle. This should fix that. Also includes the latest code from MFF, which most importantly fixes the Javascript on the dealer form page so that waitlisting and declining dealers actually works.
> Account for multiple emails in TransactionRequests

- uber/models/panels.py
- uber/templates/panel_app_form_new.html
- uber/templates/panels_admin/form.html
Requested via Slack. Also fixes a really annoying bug where if you had "None" for granular rating selected, the box would always be unchecked when you loaded an application.
> Update events tied to panel apps when they are updated

- requirements.txt
- uber/site_sections/registration.py
This generator should perform much better than treepoem for the barcodes that end up in attendee emails.
Generated codes appear to scan the same, though the border is slightly thicker.
> Moving attendee barcodes to pure python generator

- alembic/versions/51f17950b88e_add_full_description_to_attractions.py
- uber/forms/attendee.py
- uber/models/attraction.py
- uber/templates/attractions/features.html
- uber/templates/attractions_admin/form.html
- uber/templates/attractions_macros.html
Adds the ability to set a full description for an attraction so that you can make the main description shorter.
> Add "full description" for attractions

- uber/automated_emails.py
Fixes https://jira.magfest.net/browse/MAGDEV-1216
> Explicitly remove contractors from several automated emails

- uber/model_checks.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/payments.py
- uber/receipt_items.py
- uber/site_sections/group_admin.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-1279 by detecting and correctly updating attendee receipts if they change their DOB. Also fixes a ton of bugs regarding how we handle promo codes -- you can now actually add promo codes to people and their payment status and receipt changes correctly.
> Fix age discount receipt behavior

- uber/models/__init__.py
Fixes https://jira.magfest.net/browse/MAGDEV-1296.
> Fix has_ribbon attribute search

- alembic/versions/1ad8716bfc74_add_start_and_end_time_to_access_groups.py
- uber/models/admin.py
- uber/site_sections/accounts.py
- uber/templates/accounts/access_groups.html
Fixes https://jira.magfest.net/browse/MAGDEV-1074 by letting you specify a start and end time for an access group.
> Add admin access start and end dates

- docker-compose.override.yml.template
- uber/models/__init__.py
- uber/models/attendee.py
- uber/payments.py
- uber/site_sections/email_admin.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_reports.py
- uber/site_sections/registration.py
- uber/templates/email_admin/index.html
- uber/templates/forms/attendee/check_in_form.html
- uber/templates/reg_reports/attendee_receipt_discrepancies.html
- uber/templates/registration/attendee_shifts.html
- uber/templates/registration/form.html
- uber/templates/registration/menu.html
- uber/templates/staffing_reports/volunteer_hours_overview.html
I'm sure there will be more, but here's what we have so far:
- Better manage 'paid' status based on receipts
- Also give 12 and under ribbons to 0-year-old children
- Add explicit check-in notes
- Reset badge #s if they end up mismatched to type
- Add attendee search bar to all attendee detail pages
- Fix error when unassigning from multiple shifts in a row
- Use the correct page handler for deleting an attendee from registration/form
- Add badge type column to volunteer hours overview
- Add pagination to receipt discrepancy report
> Fixes for Super 2024 at-event

- uber/tasks/registration.py
- uber/templates/forms/prereg_intro.html
- uber/templates/preregistration/additional_info.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/index.html
- uber/templates/registration/form.html
Adds check-in notes to the main form page and adds a 'about to sell out' warning to the preregistration form.
> Update registration pages for at-con

- alembic/versions/e4a1d20d687b_add_report_tracking_table_and_update_.py
- uber/configspec.ini
- uber/decorators.py
- uber/models/__init__.py
- uber/models/admin.py
- uber/models/tracking.py
- uber/site_sections/api.py
- uber/site_sections/registration.py
- uber/templates/registration/feed.html
Fixes https://jira.magfest.net/browse/MAGDEV-1181 by adding a ReportTracking class. Also fixes https://jira.magfest.net/browse/MAGDEV-1076 by adding explicit collection logging via the new register_attribute_listeners function. Also gives admins new buttons on the FODC to view page view and report logs.
> Add report and many-to-many table tracking

- uber/forms/widgets.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/payments.py
- uber/site_sections/preregistration.py
- uber/templates/forms/attendee/badge_extras.html
- uber/templates/forms/attendee/other_info.html
- uber/templates/forms/attendee/personal_info.html
- uber/templates/forms/macros.html
- uber/templates/preregistration/dealer_confirmation.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/upgrade_modal.html
Fixes some server-killing bugs I introduced with the flake8 update. Also fixes a few payment-related bugs, adds a way for event plugins to control the receipt updater, and updates the form templates to accommodate changes in the MAGStock plugin.
> Updates and bug fixes for Stock 2024 artist registration

- uber/automated_emails.py
- uber/custom_tags.py
- uber/site_sections/preregistration.py
- uber/site_sections/security_admin.py
- uber/templates/emails/reg_workflow/badge_transfer.txt
- uber/templates/preregistration/banned.html
- uber/templates/preregistration/duplicate.html
- uber/templates/preregistration/transfer_badge.html
- uber/templates/registration/attendee_watchlist.html
Fixes https://jira.magfest.net/browse/MAGDEV-1307 and https://jira.magfest.net/browse/MAGDEV-1300. Also fixes a bug with badge transfers where the badges wouldn't transfer cleanly, with tracking data in particular added to the wrong badge.
> Badge transfer updates and fixes

- uber/models/attendee.py
Fixes https://jira.magfest.net/browse/MAGDEV-859
> Stop cascading deletes for created badges

- docker-compose.yml
- test-defaults.ini
- uber/configspec.ini
- uber/models/commerce.py
- uber/payments.py
- uber/site_sections/dealer_admin.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_reports.py
- uber/site_sections/registration.py
- uber/templates/registration/index_base.html
- uber/templates/registration/menu.html
There was some config missing since it was living in development-defaults.ini. We also needed some updates to work with Stripe's latest library. Also adds dev_box=True to docker-compose.yml and fixes a few other minor issues with the registration index page, converted dealer admin notes, and the self-service refunds page.
> Fix attendees buying badges + other issues post-upgrade

- uber/models/panels.py
- uber/site_sections/panels.py
- uber/templates/guest_checklist/band_panel_deadline.html
- uber/templates/guest_checklist/guest_panel_deadline.html
- uber/templates/guest_checklist/panel_deadline.html
- uber/templates/panels/guest.html
- uber/templates/panels_admin/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-676. Part of this was already done, we just needed to stop setting the guest group leader as the point of contact for the panel.
> Stop setting guest submitter as POC for panels

- uber/site_sections/preregistration.py
I fixed a bug in an earlier PR, which revealed a much worse bug that is preventing anyone from registering at all. I'll have to fix that bug later -- for now, let's just pretend it doesn't exist.
> Emergency bandaid for prereg errors

- uber/forms/attendee.py
Unlimited promo codes were breaking prereg.
> Fix 500 error for promo codes

- uber/automated_emails.py
> Add extra reminder emails for band checklist

- .github/workflows/ci-docker.yaml
- alembic/versions/983af01225fc_add_player_count_content_warning_and_.py
- docs/DEVELOPERS.md
- uber/models/mivs.py
- uber/templates/mivs/game.html
- uber/templates/mivs/index.html
While we couldn't get everything on the list done before opening time, this should improve the MIVS workflow a bit!
> Update MIVS form for Super 2025

- alembic/versions/0ba9060b0434_add_schedule_description_and_separate_.py
- uber/api.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/panels.py
- uber/site_sections/schedule.py
- uber/templates/emails/panels/application.html
- uber/templates/mivs/show_info.html
- uber/templates/panel_app_form.html
- uber/templates/panel_app_form_new.html
- uber/templates/panels/guest.html
- uber/templates/panels/index.html
- uber/templates/panels_admin/app.html
- uber/templates/panels_admin/form.html
- uber/templates/schedule/form.html
- uber/templates/schedule/schedule.tsv
- uber/templates/schedule/schedule.xml
Fixes https://jira.magfest.net/browse/MAGDEV-1318 and also stops setting the livestream/record option to 'yes' by default.
> Update Panels for Super 2025

- alembic/versions/643d80417d4a_add_is_header_and_is_thumbnail_as_.py
- uber/configspec.ini
- uber/custom_tags.py
- uber/model_checks.py
- uber/models/mits.py
- uber/site_sections/mits.py
- uber/templates/mits/game.html
- uber/templates/mits/index.html
- uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-1316.
> Update MITS for Super 2025

- uber/api.py
- uber/site_sections/mivs_admin.py
- uber/templates/mivs_admin/import_judges.html
This isn't perfect because I forgot to add an extra API call to Super 2024 and don't feel like going back and forth on it, but you can now import MIVS judges year to year!
> Add ability to export and import MIVS judges

- alembic/versions/0578795f8d0b_add_vr_text_and_read_how_to_play_for_.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/mivs.py
- uber/site_sections/mivs_judging.py
- uber/templates/mivs_admin/assign_games.html
- uber/templates/mivs_admin/create_judge.html
- uber/templates/mivs_admin/edit_judge.html
- uber/templates/mivs_judging/game_review.html
- uber/templates/mivs_judging/index.html
Implements the part of https://jira.magfest.net/browse/MAGDEV-1329 that's for adding judges and judges reviewing games.
> MIVS 2025 judging updates

- alembic/versions/72225013a93d_guest_music_checklist_updates_for_super_.py
- uber/config.py
- uber/models/guests.py
- uber/site_sections/guests.py
- uber/templates/dept_checklist/form.html
- uber/templates/guest_checklist/band_bio_deadline.html
- uber/templates/guest_checklist/bio_deadline.html
- uber/templates/guest_checklist/guest_bio_deadline.html
- uber/templates/guest_checklist/hospitality_deadline.html
- uber/templates/guest_checklist/performer_badges_deadline.html
- uber/templates/guest_checklist/stage_plot_deadline.html
- uber/templates/guest_checklist/travel_plans_deadline.html
- uber/templates/guests/performer_badges.html
Updates text for existing steps and adds a "performer badges" step that lets groups indicate they've assigned all performer badges. Fixes https://jira.magfest.net/browse/MAGDEV-1330.
> Update Guest/Music checklist for Super 2025

- uber/models/attendee.py
- uber/templates/staffing/shirt_size.html
Also fixes up the step's form to look nicer.
> Fix shirt step being pre-checked

- uber/site_sections/dept_admin.py
Accidentally merged a few things to `main` instead of `super2025`!
> Bring in changes from main

- uber/models/attendee.py
- uber/templates/attractions/events.html
- uber/templates/attractions_badge_num.html
Fixes errors for signing up for an attraction so that they actually show up. Also fixes an issue with to_dict that prevented you from looking up attendees to check into an attraction.
> Fix attendee.to_dict and attractions error

- alembic/versions/2e4feb6c2d18_update_rock_island_checklist.py
- uber/automated_emails.py
- uber/configspec.ini
- uber/model_checks.py
- uber/models/guests.py
- uber/models/tracking.py
- uber/site_sections/guest_reports.py
- uber/site_sections/guests.py
- uber/tasks/groups.py
- uber/templates/emails/daily_checks/ri_inventory_updates.html
- uber/templates/emails/guests/rock_island_intro.txt
- uber/templates/emails/guests/rock_island_inventory_reminder.txt
- uber/templates/guest_checklist/band_autograph_deadline.html
- uber/templates/guest_checklist/merch_deadline.html
- uber/templates/guest_reports/rock_island.html
- uber/templates/guests_macros.html
- uber/templates/macros.html
Fixes https://magfest.atlassian.net/browse/MAGDEV-1313.
> Update Rock Island for Super 2025

- uber/decorators.py
- uber/site_sections/reg_reports.py
Limit the splash zone of the stream change to only pages that opt in with the `@streamable` decorator.
> Only streaming some pages

- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/group.py
- uber/site_sections/group_admin.py
Fixes https://magfest.atlassian.net/browse/MAGDEV-1343. Also fixes a bug where, if you were linked to a group, you could view the group regardless of your permissions.
> Add better access controls for groups

- alembic/versions/300b55d2f88c_add_transfer_code_to_attendees.py
- uber/configspec.ini
- uber/models/attendee.py
- uber/site_sections/preregistration.py
- uber/tasks/registration.py
- uber/templates/emails/reg_workflow/badge_transferee.txt
- uber/templates/emails/reg_workflow/badge_transferer.txt
- uber/templates/forms/attendee/other_info.html
- uber/templates/forms/macros.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/start_badge_transfer.html
Allows attendees to transfer badges using codes, including a way to check the transferer's code against the system.
> Add anonymous badge transfers

- uber/site_sections/guest_reports.py
- uber/site_sections/reg_reports.py
- uber/templates/guest_reports/rock_island.html
- uber/templates/reg_reports/comped_badges.html
- uber/templates/reg_reports/comped_badges_group.html
- uber/templates/reg_reports/self_service_refunds.html
Fixes https://magfest.atlassian.net/browse/MAGDEV-1389.
> Add extra reports for finance office

- uber/site_sections/guest_reports.py
- uber/site_sections/reg_reports.py
There were some issues with the budget reports added for Super 2025 which only cropped up with specific data. These changes fix all those issues.
> Fix errors with new budget reports

- uber/site_sections/shifts_admin.py
- uber/templates/registration/attendee_shifts.html
Fixes https://magfest.atlassian.net/browse/MAGDEV-1406.
> Update non-shift hours and notes at once

- uber/automated_emails.py
- uber/configspec.ini
- uber/templates/emails/guests/guest_checklist_announce.html
- uber/templates/emails/guests/guest_checklist_reminder.html
- uber/templates/guest_checklist/arena_hospitality_deadline.html
Fixes https://magfest.atlassian.net/browse/MAGDEV-1421.
> Add Arena checklist

- alembic/versions/34f9d87b62f4_add_accessibility_request_checkbox_for_.py
- uber/configspec.ini
- uber/forms/panels.py
- uber/models/panels.py
- uber/site_sections/panels_admin.py
- uber/templates/emails/panels/accessibility_requested.txt
- uber/templates/forms/macros.html
- uber/templates/forms/panel/panel_consents.html
- uber/templates/forms/panel/panelist_form.html
- uber/templates/panels_admin/email_statuses.html
Panelists will now be able to request to be contacted by the accessibility team, who will be notified if that panel is approved.
> Add checkbox for accessibility services to panels

- uber/templates/staffing/food_item.html
- uber/templates/staffing/volunteer_agreement_item.html
> Temporarily disable checklist steps

- uber/config.py
- uber/configspec.ini
- uber/site_sections/hotel_lottery_admin.py
Pushing final lottery weighting code
> Updating lottery code
