development-defaults.ini
This department originally wasn't going to have any shifts, but then we made shifts for them!  Huzzah!
=> removed contractors (aka Public Safety) as a shiftless dept so they can sign up for shifts

development-defaults.ini, uber/config.py, uber/model_checks.py, uber/site_sections/registration.py, uber/templates/registration/index.html, uber/templates/registration/new.html, uber/templates/registration/register.html
A bunch of first-pass bugfixes and improvements to our workflow for process new at-door registrations.
=> At-door fixes

uber/custom_tags.py, uber/model_checks.py, uber/models.py, uber/site_sections/hotel.py, uber/site_sections/registration.py, uber/site_sections/signups.py, uber/site_sections/summary.py, uber/templates/accounts/homepage.html, uber/templates/hotel/no_shows.html, uber/templates/registration/merch.html, uber/templates/registration/shifts.html, uber/templates/signups/printable_schedule.html
A bunch of small fixes for various issues, plus several more fixes for bugs I found while testing.
Fixes #131 #136 #148 #167 #796 and #671.
=> Minor fixes for STOPS and Merch

uber/templates/jobs/everywhere.html
The server is exploding on this error.
=> Emergency fix for WORKED_OPTS

uber/custom_tags.py, uber/site_sections/registration.py, uber/templates/registration/arbitrary_charge_form.html
We occasionally need a convenient way to let people pay us arbitrary amounts of money during the year.  We already have an arbitrary charge form, which we happened to put under ``registration`` since that's the place that will tend to use it on-site.  But really there's no reason to lock this down, since all it lets the internet do is pay MAGFest money with a credit card.
=> allow arbitrary charges during the year

uber/site_sections/summary.py, uber/templates/summary/extra_merch.html
=> added report on extra merch

development-defaults.ini
I also removed Press Ribbon, after fixing the production database to remove the two people with Press Ribbons.
=> fixes #949

uber/templates/groups/form.html
Fix #843 to make our lives easier at-fest.
=> Add unassign button to group form

uber/custom_tags.py, uber/models.py, uber/site_sections/preregistration.py, uber/templates/accounts/homepage.html, uber/templates/emails/reg_workflow/attendee_confirmation.html, uber/templates/preregistration/confirm.html, uber/templates/preregistration/group_members.html, uber/templates/registration/form.html, uber/tests/models/test_attendee.py
=> Add text for prices and fix transfer button

uber/site_sections/preregistration.py, uber/templates/emails/reg_workflow/prereg_check.html, uber/templates/preregistration/check_if_preregistered.html
=> Add public form to check badges by email

uber/automated_emails.py, uber/templates/emails/shifts/schedule.html
Add group payment reminder emails and shift schedule emails.
=> New automated emails

uber/site_sections/preregistration.py
=> Keep badge type and ribbon when claiming

uber/templates/emails/daily_checks/duplicates.html, uber/templates/emails/dealers/payment_reminder.txt, uber/templates/groups/index.html, uber/tests/import_test_data.py
Fixes #965. Also fixes reference to a non-existent amount_owed property
in a couple emails.
=> Split "Owed" into "Cost" and "Unpaid"

uber/automated_emails.py, uber/site_sections/schedule.py
I also did some refactoring, which I'll explain inline.
=> fixed schedule.tsv file to use correct timezones

uber/site_sections/jobs.py, uber/site_sections/schedule.py
I did a grep of our codebase for all instances of ``start_time`` so that I could change it to ``start_time_local``.  I swear I did this before, but there were some places that I must have missed... or maybe I never did it at all.  Either way, it's been done now.
=> only remaining (I think) timezone bugs

uber/models.py, uber/site_sections/tabletop.py, uber/static/lib/angular/tabletop/app.js, uber/static/lib/angular/tabletop/form.html, uber/static/lib/angular/tabletop/game_list.html, uber/templates/tabletop/index.html
The tabletop Angular app hadn't yet been converted to idiomatic Angular.  Also there was a minor fix I wanted to make to keep checkouts in the database after they're no longer relevant, plus a couple of efficiency improvements.
=> fixed tabletop code to work with new Angular system

uber/templates/preregistration/check_if_preregistered.html
Text changes requested by Nick.
=> Reword pre-reg check

uber/templates/signups/printable_schedule.html
This matches what we put in the emails.
In the long run we should have this come from the same source or something.
=> minor tweaks to Galaxy Cafe info

uber/site_sections/registration.py
I made a performance improvement last night but didn't do a good enough job on the Shifts form for an attendee.  I've improved it to show start/end time and department and to only show jobs with open slots.
=> signups dropdown now only shows available shifts

uber/templates/static_views/prereg_closed.html
=> Add line about not selling out

uber/site_sections/registration.py, uber/templates/registration/new.html
I'll comment on my fixes inline.
=> fixes #989, fixes #988, fixes #987

uber/models.py
I'll explain the changes inline.
=> fixes #550

uber/automated_emails.py, uber/templates/emails/shifts/schedule.html, uber/templates/signups/printable_schedule.html
Derp, I accidentally included another timezone bug in our shift email.  Derp.
=> fixed shift email

uber/automated_emails.py, uber/site_sections/jobs.py, uber/site_sections/preregistration.py, uber/templates/common.js, uber/templates/jobs/signups.html, uber/templates/preregistration/group_members.html
I'll explain all of the changes inline.
=> turned off most emails when Uber is not in precon mode, plus made some miscellaneous shift-related fixes

uber/custom_tags.py, uber/site_sections/jobs.py, uber/templates/jobs/all_shifts.html
Previously we had a CSV file that got spit out that had to be manually adjusted and then used to generate a PDF, which would be printed.
That was stupid, so we made this.
=> added new all_shifts printout

uber/templates/accounts/homepage.html, uber/templates/registration/checkin.html, uber/templates/registration/form.html, uber/templates/registration/index.html
Three fixes, which I'll explain inline.
=> misc reg checkin fixes

uber/site_sections/groups.py
=> authorized REG_AT_CON access people to be able to see groups

uber/site_sections/registration.py
Really simple fix, should have spotted it before now.
=> fixed checkin count to show basges checked in instead of badges NOT checked in

uber/model_checks.py, uber/site_sections/registration.py
Two fixes, which I'll explain inline.
=> fixed reg error and added filter to shifts on attendee form

uber/site_sections/accounts.py
The bug was in how the rows were ordered not in whether they displayed at all.
=> fixes #1012

uber/templates/registration/checkin.html
Vicki clearly didn't test this before pushing, so in honor of her, I didn't test this either :P
=> fixed Vicki's zip code typo

uber/site_sections/registration.py, uber/templates/accounts/homepage.html, uber/templates/jobs/everywhere.html, uber/templates/preregistration/badge_choice.html, uber/templates/registration/index.html
A batch of improvements, which I'll explain inline.
=> Misc atd improvements

uber/templates/preregistration/form.html, uber/templates/preregistration/paid_preregistrations.html
Minor fixes to the pre-reg pages for Magstock (and other MAGFest events).
=> Prereg display fixes

development-defaults.ini, uber/static/theme/prereg.css, uber/templates/preregistration/form.html, uber/templates/regform.html
Changes are explained inline.  I'll go ahead and merge this now so that it won't end up conflicting with anything that anyone else does.
=> fixes #1049, #1054, #1055, #1058

uber/config.py, uber/templates/preregistration/form.html
=> Add limited stock for Supporter packages

uber/templates/static_views/legal_name.html
=> Remove references to badges in Legal Name template

uber/site_sections/registration.py, uber/templates/registration/print_badge.html, uber/templates/registration/printable_badges.html
Fixes a few minor bugs from the last PR, and adds in the ability to distinguish between minor and adult badges.
=> Badge printing fixes

uber/site_sections/preregistration.py
Fixes a bug where you couldn't view a group page unless there was a
group leader.
=> Fixes 1116

LICENSE.txt
This updates our license to the Affero General Public License 3.0.
At the time of this commit, there are 11 contributors to this repository. All of them are tagged below. Please reply to this issue with a comment such as "I agree" to note your consent to this license change. 
(Note, if anyone does not agree / does not respond, we will need to remove their contributions from the current version before landing this PR. As only the first 3 contributors listed have more than 10 commits, this shouldn't be too hard, but it's easiest if everyone just replies with their consent.)
=> Change license to AGPL3

uber/badge_funcs.py, uber/config.py, uber/configspec.ini, uber/models.py, uber/site_sections/registration.py, uber/templates/preregistration/preregbase.html, uber/templates/regform.html, uber/templates/registration/checkin.html, uber/templates/registration/form.html, uber/templates/registration/index.html, uber/templates/registration/new.html, uber/templates/registration/register.html
With MAGStock coming up, I needed to make two big fixes:
1) When unifying all of the reg forms, I forgot to include the form for at-the-door registration, so I updated that one to use the same common reg form that the others use.
2) Since MAGStock doesn't use numbered badges, I added a new ``c.NUMBERED_BADGES`` boolean config option which is True by default.  When false, we no longer require badge numbers to be entered when checking someone in.
There were also a couple of minor code fixes.  I've leave inline comments explaining what I did.
=> Fixes for at-the-door checkin

uber/models.py
Since the atd_fixes PR isn't merged yet, I'm making this PR into that branch, since it's an issue I'd like to get deployed at the same time. I figure we can merge this branch into atd_fixes and then accept that PR into master.
I'll explain my fix inline.
=> added fix for bug that was recently introduced in column overriding fix

.gitignore, uber/templates/groups/form.html
=> Added badge name to Group page, cleaned up line spacing

uber/custom_tags.py, uber/templates/static_views/prereg_closed.html
for https://phab.thae.li/T82
Note:  development-defaults.ini has wrong prices and # of days in
[[single_day]] section.  Not _quite_ sure where $55 for the weekend is
coming from.
=> Fixes mangled display of single day prices

uber/site_sections/registration.py, uber/templates/registration/temp_fix_badge_status.html
Thanks to an uncaught bug in AC, many badges' statuses are wrong. This
script attempts to fix them en masse.
=> Add temp script to fix badge status

alembic/versions/16acd13b4aa1_base.py, alembic/versions/51e4adb4b60_jobs_and_food.py, alembic/versions/54fae9d8798_add_donation_tier.py
These adjustments allow the ac prod db schema to cleanly upgrade to the current version.
=> Alembic fixes to upgrade the ac prod db to current

uber/models.py, uber/site_sections/registration.py
The previous adjustment missed out on people inside paid or comped groups, so this improves that on the fix-script level and the database-entry level.
=> Improve badge status adjustment

uber/models.py, uber/sep_commands.py, uber/site_sections/accounts.py, uber/utils.py
I need this fixed up in master, so here are just the 4 commits cherry-picked
please code review this one, I'd like to merge for magclassic asap.
=> Insert admin (same thing, but rebased against master)

uber/models.py, uber/site_sections/registration.py, uber/templates/registration/print_badges.html
AC needs some changes to the exact way a badge is printed and formatted, so here we go.
=> AC print fixes

uber/templates/accounts/index.html
There were some front-end issues with admin accounts that posed a real usability problem, so they have to be fixed for AC.
=> Fix admin account page styling

uber/site_sections/registration.py, uber/templates/registration/printed_badges.html
The page links were going to the wrong page because it's way too late at night to be trying to do anything useful.
=> Pending pagination fix

development-defaults.ini, uber/models.py, uber/templates/preregistration/form.html, uber/templates/regform.html
I need to do a bunch more testing, but I've fixed the stuff that was stopping group preregs from being possible.
This was all tested originally before I launched Magstock prereg, but since Magstock didn't use groups, it ended up breaking when I made further refactors.
I'll explain my changes inline.
=> Group preregistration now works

uber/site_sections/registration.py, uber/templates/registration/form.html, uber/templates/registration/watch_list.html
This is an incomplete revamp of the watch list. It's WIP but the current commits contain fixes that we need for AC opening.
=> Revamp watch list

uber/decorators.py, uber/site_sections/summary.py, uber/templates/base.html
Also includes some extra fixes to the summary page
=> Re-enable pre-reg page for phones just for AC

uber/site_sections/preregistration.py, uber/templates/base.html, uber/templates/preregistration/index.html
emergency Anthrocon fix
fixes the silent failure of Stripe on the prereg form.
however, introduces one more issue to fix, which is it says "are you sure you want to navigate away before paying" which is incorrect because they did in fact pay already.
bonus: fixes weird formatting stuff that was going on when you had 1 vs multiple regs
=> fix prereg stripe form not working due to HTML error

uber/templates/preregistration/form.html
=> Move badge types div

uber/templates/static_views/slow_load.html
=> Change contact to Registration AT MAGFest . org

uber/site_sections/preregistration.py
=> Fixes charge error for group payment

uber/site_sections/jobs.py, uber/templates/base.html, uber/templates/jobs/index.html, uber/templates/jobs/main_menu.html, uber/templates/jobs/staffers.html
A couple very minor fixes for STOPS' workflow.
Fixes #1258
Fixes #1180 
Fixes #1181
=> Staffing Ops fixes

uber/templates/registration/staffers.html
these were omitted from the refactor probably just for the sake of time, I just put them back in.
should fix #1265 
@thaeli probably a good idea to put your eyes on this just to make sure I didn't do anything that breaks the UI.  I think it's pretty straightforward though
=> put sorting options back into the code

development-defaults.ini, uber/automated_emails.py, uber/templates/preregistration/preregbase.html, uber/templates/regform.html
High-priority changes which need to happen before we can import last year's staffers.
=> Preimport fixes

uber/templates/base.html, uber/templates/preregistration/dealer_confirmation.html
Fixes #1248.
Would like a review by Danielle, if possible. @nickthenewbie1 can you contact her?
=> Generic text for dealer confirmation

uber/configspec.ini, uber/site_sections/preregistration.py, uber/templates/preregistration/dealer_registration.html, uber/templates/preregistration/form.html
Fixes #1101 and fixes #1244.
There were also a couple of unreported bugs that prevented people from registering as a dealer, so we definitely need this merged before the weekend.
=> Basic fixes for dealer registration

uber/templates/preregistration/preregbase.html
Fixes the 500 error when access the dealer reg page.
=> Don't display ribbon_and_or_badge for dealer reg

uber/models.py, uber/site_sections/jobs.py, uber/templates/regform.html, uber/templates/registration/form.html
I don't believe that any of this conflicts with any of the other PRs, so the order in which things are merged shouldn't matter.
I'll explain my fixes inline.
=> Several STOPS-related fixes

uber/custom_tags.py, uber/models.py, uber/templates/emails/dealers/payment_notification.txt, uber/templates/groups/form.html, uber/templates/preregistration/form.html, uber/templates/regform.html
Miscellaneous fixes to the workflow and UI for dealer registration.
Fixes #1287 
Fixes #1286 
Fixes #1283 
Fixes #1288 
Fixes #1282
=> Dealer frontend fixes

db/deploy/add-badge-statuses.sql, db/deploy/master-base.sql, db/raw/add-badge-statuses.sql, db/raw/master-base.sql, db/raw/master-head.sql, db/revert/add-badge-statuses.sql, db/revert/master-base.sql, db/sqitch.conf, db/sqitch.plan, db/verify/add-badge-statuses.sql, db/verify/master-base.sql, uber/configspec.ini, uber/models.py, uber/static/theme/prereg.css, uber/templates/registration/form.html
Fixes #1222 and, in the process, attempts to address #199.
=> Add badge statuses

uber/templates/registration/form.html
Fixes the current 500 error on the server.
Emergency fix!
=> Change 'staffing' checkbox to 'trusted'

uber/templates/preregistration/form.html, uber/templates/regform.html
We had some Javascript code on the main prereg form which assumed that certain fields would always be there, but those fields are not present for dealer reg.
=> fixed some JS errors on dealer reg

uber/templates/registration/staffers.html
When the Anthrocon folks did the bootstrap refactor the made the form a lot prettier, but the part where the form actually submitted anything to anywhere got removed :)
That's fixed now.
=> Fixed staffer search

development-defaults.ini
Required to fix some of the config-related bugs.
Please merge only after https://github.com/magfest/production-config/pull/19
=> Removes several config options added to puppet

uber/models.py
I'll explain inline, but we were previously giving an error if someone entered a birth date which indicated they were more than 100 years old.
=> fixed error for people over 100 years old

uber/custom_tags.py, uber/templates/emails/reg_workflow/attendee_confirmation.html, uber/templates/emails/reg_workflow/badge_transfer.txt, uber/templates/emails/reg_workflow/group_confirmation.html, uber/templates/emails/reg_workflow/group_preassign_reminder.txt, uber/templates/emails/reg_workflow/under_18_reminder.txt
We now include the event dates in all of the confirmation emails.
=> fixes #1275

development-defaults.ini
=> Configure and standardize entries under the [age groups] section

uber/templates/preregistration/form.html
Danielle asked for this wording change.
=> tweaked wording on dealer address

uber/site_sections/preregistration.py
This was removed during a refactor and is now being added back in.
=> added validation for dealer address being required

uber/templates/emails/dealers/application.html, uber/templates/emails/dealers/approved.html, uber/templates/emails/dealers/dealer_received.txt, uber/templates/emails/dealers/payment_confirmation.html
Nick pointed out that the earlier pull request didn't touch any of the dealer emails, and we should definitely have our event dates in those.
=> added event dates to marketplace emails

requirements.txt, setup.cfg, uber/models.py, uber/tests/conftest.py, uber/tests/models/test_apply.py, uber/tests/models/test_attendee.py, uber/tests/models/test_badge_funcs.py, uber/tests/models/test_event.py, uber/tests/models/test_getattr_fields.py, uber/tests/models/test_getter.py, uber/tests/models/test_group.py, uber/tests/models/test_job.py
I fixed the unit tests to work again after the big refactor.  The main change was the ``c`` refactor, which actually makes unit testing a lot easier, since we don't have to muck around with global variables as much.
While fixing the unit tests, I found several bugs, so this has already paid off :)
I'll explain the fixes inline.  @kitsuta and I can hopefully find some time within the next week or so to go over unit testing in general and walk through writing some new unit tests, etc.
=> working unit tests

uber/site_sections/signups.py
There were two bugs with the hotel form on the volunteer checklist.  I've fixed both of them, which I'll explain inline.
=> Hotel requests form fix

uber/config.py, uber/configspec.ini, uber/server.py
This involved a fairly significant change which I'll explain inline.
=> Shift signups now work again

uber/automated_emails.py
Derp.
The really troubling thing here is that I *swear* I tested this locally and didn't see this.  I'm wondering if ``sudo supervisorctl restart all`` just sometimes doesn't actually restart.
Or maybe I was just tired and totally zoned out during testing and looked straight at the error message and was like, "Yep, looks good."  I like to imagine that's not it, but knowing me it's hard to be sure :/
=> fixed email sending bug

uber/common.py, uber/config.py
My earlier PR which implemented the ``[secret]`` stuff had a bug in it, which this fixes.  I'll explain inline.
=> Config fix

uber/config.py
Requested in Slack, can't find issue here.
=> Alphabetize Jobs List (requested by @bsmart)

uber/templates/jobs/staffers.html
Would like to merge ASAP so @JennyTruss can review/comment
=> Fixes #1375

Gruntfile.js, bower.json, uber/static/deps/combined.css, uber/static/deps/combined.js, uber/templates/accounts/index.html, uber/templates/base.html, uber/templates/budget/index.html, uber/templates/groups/index.html, uber/templates/jobs/staffers.html, uber/templates/preregistration/index.html, uber/templates/preregistration/paid_preregistrations.html, uber/templates/registration/attendee_upload.html, uber/templates/registration/index.html, uber/templates/registration/staffers.html
Fixes https://github.com/magfest/ubersystem/issues/1273 by replacing the broken FooTable plugin with DataTables.
=> Replace FooTable with DataTables

uber/models.py
Fixes https://github.com/magfest/ubersystem/issues/1404.
=> Automatically set new volunteers as staffing

uber/templates/preregistration/index.html, uber/templates/preregistration/paid_preregistrations.html, uber/templates/preregistration/preregbase.html
Fixes https://github.com/magfest/ubersystem/issues/1423, which is needed for Super MAG, plus changes the pre-reg form so it's a little cleaner during checkout.
=> Super MAG Frontend Fixes

uber/templates/preregistration/preregbase.html
=> Remove extra if statement from merging

development-defaults.ini
=> remove obsolete option

uber/api.py, uber/common.py
Implements the API requested at #1163 over JSON-RPC.  Two methods have been implemented:
- ``attendee.lookup(badge_num)``: returns a single attendee with the given badge number as a dictionary.  If the attendee doesn't exist, a dictionary with an ``error`` key will be returned.
- ``attendee.search(query)``: returns an array of all attendees which match the search string, using the same search logic implemented on the admin Attendees list.  An empty array will be returned if no attendees match the query.
Note: this will do absolutely nothing at all until @binary1230 adds some Nginx config, because Sideboard exposes a ``/jsonrpc`` web handler, but Nginx is currently configured to only proxy requests under ``/uber``.
However, if you were running locally on the box, where you can connect …
=> Implemented a basic API for querying attendees

uber/templates/preregistration/preregbase.html, uber/templates/regform.html
Fixes https://github.com/magfest/ubersystem/issues/1464.
=> Fix Kick-In Buttons on Confirmation Page

uber/config.py, uber/templates/base.html
Fixes https://github.com/magfest/ubersystem/issues/1212.
=> Add tooltips and logged-in user to nav-bar

uber/models.py, uber/tests/models/test_badge_funcs.py
Fixes https://github.com/magfest/ubersystem/issues/1484.
=> Allow badge_num to be set to 0 when shift_custom_badges is False

uber/site_sections/jobs.py, uber/templates/jobs/main_menu.html, uber/templates/jobs/staffers.html
can be viewed across all departments fixed #1392
=> Add "All" option so that the staffer summary

uber/models.py, uber/site_sections/registration.py
This problem happened if we checked someone in who didn't already have an age group set.
=> fixed age group int conversion

uber/config.py, uber/templates/base.html
Previously if you logged in and only had ``REG_AT_CON`` access then you got a homepage with no links in the menu.  There should probably be links there :)
=> added links for people with reg-at-con access

uber/site_sections/summary.py
I tested locally and on staging, but neglected to check the case where all of the volunteers were refunded, which trips a dumb typo I made.
=> fixed dumb typo in previous PR

uber/site_sections/summary.py, uber/templates/summary/volunteers_owed_refunds.html
Brent asked for a new section on the report of volunteer refunds to show the volunteers who will eventually be eligible for refunds once they get their hours marked.
=> added Volunteers Eventually Eligible For Refunds to stops report

db/deploy/add-watch-list.sql, db/raw/master-head.sql, db/revert/add-watch-list.sql, db/sqitch.plan, db/verify/add-watch-list.sql
I mistakenly though the database would add columns automatically, but that seems to not be the case. This is better for long-term records, anyway.
=> Add watchlist sqitch migration

uber/site_sections/preregistration.py
Fixes https://github.com/magfest/ubersystem/issues/1042.
=> Only force refresh if not AT_THE_CON

uber/templates/base.html
Fixes https://github.com/magfest/ubersystem/issues/1548. Fixes https://github.com/magfest/ubersystem/issues/1549.
=> Add "All" filter and save state for datatables

uber/tests/models/test_attendee.py
1) some tests weren't running because the test names didn't start with 'test_'
2) 4 of these tests weren't working originally, they were crashing on calling presave_adjustments() because we were doing monkeypatch() stuff.  solution: DO MORE MONKEYPATCH STUFF!!
These are the tests I identified in https://github.com/magfest/ubersystem/issues/1574
=> re-enable some unit tests that weren't running

uber/model_checks.py, uber/templates/base.html, uber/templates/preregistration/preregbase.html, uber/templates/regform.html
Makes amount_extra actually work when this option is turned off.
=> Finish implementing c.DONATION_SLIDER_DISPLAY

uber/decorators.py, uber/model_checks.py, uber/models.py, uber/site_sections/preregistration.py, uber/utils.py
Gonna take a page from @binary1230's book here and merge into a feature branch since this is essentially a new feature required by that other branch.
=> Add Prereg Validations

uber/site_sections/registration.py, uber/templates/registration/inactive.html
As requested, this report shows all attendees whose registrations are not new / complete.
=> added report for invalid/deferred badges

uber/site_sections/summary.py, uber/templates/summary/shirt_counts.html
This year we changed the label from "no shirt" to "No Shirt", which broke one of our pages.  I fixed this so that it will not matter what the label is in the future.
=> fixed shirt count page

uber/badge_funcs.py
Fixes https://github.com/magfest/ubersystem/issues/1543 by changing attendee's badge status when they're detected as duplicates, which we want anyway because they shouldn't check in without their situation being resolved.
Also stops sending emails for duplicates in unapproved groups, because nothing can be done with them until they've been waitlisted, approved, or declined.
=> Make Duplicates report stop sending the same attendees

uber/static/angular-apps/signups/possible.html
Changes c.EVENT_NAME to c.EVENT_NAME_AND_YEAR. See issue #1494.
=> Change to c.EVENT_NAME_AND_YEAR

uber/templates/preregistration/preregbase.html, uber/templates/regform.html
Fixes https://github.com/magfest/ubersystem/issues/1626, which was a bug exposed by a configuration change this year. Also fixes a previously-unknown bug with groups.
=> Fix prereg JS errors

uber/reports.py, uber/site_sections/summary.py
potentially fixes #1648, still need to test.  bored at jury duty. internet barely works YOLO PULL REQUEST
-Dom
=> printed badges: only list badges for printing that are not invalid or deferred

uber/automated_emails.py, uber/models.py, uber/site_sections/budget.py, uber/site_sections/emails.py, uber/site_sections/jobs.py, uber/site_sections/registration.py, uber/site_sections/summary.py, uber/templates/jobs/everywhere.html, uber/templates/jobs/job_renderer.html, uber/templates/jobs/signups.html, uber/templates/registration/recent.html, uber/templates/summary/affiliates.html, uber/templates/summary/index.html, uber/templates/summary/shirt_counts.html
Here are the stats on page load times before and after this round of optimizations.  As you can see, there's still a lot more slowness than we'd probably like, but it's way better, and all of the common pages especially have been much improved.
Here are the before numbers (all pages sorted from fastest to slowest):
```
0.0008997917175292969 seconds: /preregistration/kiosk
0.0010788440704345703 seconds: /preregistration/paid_preregistrations
0.002763032913208008 seconds: /registration/new
0.003251314163208008 seconds: /magprime_dept_checklist/index
0.004004478454589844 seconds: /accounts/insert_test_admin
0.009475231170654297 seconds: /common/index
0.018666744232177734 seconds: /tabletop_checkins/badged_attendees
0.02135157585144043 seconds: /signups/jobs
0.029811859130859375 seconds: …
```
=> Performance tuning

uber/models.py, uber/site_sections/registration.py, uber/templates/registration/new.html
There were some bugs I just fixed after an initial round of testing on at-the-con mode, mostly relating to badge statuses.  I'll explain them inline.
=> initial round of at-the-door fixes

uber/configspec.ini, uber/models.py, uber/site_sections/registration.py
As discussed via email earlier today, there is now a config option to turn wristbands on and off.
=> wristbands can now be turned off as a feature

uber/models.py, uber/site_sections/accounts.py, uber/templates/accounts/index.html, uber/templates/registration/checkin.html
=> Badge num to bottom of checkin popup

uber/site_sections/accounts.py, uber/templates/accounts/index.html
=> Sort Accounts table by last_first

uber/site_sections/registration.py
=> attendee search now properly strips leading and trailing whitespace

uber/templates/registration/new.html
=> At-the-door admin page now uses datatable for searching/filtering

uber/templates/registration/check_in_form.html
fixes #1718 which it turns out CAN just be done in the core repo.  Whoops.
=> added badge printed name to check-in modal

uber/site_sections/registration.py, uber/templates/registration/register.html
This somehow got lost awhile back.
=> we now perform standard validations on at-the-con registrations

uber/site_sections/registration.py
Fixed a dumb typo in the badge change page handler.
=> fixes #1726

uber/site_sections/summary.py, uber/templates/summary/index.html
=> Badge stocks on summary page

uber/site_sections/registration.py
=> Badge types can now be changed without assigning a number

uber/templates/registration/shifts.html
To prevent it touching the rating icons
=> Added a bit of whitespace after the Unassign button

uber/templates/preregistration/disclaimers.html, uber/templates/registration/register.html
Added 2 lines to disclaimer, and added disclaimer to at-the-con reg.
=> Disclaimer changes

uber/static/angular-apps/signups/app.js
It used to print out endless info lines, now it toggles the info line.
=> Added a toggle to the shift info '?' mark

uber/templates/registration/shifts.html
=> adds total weighted hours

uber/templates/registration/new.html
These changes were discussed with Bob and Vicki, respectively.
=> added date of birth to atd new page, and also added registered column

uber/site_sections/registration.py
So volunteers can be assigned shifts they picked up on the spot
=> Shifts stay available for 2 hours after they end

uber/templates/groups/form.html
=> Time fixed, columns rearranged, padding added

uber/config.py
This should make the badge count more accurate.
=> Update BADGES_SOLD to be only Completed badges

uber/site_sections/registration.py
=> allows for leading and trailing spaces in database search

uber/templates/regform.html
=> alligned checkbox, disable field if no phone

uber/templates/regform.html
Reverts magfest/ubersystem#1760
=> Revert "alligned checkbox, disable field if no phone"

uber/templates/regform.html
This is the real fix, ignore the reverting stuff.
=> fixes #1384

uber/templates/regform.html
=> removed kick in from badge transfer

uber/templates/preregistration/group_members.html
makes changes to group_members.html. Button to add members disabled if group not paid up. Links made into buttons as well. #620
=> fixes #620

uber/templates/registration/shifts.html
Makes every other row in the table light grey. #1770
=> fixes #1770

uber/templates/registration/form.html
=> Disabled delete badge button for paid badges

uber/templates/registration/index.html
auto selects text in search bar on load. #1771
=> fixes #1771

uber/templates/accounts/index.html
=> Added a check password field to create admin

uber/models.py
Fixes checks made against watchlist when creating new attendee to make it more accurate. #1714
=> fixes #1714

uber/site_sections/preregistration.py, uber/site_sections/registration.py, uber/static/js/servertimecheck.js
fixes 'magbot badges' which was not receiving JSON but an error saying "Pregistration is now closed! Look out for next year!"
=> fix stats JSON not working after con is over

uber/model_checks.py
=> Remove arbitrary $2000 group limit

uber/model_checks.py
Fix a typo introduced a while back that no one caught prior to now
Since this is extremely minor, and already broken, I'm going to merge this now.
=> fix typo in model_checks.py

uber/configspec.ini
- for use with (maybe) bands plugin, and probably other future stuff
goes with https://github.com/magfest/ubersystem-puppet/pull/84 and https://github.com/magfest/production-config/pull/26
=> add INI settings for event venue name + address

uber/templates/preregistration/preregbase.html
Fixes https://github.com/magfest/magclassic/issues/27.
=> Fix variable check for toastr group prereg error

uber/models.py, uber/templates/registration/index_base.html
fixes https://github.com/magfest/magstock/issues/95
testing this out now locally
=> show error message if we can't check someone in

uber/site_sections/registration.py
The override price when entered as blank comes in as a string. In the case of this, it is converted to the integer -1. I also check for the parameter existing in the case of a weird post request or something I'm unaware of triggering the function. If the price is 0, the user is set to NEED NOT PAY, and the override price is reset back to BADGE_PRICE in case of any math done with said price.
=> Allow Admins to create Discount Badges at the cost of nothing.

uber/templates/registration/placeholders.html
=> display placeholder length on registration/placeholders

uber/site_sections/preregistration.py
=> remove dead code as stated in issue #1889

uber/site_sections/budget.py
Reverts magfest/ubersystem#1920
This doesn't actually work on the staging server.
=> Revert "fix-#1919 Add Kickins"

development-defaults.ini
Goes with / required for https://github.com/magfest/magprime/pull/95.
=> Change default age groups

uber/reports.py, uber/site_sections/summary.py
=> Export of volunteers who worked hours

uber/custom_tags.py
Indicate that price may increase earlier. Fixes https://github.com/magfest/ubersystem/issues/1944
=> Modify verbiage on price increase text

uber/common.py, uber/config.py, uber/models.py
Fixes https://github.com/magfest/magclassic/issues/41.
=> Make admin_table_opts floats

uber/automated_emails.py, uber/models.py, uber/utils.py
Fixes https://github.com/magfest/ubersystem/issues/1594.
=> Add email_id to let us change automated emails' subjects

uber/templates/regform.html
Chaney sync'ing this up so we can continue working on it.
=> more WIP kickin ui changes

uber/templates/regform.html
CHANEY AND DARE GETTING IT DONNNNNNNNNNNNNE
probably final pass on UI for kickin
=> basically final pass on UI for kickin tiers

uber/templates/regform.html
=> WIP mediaquery for kickin UI

uber/templates/preregistration/disclaimers.html
Resolves [MAGPrime #137](https://github.com/magfest/magprime/issues/137)
=> Fix spelling error

uber/models.py
Fixes https://github.com/magfest/magprime/issues/133.
=> Fix auto_badge_num error when registering a group/dealer

uber/sep_commands.py
- needed for a data migration we need to do to fix group prices
=> add sep command to resave all attendees and groups

uber/reports.py, uber/site_sections/summary.py
Add a few extra supporter and staff badges
=> add some extra badges to badge report export

uber/site_sections/summary.py
rename to badge_hangars
- turns out, it didn't make much sense what we were doing
=> revert previous extra supporter badge change

uber/templates/preregistration/dealer_confirmation.html, uber/templates/preregistration/form.html
Danielle asked for these changes
This does change the text for maglabs, however, since their applications are already done, it's OK and next time we can do some template overriding to make this work more generically.  Even with that, it's all still pretty generic.
=> tweak dealer application text per Danielle

uber/sep_commands.py
per https://github.com/magfest/ubersystem/pull/1985#discussion_r75587982
=> print more accurate messages when re-saving

uber/site_sections/devtools.py, uber/site_sections/registration.py
Allows @cybersenshi and I to display current badge price on the website through AJAX without exposing sensitive data
=> Add a function to the ubersystem to display current badge price

uber/site_sections/accounts.py, uber/templates/accounts/change_password.html
=> add password confirmation

uber/tests/models/test_attendee.py, uber/tests/models/test_config.py
- one victoria already fixed in a PR
- the other was being affected by threadlocal caching, I have added a few checks in here to kill the caching
=> fix 2 unit tests

uber/model_checks.py, uber/models.py, uber/tests/models/test_badge_funcs.py
=> Replace while loop in auto_badge_num, fix infinite loop

uber/site_sections/preregistration.py
=> redirect attendee_donation_form to confirm if amount unpaid is zero

uber/templates/common/index.html
This link is one of those links that people gain use from, but can NEVER FIND. Adding it to the front page to make everyone's lives easier.
=> add button to home page to check if already registered

uber/configspec.ini, uber/site_sections/preregistration.py
totally minor  cleanup to go with https://github.com/magfest/ubersystem-puppet/pull/113
=> cleanup cherrypy proxy settings

uber/site_sections/emails.py
=> Allow people with Registration At Con access to view emails

uber/api.py
=> Fixing variable names that I changed without testing

uber/static/angular-apps/signups/possible.html
Trying to clear up some text based on:
https://github.com/magfest/ubersystem/issues/1996
@rscullin Is that clearer for you?
There is a secondary related issue that is more indepth as well that @ArthurGreenberg had been working on.
=> Updating non-shift verbage

uber/templates/signups/food_restrictions.html
Also removes the sandwich options. Requested by Staff Suite.
=> Change verbage for food restriction form

uber/configspec.ini, uber/templates/signups/food_restrictions.html
Staff suite wanted this removed for MAGFest, so it shouldn't be in configspec.ini anymore.
=> Remove pork from default food_restriction opts

uber/templates/signups/food_restrictions.html
=> update text to be clearer that this page is optional but needs to be saved

uber/site_sections/summary.py
- convert list of which stuff gets exported into a list which downstream plugins can modify
- minor unrelated shirt typo fix
- add minor badges as exportable badge types
part of closing #2100
=> badge export upgrades

uber/site_sections/summary.py
@binary1230 I actually tested it this time!
can't use a property as a filter.
=> property cannot be used for a SQL filter

uber/templates/common/index.html
Nick requested that the main page where it leads to the admin login, also has a second button that leads directly to the staff/volunteer login.
=> add staff login and admin login links to make things more clear

uber/reports.py, uber/site_sections/summary.py
simplify badge export now that #2143 is in
=> add in extra badges to the badge export

uber/decorators.py
#1605 can be fixed with this simple trick
=> make CSV files appear on the site map

uber/model_checks.py
Reverts magfest/ubersystem#2150
=> Revert "enforce no changing of attendee printed badge name after deadline"

uber/models.py, uber/templates/signups/food_restrictions.html
fix-#2136 to remove left over code requesting Vegetarian
=> fix-#2136 Remove Leftover Vegetarian Code

development-defaults.ini, uber/templates/regform.html
This PR is based on Slack comments, no Issue was created.
=> Clean up prereg permission form wording & fix URL

uber/templates/emails/reg_workflow/reg_notes.html, uber/templates/regform.html
=> Change "permission slip" to "consent form"

uber/common.py, uber/decorators.py, uber/site_sections/common.py, uber/site_sections/preregistration.py, uber/templates/common/invalid.html
A revert revert: My favorite kind of pull request.
Reverts magfest/ubersystem#2159. This now includes a fix for the code because we merged the fixed version of the original branch into this branch.
=> Add invalid attendee ID decorator (fixed)

uber/models.py, uber/site_sections/preregistration.py, uber/templates/preregistration/disclaimers.html
1 - Keep volunteer status when switching to DH
2 - Keep badge # when claiming group badge
3 - Add disclaimer about not mailing stuff
=> 3 total changes 

uber/templates/registration/review-base.html, uber/templates/registration/review.html
- so that downstream templates can override it
needed for https://github.com/magfest/hotel/pull/67
=> refactor review page into a base subpage

uber/templates/preregistration/disclaimers.html
Cleans up disclaimers block, adding links to FAQ as needed
=> Revamping prereg disclaimer block

uber/config.py, uber/models.py
Fixes https://github.com/magfest/ubersystem/issues/2108, with some caveats.
=> Calculate group prices based on attendee's prices

uber/site_sections/summary.py
this was broken by recent email refactoring, fixing
=> Fix staff manufacturing report

uber/site_sections/summary.py
Got an email asking to list the vendors on magfest.org, and decided the quickest way to do this was to extract the information from Uber, and beautify it with some Python on my local box. 
**The sooner this is merged, the sooner that info goes on our website for attendees.**
=> Add csv file to get approved dealers information to put on website

uber/templates/registration/form.html
fixes-#1794 by displaying signed up and checked in even when not AT-CON
=> Display Checked In item on Attendee form

uber/site_sections/emails.py, uber/templates/emails/index.html
Fixes #2218. Found a handy function called icontains, but to be honest I'm a bit unsure of how this search is going down. It works though!
=> Add a search function to emails/index

uber/models.py, uber/templates/preregistration/group_members.html
This PR will add a column to the group_members page which allows the leader to see how much each member in the group has kicked in extra.
=> Add a kicked-in column to the group members page.

uber/templates/preregistration/form.html
Add minimum # new group badges to prereg page
Fixes #1989
=> Add minimum # new group badges to prereg page

uber/static/deps/combined.js
(we think) a merge error resulted in this going away by mistake, re-ran grunt on a fresh copy and this was re-generated
fixes https://github.com/magfest/magfest/issues/8
=> regenerated bootbox in combined.js

uber/templates/regform.html
This may be caused by an Order of Operations Issue. Fixes https://github.com/magfest/ubersystem/issues/2252.
=> Attendee Admin Form is showing data from Prereg Page

uber/site_sections/preregistration.py
Fixes https://github.com/magfest/ubersystem/issues/2262
=> Transfer overridden_price when claiming a group badge

uber/templates/registration/form.html
adds target="_blank" to an anchor tag. tested and working. Fixes #2261.
=> Open group page in a new tab instead of on the same page.

uber/config.py
Fixes https://github.com/magfest/ubersystem/issues/2269.
This is purely theoretical because my entire dev install has become hosed for the nth time. Someone else needs to test this if they want it tested before tomorrow.
=> Keep QR_CODE_PASSWORD in SecretConfig

uber/automated_emails.py
=> Fix mistake of forgetting c variable in c.APPROVED

uber/config.py, uber/templates/base.html
This is required to include javascript needed to detect barcode scans.
=> Add dynamic JS includes

uber/models.py
Fixes https://github.com/magfest/ubersystem/issues/1641. We were checking if the search text was an integer, and then assuming it was a badge number if this was the case. Now we try to search by phone number if it's 10 digits long, then check if the number is in our range of badge numbers, then search other fields if those are both untrue.
=> Stop only searching by badge number if search text is integer

uber/templates/registration/index_base.html
This isn't actually super necessary right now but it's nicer.
=> Separate out QR code JS into its own function

uber/models.py, uber/site_sections/registration.py, uber/templates/registration/merch.html
This implements the feature requested by @nickthenewbie1 and documented in the flowchart at https://github.com/magfest/magprime/issues/189
=> Added staff merch discounts

uber/site_sections/registration.py, uber/templates/emails/reg_workflow/attendee_qrcode.html, uber/templates/registration/index_base.html
Fixing issues with [QR Codes #2277](https://github.com/magfest/ubersystem/issues/2277).
Should be handled :)
=> Fixing QR Codes #2277

uber/models.py, uber/site_sections/signups.py, uber/templates/signups/login.html
Split Names in Volunteer Sign up
Originally, at sign in, volunteers typed in their full name. 
We are now changing it so that volunteers can type in each name individually.
=> Split Names in Volunteer Sign In 

uber/model_checks.py
=> Check cellphone number isn't emergency contact num

uber/models.py, uber/site_sections/jobs.py, uber/templates/jobs/job_renderer.html, uber/templates/regform.html, uber/tests/email/__init__.py, uber/utils.py
NOTE FROM ELI: although I have a high degree of confidence this won't break anything, I'm still going to hold off on merging it until after MAGFest just in case.  (EDIT: Now that it's after MAGFest I'm gonna merge this.)
REPLACING [#2308](https://github.com/magfest/ubersystem/pull/2308) because I needed to do branching properly on my side :|
Fixes #1722 and comes with tests!
Considers but does not fix #527 with the simple input type in regform.
Also fixes one inconsistent "for" field in the regform.
=> Fixing gmail emails (and pulled in email validation)

uber/decorators.py, uber/models.py, uber/site_sections/groups.py, uber/site_sections/preregistration.py, uber/site_sections/registration.py, uber/templates/groups/form.html, uber/templates/groups/history.html, uber/templates/registration/history.html
I got a little carried away.
Fixes https://github.com/magfest/ubersystem/issues/1654. Fixes https://github.com/magfest/ubersystem/issues/1006. Fixes https://github.com/magfest/ubersystem/issues/1002. Fixes https://github.com/magfest/ubersystem/issues/981 (though not especially cleanly). Fixes https://github.com/magfest/ubersystem/issues/2038. Fixes https://github.com/magfest/ubersystem/issues/770. Fixes https://github.com/magfest/ubersystem/issues/1436 (I think?). Also adds a 'page' column and a 'snapshot' column for later, splits off PageViewTracking into its own table, and records the difference between a true non-admin action and someone messing around on the server.
=> Major upgrades to Tracking DB

uber/models.py
Fixes https://github.com/magfest/ubersystem/issues/2341. Also adds a docstring to explain a function I was having trouble figuring out while trying to fix a different issue.
=> Stop updating check-in time every time an attendee is saved

uber/automated_emails.py, uber/templates/registration/form.html
Fixes https://github.com/magfest/ubersystem/issues/2305.
=> Allow admins to create placeholder badges during at-con mode

uber/templates/regform.html
Fixes https://github.com/magfest/ubersystem/issues/2259.
=> Make zip code field optional on registration/register

uber/api.py, uber/configspec.ini, uber/model_checks.py, uber/models.py, uber/templates/regform.html, uber/templates/registration/check_in_form_base.html
Fixes https://github.com/magfest/ubersystem/issues/2314.
=> Add emergency contact name field

uber/models.py
=> Fix UUID search to not allow surrounding text

uber/models.py
Fixes https://github.com/magfest/ubersystem/issues/2369.
=> Rename ident column to ident

uber/models.py
Was working on my own plugin/sideboard stuff, and found that this code was duplicated. Removed and tested on my own seemed to have no effect, so I figured I'd throw a PR in here in case this change is desired.
=> Remove Duplicate Code

uber/model_checks.py, uber/templates/check_in.html, uber/templates/groups/form.html, uber/templates/registration/index_base.html
Fixes https://github.com/magfest/ubersystem/issues/2295. In order to accomplish this, I pulled out some code from index_base into its own template. Also fixes a bug where duplicate badge numbers weren't getting caught before saving to the DB, under certain circumstances.
=> Add check-in buttons to group management page

uber/menu.py, uber/templates/base.html
- add __getitem__() to MenuItem for ease of use with plugins
- simlpify and rename access filtering code (thanks Vicki)
- remove extra space in base.html
addressing a couple minor things from https://github.com/magfest/ubersystem/pull/1857
=> add menu improvements

uber/templates/summary/departments.html
There are slight differences in how `dictsort` works between [Django](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#dictsort) and [Jinja2](http://jinja.pocoo.org/docs/2.9/templates/#dictsort).
=> Fixes #2408: summary departments template error

uber/templates/groups/form.html
This tag was malformed, causing the page to 500 error.
=> Fix sum tag in Group form for Jinja2

uber/custom_tags.py
=> Fixes #2402: Adds full module path to model classes

uber/server.py
See https://github.com/magfest/magclassic/issues/71
=> Fixes magclassic #71: Removes very last Django reference

uber/models.py, uber/tests/models/test_attendee.py
There's some additional discussion over on #1816.
=> Fixes #1816: Changes AT_THE_CON auto checked_in logic

test-defaults.ini, uber/config.py, uber/configspec.ini, uber/tests/README.md, uber/tests/models/test_attendee.py, uber/tests/models/test_config.py
Note, this fixes https://github.com/magfest/magclassic/issues/64 in the magclassic repo.
=> Fixes magclassic #64: Modifies STAFF_GET_FOOD to use FOOD_PREP instead of STAFF_SUITE

README.md
literally, one spelling and one grammar issue.
=> Fixed a couple of typos in the README

uber/templates/regform.html, uber/templates/registration/form.html
Fixes #2443. Cherry-picked commits 43ce109 and 689527e.
=> Never require legal_name for placeholder badges

uber/templates/groupform.html
Fixes https://github.com/magfest/ubersystem/issues/1989.
=> Add note about adding MIN_GROUP_ADDITION to prereg form

uber/templates/regform.html, uber/templates/registration/shifts.html, uber/templates/signups/printable_schedule.html
=> Changes non-existent hour_day() template tag to hour_day_local()

uber/custom_tags.py, uber/templates/accounts/index.html, uber/templates/accounts/sitemap.html, uber/templates/budget/index.html, uber/templates/groups/form.html, uber/templates/groups/index.html, uber/templates/registration/form.html, uber/templates/registration/index_base.html, uber/templates/registration/register.html, uber/templates/registration/watchlist_entries.html, uber/templates/static_views/additional-styles.css, uber/tests/test_custom_tags.py
Adds `<div class="panel-body">` where appropriate, adds padding in a few places, tweaks html indention in a few places
=> Fixes #2498: Adds <div class="panel-body"> where appropriate

uber/configspec.ini, uber/templates/preregistration/preregbase.html
=> Adds special case handling for t-shirt supporter notice text

uber/templates/groups/form.html, uber/templates/jobs/form.html, uber/templates/macros.html, uber/templates/regform.html, uber/templates/registration/form.html, uber/templates/registration/watchlist_entries.html
=> Fixes #2510: Adds <label> elements around checkboxes so they're easier to click

uber/model_checks.py, uber/models.py, uber/tests/models/test_group.py
=> Fixes #2519: Adds presave adjustments to Group which convert falsey values to zero for cost attributes

uber/templates/signups/shifts.html
I don't know when i don't know how I don't know why, but {{name}} got replaced with T U at some point, assumed to be Test User, and just never got switched back or something. What is lifeeee.
=> Replace T U with {{name}}

uber/templates/signups/shifts.html
=> Fixes #2506: Includes department with shift on shift signups page

uber/site_sections/registration.py
fixes #2302 by adding to display message on merch page. I thought this was a better solution than editing the html/javascript
=> Add attendee shirt size to message, after attendee has received merch

uber/templates/regform.html
This time without breaking prereg. Reimplementation of https://github.com/magfest/ubersystem/pull/2532, which had to be reverted in https://github.com/magfest/ubersystem/pull/2540.
=> Fix 'no hacking allowed' error for at-door

uber/templates/preregistration/preregbase.html
Fixes https://github.com/magfest/ubersystem/issues/2544.
=> Fixes #2544: If an attendee already has a staff badge, don't overwrite their badge_type

tests/casperjs/ac_staging.js, tests/casperjs/regular_registration.js, uber/site_sections/preregistration.py, uber/templates/preregistration/form.html
These changes are part of the fix for https://github.com/magfest/ubersystem-puppet/issues/135
This pull request is related to https://github.com/magfest/ubersystem-puppet/pull/136
=> Companion changes for NGINX preregistration cache

uber/decorators.py, uber/templates/preregistration/form.html
I had to do this anyway to test other changes. Fixes https://github.com/magfest/ubersystem/issues/2580.
=> Don't redirect the prereg page if DEV_BOX is true

uber/models.py
Emergency fix to facilitate importing a json export from the tracking table.
=> Better null value handling in model.apply()

uber/templates/regform.html
I am just re-adding some code that was commented out for an emergency fix (except the one line that was actually broken).
=> Fixes #2585: Toggles visibility of volunteer fields when staffing checkbox is clicked

uber/templates/regform.html
I added the "required" property on a few more fields, and I forgot to toggle it on/off the cellphone field when selecting "I want to volunteer".
=> Fixes cellphone required property toggling on regform

uber/automated_emails_server.py, uber/configspec.ini, uber/templates/emails/daily_checks/pending_emails.html
There's no new code here, this is just merging the new pending email report into master.  The previous PR merged it into a different non-master branch and I messed up the instructions on the order in which to merge them.
After this we should also delete the ```move_email_daemon_into_new_file``` branch, from which this commit was cherry picked.
=> merge new email report in master

uber/templates/emails/shifts/schedule.html
Fixes https://github.com/magfest/ubersystem/issues/1030.
=> Add shirt info to volunteer info email

uber/site_sections/accounts.py, uber/templates/emails/accounts/new_account.txt
Fixes https://github.com/magfest/ubersystem/issues/1667.
=> Add welcome message detailing permissions for new admin accounts

uber/site_sections/signups.py, uber/templates/emails/shifts/created.txt, uber/templates/emails/shifts/reminder.txt
Fixes https://github.com/magfest/ubersystem/issues/2546. This was easier than I expected!
=> Email volunteers a direct link instead of making them log in

alembic/versions/71991162a59c_adds_requested_hotel_info_to_attendee_.py, uber/config.py, uber/configspec.ini, uber/custom_tags.py, uber/models.py, uber/site_sections/preregistration.py, uber/templates/macros.html, uber/templates/preregistration/banned.html, uber/templates/preregistration/duplicate.html, uber/templates/preregistration/form.html, uber/templates/preregistration/group_members.html, uber/templates/preregistration/hotel.html, uber/templates/preregistration/index.html, uber/templates/preregistration/paid_preregistrations.html, uber/templates/regform.html
This pull request does **NOT** implement the automated emails that will be sent with the booking link. This pull request **ONLY** implements the sign-up portion of the preregistration workflow.
=> Fixes #2579: Adds "request hotel booking info" step to prereg

uber/models.py, uber/templates/emails/reg_workflow/attendee_watchlist.txt, uber/templates/emails/reg_workflow/banned_attendee.txt
Fixes https://github.com/magfest/ubersystem/issues/2113.
=> Alter wording of "banned" email sent when an attendee registers

uber/templates/regform.html, uber/templates/static_views/styles/main.css
=> Makes validation messages red

test-defaults.ini, tox.ini, uber/templates/regform.html, uber/templates/static_views/styles/main.css
Removes tox dependency on development-defaults.ini by adding settings to test-defaults.ini.
=> Removes tox dependency on development-defaults.ini

uber/templates/groups/form.html
=> Add clickable version of Dealer URL

uber/config.py, uber/configspec.ini, uber/site_sections/preregistration.py, uber/templates/emails/dealers/application.html, uber/templates/emails/dealers/reg_notification.txt, uber/templates/preregistration/dealer_confirmation.html, uber/tests/models/test_config.py
Fixes https://github.com/magfest/ubersystem/issues/2577.
=> Add a cutoff for # of dealer applications received

uber/tests/test_custom_tags.py
Somehow I completely failed to commit these tests!
=> Adds tests for basename custom tag

uber/templates/emails/reg_workflow/hotel_booking_info.html
Slight tweaks for clarification
=> Updated hotel text

uber/templates/emails/reg_workflow/attendee_confirmation.html
Added clarification that people should really keep an eye out for that e-mail
=> hotel text update

uber/templates/emails/dealers/dealer_received.txt
Reverts magfest/ubersystem#2700
Whoops, {{ attendee.requested_hotel_info }} needs to be {{ group.requested_hotel_info }}
=> Revert "Add hotel booking info to dealer app confirmation"

uber/site_sections/summary.py
Modifies the hours threshold for shifts to be greater than or equal to 12 hours in an 18 hour period.
=> Modify hours threshold

uber/templates/jobs/job_menu.html
=> Replacing commas with spaces

uber/config.py, uber/model_checks.py, uber/site_sections/preregistration.py
I **think** this covers the places in this repo where we could use the group.is_dealer property
=> Convert group.tables to group.is dealer where appropriate

uber/models.py, uber/site_sections/registration.py, uber/templates/registration/feed.html
Didn't add any tests because this is a quick fix for @jcooter. Should probably only be used for emergencies anyway.
Fixes #2597.
=> Adds "Undo" button to the database feed for deleted items

alembic/versions/9359297269a8_convert_ribbon_to_a_multichoice_column.py, test-defaults.ini, uber/automated_emails.py, uber/badge_funcs.py, uber/config.py, uber/configspec.ini, uber/model_checks.py, uber/models.py, uber/site_sections/groups.py, uber/site_sections/preregistration.py, uber/site_sections/registration.py, uber/site_sections/summary.py, uber/templates/emails/personalized_badges/volunteers.txt, uber/templates/emails/placeholders/imported_volunteer.txt, uber/templates/emails/placeholders/reminder.txt, uber/templates/emails/shifts/schedule.html, uber/templates/preregistration/duplicate.html, uber/templates/registration/check_in_form_base.html, uber/templates/registration/duplicate.html, uber/templates/registration/form.html, uber/templates/registration/index_base.html, uber/templates/summary/departments.html, uber/templates/summary/food_eligible.xml, uber/tests/models/test_attendee.py, uber/tests/models/test_group.py, uber/utils.py
Converts attendee.ribbon to a MultiChoice column, and updates the core repo to reflect this change.
=> Convert "ribbon" to multichoice

alembic/versions/c755142df6c1_adds_indexes_for_badges_sold.py, uber/automated_emails_server.py, uber/config.py, uber/decorators.py, uber/models.py, uber/server.py, uber/site_sections/registration.py, uber/tests/models/test_session.py
This is good to go. Too tired to annotate the changes, will do it tomorrow. Feel to ask questions!
=> Performance improvements

bower.json, uber/custom_tags.py, uber/tests/models/test_utils.py, uber/utils.py
Fixes https://github.com/magfest/ubersystem/issues/2738. Also fixes an additional error that would come up after a charge completed, where the system would fail to log a Stripe transaction.
=> Fix email error for arbitrary charges

uber/templates/macros.html, uber/templates/regform.html
Makes the `toggle_checkbox()` macro slightly more flexible. I am using it in the panels application form to show/hide elements.
=> Improved toggle_checkbox macro

uber/templates/signups/shifts.html
This changes no code, I just absolutely could not parse the file as it was.
=> Fix whitespace in shifts.html

alembic/versions/d0c15c44a031_add_extra_donation_column.py, uber/configspec.ini, uber/model_checks.py, uber/models.py, uber/templates/regform.html
This used to exist only in a couple event plugins, but now it's a common enough want that we're moving it into the core plugin and using a config option to show or hide the field itself.
=> Add extra_donation column and config option

uber/common.py, uber/custom_tags.py, uber/decorators.py, uber/models.py, uber/site_sections/preregistration.py, uber/templates/groups/form.html, uber/templates/preregistration/banned.html, uber/templates/preregistration/duplicate.html, uber/templates/preregistration/index.html, uber/utils.py
This pull request fixes #1967, along with the sideboard pull requests:
* https://github.com/magfest/sideboard/pull/88
* https://github.com/magfest/sideboard/pull/89
It takes the following page load time from 25s down to under 3s. I am very excited to try load testing these changes, so I may merge this before it's reviewed (hoping to get this in before dealer reg opens).
=> Big performance improvements on the prereg pages

tests/locust/locustfile.py, uber/models.py, uber/templates/preregistration/index.html, uber/utils.py
Makes changes requested in code review of pull request #2754
=> Makes changes requested in code review of pr #2754

uber/site_sections/preregistration.py
In a previous PR, we changed group fields to always have `group_` appended to them. However, we forgot that group_members also uses these fields, and was not prepared to accommodate that change. This allows groups to edit their information again by:
1. dropping the 'detect changes' code (not really needed)
2. copying the apply params from the form function
=> Allow dealers to edit their groups

uber/models.py, uber/site_sections/signups.py, uber/templates/signups/shifts.html
Fixes https://github.com/magfest/ubersystem/issues/2656. Fixes https://github.com/magfest/ubersystem/issues/2665. Fixes https://github.com/magfest/ubersystem/issues/2681. Fixes https://github.com/magfest/ubersystem/issues/2706. Fixes https://github.com/magfest/ubersystem/issues/2751. Fixes https://github.com/magfest/ubersystem/issues/2646. Most of this is done through changing options for the fullCalendar object that we generate in shifts.html. Also fixes some minor ugliness in the confirmation dialogue when adding or dropping a shift.
=> Fix calendar behavior for shift signups

uber/config.py, uber/site_sections/signups.py, uber/templates/jobs/index.html, uber/templates/signups/shifts.html
Adds shift description, weight, and an indicator of a shift being +15 minutes. Also makes the sign up and drop buttons smaller for the calendar views. Fixes https://github.com/magfest/ubersystem/issues/2653. Fixes https://github.com/magfest/ubersystem/issues/2674. Fixes https://github.com/magfest/ubersystem/issues/2765.
=> Fix shift signup descriptions

uber/common.py, uber/custom_tags.py, uber/jinja.py, uber/models.py, uber/templates/accounts/bulk.html, uber/templates/accounts/index.html, uber/templates/emails/emails_by_interest.html, uber/templates/groups/form.html, uber/templates/macros.html, uber/templates/preregistration/group_members.html, uber/templates/regform.html, uber/templates/static_views/additional-styles.css, uber/templates/static_views/styles/main.css
Supports magfest/panels/issues/82
Supports magfest/panels/issues/89
Supports magfest/panels/issues/90
=> Adds JSONColumnMixin, adds cool form macros, Adds @JinjaEnv.jinja_test

uber/site_sections/summary.py
This just makes the shirt reports look cleaner and less confusing when staff shirts are disabled in the config
=> don't show staff shirts in shirt reports if config is set to disable staff shirts

uber/site_sections/groups.py, uber/tests/models/test_utils.py, uber/utils.py
We were uniquify-ing the input, but not the output! Fixes https://github.com/magfest/ubersystem/issues/2775.
=> Make add_opt actually return a unique set

uber/templates/regform.html
Fixes https://github.com/magfest/ubersystem/issues/2739.
=> Update 'cellphone excuse' label

uber/configspec.ini, uber/custom_tags.py, uber/models.py, uber/site_sections/preregistration.py, uber/static/theme/prereg.css, uber/templates/groupform.html, uber/templates/preregistration/group_members.html, uber/tests/test_custom_tags.py
=> Fixes #2620: Adds configurable grace period during which groups can add individual group members

uber/templates/macros.html, uber/templates/regform.html, uber/templates/static_views/styles/main.css
Changes needed to support magfest/bands/issues/85 and magfest/bands/pull/86
=> Changes needed to support magfest/bands/issues/85 and magfest/bands/pull/86

uber/automated_emails.py
=> Send confirmation emails to comped attendees with a promo_code_id

uber/configspec.ini
See https://github.com/magfest/production-config/pull/272.
Ugh, I should have never implemented it this way!
=> Compensate hotel email date for increased hotel availability

uber/configspec.ini
We still don't know when we're sending out the email. But we still don't want it to go out early, so I'm just pushing it back by another week.
For anyone in the general public reading this, don't read too much into it. We still haven't decided, and we will probably be changing this date again several times. Either moving it up or moving it back.
=> Pushes the hotel email back by another week

uber/templates/emails/personalized_badges/reminder.txt
Fixes https://github.com/magfest/ubersystem/issues/2764.
=> Add badge printed name to personalized badge reminder email

uber/utils.py
Deploying the last PR caused an error -- this should fix that.
=> Fix DeptChecklist initialization error

uber/site_sections/summary.py, uber/templates/summary/index.html
Is this the best possible implementation? Nope.
Does it work? Yep!
=> Adds summary counts for each donation tier

uber/site_sections/groups.py, uber/templates/groups/index.html
Applied str.lower() to sorted key for case-insensitive sort. Is this an appropriate solution to issue #2574?
This is my first time using git and github, and first foray into this project. Constructive advice is welcome!
=> fixes #2574, use case-insensitive sort for groups table

uber/templates/preregistration/stripeForm.html
implements issue #2731 for @ShevaDas
=> Add functionality to test bitcoin payments on dev_box

uber/site_sections/preregistration.py
Trying to see if this will fix the broken build
=> Fix python style violation

uber/models.py
* Changes the generated `fields_name` to begin with an underscore, so it doesn't pollute the `to_dict()` output
* Fixes the case where already existing fields are updated; previously the json column wasn't considered dirty by SQLAlchemy when individual fields were updated (like changing the value of `twitter`)
=> Fixes to the JSONColumnMixin

uber/tests/models/test_attendee.py, uber/tests/models/test_utils.py
This PR improves the unit tests I've added over the last few days.
I parameterized the phone number validation tests, and added tests to cover the default argument for `get_age_from_birthday` that was previously untested.
=> Improve recently added unit tests

alembic/README.md, uber/tests/import_test_data.py
Goes with https://github.com/magfest/guests/pull/99
=> Rename bands plugin to guests

uber/menu.py
Related to https://github.com/magfest/panels/pull/113
=> Moves schedule menu item to panels plugin

uber/sep_commands.py
This is what we discussed at https://github.com/magfest/mits/pull/1#discussion_r141524697
Now when you run ``sep alembic revision`` it will check to see whether there are any migrations and if not then it'll automatically head the head to the ``uber@head`` revision.
I've tested this locally by clearing out my MITS migrations and then re-generating them from scratch.  I then tested adding another revision to make sure that still worked correctly.  I also ran through a number of other ``sep alembic`` commands to ensure that I hadn't somehow messed those up.
=> 'sep alembic revision' now correctly sets the head for intiial migrations for new plugins

uber/templates/static_views/styles/main.css, uber/utils.py
https://github.com/magfest/guests/pull/108 depends on this.
=> Moves comma_and method (renamed from comma_join) from guests plugin to main uber plugin

uber/templates/static_views/styles/main.css, uber/utils.py
Reverts magfest/ubersystem#2878
I'm reverting this cause there's actually a few more changes I wanted to put in that pull request. Momentary brain fart!
=> Revert "Moves comma_and method (renamed from comma_join) from guests plugin to main uber plugin"

uber/templates/macros.html, uber/templates/static_views/styles/main.css, uber/utils.py
I merged  magfest/ubersystem#2878 before it was ready to be merged. So I reverted that merge, and created a new pull request with the additional changes.
Also, https://github.com/magfest/guests/pull/108 still depends on this.
=> Adds some additional stuff that was missing from the erroneously merged pull request

uber/site_sections/preregistration.py
=> Emergency fix, someone is donating money and page is blowing up and not registering their donation after we accepted the payment!!!

uber/decorators.py, uber/site_sections/preregistration.py, uber/tests/site_sections/test_registration.py, uber/utils.py
Okay, I actually think this is good to merge 😄
=> Adds additional armor around credit card payments

uber/templates/signups/index.html
=> Fixes #2928: Adds requested text to volunteer checklist

uber/models/__init__.py
Fixes #2931
Not actually sure what caused the original exception 😅
=> Adds some armor around our cost property calculation

uber/models/__init__.py, uber/templates/base.html, uber/templates/dept_checklist/overview.html
Trying to make our toastr messages less annoying 😄
=> Makes our toastr messages less annoying

uber/templates/base.html
I called it "My Account", but I'd be happy to change that if anyone has any other suggestions!
😄
=> Adds a "My Account" link to the main menu, which takes you to your own reg form

uber/templates/jobs/form.html
I searched through the codebase, and this is the only place I could find that needed to change 😄
=> Allows weighted setup/teardown shifts

uber/templates/jobs/form.html
Turns out, this was a feature specifically requested by Registration 😅
=> Adds "Extra 15" to setup/teardown shifts, per Registration's request

uber/site_sections/dept_checklist.py, uber/templates/dept_checklist/logistics.html
Depends on https://github.com/magfest/production-config/pull/336
=> Adds link to "Logistics Request" google form

uber/jinja.py, uber/templates/base.html
- turn on more aggressive whitespace trimming in Jinja env
- add more aggressive trimming to main menu
=> aggressively trim more whitespace

uber/templates/emails/reg_workflow/group_donation.txt, uber/templates/emails/shifts/dept_checklist.txt
This is another followup to Dom's recent [aggressive whitespace stripping pull request](https://github.com/magfest/ubersystem/pull/2986) (see also the [previous followup](https://github.com/magfest/ubersystem/pull/2987)). There may be other places in the source code that have the same or similar problems. I searched the codebase using a few different regexes and this was all I found, but we should still be on the lookout for unexpected formatting issues 😄
=> Found some additional places where the aggressive whitespace stripping was causing formatting issues

uber/site_sections/preregistration.py
Looks like this function was removed here: https://github.com/magfest/ubersystem/commit/2dd68e999c46b95e973e664c0345e3032c9c3ffa
=> Fixes 404 guest_food url

uber/decorators.py, uber/menu.py, uber/site_sections/registration.py
* Fixes #2995 
* Related to #2909
=> Fixes #2995, Related to #2909: Restricts database feed to ACCOUNTS permissions

uber/api.py, uber/site_sections/api.py, uber/templates/api/reference.html
Adds "full" parameter to Attendee API service, so not every api call needs to join a bunch of tables.
=> Api efficiency updates

uber/api.py
Talked to rscullin about this, and techops needs the ribbons in the non-full api call.
Also added subqueryloads to improve attendee search performance.
=> Adds ribbon_labels back to non-full api call, adds subqueryloads for better performance

uber/templates/departments/requests.html
Someone needs to use this feature 😄
=> Improves dept membership request table by adding Anywhere column

uber/config.py, uber/menu.py, uber/site_sections/accounts.py
Reduces number of db queries by a huge amount.
=> Radical performance improvements for the menu and sitemap

uber/sep_commands.py
=> Adds initialize=True to Session.initialize_db() for sep commands that need it

uber/models/attendee.py, uber/tests/models/test_attendee.py
See https://github.com/magfest/ubersystem/pull/3021
=> Now that we have the presave_adjustment for dept head ribbons, we no longer need the custom ribbon_labels property

uber/custom_tags.py
Requested here: https://github.com/magfest/ubersystem/pull/2990#discussion_r157970525
=> Adds docstring for format_location()

uber/models/types.py
Required by https://github.com/magfest/panels/pull/142
=> Adds utcmin like utcnow, but for 0001-01-01 0:00 UTC

uber/automated_emails_server.py, uber/tests/email_tests/email_fixtures.py
These changes are the improvements to the automated email system I suggested in [this comment](https://github.com/magfest/ubersystem/pull/2985#issuecomment-346984792).
=> Implements suggested automated email improvements

uber/config.py
...since we sell badges, not passes
=> Replace instances of Pass with Badge

uber/sep_commands.py, uber/site_sections/groups.py
https://github.com/magfest/ubersystem/pull/3076 is making Travis mad.
=> Fix pep8 problems from previous PR

uber/sep_commands.py, uber/site_sections/groups.py
This would have saved me a full day of work the weekend before Super MAGFest.
*sigh*
=> Safer resave all staffers

uber/templates/registration/index_base.html, uber/templates/registration/merch.html, uber/templates/registration/new_base.html
Requires https://github.com/rams/barcode/pull/22
=> Uses new jQuery barcode scanning plugin for reg QR code lookup and badge num scanning

uber/templates/registration/index_base.html
Requires https://github.com/rams/barcode/pull/24
=> Supports searching by badge num using barcodes

uber/site_sections/registration.py
Fixes https://github.com/magfest/ubersystem/issues/3105
=> Changes default sort on reg/new to registered.desc()

uber/site_sections/jobs.py, uber/templates/jobs/everywhere.html
I am finally, finally, finally going to sleep. Josiah really wants this soon, so whomever reviews it, please fix it up (if it needs it) and merge/deploy it on my behalf.
=> By default, hides shifts that belong to depts that don't solicit

uber/templates/registration/duplicate.html
Ping @kitsuta 
As a reg manager, I got confused when choosing the middle option - I didn't expect the badge to be created, and so was baffled when the badge suddenly showed up on a later search.
=> Clarify wording on reg duplicate badge page

uber/templates/registration/form.html
Fixes a simple template error, plus adds a checkbox for having received staff merch.
=> Fix "got staff merch" on Attendee Details page

uber/templates/registration/feed.html
=> Focus keyword field in FODC

uber/site_sections/emails.py
Fixes the previous PR, which does not work.
=> Add email report by kickin

uber/site_sections/registration.py, uber/templates/registration/shifts.html
=> Correct text on update notes button

development-defaults.ini, uber/config.py
=> Add sqlite as default in development-defaults.ini

alembic/versions/73b22ccbe472_initial_migration.py, uber/config.py, uber/configspec.ini, uber/models/__init__.py, uber/models/attendee.py, uber/models/attendee_tournaments.py
Required for backwards compatibility with legacy servers.
=> Incorporates attendee_tournaments data model into uber plugin

INSTALL.manually.md
Pulled from my document I've been working on here: https://khyperia.com/tutorials/uber.html
=> Add sqlite manual install method

test-defaults.ini, uber/api.py, uber/models/attendee.py, uber/models/department.py, uber/site_sections/api.py, uber/site_sections/export.py, uber/site_sections/import.py, uber/templates/api/reference.html, uber/templates/import/staff.html
This is ugly code, but it's _far_ nicer than the scripts we were previously using to import staff. Plus it's all hidden behind "Server Admin" access, so like... at most 3 people will have access to it.
=> Server-to-server staff import via the API

uber/site_sections/registration.py
=> Fixes placeholders page for events that do not use the placeholder dept checklist

uber/config.py, uber/configspec.ini, uber/models/__init__.py, uber/site_sections/schedule.py, uber/templates/schedule/edit.html, uber/templates/schedule/form.html
These changes were written last year for MFF in the panels plugin, but never got moved over to MAGFest.
Largely MAGFest won't care about these changes, but it does include a bug fix.
=> Port 2017 upgrades from MFF

uber/templates/base.html
=> MAGDEV-83 Adds bug report and improvement request Jira forms

uber/api.py
This is the initial commit to add a Guest API to uber.  Initially, this is intended only for getting biographical information out of uber for use in other applications (e.g. Website).
=> Adding Guests API

uber/api.py
I haven't tested this, but I'm like 99.999% sure it should work without errors.
=> Add c.URL_BASE to config.info

uber/site_sections/preregistration.py
=> Stop defaulting 'can_spam' to True

uber/templates/emails/dealers/application.html, uber/templates/emails/dealers/badge_converted.html, uber/templates/preregistration/dealer_confirmation.html, uber/templates/preregistration/duplicate.html
Also incorporates @earl7399's suggestions and adds dealer notice on the duplicates page.
=> Fixes MAGDEV-232: Cleans up dealer application wording

tests/uber/site_sections/test_preregistration.py, uber/models/attendee.py, uber/site_sections/preregistration.py, uber/site_sections/registration.py, uber/templates/base.html, uber/templates/regform.html, uber/utils.py
Fixes MAGDEV-185 in the simplest way possible -- new attendees must check a box stating that we are allowed to store their personal information.
We should get more info on how exactly this should be done before merging this. Currently we don't even store that they checked the box -- this was simpler but I'm not sure it's sufficient.
=> Add required PII consent checkbox

uber/__init__.py, uber/config.py, uber/configspec.ini
Makes our new deployment much easier and shouldn't affect our legacy deployments.
=> Moves uploaded data dirs to a [data_dirs] config section and creates those dirs on server startup

uber/templates/registration/check_in_form_base.html, uber/templates/registration/new_base.html
=> Adds volunteer agreement indicator to checkin process

uber/site_sections/summary.py, uber/templates/summary/volunteer_checklists.html
=> Adds a volunteer checklists summary page

uber/site_sections/summary.py, uber/templates/summary/volunteer_checklists.html
=> Improves the volunteer checklists summary page, adds CSV download

requirements.txt, tests/locust/locustfile.py, uber/model_checks.py, uber/utils.py
This just adds some basic HTTP status code checking to our locust swarm.
=> Whoops, added new code to a closed branch!

alembic/versions/61734fcb2e72_adds_guest_wants_mc.py, uber/config.py, uber/models/guests.py, uber/site_sections/guests.py, uber/templates/emails/guests/band_agreement_reminder.txt, uber/templates/guest_admin/band_info.html, uber/templates/guest_checklist/info_deadline.html, uber/templates/guest_checklist/mc_deadline.html, uber/templates/guest_checklist/panel_deadline.html, uber/templates/guests/band_agreement.html, uber/templates/guests/mc.html
=> Adds wants_mc to bands checklist

alembic/versions/116e5aad3a5c_adds_attendee_hotel_pin_unique_.py, uber/configspec.ini, uber/models/attendee.py, uber/site_sections/hotel_assignments.py
Also makes hotel_pin assignment lazy (the hotel_pin isn't assigned until the hotel report is generated).
Last year we had a couple of duplicate pins.
=> Ensures hotel_pin is unique for every attendee

uber/templates/panel_macros.html
=> [MAGDEV-136] Adds some verbiage to indicate a panelists credentials and social media links may be used on our public schedule

uber/templates/preregistration/hotel_disclaimer.html
Modified to reflect that they will receive login credentials as well as a link.
=> Update hotel disclaimer

alembic/versions/f142e4d54e49_adds_attendee_requested_accessibility_.py, uber/configspec.ini, uber/models/attendee.py, uber/templates/regform.html
Could not be a simpler change. I'm gonna merge and test on staging now. @kitsuta, please feel free to do a post-merge review 😄
=> [MAGDEV-280] Adds "Accessibility Services" checkbox to reg form

uber/models/attendee.py
@kitsuta what do you think of this instead?
=> Emergency fix for child badge pricing

uber/models/attendee.py
I _KNEW_ we'd have a problem with this line, dagnabit
=> Fix group badges under 18 not getting the group discount

uber/templates/emails/reg_workflow/refund_policy.html
Currently says "send themthis personalized link" - forced SPACE between them and this
=> Adds missing space in template

uber/models/attendee.py, uber/site_sections/preregistration.py, uber/templates/preregistration/badge_refund.html
https://github.com/magfest/ubersystem/pull/3310 may not be feasible in the time we have. If not, we should merge this instead.
=> Disable refunds for attendees with multi-model Stripe transactions

uber/site_sections/preregistration.py
Fixes https://jira.magfest.net/browse/MAGDEV-291.
=> Remove old ID from repurchased badge

uber/site_sections/dept_checklist.py, uber/utils.py
Fixes https://jira.magfest.net/browse/MAGDEV-281. To that end, adds a writecell() helper function to our xlsx_file decorator to allow per-cell formatting.
=> Add Dept Checklist overview XLSX export

uber/site_sections/mits_applications.py
Fixes https://jira.magfest.net/browse/MAGDEV-317.
=> Add bools to MITS' game submission page handler

uber/models/guests.py
My local server won't even run email and I can't fix it! Let's work completely blind! :D
=> Fix 500 error from sending guests an email

uber/site_sections/mivs_admin.py, uber/templates/mivs_admin/edit_judge.html, uber/templates/mivs_admin/index.html
Fixes https://jira.magfest.net/browse/MAGDEV-303.
=> Add MIVS judges' response to admin overview and judge edit pages

uber/site_sections/summary.py, uber/templates/summary/volunteer_checklists.html
Fixes https://jira.magfest.net/browse/MAGDEV-282.
=> Update Volunteer Checklists page and CSV with more info

uber/templates/preregistration/disclaimers.html
Fixes https://jira.magfest.net/browse/MAGDEV-283.
=> Remove all links to old FAQ anchors

uber/site_sections/schedule.py, uber/templates/schedule/form.html
Fixes https://jira.magfest.net/browse/MAGDEV-167.
=> Only show approved panels without existing events while adding an event
