development-defaults.ini
uber/config.py
uber/custom_tags.py
uber/templates/preregistration/badge_choice.html
uber/templates/static_views/prereg_closed.html

Adds DISPLAY_ONSITE_BADGES to control when to display the at-door badges, which is currently configured to be 30 days before the start of the event. Also adds them to prereg_closed.html.
Fixes #305.

Change logic for display single-day prices

---

uber/decorators.py
uber/site_sections/schedule.py
uber/templates/preregistration/preregbase.html

This does two things:
1) There's a new ``@cached`` decorator, which will cause a page to be cached.  I'll explain inline.
2) There's a new ``@timed`` decorator, which will cause the time of the page to be logged to syslog.

decorators for timing and caching

---

uber/automated_emails.py
uber/templates/emails/shifts/shirt_reminder.txt

As per Ryan's request, a reminder email for people to fill out their tshirt size.
This is especially useful since most of our reminder emails are for people who need shifts, so this will be a good reminder for people without shifts to fill out the checklist.

added shirt reminder email

---

uber/config.py

In the rockage branch, I was trying to do this:
```
[[donation_tier]]
'SJSU Student discount' = -10
'No thanks' = 0
'Supporter Package' = SUPPORTER_LEVEL
```
(note: not necessarily that doing that above is a good idea, just something I was trying out)
This exposed a bug in the underlying config parsing since I guess we've never tried to parse a negative INI value in the history of ubersystem.
This was crashing on '-10' because the previous code was using str.isdigit() which returns false for -10.  That would instead try to resolve it like a variable name doing globals()['-10'] which threw a KeyError.
The fix is that instead of using isdigit() directly, we check for the presence of a +/- first and then do isdigit() after that.

fix bug in config.py parsing where it doesn't accept negative values

---

uber/utils.py

current code worked when server's time zone == EVENT_TIMEZONE
if it was not (example: server timezone = EST, EVENT_TIMEZONE = PST), then it would take the datetime.now() which was in local timezone, chop off the local timezone, and replace it with the EVENT_TIMZEONE.  however, this replacement is incorrect, as the local time is not converted into the desired timezone.
cherry-picked from Rockage branch

fix major timezone conversion bug

---

uber/configspec.ini
uber/site_sections/registration.py
uber/templates/registration/form.html
uber/templates/registration/index.html

Fix #847. Helps reg quickly handle lost badges by adding a button to attendee list
and details pages.
Volunteers will have to manually restore lost badges using the
information in the admin notes.

Add a lost badge report button

---

uber/decorators.py
uber/site_sections/signups.py
uber/templates/preregistration/attendee_badge_description.html
uber/templates/preregistration/badge_choice.html
uber/templates/preregistration/extra.html

Talked to @kitsuta and we decided that we definitely want people to be able to preregister on our website for full weekend passes.  We also want people to be able to log in and print out their shift schedules.

added support for preregistering at the door and also being able to print schedules from at-the-con mode

---

uber/server.py
uber/templates/closed.html

In previous years we literally shut down public Uber for the entirety of MAGFest.  This year we're just moving to the hotel and then redirecting people to the onsite Uber so people can still preregister, claim group badges, etc.  So instead of saying that we're offline for the weekend, we now instead say that we're temporarily offline and will be back online shortly.

changed UBER_SHUT_DOWN message

---

uber/models.py

@kitsuta pointed out in chat: Well, I mean... if an attendee badge gets a number, but they're not checked in, we should be able to reset that number to 0. But something's preventing us from doing that.

we now allow badge numbers to be unset before someone checks in

---

uber/templates/registration/checkin.html

Lets volunteers more easily verify which badge is duplicate.

Add email and zipcode to quick check-in

---

uber/models.py
uber/server.py

Earlier today, Uber started slowing WAY down when we hit a high number of users.  I realized that there were three easy things I could do to address this issue:
1) I completely forgot to review our web server settings when we puppetized them, to make sure they matched last year's settings.  MY BAD!  We had our thread pool set to 10, which isn't really enough when people's web browsers have keepalive turned on.  I bumped this up to 150 in the puppet template on mcp.magfest.net so that's not included in this change.
2) Relatedly, our SQLALchemy default connection pool size was laughably low.  I don't think this actually matters much in practice since I think the web server change was the only real issue that mattered, but just to be safe I bumped this up to 50 and increased the queue size …

part of the fix for earlier performance issue

---

uber/models.py

Derp, I grepped the codebase for all cases of ``start_time`` to find any remaining issues like this, but forgot to do the same thing with ``registered`` so this one slipped through.  Derp.

fixed utc bug with oneday badge prices

---

uber/site_sections/preregistration.py

The "MAGFest is over" message should be generic and use our snazzy config options.

fixed wording to no longer refer to MAGFest 13 explicitly

---

uber/utils.py

fixes #1070
normally for deploys we're using "/magfest" so this makes it look at the INI. seems to work OK.
-Dom

fix hardcoded path

---

uber/models.py

As @kitsuta noted in Slack, you can't use ``@Session.model_mixin`` to add new ``SessionMixin`` methods.  I've updated it so that you can now do this.

Session.model_mixin decorator now works for SessionMixin and QuerySubclass

---

uber/common.py
uber/server.py
uber/templates/base.html
uber/utils.py

There are two main changes:
1) There's a new ``mount_site_sections()`` function which plugins can use to expose new webpages.
2) There's a new ``MENU`` object which can be overridden in event-specific plugins to add links to the main admin menu.

plugins now have an API for defining their own site sections

---

uber/models.py

The issue turned out to be a case of me just plain mis-reading the SQLAlchemy documentation.  The ``cascade`` value of ``"all"`` is shorthand for ``"save-update,merge,refresh-expire,expunge,delete"`` but I thought it was all of those except ``delete``.  Whoops!
Anyway, the fix was just to change the ``cascade`` value to the correct thing, by replacing ``all`` with ``save-update,merge,refresh-expire,expunge``.  Anyone interested in what all of that means can read the docs at
http://docs.sqlalchemy.org/en/improve_toc/orm/relationship_api.html#sqlalchemy.orm.relationship.params.cascade

fixes #1119

---

uber/models.py

Plugins were previously able to add new columns, but until now they couldn't change existing columns.  I never tested that out, since I never needed to do it for MAGStock, and it turns out that there's a special method you need to call to replace a column rather than adding it:
http://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.ColumnCollection.replace

Column overriding

---

uber/common.py
uber/models.py
uber/sep_commands.py

per Eli's suggestion
1) initialize the DB in a task that runs only on actual startup after all classes have registered themselves.  any other calls that omit modify_tables=True are basically ignored.
2) this also tries to initialize the DB, and if it fails, retries 10 times with a 5 second delay, to deal with the database not being ready to accept connections (this happens with docker containers starting up for the first time, and out of order)
--
These changes accomplish the following:
1) Fixes broken behavior where ubersystem didn't create all it's DB tables at startup automatically
2) Makes this startup in our current docker setup where uber tries to connect to the DB before the DB is ready to accept connections
Probably should remove Session.initialize_db() from magstock plugins, and …

initialize_db() now happens on post-init, ignore any other times it's called

---

uber/models.py
uber/templates/registration/change_badge.html

Two changes here:
1) We no longer ask for badge numbers on the Change Badge form if ``c.NUMBERED_BADGES`` is False.
2) There was a bug where we wouldn't successfully change the badge type for a non-preassigned badge.  I'll point it out inline.

fixed badge update code to work on non-preassigned badges

---

uber/decorators.py
uber/templates/base.html
uber/templates/preregistration/index.html
uber/templates/static_views/prereg_offline.html

Fixes #1131.
This adds a new configuration option called "Offline Mode." The idea behind this option is that if an event loses its internet (or just can't acquire it in the first place), we want an easy way to turn off internet-dependent features, particularly Stripe. 
This is also disables online at-door reg, since there's no more syncing between the cloud server and the local server while the system is offline.
Requires config option `offline_mode = True`

Add offline mode

---

alembic/versions/51e4adb4b60_add_watch_list.py
alembic/versions/54fae9d8798_add_donation_tier.py

Fixes the addition of the donation tier column so it actually sets everyone to the real default. Also adds some previously-manual SQL into
the WachList migration.

Fix donation tier migration

---

uber/site_sections/registration.py

Adding the paid by group attendees breaks if you haven't already fixed
the attendees with no group, so this changes around the order. Hopefully
that's the last of the fixes needed.

Change the order of the badge status alterations

---

uber/site_sections/preregistration.py
uber/templates/static_views/invalid_badge.html

Redirects attendees to a static view to prevent them from viewing or paying for an invalid badge.

Fix confirmation page for invalid badges

---

uber/site_sections/registration.py
uber/templates/registration/printed_badges.html

This avoids the slow-loading problem that crops up when you have 5000 badges.

Paginate the printed badges page

---

uber/site_sections/preregistration.py

When pre-con, we want people to see who they just registered and show them their badge pages. At the con, however, this is extremely undesirable. Adds a check to change the behavior when paying through Stripe.

Changes the Stripe confirmation page

---

uber/custom_tags.py
uber/templates/base.html
uber/templates/common.js
uber/templates/preregistration/form.html
uber/templates/preregistration/stripeForm.html

This has two fixes:
1) We change "Preregister" to "Add to Cart" on the prereg form, since people will be less likely to think they're preregistering when the fill out the form and then don't pay.  That was a simple one-line change.
2) When someone opens the Stripe form and then cancels out of it, the other Stripe buttons are no longer disabled.  This took me 4 hours to figure out how to accomplish!  Relevant XKCD: http://xkcd.com/1425/ though arguably it's not the same thing because the answer did turn out to be relatively simple in the end :/

fixes #1192 and fixes #1194

---

uber/custom_tags.py
uber/site_sections/preregistration.py
uber/static/theme/prereg.css
uber/templates/base.html
uber/templates/preregistration/confirm.html
uber/templates/preregistration/form.html
uber/templates/preregistration/preregbase.html
uber/templates/preregistration/register_group_member.html
uber/templates/preregistration/transfer_badge.html
uber/templates/regform.html
uber/templates/registration/index.html
uber/templates/registration/register.html
uber/templates/static_views/stafferComps.html

We now have two rows of badge selection:
- The first row is for selecting between a single or a group registration.  This row ONLY appears on the main prereg form.
- The second row is for selecting badge level (regular, tshirt, supporter, etc).  It shows up on all the prereg forms (main prereg form, badge confirmation page, badge transfer page, and group badge claiming page).
As discussed in #1217 we don't show any of badge levels lower than what's already selected.
I made a couple of other fixes/improvements, which I'll explain with inline code comments.

Separate badge type buttons into different groups

---

development-defaults.ini
uber/custom_tags.py
uber/static/theme/prereg.css
uber/templates/preregistration/form.html
uber/templates/preregistration/preregbase.html

This has four main changes:
1) The actual contents of the ticket: for each badge type, we display a warning indicating when and to what the price will be raised.  As before, this warning changes to a warning about when preregistration closes when we reach that point.
2) I was testing out the group stuff and found myself unhappy with the way the prices displayed.  If you selected the "Group Leader" option, it would still tell you that your Attendee badge cost $50 even though that's no longer true.  So I added some Javascript code to check the group selection; if you're making a single registration it shows the overall price (e.g. $70 for a shirt) but if you're making a group registraton it only shows the amounts added (e.g. +$20 for a shirt).  The other forms all just work the same way …

Price notices and Volunteer options

---

uber/templates/preregistration/preregbase.html

"membership"->"registration"
fixes https://github.com/magfest/ubersystem/issues/1230
I could only find this one instance of the word "membership" in the code anywhere, so fixing that, and I think it handles all "membership" related text.

txt change

---

uber/configspec.ini
uber/templates/preregistration/form.html

1) ability to have dealer reg be open, but not on the public form (so you can send stuff to dealers before announcing it publicly)
2) add dealer_reg_public to configspec.ini, by default it's none which disables all references to dealer stuff on the prereg form
3) unrelated: remove unneeded/bad c.BASE_URL in form.html template
In its default configuration (as it is now) it won't show any dealer stuff.  This will need to be changed in order to open dealer registration for magclassic.  
For how to fix, see https://github.com/magfest/ubersystem/issues/1244

Tempfix dealer reg

---

uber/templates/preregistration/form.html

It makes no sense to say "Add to Cart" when you're editing a badge before paying, so this adds another if statement to the template.

Rename pre-reg save button for editing badges

---

uber/config.py
uber/site_sections/preregistration.py
uber/site_sections/registration.py
uber/templates/registration/new.html
uber/templates/summary/index.html

- mostly trivial, replaced a few copy+paste instances of badge capping formula with c.REMAINING_BADGES
- since that's a config property now, we don't need to explicitly pass it into templates, they can access c.REMAINING_BADGES directly
- feature: display the # of remaining badges on the summary page

refactor badge capping (max_badge_sales) logic slightly

---

uber/templates/base.html

Fixes #1229.
The way we check for people who enter a year too early is hard-coded for right now - I wasn't able to get our date text field to accept a function return for `min_year` like it does for `max_date`. Weird.

Add client-side date-of-birth validations

---

uber/models.py
uber/site_sections/summary.py
uber/templates/base.html
uber/templates/registration/checkin.html
uber/templates/registration/form.html
uber/templates/static_views/supporters.html

Fixes #1227.
Unfortunately this includes my last PR because my local copy of master got dirty, but luckily it's a pretty simple change.
I've left a lot of the checks for Supporter badges in because I expect we'll need those later for when we add comped kick-in levels.

Remove Supporter badge autoassign

---

uber/templates/regform.html
uber/templates/registration/form.html

These are hidden from the admin page as part of a larger block, but we should really be able to edit them. Fixes #1183.

Add Badge Printed Name and Shirt to Admin page

---

uber/models.py

it's an anthrocon reference that we aren't using in core yet
- this has been causing some emails to not go out, it may cause a bunch to go out as soon as we re-enable them

remove c.DECLINED reference, maybe fix some automated emails

---

uber/site_sections/preregistration.py
uber/site_sections/registration.py

Brent noticed that we get an error if we tried to "delete" a group badge (which actually just unassigns the badge so someone else can take it).
This was a one-line fix which I'll explain inline, but there were two other fixes which went along with it, which are also explained inline.

fixed issues with deleting a group badge

---

uber/templates/jobs/staffers.html

Brent asked to add a marked on the "staffers" page on the jobs section indicating whether the staffer was a department head.  This seems like a good idea in general, and it's especially useful for events where 3-5 people all have that title (though it seems like it would be useful in any case).

added [D] to staffer list on jobs section

---

uber/models.py

Brent noticed that after changing someone from a Staff badge to an Attendee badge, they were still marked as a volunteer (which is correct) but without a volunteer ribbon (which is not correct).
This fixes that, so that doing that change will leave them with the correct ribbon.

volunteers now correctly get assigned volunteer ribbons after a badge change

---

uber/models.py

As some people have noticed in their own testing, the prices for dealer registrations weren't adding up properly.  It turns out that we were using the group badge price instead of the dealer badge price.  This fixes that to use the correct price when computing group badges based on whether or not each attendee is a dealer.

dealer badge prices are now correctly calculated

---

uber/custom_tags.py
uber/templates/preregistration/form.html

Dealer tables were just displaying the "default price" per table.  However, we typically have different prices for each table so we can make them progressively more expensive.  I've implemented a custom tag which does this automatically by using the contents of ``c.TABLE_PRICES``.

dealer table prices now display correctly

---

uber/models.py

There are two fixes here:
1) I changed the hard-coded value of ``5`` to instead use ``c.MIN_GROUP_ADDITION`` (which is 5 by default).  This is unambiguously a fix.
2) I updated the code to conform to MAGFest's policies; dealers cannot add badges unless explicitly marked as ``can_add``.  This is different than what Anthrocon had in place.  Theoretically any event can just override this property in a ``@Session.model_mixin`` in a plugin, and I think this is a good default behavior.  I considered putting just leaving this code as-is and putting our logic in a plugin, but I didn't for several reasons:
- I wanted to fix the hard-coded issue anyway
- the existing code arguably has a bug in that it checks the dealer max badges but allows more than the max to be added
- I'd have needed to …

Min group badges addable fix

---

uber/custom_tags.py

We were previously always saying ``11:59pm EST" for all of our deadlines and such even if those were set to some other time of day.

datetime filter no longer hard-codes 11:59pm EST

---

uber/templates/regform.html

We require a phone number for registering dealers.  However, we were previously failing to mark the field as bolded to indicate it's required.

dealer phone field now marked as required

---

uber/config.py
uber/templates/preregistration/confirm.html
uber/templates/regform.html

Two issues here:
1) Dealers were breaking the confirm page because they didn't have ``amount_extra`` and a lot of our Javascript code relies on them having it.  I'll note that we don't expect dealers to ever end up on this page (though it's theoretically possible, e.g. if we link them to it, or if they volunteer, etc).
2) There's a price warning which shows up on this page if you have an unpaid balance... but this was showing up even if the form failed validation and hadn't been saved yet.

fixed two minor issues on confirm page

---

uber/site_sections/groups.py

When a dealer application is explicitly waitlisted or declined by an admin, they type out an email into a textarea field on the admin form, which gets sent to that dealer from the marketplace address.  This change also bccs the marketplace mailing list on those emails so that everyone can keep up with what's happening.

bcc marketplace on all waitlist/decline emails

---

uber/site_sections/groups.py

Here's how it works now:
- when you enter a group on the admin form with the "New Dealer" button, the system will check whether or not you've marked the group as paid
- if you've marked the group as paid in full, it'll just direct you back to the main group list, where you can click the "Add a Dealer" button again if you want
- if the group has an unpaid balance, it'll do what it did before, and direct you to the page where the payment can be made
This was asked for by Danielle in an email thread today.

modified new dealer admin workflow

---

uber/custom_tags.py
uber/static/theme/prereg.css
uber/templates/preregistration/preregbase.html

See #1290 for a more detailed explanation, but basically we want "prereg closes" notices to always show up, but "price goes up" notices to only be shown if someone is paying for the first time (e.g. not claiming a group badge).

Notices now show and hide appropriately

---

uber/custom_tags.py
uber/templates/preregistration/form.html

Fixes a bug where the Supporter badge is shown with a message about the price going up at-door.

Only show at-door price notice for badges without unique deadlines

---

uber/models.py
uber/templates/preregistration/index.html
uber/tests/models/test_attendee.py

We took the time to configure discounts for our various age groups... and then we never actually implemented our cost code to look at those discounts!  And then we never noticed - whoops!
Anyway, this is fairly straightforward, but I'll explain my changes inline.  I also wrote unit tests for the new functionality, since those are working again.

age discounts now actually work

---

uber/templates/preregistration/group_members.html

minor UI fix, any reason to not do this?
basically it adds the field highlighted below in red, which shows assigned people what kind of badge+ribbon they have.

display badge type of assigned group members

---

uber/automated_emails.py
uber/site_sections/emails.py

This was a dumb mistake on my part.  I know I tested the ``extra_models``stuff, but I must have accidentally run ``supervisorctr restart all`` after making that change, because this was broken due to not having this argument.  I see that I ran it about half a dozen times while testing, but I must have neglected it once at the end.  Ah well :/

added session parameter to extra_models list function

---

uber/models.py
uber/site_sections/groups.py
uber/templates/groups/form.html

ribbon selection dropdown doesn't show when group is a dealer, only shows when it's a normal group
plus, minor UI fixes to make the buttons slightly less confusing than before
fixes https://github.com/magfest/ubersystem/issues/1354 and probably at least makes https://github.com/magfest/ubersystem/issues/1345 not be so confusing.

group edit page allows assignment of ribbons to new badges

---

uber/site_sections/schedule.py

fixes https://github.com/magfest/ubersystem/issues/1376
NOTE: the original error was, after it bombed out, causing a subsequent search on the reg page to crash.  I suspect maybe the session wasn't being cleaned up and that was affecting the next thing trying to use the session.
Or something.
@EliAndrewC @kitsuta please look and let me know if i'm doing anything silly here.
What was happening was we were passing in just attendee.id and not attendee itself to the AssignedPanelist() class, which when it tried to add itself to the db it would not pull up its Attendee object.
I'm not super-sure what's going on here, only that the other sections of code that access this type of lookup passed in the attendee object, so I made this one do it too.  Seems to work.

fix schedule crash when adding panelists

---

uber/models.py
uber/tests/models/test_apply.py

add some tests that reproduced this bug, and work now that it's fixed.
the bug was a copy+paste error we didn't catch til now
fixes #1381

fix typo when trying to unassign all checkboxes on admin attendee edit

---

bower.json
uber/templates/groups/index.html
uber/templates/jobs/staffers.html
uber/templates/registration/attendee_upload.html
uber/templates/registration/staffers.html

Spaces were wreaking havoc on DataTables' auto-detection of data types, so this fixes that and manually specifies data to sort by in some cases (like when we link to a Group page). Fixes https://github.com/magfest/ubersystem/issues/1396.

Fix DataTables Sorting

---

uber/models.py
uber/site_sections/emails.py
uber/templates/emails/test_email.html
uber/tests/models/test_attendee.py

Adds a simple page to test email sending from the web UI.
This just calls ```send_emails()``` with the info.
I was using this to test out a switch of our Amazon AWS key

Add test email sending

---

uber/tests/models/test_attendee.py

see https://github.com/magfest/ubersystem/issues/1404 for discussion.
this is just the unit test, not the fix.  safe to merge, but does not contain the fix yet which is yet to be written.
I don't have time to look at this tonight unfortunately.

add unit test to make sure staffing=true when volunteer ribbon set

---

uber/models.py
uber/templates/registration/change_badge.html

The JavaScript for the badge change page was checking for the wrong config value, so the box to change the number wasn't showing up. This fixes that plus a 500 error that would have prevented number changes from going through.
Fixes https://github.com/magfest/ubersystem/issues/1395.

Re-enable manual badge number assignments

---

uber/templates/regform.html

makes it so it doesn't appear bold to denote required field
not sure if there was an open issue for this one, Brent was asking about it.
example of what it looks like fixed, notice it's no longer bold:

mark "name printed on badge" as optional

---

uber/templates/regform.html

This functionality already exists in the MAGClassic plugin, but it's a nice bit of explanation text and we want it for all events that use groups or dealers, so it's being moved to core.

Add group explanation

---

uber/common.py
uber/decorators.py
uber/site_sections/summary.py

Huh. turns out this was actually really easy to do. part of #1397 
I wanted to the ability to take a bunch of our existing CSV reports and stick them into a .zip file.  If you stick the ```@multifile_zipfile``` decorator on a function, it'll pass you a ```ZipFile``` object which you can use to easily create a bunch of files inside a zipfile.
result from the test data in here:
I'll be updating the stuff in summary.py to have real data in it in the next PR.

Add zipfile decorator

---

uber/configspec.ini
uber/custom_tags.py
uber/templates/preregistration/preregbase.html

Fixes https://github.com/magfest/ubersystem/issues/1425. This is pretty complex view logic, but in essence we now check to see if the amount_extra field is present and visible. If so, we can assume that the more sensible way to display price information is to attach it to the registration type and show the badge levels as additional prices - otherwise, we display the total on the badge level buttons.
I've also made the badge level buttons only highlight if you select their exact kick-in level, as their prices are misleading otherwise.

Switch price display depending on # of kick-in levels

---

uber/templates/regform.html

We previously had a link on the admin form where if someone was volunteering, an admin could click a link to log into the checklist as that person.  The link was lost in the big form refactor this year, but this PR re-adds that link.

Add link to volunteer checklist

---

uber/decorators.py

Python 3 no longer accepts strings when writing in byte-mode, so this encodes the contents first.
This is an emergency fix, but we'll refrain from merging and just switch the production server's git branch. After we merge this we need to checkout master again.

Fix page caching

---

uber/site_sections/preregistration.py

this is needed because once laptops are imaged, it's really painful to change their homepage
this allows devs to redirect to a different page if needed without having to mess with the laptop config

add laptop "kiosk-mode" landing page

---

uber/config.py

Our ``magfest.js`` file iterates through everything in ``c`` (except stuff in ``[secret]``) and renders it into a Javascript object.  As currently implemented, if anything raises an exception, then ``magfest.js`` results in an HTTP 500 error because of the uncaught exception.

fixed common.js error

---

uber/automated_emails.py
uber/templates/emails/shifts/schedule.html
uber/templates/signups/food_info.html
uber/templates/signups/printable_schedule.html

This was deleted during the big refactor this year, so I'm turning it back on now.

re-added shifts email and removed MAGFest-specific info

---

uber/site_sections/preregistration.py

The kiosk page was redirecting to the main prereg form instead of the at-the-door reg form.

fixed kiosk page

---

uber/site_sections/accounts.py
uber/templates/accounts/index.html

When the bootstrap refactor happens, the buttons didn't all get hooked up properly.
Here are the three fixes I made:
- You now get an error when trying to create an account but don't enter a password.  (This is unrelated to the bootstrap refactor.)
- The delete button now works properly; we added a separate form for it, since previously that got deleted somehow; we'd get a confirm modal but clicking Ok didn't do anything.
- The update button is now actually hooked up to the update form properly.
I also cleaned up the whitespace, since a there was a mix of tabs and spaces in the form and we use spaces only by convention.

three fixes to account management forms

---

uber/templates/registration/merch.html

Ryan noticed that doing certain things on the merch page would just not show anything.  This was always things where we would have just expected no action to take place, but a message should have still been shown.
There used to be a ``<div id="message></div>`` on every page, and the merch page relied on that.  The bootstrap refactor replaced that with ``toastr``, which meant that a lot of messages on this page just weren't being shown.

re-added missing message div for merch

---

uber/site_sections/registration.py
uber/templates/registration/multi_merch_pickup.html

We have a page that merch uses when someone collects merch on behalf of one or more individuals.
That page previously didn't allow merch to select the size of tshirt that was given out.  This adds that ability, which is important for current inventory tracking and future inventory.

added shirt sizes to multi-merch pickup

---

uber/configspec.ini
uber/site_sections/summary.py
uber/templates/static_views/stafferComps.html
uber/templates/summary/volunteers_owed_refunds.html

In the past we generally waited for someone to come to Stops and ask for a refund.  This used to be sensible since most of the time their hours wouldn't be marked until they brought us their sheet anyway.
Nowadays with people having smartphones and network access being more prevalent, we can refund volunteer registrations as soon as their hours are marked off, so it's nice to have a report so we can start doing that during quiet time on Saturday night.

added report on volunteers who are owed refunds

---

uber/site_sections/summary.py
uber/templates/summary/ratings.html

Brent and I were looking at the report of poorly-performing staffers and we noticed that it only had ratings from previous years.  Whoops - this made sense the very first time we used this report but obviously it needs to include both past and current ratings.

added ratings from the current year to the poor ratings report

---

uber/site_sections/preregistration.py

Using c.EVENT_NAME in this line is actually incorrect because of the way it's processed in utils.py, so we need to undo this change.

Fix group email error

---

uber/custom_tags.py

I was diagnosing a config error with CoolCon (generic install with no event-specific config), this validation check helps spot which template items are invalid.
instead of 
```python
TypeError: unorderable types: datetime.datetime() < NoneType()
```
it now says
```python
ValueError: price_notice tag error: Takedown date not valid for "Group registration"
```

price_notice tag: throw a better error message when takedown is None

---

uber/common.py
uber/templates/emails/daily_checks/placeholders.html

Brent said it would be useful to see which departments our placeholder volunteers are assigned to so that we know which department heads to bug.

Added job locations to placeholder emails

---

uber/models.py
uber/site_sections/registration.py
uber/templates/registration/watchlist.html

Using listify on the session object returned by guess_attendee_watchentry was causing a session-related exception, so we use it only on watch_list where it is needed. Also fixes a bug that prevented admins from properly confirming watchlist entries.

Use listify only on the watch_list relationship

---

uber/models.py
uber/site_sections/jobs.py
uber/site_sections/registration.py
uber/site_sections/summary.py
uber/templates/jobs/signups.html
uber/templates/jobs/staffers.html
uber/templates/registration/form.html
uber/tests/conftest.py
uber/tests/models/test_attendee.py
uber/tests/models/test_job.py

Change attendee concept of 'trusted' in RAMS.
Previously we had a concept of an attendee being 'trusted' vs 'not trusted'.  i.e. trustworthy enough to handle money, work security, whatever.
However, someone trusted in one department might not necessarily be trusted in another.  When someone was re-assigned departments, they would show up as being trusted in the new department, even though the department heads didn't know them.
This change allows someone to be set as trusted on a per-department basis.  i.e. trusted in Arcade but not in Treasury/etc.
Goes with another PR for magprime repo https://github.com/magfest/magprime/pull/35 which must be merged at the same time.
This PR contains all the code changes needed for this, and will need to have a database migration to migrate attendee …

Attendees trusted per-department

---

uber/site_sections/groups.py
uber/site_sections/preregistration.py
uber/templates/emails/dealers/badge_converted.html
uber/templates/groups/form.html
uber/templates/preregistration/confirm.html

Adds a "Reject and Convert" button to allow admins to save assigned badges when declining dealers. The system will automatically email each badge holder offering them a chance to finish their registration.

Add ability to convert dealer badges to regular badges when declined

---

uber/automated_emails.py

Changed parental consent form to e-mail out 2 weeks beforehand instead of just 1.

Change consent form email date

---

uber/site_sections/accounts.py

fixes #1428
BRO, DO YOU EVEN SITEMAP? for my sanity, I needed this fixed in the course of fixing something else.  PyCharm debugger+inspector to the rescue.  Many Bothnans died to bring you this information.
verified that the output for core pages is identical, and it adds pages from plugins now.
sample output:
only thing is that the page takes about 5sec to load.  seems a little high, maybe we want to cache this output the first time it's used or something.  it works fine though.

Fix sitemap to show content from all plugins

---

uber/site_sections/groups.py

A previous change had made waitlisting dealers impossible due to a minor variable reference bug. It will now work again.

Fix the Waitlist button

---

uber/models.py
uber/templates/emails/sent.html
uber/templates/registration/history.html

Now on the history page for an attendee, we continue to show text emails as we always have, and for HTML emails we instead show a link to where they can view the email.  This addresses the performance issues we've seen.

added special casing for HTML emails on history page

---

uber/badge_funcs.py
uber/site_sections/registration.py

In the long run we need to give some thought to how we handle invalid/deferred badges so that it's easier to not have to individually fix tons of different reports to all ignore these badge statuses, but in the meantime this is an easy fix.

placeholder badge page/report now ignore invalid/deferred badges

---

uber/configspec.ini
uber/templates/signups/food_item.html
uber/templates/signups/shirt_item.html

We changed the default order of the volunteer checklist, but forgot to change the if-statements that determine when you can complete each step.  That meant that even though the order of the steps changed, you still had to complete them in the original order (e.g. 1-3-2-4-5).  This is now fixed.

fixed order of volunteer checklist to work for attendee volunteers

---

development-defaults.ini

We had a price bump defined in ``development-defaults.ini`` for some reason, probably as a holdover from last year (which fits with the date).  This was making its way into production and yielding a confusing error message where the price was already $70 but a message explained that it would be raised to $70 in the future.

removed superfluous price bump day from config

---

uber/site_sections/summary.py

Ryan from the merch department says this is the more useful number, and the numbers we had before weren't useful since they don't help with sales projections, which is the main reason for them.

shirt sale figures on summary page now ONLY track actual shirts sold and not free shirts

---

uber/config.py
uber/configspec.ini

There's a new config option for determining how many days before the event setup shifts start.

Setup shifts now go configurably early

---

uber/models.py
uber/site_sections/preregistration.py
uber/tests/models/test_group.py

We just uncovered an issue which we haven't run into before.  MIVS studios get groups created for them, where they're asked to fill out badges.
These are NOT paid-by-group badges because we need them to be need-not-pay badges.  This is because we want them to be able to add new badges to their groups, but additional badges need to be paid for.
This change allows us to claim need-not-pay group badges through the Group Members page.

unassigned group badges now track payment type when being claimed

---

development-defaults.ini

See #1630 for a "real" fix for this (by puppetizing the config option) but in the short run I need to update the Panels email signature so that the panel folks can approve their accept/decline emails.

updated default panel email signature (see #1630)

---

uber/site_sections/registration.py

UPDATED: this is now a DEVELOPMENT-ONLY change, production systems are unaffected. (checking for c.DEV_BOX)
on /registration/ this reverts to the previous behavior of the system before Bootstrap where we would show the first page of results instead of a blank search page.
this is really extremely handy for testing (saves one annoyingly well-placed click), slightly less useful in production.
old behavior:
new behavior:

DEV ONLY: show first page attendee search results by default

---

uber/site_sections/registration.py
uber/templates/groups/form.html
uber/templates/registration/form.html

UPDATED, does something slightly different now.
2 unrelated but really minor things so I put them in the same PR.  
These are some arbitrary UX/design things that were slowing me down, I'm open to not doing them if people have strong opinions.
1) Two buttons at the bottom of the attendee edit page instead of one:
* Save - which when clicked, brings you back to edit the attendee info
* Save + return to search - when clicked, saves the attendee and returns to the search page (this is the original behavior)
If the user presses Enter on the form, it will use Save+return to search.
Looks like:
2) change a bunch of button text from "Upload" to "Save", mostly around attendees and groups.  I only changed the text as this was the most minimal change I could do.  "Upload" always struck me as a …

Ux improvements: 2nd button added to attendee edit page, change "upload" to "save"

---

uber/templates/registration/history.html

small fixes that make the history page easier to read.
1) vertically align cells to the top
2) add a small black border
I'm ignoring CSS cause lazy and probably everything about this massively internal page needs a CSS overhaul anyway.
been fixing minor things as I work on some other stuff.

UX: add border, alignment fixes to history page

---

uber/templates/registration/form.html

We already had these fields in the database, but there was no way for an admin to set them.  This has been causing issues for various department heads.

Checkboxes for allowing setup/teardown shifts

---

uber/templates/base.html

As discussed in #1658, we only need this if ``c.COLLECT_FULL_ADDRESS`` is turned on, so we check for this before loading that resource.

Wraps Google API script in an if block

---

uber/common.py
uber/site_sections/registration.py
uber/templates/registration/staffers.html

The page went from taking 10s of seconds to load to rendering in ~1.5 seconds on my Vagrant VM.  Still slower than it could be, but good enough for now.
The main fix was to stop using ``session.everything()`` which itself probably could be refactored with some of the same principles that I used here, which I'm going to try tackling tomorrow.

optimized the staffers page

---

uber/site_sections/summary.py

From my conversation with Ryan from Merch in email:
> Ryan: And not to be a nitpicker, but... The total number of "prepaid" shirts according to the "shirt counts" list is 1,068. However, over at the week by week summary of sold shirts, the total count is 1170. Why the 102 shirt difference?
> Me: Whoops!  Not a nitpick at all, with a difference that big!  I made a mistake - the week-by-week summary is looking at shirts of paid attendees, instead of paid shirts.  Those are two completely different numbers, because e.g. someone with a free badge can also kick in at the shirt level.  This is what accounts for the 102 shirt difference.
This PR fixes that discrepancy.
Since this is NOT a super-urgent fix, I'll wait for someone to actually +1 it before merging for once :)

changed shirt count again, this time even more refined

---

uber/site_sections/summary.py

Merch wants a separate category of shirt counts showing counts for people who get both free AND paid shirts, so that they can set aside a shirt of each type for those people.

Added "both" category of shirt counts

---

uber/automated_emails.py
uber/templates/summary/index.html

Two fixes:
1) Email throttling is now working correctly and causes a delay of less than 5 minutes instead of many hours.
2) Missing counts have been added to the summary page.

Fixes what broke in the performance tuning

---

uber/templates/jobs/staffers.html

Another display bug that was introduced in the performance tuning.  Just had to update the template to grab the counts from the new more-efficient ``counts`` object.

department hour counts now work again

---

uber/site_sections/jobs.py
uber/templates/base.html

Two changes here:
1) The count of "hours here" on the ``/jobs/staffers`` page now works again.  It was displaying the total hours as of the performance tuning because I forgot to include an if statement.
2) I removed the "Staffers" link from the main admin dropdown, since it's not the recommended way to look up staffer information and is only really intended to be used by Stops.  The page still exists and is accessible through the sitemap.

Staffer summary fixes

---

uber/model_checks.py
uber/models.py

Turning off badge shifting now ALSO turns off the ability to add new custom badges, which is a feature we've had in past years but which must have broken in some refactor or other.
Since there are two ways to give someone a badge type (creating or changing the badge), we add a check in both places.

Disabled custom badges

---

uber/models.py

When doing the performance refactor I accidentally swapped the sort order on jobs.  It's supposed to sort by start time THEN by name, but I accidentally reversed that.  This is a one-line fix that corrects all of the places where jobs weren't showing up in the order in which they start.

fixed sort order of jobs

---

uber/models.py
uber/tests/models/test_attendee.py
uber/tests/models/test_group.py

There are three places where you can mark someone as getting a customized badge.  I already disabled 2 of those 3 places in a previous PR but forgot about one.  This PR fixes that.

disabled ability to add custom badges to groups after the deadline

---

development-defaults.ini
uber/configspec.ini
uber/site_sections/registration.py
uber/templates/registration/register.html

New configuration option for free late badges

---

uber/models.py

When someone is marked as a department head, they are automatically assigned a staff badge.  In general this is good, but we don't want to do this after the badges have been ordered.  I added an if statement to ensure that after badges have been ordered, people's badge type is not adjusted.

Fixed dept head ribbon / badge issue

---

uber/templates/common.js
uber/templates/jobs/job_renderer.html

Two bugs are fixed here:
1) A recent refactor to simplify the job rendering code broke the ability to mark shifts as worked from the volunteer's shifts page, i.e. the "Shifts" tab of their admin form.  This fixes it.
2) Previously we were rendering the rating form for people who were marked as not showing up, which is not correct.

fixed bug with shift marking from the attendee shifts page

---

uber/templates/jobs/job_renderer.html

David Boyd pointed out that in our floating dropdown of volunteers to assign to shifts, the first volunteer was selected by default.  This has led to a tendency to assign people named "Aaron" to shifts accidentally, forcing us to remove them and then assign the correct person.
This implements a "Select a volunteer" default first option, and clicking "Assign" when that option is selected will throw up an error alert box.

Signups pages no longer default to first volunteer in dropdown

---

uber/config.py
uber/configspec.ini
uber/models.py
uber/site_sections/registration.py
uber/templates/registration/register.html

For this year, we wanted to allow anyone to buy any day's badge through our 'at-door' page.
This was trickier than expected, because our badge configuration is fairly limited - you can't have multiple 'attendee'-type badges with their own sets of prices. While this is a good argument for refactoring badge types into object-based entities, that was too much to tackle right now.
I'll explain the changes in-line.

Add the ability to 'presell' one-day badges at-door

---

uber/templates/regform.html
uber/templates/registration/form.html
uber/templates/registration/menu.html

This implements 2 features:
1) If you're in at-the-con mode then clicking on the "Return to Attendees" link takes you to a search that displays only the attendee you were just viewing, which makes it easier to check them in.
2) On the admin form, the age group label is displayed next to the birthdate, e.g. it'll say ``(over 21)``, etc.

Two features Bob asked for

---

development-defaults.ini
uber/config.py
uber/models.py
uber/templates/registration/merch.html

Three fixes here:
1) I set the merch prices for this year.  We really need to move this out of ``development-defaults,ini`` but that's where it's always been, and fixing that is out of scope for this PR.  (I'm hoping to get Dom to tackle https://github.com/magfest/ubersystem-puppet/issues/28 in the next couple of months and then we'd get that for free.)
2) I fixed a minor display bug with the "Check Merch" button on the merch page.  We now property listify all of the "number of things you get" cases (nothing, 1 thing, 2 things, many things).
3) Most seriously, there was a bug in the merch code that we never noticed because it only triggers when two items in your store cost the same thing,  This didn't happen for MagClassic, but it's totally a thing for us.  I fixed the ``prices`` feature …

fixed merch prices and merch check layout

---

uber/templates/preregistration/preregbase.html

Group registrations would still show up after the deadline had passed; this fixes it so that they no longer do.

actually disabled group badges after the deadline

---

uber/templates/registration/new.html
uber/templates/registration/register.html

Two fixes here:
1) Bob pointed out that in the at-the-door reg form, "Email Address" is bolded, making it look like a required field.  In fact it's optional.  I fixed it so that it shows up as required for Stripe and nothing else.  (In theory it's option for Stripe as well, but we might as well make it bold since they'll need to type in their email when they pay via Stripe anyway.)
2) There was a DataTables error on the at-the-door registration page, which I fixed.  Apparently datatables doesn't support colspan, which is unfortunate.

two minor fixes for at-the-door registration

---

uber/templates/registration/new.html

When we implemented ``DataTables`` on the New registrations page, we change the class name on the table.  This broke the jQuery selector we used to set the "disabled" status of the buttons on that page, which resulted in us not being able to click the "Mark Paid" button until we changed the value in the dropdown, even if a correct value was already selected.

fixed Mark Paid button being disabled on initial page load

---

uber/site_sections/signups.py
uber/templates/signups/onsite_jobs.html
uber/templates/signups/printable.html

We've always disabled the usual signups page when we're in on-site mode because we don't want people dropping shifts.  I added the ability for them to take new shifts so that we can direct on-site volunteers to sign up for new shifts on their smartphones.

implemented ability for volunteers to sign up for shifts in at-the-con mode

---

uber/config.py

We noticed that single day passes couldn't be transferred, so we now automatically add those badge types to ``c.TRANSFERABLE_BADGE_TYPES``.

presold single day passes are now automatically transferable

---

uber/models.py

when dept checklist sections are missing from the INI, make the error message more obvious about what went wrong.
old message:
```
KeyError: 'creating_shifts'
```
new message:
```
Can't access dept checklist INI settings for section 'creating_shifts', check your INI file
```

add informative error message on incorrect dept checklist INI settings

---

uber/site_sections/preregistration.py

this code https://github.com/magfest/ubersystem/commit/fe4266d24ebe1844c59260ded8175c4941a8c7cc#diff-9c3818f655c258e1b711348de8f069c9R400 introduced a merge error which we didn't notice til now.
```check_prereg_reqs(attendee)``` was replaced with ```check(attendee, prereg=True)```, did that here and tested, so it works.
fixes https://github.com/magfest/magstock/issues/36

fix merge error resulting in badge transfers not working

---

uber/site_sections/budget.py
uber/templates/budget/index.html

budget page was previously counting kickins twice
- once in "kickins" - attendee.amount_extra
- again in "attendee sales" - attendee.amount_paid (which INCLUDES the kickin)
this whole page probably needs a once over, I think it is also miscounting dealer table sales. not sure.
tested this by doing a bunch of registrations locally and they all match up money-wise now (before it was totaling up too much)

fix budget page

---

uber/custom_tags.py

Needed for https://github.com/magfest/bands/pull/17 - in order to use custom tags with nested models (e.g., parent.child.property) we need to change how they're unpacked.

Make custom tags work with nested models

---

uber/templates/signups/login.html

Sets dates for Shift Signups to be live on 11/26/15, for MAGFest 2016.
This should update: https://prime.uber.magfest.org/uber/signups/login
I'm not sure if there is a more specific MAGFest 2016 branch that this should be in?

add more helpful message when volunteers try to login before shifts are created

---

uber/custom_tags.py

This is resulting in a 500 error because the discount is a string (apparently when configured through puppet?).

Force discount to be an int for math operation

---

uber/templates/registration/register.html

Doing this is unnecessary and is liable to break JavaScript in plugins' regextra.html.

Stop removing fields from at-door page

---

uber/configspec.ini
uber/custom_tags.py

Events can now set group_prereg_takedown and prereg_takedown to an empty string and the pre-reg page will still work. The pre-reg page will no longer warn about pre-reg closing if the takedowns are set blank.

Allow events to have blank prereg_takedown

---

uber/models.py

The new single day badge feature, which involves checking badge labels, broke dealer applications because dealer badges are not configured with labels. This is silly. We now swallow KeyErrors for badge labels.
Fixes #1840.

Stop missing labels from preventing function

---

uber/templates/preregistration/disclaimers.html

This is how most of our templates behave, we just missed a spot.

Hide under-18 disclaimer if no consent_form_url

---

uber/templates/registration/history.html

If an attendee changes their email address, this link would result in an error because it was only searching by attendee email. We have the exact email available to the template so there's no reason to link using fuzzy search terms.

Change link to HTML emails to always work

---

development-defaults.ini

The system works perfectly fine without this variable being set, so there's no reason to include it in the 'defaults' file, which we want to phase out anyway.
Fixes https://github.com/magfest/magstock/issues/81.

Remove default for badge_price_waived

---

development-defaults.ini

These aren't needed; even if PRESELL_ONE_DAYS is set, the system will use the default oneday badge price. Again, we want to phase out this config file as it often leads to unexpected results.

Remove defaults for single day prices

---

uber/models.py

There are two potential problems when accessing a label that can cause an exception. We already fixed one in https://github.com/magfest/ubersystem/pull/1841 - this refactors that to be cleaner, and fixes the other.

Handle _label problems more gracefully

---

uber/templates/registration/check_in_form_base.html
uber/templates/registration/index_base.html
uber/templates/registration/new_base.html

If a check-in form shares an ID with another form on the page, we run into unexpected problems (like the wrong fields saving). This also fixes an underlying bug where the quick checkin dialog was opening twice due to generically-named django blocks.

Make sure all check-in forms have unique IDs

---

uber/model_checks.py

We only want to check badge_num if the event has `c.NUMBERED_BADGES` turned on; additionally, dupe_badge_num had a bug in it and so would always return "true."

Fix badge_num checks

---

uber/site_sections/registration.py

fixes #1878 I -think-
pretty sure that by including ```checkgroups=Attendee.all_checkgroups, bools=Attendee.all_bools``` here, it causes anything not in ```params``` to be zero'd out.
Removing this seems to fix it.  This code was recently touched in magstock refactorings.
really could use a second set of eyes ASAP on this though local testing seems to work just fine.

fix checkin erasing unrelated fields like interest, assigned_depts, etc

---

uber/automated_emails.py
uber/config.py

The usage of uber_takedown has changed now that we often don't take down the system. This keeps emails from getting sent too late even if we decide to set uber_takedown to be after the start of the event (which is more accurate to reality).

Use epoch for emails when appropriate

---

uber/decorators.py

If we send the headers first, the site won't show a traceback if an exception gets thrown (it just has a cryptic browser-specific error message with no info about what went wrong).
The order in which we generate the CSV and then set the headers doesn't matter, so we can switch them with no consequences.

send headers later so that CSV errors show up

---

uber/decorators.py

- current stack traces don't tell you where the errors were, this now shows you
- this allows more pinpointing of error messages, useful when used with alerting to figure out what went wrong
sample stacktrace output (note that it displays the template source name where the problem I artificially created was, 'preregbase.html'):
```
HTTP Traceback (most recent call last):
File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/django/template/base.py", line 274, in parse
compile_func = self.tags[command]
KeyError: 'endblock43445'
During handling of the above exception, another exception occurred:
File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 218, in render
rendered = template.render(Context(data))
File …
```

provide template source, if available, on django template errors

---

uber/configspec.ini

If an end user sees a 500 internal server error, we now display a message that says:
(based on c.CONTACT_URL)
@thaeli you had this disabled sometime last year, though it looks like it was part of some other unrelated change and maybe disabled by accident.  Can you think of any reason not to turn this back on?  If so, I think we should probably turn it back on.  It was part of https://github.com/magfest/ubersystem/commit/e5f34097d37709ebe00726adbb98582c59427278 entitled 'get rid of tools.proxy.base', it looks like it was likely an overzealous delete there?

re-enable 'email us if you're not sure why you are seeing this' text on errors

---

uber/config.py
uber/configspec.ini
uber/custom_tags.py
uber/tests/conftest.py
uber/tests/models/test_config.py

Allows admins to set a badge cap for each price bump, rather than just relying on dates. Fixes #1906.
To add a badge-cap-based price bump, simply add it in the same place in the config as the dates - the system automatically sorts the type of price bump it is based on whether it can be cast to a Date type or not.
This is the simple version, which doesn't store the badge price permanently; thus, there is a chance that the badge price can go _down_ if, e.g., several badges are deleted. However, I'm leaning towards that being preferable, as changing a single config option (or adding fake badges) to force a badge price to stay high is easier than trying to modify the database if the badge price was erroneously bumped (like if a group of 50 people all registered and then requested a refund or …

Use badge caps for price bumps

---

uber/templates/static_views/prereg_not_yet_open.html

if c.HIDE_PREREG_OPEN_DATE is true, we don't show a date on the page that is displayed before the c.PREREG_OPEN date is reached.
i.e. this doesn't let attendees learn what date prereg might be open, which is apparently happening right now on social media by people looking at this page :)
goes with 2 other PRs

add config option to not display prereg opening date

---

uber/automated_emails.py

I am not sure if we want this change to be here or in the new magfest/magfest email section. 
This is a change to the Staff Operations email that goes out to all volunteers/staffers. 
The original iteration of the email was simply for volunteers to sign up for this shifts hence the "EVENT_NAME shifts available" subject line. 
For MAGFest events that email and the process has turned into a 4 or 5 step checklist (depending on if the person is a volunteer or staffer).   The MAGFest Staff Operations department refers to this Email notification and the process it entails as the Volunteer Checklist in all communication to staffers (Email, slack, fb.)   
This edit would chance the subject line of the email to: "Please complete your {EVENT_NAME} Staff/Volunteer Checklist"

Changes: c.event shifts available subject line.

---

uber/configspec.ini
uber/server.py

- this adds a ton of info to traceback logs like requesting URL+query string, admin user if logged in, HTTP headers
- can be turned on and off via config
- extremely useful when used with alerting via ELK stack reporting, now when these are posted in slack it will be MUCH clearer what's going on
Sample log error (this will show up in alerts on Slack now). Note that it displays useful info at the top.
```
2016-07-24 20:10:13,924 [ERROR] uber.server: Exception encountered
Request: GET /uber/registration/form?id=7c7be9c0-78f1-4f41-9c80-1064b429f84a3 HTTP/1.0
Current admin user is: Test Developer
Request Headers:
HOST: localhost
ACCEPT-ENCODING: gzip, deflate, sdch, br
ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
CACHE-CONTROL: max-age=0 …
```

add custom error message handler that outputs extra info about context

---

uber/common.py
uber/templates/preregistration/paid_preregistrations.html
uber/templates/static_views/howToStaff.html
uber/tests/models/test_utils.py
uber/utils.py

Wherever possible we should avoid using c.URL_BASE so that uber works from behind a proxy
This removes a few instances and sets up a function which builds an absolute URL for places where we HAVE to use absolute URLs, like emails and CSV exports.
That function expects relative URLs that begin with '../' (which is our standard way of doing it inside uber) and will do the right thing from there:
example:
input: ```relative url: "..bands/view_stage_plot?id=4"```
output: ```https://my_uber_box:4443/uber/bands/view_stage_plot?id=3```
merge before: https://github.com/magfest/bands/pull/49

Use relative urls for more stuff

---

uber/decorators.py
uber/models.py

- if in the sqlalchemy flush hooks, we acquired a badge lock and then had an exception, we would not release it
- this results in a deadlock which we generally don't catch because that code is usually already fairly bulletproof
This was a nightmare to diagnose, but totally worth it.
Replaces https://github.com/magfest/ubersystem/pull/1884, which has the technical details

fix session flush hooks not releasing the badge lock on exception

---

uber/models.py

if a particular old column can't be rendered (because of bad DB migration or other weirdness), show <ERROR> instead of failing to track anything at all, or passing the error upstream.
merge alongside https://github.com/magfest/ubersystem/pull/1884 for even more kevlar armor.
------
backstory: kinda goes with #1881, see that for all the gory details
We encountered the problem with as the following scenario:
1) Magstock had a VARCHAR DB column called site_number
2) Dom's local DB had "BOGUS SITE" in there for an attendee
3) We change the sqlalchemy code to INTEGER, however we forgot to change the DB in the migration from VARCHAR to INTEGER.
4) Tracking code, on trying to change the campsite to an integer, would try and get the old value of "BOGUS SITE" and convert to int, which would …

bulletproof tracking code by handling exceptions, part 2

---

uber/decorators.py

- breadcrumb data is navigational menu data in the UI
- this data can be used by UI designers to automatically show which page and section we're on
- Chaney wants this for future UI updates
would be available in templates like this:
```
{{ breadcrumb_page_pretty_ }} - {{ breadcrumb_page_section_ }}
```
for ```/uber/registration/watch_list``` it would show:
```
Registration - Watch List
```

inject breadcrumb data

---

uber/tests/conftest.py

This was breaking a huge number of tests. Oops.

Fix typo in conftest

---

uber/config.py
uber/configspec.ini

IND_DEALER_BADGE was from 2015 Anthrocon and has since been removed. It definitely doesn't need to be in the main codebase.

Remove reference to unused badge type

---

uber/templates/emails/dealers/application.html
uber/templates/emails/dealers/approved.html
uber/templates/preregistration/attendee_donation_form.html
uber/templates/preregistration/group_extra_payment_form.html
uber/templates/preregistration/index.html
uber/templates/registration/form.html

This was brought on by https://github.com/magfest/magprime/pull/95 - using division to reduce the badge price results in it being a float, which would display as, e.g., "$40.0". Since there could theoretically be a price involving cents anyway, I went ahead and just changed the formatting in the templates to make it pretty.

Use two decimals in prices in templates

---

uber/configspec.ini
uber/models.py
uber/site_sections/accounts.py
uber/templates/registration/watchlist.html
uber/tests/models/test_attendee.py

Fixes https://github.com/magfest/magprime/issues/92. We found that admins often set attendees to "Deferred" status in order to reserve their badges for next year, so this adds a less unclear badge status for the watchlist.

Add "On Hold" status

---

.gitignore
alembic/README
alembic/env.py
alembic/script.py.mako
requirements.txt

This ensures that all installs will have the same version of alembic, making it easier to manage and run DB migrations. Also includes a custom env.py file for using in event plugins. Simple instructions are in the alembic README.
Replaces https://github.com/magfest/ubersystem-deploy/pull/50.

Add alembic as a 'requirement'

---

uber/templates/signups/food_restrictions.html

Fixes https://github.com/magfest/ubersystem/issues/1935 by:
Putting the sandwich preferences in a div with a unique ID in the core plugin.
Hiding said div with jQuery in the magclassic plugin.
Setting all sandwich preferences to checked in the magclassic plugin; this is to bypass a validation check.

Hide sandwich preferences for MAGLabs

---

uber/automated_emails.py

Attempts to fix https://github.com/magfest/magprime/issues/146. We weren't sending the ident with the list of emails we've sent, we were using subjects instead, so I think this made the system resend emails.
I think.

Use ident in all_sent variable

---

uber/model_checks.py
uber/models.py
uber/utils.py

Fixes https://github.com/magfest/magprime/issues/133. Again.
So far we've been relying on our presave adjustments to always use a real badge type, but model_checks.py is run before any of those. So now we have a property that we can use in that case.

Add badge_type_real for use in model_checks

---

uber/config.py

main prereg form page load time goes from ~4s to ~1.5s, a nice improvement
sadly my profiler was zero help in identifying this, we took a guess and can't believe it was correct

optimize price bucketing by not calling this around 5 times

---

uber/configspec.ini

adds the config option for hardcore optimizations
- use these for extreme server load cases, these enable extremely aggressive and potentially breaking optimizations
- never use this unless you know EXACTLY what you're doing, and you have no other choice because your server's face is melting
merge with
https://github.com/magfest/production-config/pull/98
https://github.com/magfest/ubersystem-puppet/pull/102

add config option: hardcore_optimizations_enabled

---

uber/decorators.py

this popped up as a slight performance hit, we'll re-enable later if we feel like it.  it's both doing heavy string manipulation and it's a DB call to find out if the current user is Nick :)

optimization: disable screw_you_nick for now

---

uber/server.py
uber/templates/signups/shifts.html

- this is to make it so we can more aggressively cache /uber/static_views/ with nginx
- magfest.js is the only potentially dynamic file that likely we shouldn't cache
must merge with 
https://github.com/magfest/hotel/pull/50
https://github.com/magfest/tabletop/pull/7

optimization: move angular dynamically genereated javascript out of static_views

---

uber/templates/base.html

- this was originally added for browser compatibility, disabling the random hash so we can actually serve this from the cache
this is a pretty negligible optimization, it is just something that breaks caching and we're trying to serve all static content via nginx.

optimization: disable random hash for loading.gif

---

uber/custom_tags.py

- this is necessary if you're embedding popup_link inside javascript
- doesn't affect functionality of existing popup_links

escape quotes for popup_link

---

uber/config.py

part 2 of HARDCORE_OPTIMIZATIONS_ENABLED, similar to the other PR
- if your server is melting, you can enable this to disable automatic increase of badge prices based on # badges sold
- use only in extreme heavy load situations, and when you can keep an eye on your badge prices manually
- DONT USE UNLESS YOU REALLY KNOW WHAT YOU'RE DOING

optimization: add hardcore-mode optimizations to get_attendee_price()

---

uber/templates/base.html

- menu calls stuff like c.HAS_PEOPLE_ACCESS, each of which is a DB call and thus slower
- when we rip out the javascript rendering framework we have and replace with jinja2 and inheritance, this will all be gotten for free
for the record this is all horribly broken and I hate it, we shall fix with a vengeance once https://github.com/magfest/ubersystem/pull/1888 and subsequent re-integration from javascript back into server-side templates where this kind of thing belongs

optimization: don't render the menu in a few prereg pages

---

uber/utils.py

- using 2 groups and 1 attendee in the Charge(), speeds up baseline of 9.6seconds to 5seconds
very visible on the critical registration path of /preregistration/index which is where attendees pay, so we need to get this running faster

optimization: Charge class models generation, use a cache

---

uber/custom_tags.py

- if your server is melting, you can enable this to disable automatic increase of badge prices based on # badges sold
- use only in extreme heavy load situations, and when you can keep an eye on your badge prices manually
- DONT USE UNLESS YOU REALLY KNOW WHAT YOU'RE DOING
- also, added an unrelated regular optimize to cache the output of c.BADGES_SOLD which is an expensive DB call
needs more testing, and merge after the PR that enables c.HARDCORE_OPTIMIZATIONS_ENABLED

optimization: add hardcore-mode optimizations to badge price notices rendering

---

uber/server.py
uber/static/js/common-static.js
uber/templates/base.html
uber/templates/jobs/everywhere.html
uber/templates/jobs/signups.html
uber/templates/registration/shifts.html
uber/templates/static_views/ratings.js

take all truly static JS content and put it in common-static.js where it can be cached with nginx
other stuff:
- compute CSRF token inline now
- move all ratings stuff into its own file and only include it in the files that use it
needs a little more testing on the admin side, but prereg form appears to work.
REALLY MAKE SURE that CSRF_TOKEN is ok.
also, this just so happens to fix https://github.com/magfest/ubersystem/issues/1851

optimization: split up common.js so that we can do better caching

---

uber/common.py
uber/config.py
uber/decorators.py

We currently have two types of properties:
1) Regular old ``@property``.  These get invoked every time.
2) ``@cached_property`` which is invoked once and then never again for the lifetime of an object.
We found that we needed a third option, which is ``@request_cached_property``, which caches for the duration of a request.
I've added ``@request_cached_property`` to Sideboard, which means that https://github.com/magfest/sideboard/pull/20 MUST be merged BEFORE this is merged, or else this branch will be invalid.

optimization: Request cached property

---

uber/models.py

Is_dealer was always returning True, even when a group didn't have tables, because before they get saved to the DB they're '0' (a string). This also makes the assign_badges function add new badge cost to the group's cost.

Fix is_dealer and use new_badge_cost

---

uber/models.py

When we added get_real_badge_type, we put the badge type adjustment before the check for `is_dealer`. However, that check relies on the attendee's badge type being PSEUDO_DEALER_BADGE, so we were essentially making sure that people with dealer badges never got ribbons. This swaps those lines around, which fixes the unit test and should also fix the corresponding bug.

Assign dealer ribbons before adjusting badge type

---

uber/site_sections/preregistration.py

Fixes #1992.
I also did a search for anywhere else the `assign_badges` function is called, this is the only place where we're not actually changing the badge count for a group.

Stop charging for a new badge when a group badge is unset

---

uber/site_sections/summary.py

The shirt count report shouldn't crash if we have shirts in the system that don't quite match expectations. This works around that.

Get around bad data for shirt count

---

development-defaults.ini
uber/configspec.ini
uber/templates/preregistration/preregbase.html
uber/templates/regform.html

Fixes #2001.
Back when we had plain radio buttons for the 'kick in slider,' we added a DONATION_SLIDER_DISPLAY option to toggle between the radio buttons and the regular dropdown box. However, when we upgraded the kick-in slider to include descriptions and the like, we created a use-case where the slider could exist _but have no options in it_. In such a situation, the badge upgrade buttons would stop working and it wouldn't be clear why. This gets rid of the old variable in exchange for checking based on PREREG_DONATION_DESCRIPTIONS, which is required for the new slider to work anyway.

Use PREREG_DONATION_DESCRIPTIONS to turn on/off slider

---

uber/decorators.py
uber/server.py

- also, fix underlying render() issue where we were causing an exception in the exception handler if a template wasn't found
fixes #2003 
this is actually a pretty tiny detail, however, it'll do 2 things:
1) prevent our error reporting from tripping when googlebot repeatedly tries to re-index a non-existent template page and gets a 500 error response (not a 404)
2) make googlebot stop trying to read a non-existent page, over and over and over and over again :)

return 404 error when template not found in static_views

---

uber/templates/jobs/everywhere.html
uber/templates/jobs/signups.html
uber/templates/registration/shifts.html

This was broken in the optimizations and we didn't notice til now, using correct path

fix wrong include path for ratings.js

---

uber/tests/conftest.py

some properties of Config are cached the first time the thread uses them. 
this is great in web server context, it messes up unit tests though because they all run in one thread :)
unrelated fix: set hardcore_optimizations to false by default.  it's a sensible default, and we should write some tests that explicitly turn it on and make sure things still function well.

fix some unit tests by clearing thread-local cache each test

---

uber/server.py

"better" here meaning:
1) they can be more easily displayed by the OS 16 char limit
2) they show the word "mail" in them so we know these are email-related threads
requires https://github.com/magfest/sideboard/pull/22

override daemon thread names with better names

---

uber/decorators.py
uber/site_sections/accounts.py
uber/site_sections/signups.py
uber/templates/accounts/login.html
uber/templates/signups/login.html
uber/utils.py

If you are not logged in, then reach a page that requires a login, then login, you will be redirected to the original page.  Also does the same thing for the volunteer checklist.
This is a totally optional but really nice usability bonus.
fixes https://github.com/magfest/ubersystem/issues/1790
@earl7399 and @bds002 you guys will love this :)

make login page remember original URI request

---

uber/templates/index.html

Using magbot and some new scripts, it's now possible to deploy code to older ubersystem instances.
Look for the branches the start with ```__release__``` in each of our repos.  For instance, this one is against ```__release__mag85``` - NOT master.
This pull request is an example of making a change in an older ubersystem instance which we can then deploy.

test out a change to modify the magfest 8.5 deployment

---

uber/site_sections/devtools.py
uber/templates/devtools/dump_diagnostics.html

- show output from diagnostics output via webpage
- add some diagnostics output with info on c.BADGE_LOCK and db connection pools
merge after https://github.com/magfest/sideboard/pull/23
The output from this is super-cool and useful, it shows each thread.  Deadlocks should stand out like sore thumb now. Here's an example of the output of 2 threads (there are 100+ threads currently showing):
```
--------------------------------------------------------------------------
File: "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
self._bootstrap_inner()
File: "/home/vagrant/uber/sideboard/sideboard/lib/_threads.py", line 58, in _thread_name_insert
threading.Thread._bootstrap_inner_original(self)
File: "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File: …
```

add diagnostics web display

---

uber/tests/conftest.py
uber/tests/models/test_group.py

This unit test claims to want to test "after the printed badge deadline".  The code we're testing checks c.AFTER_PRINTED_BADGE_DEADLINE.
However, we were monkeypatching c.SHIFT_CUSTOM_BADGES (which is related, but separate).  Now we instead monkeypatch c.PRINTED_BADGE_DEADLINE such that c.AFTER_PRINTED_BADGE_DEADLINE is True.
I -think- this is the correct fix we want, but, @kitsuta if you can have a careful look here and make sure, that would be appreciated.

test correct deadline in group unit test

---

uber/tests/models/test_attendee.py

THIS ONE IS CORRECT, ANYTHING ELSE IS WRONG
I accidentally reverted this somehow in a bunch of merges.

re-un-re-un-revert unit test fix

---

uber/badge_funcs.py
uber/models.py
uber/tests/models/test_badge_funcs.py

replaces #2034 I think.  just got a little leery of the merge and wanted to view it here.
this means presave_adjustment()'s don't rely on 'session' existing
hotel unit tests don't have 'session' populated, so choke when they try and access it
this method doesn't need anything in Session, it was just a convenient place for it
only weird thing: I have to do some extremely bizzare 'import' stuff to get this to work for seemingly no reason. I have no idea why but I see it in other areas of the codebase too.

Fix hotel unit tests

---

uber/tests/conftest.py
uber/tests/models/test_badge_funcs.py

- override any real INI data for PRINTED_BADGE_DEADLINE
- we were running into issues where the real INI data would cause tests to fail
This is the final cleanup for unit tests! They should ALL PASS now!

fix unit test errors related to INI settings leaking into test env

---

requirements.txt

- this is an old version that conflicts with sideboard, and this one wins
- since sideboard is going to install this anyway, let's just remove it from here.  eventually may have to be added back in due to
the longer term solution if we want to keep this is probably to do something like pytest>=2.7.2, which if the other version is installed, will probably satisfy that requirement.  not sure, need to test.
eventually if we're running tests via Travis that involve just this repo and not with sideboard in the mix we may need to do this.

remove pytest from here

---

uber/models.py

We were having troubles at MAGLabs because any time you tried to save a group, as long as its 'badge type' was set to Staff, you'd get an error. This error now only triggers if you're actually trying to add Staff badges to the group.

Only complain about custom badges if adding group badges

---

uber/configspec.ini
uber/decorators.py
uber/site_sections/preregistration.py

still testing, basically this is for attendees visiting the main prereg page, they get directed to the kiosk form which is more at-event friendly and allows buying day passes online.

if onsite, redirect main prereg form to the at-door kiosk page

---

uber/decorators.py
uber/site_sections/preregistration.py

This lets us easily use config to allow people to access the pre-reg form during the event, should we so desire. It also removes the decorator in place of putting the redirect inside the page, since it's two lines of code that don't actually get used elsewhere.

Check if redirect_kiosk_url exists before using it

---

uber/templates/signups/onsite_jobs.html

Last MAGFest we realized onsite that it would be super-convenient if people could log in on their phones to sign up for new shifts onsite.  I threw together a quick page while people were waiting in line to make this happen.
I have no idea why I hard-coded the month to February when I went through the trouble to make everything else automatic, though I'm guessing it was from some quick copy/pasting or something.
Anyway, people logging in on their phones to take shifts are wondering why it says "Feb" for the month.

stopped hardcoding February

---

uber/models.py

Due to some pricing... issues... with MAGPrime, we are currently adding badge costs to groups even if auto_recalc is false. The most annoying side-effect of this is the 'free' groups are being charged for new badges - this stops that behavior.

Don't charge for new badges for free groups

---

uber/models.py

Reverts magfest/ubersystem#2057
It turns out that pre-registered groups start with a cost of 0, so this change prevented people from pre-registering in groups.

Revert "Don't charge for new badges for free groups"

---

uber/model_checks.py

Because we take input for affiliates and then add it to a JSONized list, but JSON dump only escapes quotes, users could run scripts on their Chrome browser. This is the emergency stop-gap solution, assuming there's a better one.

Fix Chrome vulnerability on the pre-reg page

---

uber/common.py
uber/custom_tags.py
uber/model_checks.py

This is a better fix than https://github.com/magfest/ubersystem/pull/2073, and addresses more vulnerability issues. Essentially, we were in some cases bypassing Django's default template safe-rendering, thus creating vulnerabilities.

Sanitize all relevant custom tags

---

uber/api.py

This PR adds the ability for API users to lookup shifts and assigned staffers based on department.  Planned use of this API by techops for dashboard and on-call functionality

Add Job/shift lookup to API

---

uber/templates/emails/shifts/created.txt

Removed the sentence about DH's not signing up for shifts, we still want them to sign up, so they can schedule themselves for breaks (scheduled time off).

removed DH reference

---

uber/site_sections/signups.py

I hotfixed this on the server since we just sent out like a thousand emails and didn't want people to run into this.
In the future we should probably make this more configurable, since whether or not an event asks about sandwich preferences probably shouldn't require a code change in the main repo.  I'm inclined to keep the database column around in the meantime since we might turn this back on for other events before we have a chance to make it more generic.
The diff looks a little weird because I removed a level of indentation (dedented?) but it was a very simple change.

removed sandwich preferences as a requirement, since we removed it from the form

---

uber/automated_emails.py
uber/configspec.ini

Uses a new email address for emails sent to Guests, since guests and panels are no longer one department.

Use guest_email for Guests instead of panels_email

---

uber/site_sections/preregistration.py

swallow all exceptions so we don't let exceptions in the email sending code (like DNS errors) cause attendees/groups to not be marked as paid. Fixes #2110

wrap prereg send_email() calls in exception handler

---

uber/badge_funcs.py
uber/site_sections/devtools.py
uber/templates/devtools/badge_number_consistency_check.html

this will check all badge numbers to make sure that:
1) there are no duplicate badge#s in the system
2) that all badge#'s fall within range
This is resurrected from magfest 8.5 code.  There is a second part I'm not including which also allows you to fix up the badge numbering code.  If we need that we can bring that back later.

add badge consistency checks to devtools

---

uber/decorators.py
uber/reports.py
uber/site_sections/summary.py

add crude duplicate badge number check to printed badge exports
- this won't catch every weird case but will catch the bulk of the issues we're seeing
tell CSV exports from multi-file zipfiles to not set headers from the CSV file itself
- this is important because if we're exporting multiple csv files, and the first one succeeds but a later one has an error, the user won't see the error's text because the headers were set to a CSV file.

Badge printer duplicate badge num check

---

uber/reports.py

Forgot, a bunch of our staff badges in groups have a None value for badge#
Which kind of begs the question.... is our CSV exporting a bunch of blank rows for these? Will check.

deal with None badge_nums

---

uber/badge_funcs.py

We want people to be able to claim unassigned badges even after we lock them down, so we want to assign numbers to them before the deadline.

Assign numbers to unassigned badges with a preassigned badge type

---

uber/templates/regform.html

We want to keep selling supporter badges after the hard deadline for Staff badge names, because the customized Supporter badges use a different manufacturing process. This let people change their badge name as long as they're not Staff (or another "Preassigned type").

Allow Supporter Deadline to work after Printed Badge Deadline

---

uber/model_checks.py

Right now people can change their badge name, and it's after the export has been sent to the printer. add a validation check that enforces not allowing this to happen.
There is a part 2 of this which is to fix the UX in a few places to grey it out, but this will at least ensure it can't happen, even if it would be better to indicate this through the UI in a greyed out box.
anyway das bad yo.  fix it bro. fix it good.  I hope no future employers of mine read my commit messages because that would be embarassing. hi.

enforce no changing of attendee printed badge name after deadline

---

uber/templates/accounts/sitemap.html

Makes sitemap a little more legible, and moves index to title

fix-#1859 Move Site Map index to section header

---

uber/automated_emails.py
uber/models.py
uber/site_sections/emails.py
uber/templates/emails/pending.html

There are two things for which we should definitely be using the new `ident` field for emails:
- Approving emails.  Right now, if you changed the email subject, the email would suddenly become unapproved.
- Looking up emails in `AutomatedEmail.instances`.  It's much more convenient to be able to look up the email by its slug than by its full subject.
This is a prerequisite for https://github.com/magfest/panels/pull/52 which relies on the second change being present.
This change is backwards-compatible, since all of our existing approvals are (as far as I can tell) for emails where the ident and subject are identical.
We'll want to make sure to test this on staging (with mailinator) before deploying to production.  Not because it's a huge change, but because our automated email code is so …

Use ident rather than subject for email approval

---

uber/decorators.py

I can't believe this works.
https://github.com/magfest/ubersystem/pull/2160 has merge conflicts because we reverted several of the commits in it. This PR lets us get around the merge conflicts by merging the fixed version of the branch to a reversion of the original revert. It makes for a bit of a messy commit stack but the workflow for resolving merge conflicts is almost always terrible.

Add fix for the revert of the revert of Invalid ID Decorator

---

uber/site_sections/summary.py

visit a URL like this:
/uber/summary/printed_badges_staff__expert_mode_only?start_badge=1&end_badge=1799
and it'll print out staff badges in that range. not the nicest easiest to use thing ever, but will get the job done for getting some extra badges done at the printers.

add (quickly) an "expert mode" staff badge export

---

uber/configspec.ini
uber/site_sections/summary.py
uber/templates/summary/shirt_manufacturing_counts.html

POLICY IMPLICATIONS NEED SANITY CHECKING ON THIS! CC @kitsuta @EliAndrewC  @ShevaDas 
for @bds002.  
There are 2 types of shirts now: (this is a change from previous years): 
- "staff shirts" - staff uniforms, each staff (someone who has an actual staff badge) gets TWO
- "swag shirts" - pre-ordered shirts, which the following groups receive:
- volunteers (non-staff who get a swag shirt for free)  (NOT someone with a staff badge)
- attendees (who get whatever they buy)
the new shirt manufacturing report shows:
1) count and sizes of staff shirts
2) count and sizes of swag pre-order shirts
this report will be given to the merch contractor (probably after we add some padding) so they know how many shirts to order
Whoever is doing this will need to pad out the number of shirts so there are …

add manufacturing-specific shirt report

---

uber/models.py

This was overlooked in https://github.com/magfest/ubersystem/pull/2109 -- we need to not set dealers' badge prices to the attendee badge price.

Make dealer badges cost the right amount

---

uber/models.py

In the future, we will want to have a @badge_cost_property so that we can affect attendee's badge_cost. For now, however, we only need to account for the age discount. It is subtracted from only a regular attendee price by design.

Include age discounts in badge_cost

---

uber/models.py

Simplifies the way groups work - they now simply use the attendee badge_cost. The attendee's badge_cost now includes any relevant discounts, including the group discount.

Calculate discounts as part of badge_cost

---

uber/sep_commands.py

we have some messed up badge#s in the system right now, and we're about to re-assign everyone.  this will start at the first badge# and re-assign all staff from there.
I believe it's OK to do it like this since everything is all saved at the end.  someone should probably double check me on this.  It worked on my box in the scenario we're in.

add resave_all_staffers which also re-assigns all the badge #'s

---

uber/models.py

This solves the second major unexpected functionality of groups, which is that new badge costs would always be added.

Only adjust group cost for new badges if auto_recalc is on

---

uber/models.py

We were accidentally subtracting a negative number, effectively adding the discount as if it were a cost. We also need to make it stop being a cost_property so it isn't applied twice.

Stop subtracting the age_discount

---

uber/tests/models/test_badge_funcs.py

- previously, we could have pre-assigned badge types without badge numbers
- now, we always require a badge# for them

fix unit tests to deal with new pre-assigned badge behavior

---

uber/model_checks.py
uber/models.py

Now that we often set the overridden_price to 0 through code, people were getting an error about setting it to 0 when they weren't actually doing so. This removes that error.

Stop throwing an error for overridden_price == 0

---

uber/models.py

Since groups now simply poll their attendees for their badge_cost, adding the `new_badge_cost` to the group's cost is unnecessary and may cause issues.

Stop adding new_badge_cost to new badges

---

uber/site_sections/jobs.py

Eli explained this problem to me at MAGCon.
`if params['id']` will throw an error if the key is not found.
`if params.get('id')` will return None if the key is not found. 
It'd be impossible for `if params['id'] == 'None'`to be true, because if id is not found it throws an error.
This _MAY_ possibly be an unwanted 'fix' if the user is meant to pass `'None'` and not meant to be passing nothing for the field.

fix a 'key error' by switching function to retrieve id

---

uber/templates/emails/shifts/schedule.html

The if statements should separate MAGFest Staff from MAGFest Attendee Volunteer and add in the language to remind Staff to pick up their t-shirt at the beginning of the event. 
Please verify the IF statements and {% if attendee.ribbon == c.VOLUNTEER_RIBBON) %}    
Staff Badges should get:
------------------------------
Thanks again for Staffing at {{ c.EVENT_NAME }}!
- Please remember to also pick up your TWO {{ c.EVENT_NAME }} Staff Shirts from the MAGFest MERCH Booth when you get to {{ c.EVENT_NAME }}  As a reminder, there is an expectation that you will wear one of these two shirts while working your scheduled shifts during {{ c.EVENT_NAME }}, (Thurs-Sunday, not during load-in or load-out).  When not on shift, you should wear a different shirt, so you can enjoy MAGFest 2017 with …

Schedule email now reflects Staff or Volunteer

---

uber/templates/emails/shifts/schedule.html

This would have likely errored out the template, so we definitely need to remove it.

Remove typo from if check

---

uber/models.py
uber/site_sections/preregistration.py

The way we calculated group.amount_extra was based on the old costs of attendees who were paid by group. This updates it so it's more accurately the amount_extra.

Fix calculation of group.amount_extra

---

uber/site_sections/preregistration.py

For some reason we were using a different way of calculating group payment after a group registers. This also fixes that way.

Fix group payment AFTER group registration

---

uber/decorators.py

fixes issue #2204 by checking that the length of the parameters of a CSV function is exactly three. The decorator by default should supply 'self' 'out' and 'session'. Tested on local box.

check that CSV has standard parameters, or it will hide from site-map.

---

uber/utils.py

Recently we've been seeing a concerning amount of errors from Stripe for an InvalidRequestError, specifically that we are missing a Source object for our parameter. [See API here.](https://stripe.com/docs/api/python#update_customer-source) To try and provide us more information on this error I have replicated a send_email function found in `decorators.py` under `def credit_card`. Try as I might I was unable to replicate this error on my own, but in brighter news I also had a hard time triggering any other new errors in my attempts.

Email code team when InvalidRequestError occurs from Stripe

---

uber/decorators.py
uber/server.py
uber/utils.py

trying to catch some issues happening in here that are masked by our currently user-friendly handling of Stripe exceptions
this will print the usual stuff when we get an exception - request params, session, etc

add verbose exception logging to all Stripe exception handling

---

uber/templates/preregistration/group_members.html

Fixes https://github.com/magfest/magfest/issues/8. We added a warning recently for unsetting group members, but the JS I added ended up selecting a random group member to unset. Oops.

Stop unsetting random group members

---

uber/custom_tags.py

nobr is not standard html and labels let you click the label to check the box. 
This has caused the interest in prereg to become bold as it is now picking up a bootstrap style.
Fixes https://github.com/magfest/ubersystem/issues/2243.

Make checkgroup use labels

---

uber/tests/models/test_attendee.py
uber/tests/models/test_config.py

Fixes https://github.com/magfest/ubersystem/issues/2225. I had changed the way group pricing and discounts worked, but failed to update the unit tests to match. This is me catching up.
Specifically, paid_by_group badges are no longer set to $0 owed, and overridden_price now overrides age-based discounts.

Update price-based unit tests to reflect changed functionality

---

uber/config.py
uber/templates/preregistration/preregbase.html
uber/templates/regform.html

Fixes https://github.com/magfest/ubersystem/issues/2224 and fixes https://github.com/magfest/ubersystem/issues/2210 so that shirt_deadline is actually meaningful. Also adds shirt_count so it mirrors the way the supporter count works. Slightly tweaks the kick-in display so that it will be hidden for attendees who have not already kicked in if there's only one option (because that option is always 'no thanks').

Hide shirt levels after shirt_deadline to fix at-door kickin display

---

uber/models.py
uber/site_sections/registration.py

Fixes https://github.com/magfest/ubersystem/issues/2207 and sets need_not_pay based on badge cost, not just overridden_price, so that we can then fix https://github.com/magfest/ubersystem/issues/2233 by checking for anything that is not "NOT_PAID" and redirect away from the Stripe form.

Allow children to register at-door without entering CC info

---

uber/site_sections/preregistration.py
uber/templates/preregistration/index.html

Currently, when an attendee's cart has a total cost of ZERO they are required to still put in their credit card information, and after doing so the page then returns that they have free badges and have not been charged. BUT, we never actually run the code to add them to the database, a line of code under preregistration/prereg_payment will return to the index before we ever get the chance. 
This should fix that.

Fix Error of Being Unable to Register Child Badges

---

uber/templates/emails/shifts/reminder.txt

Emailed Code about this - but this email was linked to uber_takedown variable, which is set to be the middle of the event. 
I think that's old code related to when Uber was taken offline during load-in.
I have updated the link here to be Event Epoch (Start).
This makes it so volunteers can't change their schedule at event, but must have a DH/Staff Ops change the schedule, so the departments are aware of changes.

Updated closing date.

---

uber/custom_tags.py
uber/templates/groups/form.html

This pull request will fix #2215 by adding a column with the weighted hours of each attendee, as well as add a new django tag `sum` usable like so `attendees|sum:'weighted_hours'`

Let Uber Admins See Group Weighted Hours

---

uber/config.py

Fixes https://github.com/magfest/ubersystem/issues/2235. Also moves around the badges_sold calculation so we only poll the DB if we need to.

Always return date-based badge price if it's between epoch and eschaton

---

uber/site_sections/accounts.py
uber/templates/accounts/index.html

After the event ends, we have generally been removing the amazon SES credentials to make sure older instances, if they ever go haywire, don't email all our people.
This creates a problem in that the 'forgot my password' link no longer sends an email.
This PR addresses this by allowing the password setting overrides that normally only work in AT_THE_CON mode to now work in normal mode.
This allows an admin to do a password reset by deleting and then re-creating someone's account
- not great UX but does allow a solution
- will need to backport this fix into older ubers

allow setting a custom password in post-con mode

---

uber/site_sections/accounts.py
uber/site_sections/signups.py
uber/utils.py

this is a security issue where an attacker could craft a url that after logging in redirects users to an external website

reject cross-domain redirects on login page

---

uber/custom_tags.py

Chaney added this:
This adds support to add in a css ID that Materialize (a CSS framework) needs.
It takes the name of the ID from the checkbox name, which should, in normal sane situations, always be unique.

Add ability to specify css ID for single checkbox

---

uber/models.py
uber/templates/registration/form.html

A slight oversight in the way we set up badge_cost for groups meant that if a staff was paid_by_group, they'd be treated as a regular attendee. Our overridden_price setting also was not respecting an overridden price of $0. This fixes both those problems.

Stop charging staff badges in groups

---

uber/config.py

In a previous PR (https://github.com/magfest/ubersystem/pull/2246) we accidentally reversed the functionality of our bucket-based pricing -- it was only being calculated for existing badges or when hardcore_optimizations was turned on. This is the real problem behind https://github.com/magfest/ubersystem/issues/2262. This fixes that.

Actually skip bucket-based pricing when appropriate

---

requirements.txt
uber/automated_emails.py
uber/common.py
uber/config.py
uber/configspec.ini
uber/site_sections/preregistration.py
uber/site_sections/registration.py
uber/templates/emails/reg_workflow/attendee_qrcode.html
uber/templates/preregistration/confirm.html
uber/templates/registration/index_base.html
uber/utils.py

Fixes #2107.
Currently, this feature branch Works. It:
1. Encrypts attendee's UUIDs and displays an Aztec QR code on their confirmation page
2. Takes a QR code via a modal pop-up, decrypts it, then automatically searches for the decrypted UUID.
There's a few problems with this as it stands.
1. ~There's no emails generated or sent. Sending an automated email will be pretty simple, but it will access our server to display the QR code when people view the email, which is not necessarily ideal. However, some folks have pointed out that email clients frequently cache images, so this may be fine.~ The email now exists -- we'll need to see what kind of performance hit it entails.
2. ~Encryption and decryption are Slow. This is the fault of the encryption library I chose. They explain the …

Implement QR Codes for Check-In

---

uber/templates/emails/reg_workflow/attendee_qrcode.html

The email looks kind of dumb otherwise.

Add line breaks between image and text for QR code email

---

uber/models.py
uber/tests/models/test_group.py

Now when we save a group, it'll cascade down to mark the attendees as having the correct badge status by running the standard presave-adjustments on those attendees if the group is all paid up.

fixes #2074

---

uber/models.py

We are using this property to send emails out for QR codes, which are currently being sent to unpaid vendors. We need to... not.

Stop counting New badges as ready to check in

---

uber/config.py

I explain this in https://github.com/magfest/ubersystem/pull/2246/files#r94468080 but there was a bug which would cause us to use the Thursday price instead of the current day's price when onsite.

fixed bug in on-site pricing

---

uber/templates/base.html

To be merged with PR in Panels, not yet made, that moves guidebook redirect to schedule/redirect, and lets schedule/index be viewable again by internal staff. I had a staffer bring up to me that they found it useful, and quick to load as our website isn't filled with ads or tracking. I was unaware we essentially removed the old schedule by blocking all access to it.

Add Internal and External Schedules To Uber Navbar

---

uber/automated_emails.py
uber/tests/email/test_automated_email_categories.py
uber/tests/email/test_automated_email_job.py

This allow us to mark specific emails as being sendable while on-site.  Currently the only email we've marked this way is the one which confirms that an attendee has paid for their badge, which the regdesk department has asked us to turn on while on-site so that they don't have to answer emails about why people didn't get a confirmation email, etc.

specific emails may now be enabled onsite

---

uber/models.py
uber/templates/registration/index_base.html

If you chose "show all badges" and THEN searched for a badge, you'd only get valid badges because we weren't passing the 'invalid' parameter in the search form. This has been annoying reg staff for a while.
Also includes the changes from https://github.com/magfest/ubersystem/pull/2283 cause I dun goofed.

Include invalid parameter in Attendee search

---

uber/server.py

fixes #2285 
we're not fixing the specific broken email code, rather, we're making this javascript more resilient to config settings that might be invalid at certain times (like, in c.AT_THE_CON mode)

handle exceptions occuring in config generation for magfest.js file

---

uber/models.py
uber/site_sections/registration.py
uber/site_sections/summary.py
uber/templates/regform.html
uber/templates/summary/shirt_manufacturing_counts.html
uber/tests/models/test_attendee.py
uber/tests/models/test_merch.py

This implements the logic which @nickthenewbie1 has requested:
- People with staff badges get a configurable number of staff shirts.
- People with volunteer ribbons get a single swag shirt (not a staff shirt).
- People who pay for a shirt get the shirt they paid for.
I added a ton of unit tests for all of this and also fixed the manufacturing reports.
fixes https://github.com/magfest/magprime/issues/188

Shirt model updates

---

uber/site_sections/registration.py

Reg had a problem checking in someone even though she'd paid for her own badge (c.HAS_PAID) because she had been put into a group and they hadn't paid for their badges. This prevents that situation.

Allow attendees in unpaid groups to check-in if they are paid

---

uber/site_sections/preregistration.py

This was a change I had made earlier that I forgot to remove when I fixed group pricing -- the end result is that the group's cost would keep going down but their badge number would stay the same. Oops.
Also transfers the badge's type and ribbon to the new unassigned badge.

Stop reducing group prices when badges are dropped

---

uber/models.py
uber/site_sections/registration.py

The bug was that when someone from a group checked in, we were *always* matching them to an unassigned group badge even when they already existed in the group and weren't trying to claim an unassigned group badge for that group.
We'll go in and fix the database after this is deployed.

Unassigned groups badges were getting erroneously deleted

---

uber/site_sections/signups.py

Stops has an onsite workflow wherein someone shows up and says, "I'd like to volunteer" and then we have them log into the signups page on their smartphone and take any non-restricted shifts from any department.
However, in order to support this we need to allow people to log in without even being assigned to any departments.

fixed onsite volunteer logins

---

uber/site_sections/registration.py
uber/templates/registration/form.html

Fixes https://github.com/magfest/ubersystem/issues/2294. The "Save" button will always stay on the attendee page, and the "Save + return" button will use return_to if it exists.
I couldn't test this because my development environment is messed up.

Stop redirecting on click 'Save' for attendees

---

uber/site_sections/registration.py

Fixes #1677, which was that the "shifts" page didn't allow editing invalid badges.
The chart of reg methods are below. "Yes" means invalid badges are allowed, "no" is not allowed. The ones with the arrows are changes in this PR.
```
yes change_badge
yes history
yes watchlist
yes delete
no  record_mpoint_cashout
no  record_old_mpoint_exchange
no  check_in_form
yes check_in
no  undo_checkin -> yes
no  lost_badge -> yes
no  give_merch
no  take_back_merch -> yes
no  register
no  pay
no  mark_as_paid
no  manual_reg_charge_form
yes new_checkin
no  undo_new_checkin -> yes
no  shifts -> yes
no  update_nonshift -> yes
no  update_notes -> yes
no  discount
```

Allow more reg tasks to be done on invalid badges

---

uber/templates/registration/form.html

"Unassign", the old wording, was incorrect.
Fixes #2309
Ping @ShevaDas to make sure the wording on the "are you sure about this" is correct.

Change delete group member button to read "delete"

---

requirements.txt
uber/automated_emails.py
uber/common.py
uber/config.py
uber/configspec.ini
uber/models.py
uber/site_sections/registration.py
uber/templates/emails/reg_workflow/attendee_qrcode.html
uber/templates/preregistration/confirm.html
uber/utils.py

Fixes https://github.com/magfest/ubersystem/issues/2343 by adding a new UUID used only for search. Changes the check-in barcodes to use that UUID, preventing all security issues with using the primary key id. Also removes the encryption that is no longer needed.

Add unique 'search key' for attendees and groups

---

uber/models.py

This prevents badges being assigned duplicate numbers at the database level. Fixes #1637. Fully tested.

Add semi-unique constraint on badge numbers

---

uber/templates/emails/reg_workflow/reg_notes.html

Fixes https://github.com/magfest/ubersystem/issues/2276 by making the block about volunteering show only if the attendee receiving the email does not have any assigned departments. This should allow us to include reg_notes in any email without showing this message out of context.

Make reg_notes more universal

---

uber/models.py
uber/tests/models/test_attendee.py

Fixes #2200. This is a rare use-case but an easy fix.

Stop forcing department heads to be trusted in all their departments.

---

uber/templates/regform.html

Addresses a comment made in https://github.com/magfest/ubersystem/issues/970 where attendees being able to 'unvolunteer' is undesirable while at-the-con. Instructs attendees to either drop their shifts explicitly, contact their dept head to drop their shifts, or see staffing ops based on if we're at-the-con and if the attendee has shifts. Also tries to address wording around the 'volunteering' checkbox so contracted staff are less likely to get confused (https://github.com/magfest/ubersystem/issues/2050).

Prevent attendees from unvolunteering in some cases

---

uber/templates/regform.html

An if statement in the regform template would always evaluate to false unless an attendee already had a kick-in. Looks like it was a typo that was just never caught. Fixes https://github.com/magfest/ubersystem/issues/2374.

Fix attendee-facing kick-in levels

---

uber/templates/accounts/index.html
uber/templates/groups/index.html

There were two extra closing </div> tags in the groups and accounts templates that were absolutely KILLING me!
In the long term I'd like to introduce some template style guides and automated HTML template linting (if that's even possible) to hopefully prevent things like this in the future.

Removes two extraneous </div> tags from groups and accounts templates

---

uber/decorators.py
uber/utils.py

Should catch the missing CSRF_Token error that keeps popping up in devbot-errors. Needs to have #2165 merged before this can be merged. Tested by deleting the CSRF input element from registration/form

Catch Missing CSRF_Token.

---

uber/model_checks.py
uber/models.py
uber/site_sections/preregistration.py
uber/templates/regform.html
uber/templates/registration/discount.html
uber/templates/registration/index_base.html
uber/templates/static_views/legal_name.html

Fixes #1894
This might need some review, but I've tested it manually a fair amount and it doesn't break much, and I think most of the review items are part of larger issues that shouldn't be tackled with this one (e.g. discount.html).
This *does* require a database schema change, however (addition of the `legal_name` column)
---
The basic overview of this change is that it adds a `legal_name` override in attendees, which is nullable and falls back to first_name+last_name if null, but can be used to add a separate legal_name. Hotel export and other plugins should be updated accordingly.
Search also displays both preferred and legal name (as well as searching both names). An example is in this image:

Implement separate preferred/legal names

---

uber/model_checks.py
uber/models.py
uber/site_sections/summary.py
uber/templates/groups/form.html

Fixes https://github.com/magfest/ubersystem/issues/1509 by letting admins mark down how much a group itself was refunded. This bypasses a lot of workflow issues with refunding group payments. Also fixes https://github.com/magfest/ubersystem/issues/1799 by modifying the output of volunteers_owed_refunds accordingly.

Add amount_refunded to groups

---

uber/automated_emails.py
uber/tests/email/test_automated_email_categories.py

Though the tests are currently broken, I have locally verified that the tests run correctly with the changes from #2360.
NOTE: Due to this change, every other plugin that sends automated emails must be updated to include a static ident.

Fixes #2383: Adds static ident to every automated email

---

uber/model_checks.py

It's unclear how this wasn't caught in the first place, but this model check was always returning an error even when inappropriate.

Fix group amount_refunded model check

---

uber/templates/regform.html

This was actually part of https://github.com/magfest/magclassic/issues/67 -- the Javascript on the confirmation page broke because we don't let people edit their name there, which then caused our amount_extra hiding script in the magclassic repo to stop working. The legal_name Javascript now checks to make sure the field exists.

Prevent JS error caused by new legal_name code

---

uber/models.py
uber/site_sections/registration.py
uber/tests/models/test_attendee.py

Fixes https://github.com/magfest/magclassic/issues/52. When we changed the way group prices worked, we started inspecting attendees' status for their price instead of the group's status. This definition wasn't broad enough for dealers, who could be in a 'dealer' group but not have a Shopkeep ribbon. This fixes that, and changes our dealer ribbon auto-assignment so it doesn't override admin choices by accident now that we've broadened this definition. It also auto-assigns Shopkeep ribbons to replacement attendees when you 'unassign' an attendee, which is the bug that revealed this problem.

Expand definition of 'dealer' for the purpose of badge prices

---

uber/custom_tags.py
uber/decorators.py
uber/site_sections/emails.py
uber/tests/test_custom_tags.py

Fixes #2404
Adds empty datetime check to filters. Also utf-8 decodes email example before passing to template.

Fixes #2404: Adds empty datetime check to filters

---

uber/__init__.py
uber/tests/test_sideboard_serializer.py

Fixes #2421. We were attempting to JSON serialize `decimal.Decimal` types, but we had not registered an appropriate serialization handler.
This change *could* have been made in the sideboard project. I chose to make the change in uber, because there are different approaches to serializing `decimal.Decimal`s, and I didn't want to enforce one method over the other in the base sideboard project.

Fixes #2421: Registers Decimal type as json serializable in sideboard

---

uber/templates/registration/index_base.html

This was an oversight in https://github.com/magfest/ubersystem/pull/2344 -- we removed the `qr_code_reader` function that this button depends on, but not the button itself. Trying to use this button would result in an error.
Since #2344 lets you scan the check-in barcode directly into the searchbox, we don't need the button anymore.

Remove nonfunctional "Scan 2D Barcode" button

---

uber/custom_tags.py
uber/tests/test_custom_tags.py

This pull request adds a new `timedelta()` Jinja filter, allowing `datetime()` addition and subtraction in our Jinja templates. This is required to fix https://github.com/magfest/magprime/issues/185.

 Adds new timedelta filter required by #185 in the magprime repo

---

uber/templates/regform.html

Fixes https://github.com/magfest/magclassic/issues/70
Supporter options now look like this:

Fixes magclassic #70: Minor css tweaks to improve supporter options

---

uber/config.py
uber/models.py
uber/site_sections/preregistration.py
uber/templates/signups/printable_schedule.html
uber/templates/static_views/howToStaff.html
uber/templates/static_views/stafferComps.html

Adds a new STAFF_GETS_FOOD option that checks if there is a department named staff_suite -- if not, we count food restrictions as 'filled out' for the purposes of showing volunteer checklist steps, and we remove references to free food elsewhere. Part of the fix for https://github.com/magfest/magclassic/issues/64.

Don't refer to staff food if there is no staff suite

---

uber/configspec.ini

remove stripe keys and some magfest-specific settings in configspec.ini
These aren't particularly sensitive but, probably don't belong here.  In particular, magfest's stripe key (which is not a big deal because it's a test key so it can't any financial harm), but could be used for a denial of service attack or something.   Also, we're about to rotate it so it is going to be invalid anyway

remove some secrets

---

development-defaults.ini

We already defined these dates in configspec.ini and set default values when needed. Doing it again in development-defaults is confusing.

Stop redefining dates in development-defaults

---

uber/tests/README.md

I was confused by where to run `tox` from, so I updated the README to specify the location (the root dir of your plugin folder). Also added formatting.

Update testing README to specify where to run tox

---

uber/decorators.py
uber/site_sections/emails.py
uber/templates/emails/pending_examples.html
uber/tests/test_templates.py

implements the same goal of #2384 
A decorator function was added to return a template's html without rendering it.
The pending examples page was edited.
The emails.py function was modified.

Show an example of an email if there are none pending

---

uber/model_checks.py
uber/models.py
uber/tests/models/test_attendee.py

This was tripping a lot of people up, so we now simply set the legal_name to an empty string if it matches. Partly addresses https://github.com/magfest/ubersystem/issues/2454.

Remove validation for legal_name matching full_name

---

uber/models.py
uber/tests/__init__.py

Fixes https://github.com/magfest/magstock/issues/119
SQLite doesn't support `ALTER` statements, so the way alembic handles table migrations in SQLite is to:
1. create a temporary table with the new schema
2. copy the data from the original table to the temporary table
3. drop the original table
4. rename the temporary table to the original table name
Because of this, it doesn't matter if the implicit check constraints for Boolean columns have names, and alembic seems incapable of correctly generating the check constraint names for the new table, so we just don't even bother naming them if we're using SQLite.
Phew!

Fixes magstock #119: Leaves check constraints unnamed in SQLite

---

uber/templates/regform.html

Fixes https://github.com/magfest/ubersystem/issues/2454. Admins creating placeholder attendees may get their names wrong, so we allow them to edit it before confirming their badge. Also added a way to show confirmed attendees what their legal_name actually is.

Allow placeholder attendees to edit their names

---

uber/models.py
uber/tests/models/test_badge_funcs.py

Fixes https://github.com/magfest/ubersystem/issues/2436. Also fixes a unique badge constraint error that would come up if a badge of a different type had a number in the same range -- there's no need to filter by badge type since we explicitly don't support the use case of having, e.g., 'staff 1' and 'attendee 1'.

Fix unique badge constraint errors in two cases

---

uber/decorators.py

There was a error during the great jinja merge, and inside `decorators.py` the `renderable()` function was defined twice, with the old wrong version defined after the new correct version.
This is one reason why I prefer flake8 over pep8, because flake8 catches this kind of thing. But there's no way were getting flake8 to run against this codebase anytime soon.

Fixes renderable decorator merge error (renderable defined twice)

---

requirements_test.txt
uber/common.py

Because the test requirements were removed from sideboard in magfest/sideboard/pull/82, the following line breaks in uber/common.py:
```
from uber.tests import import_test_data
```
```
[localhost] run: /home/vagrant/uber/sideboard/env/bin/sep alembic current
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/home/vagrant/uber/sideboard/env/bin/sep", line 11, in <module>
[localhost] out:     load_entry_point('sideboard', 'console_scripts', 'sep')()
[localhost] out:   File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
[localhost] out:     return get_distribution(dist).load_entry_point(group, name)
[localhost] out:   File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/pkg_resour …
```

Removes test imports from common.py

---

alembic/README.md
uber/tests/README.md

Following the Alembic instructions resulted in an error because we always have multiple plugins installed. Additionally, we found that updating Sideboard could cause local unit tests to start failing. This updates the relevant docs in both cases to be more helpful.

Update test and alembic instructions

---

uber/badge_funcs.py
uber/models.py
uber/site_sections/registration.py
uber/tests/models/test_badge_funcs.py

Fixes https://github.com/magfest/ubersystem/issues/2472. We were calling shift_badges during a presave adjustment in certain cases; however, this would 'stack' with the update_badge function and badge numbers would get shifted twice, resulting in a unique-constraint violation. This fixes that. Also removes the change_badge function, which was somehow left in after being fully replaced by the update_badge function.

Stop shifting badges twice in a row

---

uber/templates/emails/reg_workflow/reg_notes.html

Fixes https://github.com/magfest/ubersystem/issues/2493. During testing, MFF found that confirmation emails were not actually including the consent form link for attendees under 18. It turned out to be because we had the syntax wrong for checking whether the attendee's age group needed a consent form. This fixes that.

Fix emails never including a link to the consent form

---

uber/custom_tags.py
uber/tests/test_custom_tags.py

Fixes this error I just ran into:
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 239, in with_timing
return func(*args, **kwargs)
File …
```

Fixes 500 error when jinja attempts to serialize an undefined value

---

uber/templates/regform.html

Staff always get a shirt, but they weren't able to change their shirt size if an event had no donation opts available. This was particularly affecting Magstock, so it needs to be a quick-ish fix.

Stop hiding shirt size box if there are no prereg_donation_opts

---

uber/site_sections/summary.py

Shirt reports on old instances were giving a 500 error because they were working with huge timedeltas that they were never intended to use. We now cap the calculations at c.ESCHATON so the weekly array doesn't break.

Make shirt reports future-proof

---

uber/model_checks.py
uber/models.py
uber/site_sections/accounts.py
uber/utils.py

Fixes https://github.com/magfest/ubersystem/issues/2392. We don't need to normalize the left side of emails, so now we just don't. We DO normalize the domain, so we now also normalize it when someone is trying to log in -- that way we can be sure we don't introduce mismatches.

Stop normalizing the left side of email addresses.

---

uber/templates/registration/index_base.html
uber/templates/registration/new_base.html

Fixes https://github.com/magfest/ubersystem/issues/2527 and fixes https://github.com/magfest/ubersystem/issues/2528. Also fixes a minor display error for checked in time -- it was displaying as 'fA D' for all attendees.

Fix Jinja2 template errors for at-door workflow

---

uber/templates/regform.html

Fixes https://github.com/MidwestFurryFandom/rams/issues/144. We had `or` in this tag so it would always show the hidden input on any non-admin page. Whoops.

Stop showing badge_type on non-admin pages

---

uber/models.py
uber/tests/models/test_watchlist.py

This pull request contains the work I originally did in this insanely messed up branch: https://github.com/magfest/ubersystem/pull/1883
All I did was rewrite the query in `SessionMixin.guess_attendee_watchentry()` and add some tests.
This fixes #1882.

Fixes #1882: Fixes guess_attendee_watchentry query

---

uber/templates/regform.html

Reverts magfest/ubersystem#2532
This change is breaking preregistration for all our sites, see: https://github.com/magfest/ubersystem/issues/2538

Revert "Stop showing badge_type on non-admin pages"

---

uber/tests/models/test_watchlist.py

we checked in a fix to https://github.com/magfest/ubersystem/issues/2536
here:
https://github.com/magfest/ubersystem/commit/0aa82128c7b49fa7de12b12f9bb110c36e4fbbe9
the (stopgap, temporary) solution was to move dateparser import out of common.py and into the modules actually using it.  while not ideal, this unbreaks pycharm debugger users and fixes #2536 
that fix was accidentally checked into master, and this is a followup which fixes the unit tests

import dateparser here to fix unit test runs

---

uber/templates/regform.html

Emergency fix where we comment out the relevant block. I also changed it to `readonly`, the correct property, for when/if we want to re-enable this functionality.

Don't disable the staffing checkbox while at the con

---

uber/custom_tags.py
uber/tests/test_custom_tags.py

Required for https://github.com/magfest/bands/pull/70. Adds a handy filter that allows you to turn any URL into an HTML link, with custom text.

Add custom `url_to_link` filter

---

uber/configspec.ini

Fixes https://github.com/magfest/ubersystem/issues/2487 -- now events will not be surprised by check-in codes appearing on attendees' confirmation pages.

Turn check-in barcodes off by default

---

uber/models.py
uber/templates/registration/form.html

Fixes https://github.com/magfest/ubersystem/issues/2507 by printing attendee.merch on their details page, above their shirt size, along with info on if they have picked up their merch. Also fixes a bug where an attendee's shirt size would only display if they kicked in for a shirt.

Add "Merch Owed" to Attendee Details page

---

uber/templates/emails/dealers/waitlist_closed.txt

We had several templates with no reference to them in code. We also had a dealer email that was coded for conditions that would not ever be met -- clearly meant as a one-time automated email. Fixes https://github.com/magfest/ubersystem/issues/2106.

Remove unused email templates and emails

---

uber/templates/macros.html

Fixes https://github.com/magfest/magprime/issues/200. When we converted our Django templates to Jinja2 templates, we took out a function from the popup macro that turned `'`s into `&quot;`s. We weren't sure if we needed it, but it turns out we do -- it's the only way to properly escape quotes when including the macro inside a quoted element, as in https://github.com/magfest/magprime/issues/200. We also needed to switch the `"`s to `'`s in our magprime template to complete the fix.

Escape single-quotes in pop-up macro to fix JS error

---

uber/templates/regform.html

Fixes https://github.com/magfest/ubersystem/issues/1632 and fixes https://github.com/magfest/ubersystem/issues/2021, which were caused by the same bug. The select2 box is apparently special and needs to have the 'change' event manually triggered when you update the value.
Fix courtesy of https://stackoverflow.com/questions/14957419/select2-doesnt-show-selected-value.

Show selected option for affiliates on page load

---

requirements.txt
uber/common.py
uber/models.py
uber/tests/models/test_watchlist.py

`dateutil` is actually the library that `dateparser` wraps. Hopefully this will fix our weird PyCharm import issues.

Fixes #2536: Removes dateparser in favor of dateutil

---

uber/automated_emails_server.py
uber/configspec.ini
uber/templates/emails/daily_checks/pending_emails.html

This is a new daily report sent to STOPs that highlights which email categories require approval to send. We often fail to remember to check on this often enough resulting in emails that go out a few days or weeks after the deadline.  This will help avoid that issue going forward.
If the volume of emails gets too crazy, it can be turned off via a config option.  I also structured this so the meat of the report functionality is in its own function, so it can be exposed via the API for other uses like Slack notifications
this is mostly what was talked about in https://github.com/magfest/ubersystem/issues/2431 except Vicki had some further suggestions we might want to implement.  For right now, I really wanted to get the basic version done sooner than later with so many events and so many …

Add pending email report

---

uber/automated_emails.py

Changes to days_before(28, c.FINAL_EMAIL_DEADLINE).
I chose to expand the total date range here, instead of changing `c.FINAL_EMAIL_DEADLINE` in the config because I didn't want to impact other things that may depend on it.
See also: https://github.com/magfest/production-config/pull/229

Fixes #2624: Extends allowed date range for volunteer still interested email

---

uber/site_sections/preregistration.py

Hotel space is often a critical requirement for dealers, and it's entirely possible that we won't open dealer applications until AFTER the hotel booking request deadline passes. This change ensures that dealers who apply during the window AFTER the hotel booking request deadline but BEFORE the hotel email is sent will still receive the emailed link when it goes out.

Per marketplace's request, dealer applications will ALWAYS be marked as requested hotel booking info

---

uber/templates/regform.html

The fix for this was to turn off jquery validation on the admin area. Falls back to HTML5 validation + server side validation the way it used to work.

Fixes admin reg form delete button

---

alembic/versions/b6074f8ea4ab_add_base_badge_price_column.py
uber/models.py
uber/site_sections/preregistration.py
uber/templates/registration/form.html
uber/tests/models/test_attendee.py

Fixes https://github.com/magfest/ubersystem/issues/2587 by adding a new column to the attendee table and slightly reorganizing how badge prices are calculated.

Add 'base_badge_price' to save attendee badge prices

---

uber/automated_emails_server.py
uber/models.py
uber/site_sections/emails.py
uber/site_sections/groups.py
uber/templates/base.html
uber/templates/emails/index.html
uber/templates/emails/sent.html
uber/templates/groups/history.html
uber/templates/registration/history.html
uber/tests/email/email_fixtures.py
uber/tests/models/test_email.py
uber/tests/site_sections/test_emails.py

Fixes https://github.com/magfest/ubersystem/issues/2104 by adding a "resend email" button to every automated email listed in an attendee's history page.
This has been manually tested and works like a charm; however, there's still some things missing:
See below:

Add resend email buttons in attendee history pages

---

uber/sep_commands.py

Some DB migration code I wrote a while back broke a few `sep` commands, because they were expecting the DB Session to already be initialized.

Adds db session initialization to sep commands

---

uber/model_checks.py

Stripe literally cannot charge an attendee more than eight digits ($999,999.99). Fixes https://github.com/magfest/ubersystem/issues/2257 by preventing attendees from registering a badge with a total_cost more than $999,999.

Prevent attendees from trying to pay over $999,999

---

uber/site_sections/preregistration.py
uber/templates/preregistration/attendee_donation_form.html
uber/templates/preregistration/preregbase.html

Fixes https://github.com/magfest/ubersystem/issues/2433 by triggering togglePrices(); AFTER the badge_types area has been built, without depending on a click event that doesn't happen on some pages. Also tweaks when prices for the base badge are displayed, effectively turning it off for new group members (because they don't pay any money for their badge, so it's confusing to show them their badge's price) and anyone without a badge cost.

Show prices on pages without a REG_TYPES area

---

uber/models.py
uber/site_sections/preregistration.py
uber/tests/conftest.py
uber/tests/models/test_badge_funcs.py
uber/tests/site_sections/test_preregistration.py

Fixes #2675, also fixes #2703 (GET TO DA BADGE NUMBA!)
* Fixes NULL SQL conditional in `shift_badges`
* Fixes register_group_member by using existing unassigned badge instead of deleting it
* Removes many redundant SQL queries from badge shifting code
* Improves performance of certain SQL queries in badge shifting code

Fixes register_group_member by using existing unassigned badge instead of deleting it

---

uber/templates/macros.html

`os.path.basename("/url/with/trailing/slash/")` evaluates to an empty string `""`.
`"" in "any string"` will always evaluate to `True`.
Thus `os.path.basename("/url/with/trailing/slash/") in "paid_preregistrations"` will always be true, so the wizard used to think any url with a trailing slash was actually the "paid_preregistrations" page.

Changes prereg wizard url indexes to use tuples instead of strings

---

uber/custom_tags.py
uber/tests/test_custom_tags.py

Was blowing up on watchlist import, because the watchlist class doesn't have a `name` attribute.

Fixes form_link tag used by import results template

---

uber/config.py
uber/tests/models/test_config.py

Fixes https://github.com/magfest/ubersystem/issues/2591. We add the property to the core system because it can be useful, but it's a pretty specific use-case so we only print it in SuperMAG's registration template.
I'm currently debating whether or not the limits/wording should be a dictionary in config or if it's not really worth it.

Add estimate for remaining # of badges at a certain price

---

uber/configspec.ini
uber/templates/emails/reg_workflow/reg_notes.html
uber/templates/emails/reg_workflow/under_18_reminder.txt

Fixes part of https://github.com/magfest/ubersystem/issues/2618. While adding the prereg FAQ link, I noticed that we had a code_of_conduct_url config option that we never used anywhere, so I also added that. Reg_notes.html gets included in confirmation emails, so these changes should make it to every attendee.

Update reg_notes to use FAQ and CoC link and change under 18 reminder

---

uber/templates/emails/reg_workflow/badge_transfer.txt
uber/templates/emails/reg_workflow/group_confirmation.html
uber/templates/emails/reg_workflow/reg_notes.html
uber/templates/emails/reg_workflow/under_18_reminder.txt

Fixes https://github.com/magfest/ubersystem/issues/2618 (the rest of the way) by adding text about parental consent forms to more emails, ensuring that everyone will get notified that they need a consent form. Also slightly updates the text in some places.

Add parental consent form text to more emails

---

uber/templates/static_views/prereg_not_yet_open.html

This shows the link to the dealer registration page from the "Preregistration not yet open" page. We've never opened dealer reg earlier than prereg before, so it's never come up. With the changes, it looks like this:

Ensures dealer reg is visible from the "Prereg not yet open" page

---

uber/decorators.py

The prereg pages need the session expunged because of the weird disconnected model objects. I am going to merge this right now, because all of the preregistration pages will throw errors after anyone pays.

Turns out expunge_all was really important

---

uber/templates/preregistration/preregbase.html

Prevents PSEUDO_GROUP_BADGE from reverting to ATTENDEE_BADGE when an invalid form is submitted.
Steps to reproduce:
1. Navigate to the preregistration page (/uber/preregistration/form)
2. Select Group Badge
3. Fill out everything except date of birth
4. Submit the form
5. The page will refresh with a message saying "please fill out date of birth"
6. Note: everything LOOKS correct, i.e. the Group Badge is still selected
7. Fill out date of birth and click submit
8. On the confirmation page (/uber/preregistration/index), the preregistration will be listed as a regular attendee without the group badges
This also fixes a second issue where clicking "No Thanks" will revert a Group Badge to an Attendee Badge. Steps to reproduce:
1. Navigate to the preregistration page …

Fixes badge type reversion after submitting an invalid form

---

uber/models.py

The `PanelApplicant` class is not available in `globals()` at the time the resend action happens.

Fixes email resending for model objects from plugins other than uber

---

uber/templates/regform.html
uber/templates/static_views/legal_name.html

These changes make the legal name field look like this:
Fixes #2770

Fixes #2770: Makes legal name label less ambiguous

---

uber/configspec.ini

only supermag is going to want this set to non-zero, so this is a more sane default
look out for more PRs that add this as a puppet option

set default number of staff shirts to 0

---

uber/configspec.ini
uber/models.py
uber/tests/models/test_merch.py

- this was the original way we did it, but supermag is now different
- add a config option to control this
- magwest and maglabs need to give staff swag shirts, so we needed to make it configurable

add support for letting people with staff badges also be eligible for swag shirts

---

uber/config.py
uber/model_checks.py

Fixes https://github.com/magfest/ubersystem/issues/815. Uses a new config variable just in case other events want to override the set of allowed characters.

Add model_check to prevent badge printed names with special characters

---

uber/templates/regform.html

This is a thing that I personally find very annoying, so I am fixing it. The text wrapping algorithm breaks the label "Name as appears on Legal Photo ID" in different location based on whether or not it's bold. See screenshots for examples. 
This change simply prevents the line from breaking in the middle of the phrase "Legal Photo ID", thus preserving the break point whether or not it's bold.

Prevents the "Legal Photo ID" label on the prereg page from jumping around when it is bolded/unbolded

---

uber/automated_emails.py
uber/templates/emails/reg_workflow/attendee_confirmation.html
uber/templates/emails/reg_workflow/group_confirmation.html

Adds an automated email to attendees with free badges, and changes the attendee_confirmation template to accommodate that. Also adjusts the group confirmation email to go to group leaders if their groups are free (since they won't get an email otherwise). Finally, adds the hotel disclaimer to the group payment email, since it's the only email group leaders will get as confirmation of their registration. Fixes https://github.com/magfest/ubersystem/issues/2772. Fixes https://github.com/magfest/ubersystem/issues/1709. Fixes https://github.com/magfest/ubersystem/issues/1825.
Warning: Late-night coding. I probably missed something in testing.

Send confirmation emails to comped attendees

---

alembic/versions/4947b38a18b1_add_confirmed_column.py
uber/automated_emails.py
uber/models.py
uber/site_sections/preregistration.py
uber/templates/emails/reg_workflow/attendee_confirmation.html

Prevents emails from going out to placeholder badges long after they were confirmed by keeping track of when they were confirmed. Also updates the email text to reflect this -- we no longer show the disclaimer about "if you don't remember claiming a badge" to non-group-leaders. Reopens https://github.com/magfest/ubersystem/issues/1709.

Add 'confirmed' column for placeholder badge confirmations

---

uber/automated_emails.py
uber/automated_emails_server.py

This pull request does three things:
1. Checks that groups have assigned leader before attempting to send the group confirmation email
* This prevents an error when rendering the email template because it references `group.leader.age_group_conf`
* Further, it doesn't make sense to send the email to a non-leader group member, because it has specific instructions for the group leader
* Non-leader group members will receive emails anyway when they're badge is assigned
2. Uses group.leader_id to compare attendee to group leader
* This prevents an additional SQL query to pull up the leader's attendee record
3. Eagerly loads attendee.group relationship for automated emails
* This prevents an additional SQL query for each attendee in the system

Improve attendee/group AutomatedEmails

---

uber/config.py
uber/model_checks.py

For our currently running instances, several people already have invalid names, but they can no longer edit them. This change allows them to still save their form without a validation error they can't do anything about.

Only check for non-standard characters before the printed badge deadline

---

uber/model_checks.py

Fixes https://github.com/magfest/ubersystem/issues/2761. This isn't locked behind a special permission or anything since admins have little reason to go around changing people's printed badge names after the deadline. The field was already editable on the admin page, this just keeps them from running into an error.

Allow admins to change printed badge names

---

uber/templates/static_views/styles/main.css

Fixes height, border color, and inner box shadow to match all our other fields.

Fixes styling on the date field to match all the other fields

---

uber/models.py
uber/site_sections/preregistration.py

Fixes https://github.com/magfest/ubersystem/issues/2805 by making groups closer match how attendee's costs are calculated.

Stop using amount_extra in default_cost for groups

---

uber/custom_tags.py

Steps to reproduce issue:
1. Click Group Badge button
2. Change number of badges to 20
3. Click t-shirt supporter button
4. Fill out prereg form, except for t-shirt size
5. Click submit
6. Page will reload with error about missing t-shirt size
7. **Note**: the number of badges will be set to 8 (the default)

Fixes int_options() custom tag to select the right value whether it's given a string or an int

---

uber/automated_emails.py
uber/config.py
uber/configspec.ini

Ok, this adds an extra duration to prevent the hotel link from being sent out too early. I have hardcoded our desired duration in the `configspec.ini`, but we can puppetize it and fix the default value later. 
I just want to make sure this is deployed sometime this evening when the traffic dies down a bit, but before the hotel request window elapses.
We've pushed the hotel email date back to August 17th at 8pm, and I **really** don't want the email going out early.

Prevents admins from accidentally sending the hotel link too early

---

uber/decorators.py
uber/site_sections/preregistration.py
uber/utils.py

This starts with and probably replaces Vicki's PR: https://github.com/magfest/ubersystem/pull/2810
This heavily armors up the logging around anything to do with attendee payments, to a paranoid insane level. Spam as much info as we can into the logs so if there are ever issues, we should be able to better see what's going on
Some of this is redundant with the DB logging we're also doing, but, could be helpful during audit events to understand what really happened and fix any timing-dependent issues once and for all when coupled with nginx and cherrypy access/error logs.
One thing this doesn't do is fix the end-user seeing a non-nice error message if they visit ```prereg_payment``` with a GET request.  You can see there's a check for POST in here, but it comes too late and by that point …

Armor up prereg

---

uber/server.py

two unrelated parts:
1) cleanup 404 handling to be more consistent for static_views/ related section, fix harmless but ugly TupleError/IndexError on default static_views/ page
2) display a nicer looking page to end user without stacktrace for 404 errors across entire app
@RobRuana could you give my ```@classmethod``` usage a quick look here to make sure it's sane
I wanted to get this in here to 1) reduce the signal to noise ratio in our slack error reporting (which currently pukes verbosely whenever search bots trip on a 404 on static_views/) and 2) make the errors less public-facing to end users

handle 404 errors better

---

uber/templates/macros.html

This isn't 100% necessary, it's just a small refactor to pull out some of the common elements from our form macros into a single macro.
I'm not committed on this change, it was partly an exercise to see if we could combine form_checkgroup and checkgroup into one macro. Now that I've done this refactor I don't think it'd help much -- even if we combined them, we'd still have to call checkgroup with like eighteen different flags.

Add "form group scaffolding" to form macros

---

uber/templates/accounts/reset.html
uber/templates/dept_checklist/form.html
uber/templates/groups/index.html
uber/templates/regform.html
uber/templates/registration/form.html

The great Jinja merge strikes again!
Django's `default()` filter works slightly differently from Jinja2's `default()` filter. Jinja2's `default()` filter only considers whether the variable is defined, not whether it is Truthy or Falsey. You can make Jinja2's `default()` filter work the same way as Django's by passing the second parameter as `boolean=True`.
See the Jinja2 source code [here](https://github.com/pallets/jinja/blob/8a49e066af3d88d1edb34aa1680b668c959dfcf7/jinja2/filters.py#L284)
Fixes #2834

Fixes #2834: Changes Jinja2's default() filter to use falsey/truthy values instead of undef

---

uber/site_sections/summary.py

A "minor badges" report was added at some point, but only MAGFest Prime has a "Minor" badge type. For other events, the related report was causing a 500 error. The 'best' fix would be to use MAGPrime's event-specific repo to override/add the minor badge report, but this isn't yet supported by Sideboard -- plugins can only _add_ site sections, not modify them. Since this feature is needed quickly, this clumsy-ish fix will have to do for now.

Fix 500 error for non-Prime personalized badge reports

---

uber/automated_emails_server.py
uber/configspec.ini

We have a department head checklist email that's meant to be sent after the event, but refuses to send any emails because we're in post_con mode now. This enables all the emails during post con mode.

Make Dept Head Checklist emails sendable in POST_CON mode

---

uber/site_sections/preregistration.py
uber/templates/preregistration/confirm.html

This PR renames the `invalidate` function in `preregistration.py` to `abandon_badge`. This function will now additionally handle the case where an attendee is part of a group. In this case, the badge will be deleted and removed from the group instead of being marked as invalid. The conditions for displaying the "I'm not coming" button have also been changed to exclude any attendee who is the leader of a group.
I have some concerns about the changes so far:
1. After the user deletes their group badge, it does not appear that they can use `invalid_badge`, so they are instead being sent to `not_found`. Is there a more appropriate destination to use here?
2. There are two different conditions being replaced by `can_abandon` in `confirm.html`. One condition uses `and`, and the other uses `or`. …

Fix #1669, delete badge when attendee abandons their group

---

uber/templates/regform.html

Are we happy with the text "Add new"?
Fixes #431

Fix #431, show "(Add new)" when user enters a new affiliate

---

uber/templates/preregistration/index.html

This is a minor bug that was found right before registration opened. Our badge cost now takes age_discounts into account by default, which made this text display incorrectly in some cases. It was even telling people that there was a $0 discount for attendees 6 to 13!

Display age discounts correctly

---

uber/config.py
uber/configspec.ini
uber/model_checks.py
uber/tests/models/test_badge_funcs.py
uber/tests/models/test_config.py

This PR does three major things:
1. Improve various bits of documentation in configspec.ini
2. Adds a SUPPORTER_BADGE_DEADLINE config option that defaults to the same date as SUPPORTER_DEADLINE
3. Adds a get_printed_badge_deadline_by_type function to our config that returns the deadlines that work for MAGFest.
This codifies a kinda-hacky change we made last year to allow supporter badge names to be editable after the printed_badge_deadline while allowing other events to easily modify the business logic involved. I wanted to make it less hacky this year.

Allow multiple printed_badge_deadlines

---

requirements.txt
uber/model_checks.py
uber/tests/models/test_attendee.py

Fixes #1578.
This PR replaces the regex in `model_checks.py` for phone number validation with [this Python port](https://github.com/daviddrysdale/python-phonenumbers) of [Google's phone numbers library](https://github.com/googlei18n/libphonenumber). `phonenumbers` appears to already be accessible in this repo.
Input is parsed as a US phone number, unless a country code is provided. This library should handle international numbers correctly as long as the country code is known. Certain non-digit characters are acceptable, allowing for input like `(703) 123-4567`.
Note that I am using `is_possible_number` here instead of `is_valid_number`. The former only checks that the input is *like* a phone number (correct number of digits). The latter requires that the number is *valid* (a US number …

Fix #1578, use phonenumbers library for validation

---

uber/models.py
uber/tests/models/test_utils.py
uber/utils.py

Adds a utility function to calculate a person's age given a birthdate and effective date. This doesn't return a real timespan, so this function shouldn't be used for anything other than finding the age of a person.
I used TDD to implement this function. First, I wrote unit tests to cover a variety of cases that I made up on the spot Then, with the old age code, I ran the tests and found that some of them failed. I've reproduced those results below. Finally, I wrote the new function `get_age_from_birthday` and ran the tests again.
Old code: `(day - self.birthdate).days // 365.2425`
Test failures:
```
get_age_from_birthday(datetime.date(1997, 1, 4), datetime.date(2018, 1, 4))
Expected 21 years, got 20
get_age_from_birthday(datetime.date(2000, 7, 31), datetime.date(2010, 7, 31))
Expected 10 …
```

Fix #1125, use accurate age calculation

---

uber/site_sections/registration.py
uber/templates/registration/reg_take_report.html

This should fix the query used by reg_take_report. Also, I took the liberty of including reg stations in the dropdown if they are associated with one or more sales, but no attendees. 
Fixes #1778
It looks like the table on this page is trying to access css class `list` defined in `uber/static/styles/styles.css`, but that file is not being loaded here. As a result, the report looks like a squishy mess. Should the appearance of this table be dealt with in this PR, or should I make a new one?

Fix #1778, make reg_take_report work again

---

uber/static/styles/styles.css
uber/templates/macros.html
uber/templates/static_views/styles/main.css

This PR restores some missing CSS rules by moving some classes from `styles.css`, a file that currently has no references, into `main.css`, a file which is included in many places. Presumably, some event took place which resulted in `styles.css` being removed from many pages.
The reason only some of the CSS was moved is because not all of `styles.css` should be restored at this point. For example, the `{% for attendee in charge.attendees %}` table on `preregistration\index` has since been updated with new css. Applying the old rules from `styles.css` does not look good.
However, some places appear to have NOT been updated with new css. This includes the `reg_take_report` and `registration\comments` tables, and also the `macros.nav_menu` section on many pages (registration, groups, jobs). …

Restore old css that was not replaced

---

test-defaults.ini
uber/configspec.ini

I'd prefer to do this in production-config, but this particular variable is not puppetized. Also, we're only running one event at the moment, so we don't have to worry about affecting other events.

Updates transferable_badge_types to disable badge transfers

---

uber/site_sections/preregistration.py

Fixes #2875: Adds a default argument to the message parameter of the not_found() method

---

uber/templates/emails/reg_workflow/group_confirmation.html

There are very rare circumstances where the group management link isn't displayed in a group confirmation email. This pull request adds the link to the end of the email, no matter what.

Fixes #2871: Adds the group management link to the end of the group confirmation email

---

uber/site_sections/preregistration.py

This doesn't take into account badges that actually can't be transferred, and is a temporary fix while all badge transfers have been disabled. This PR will need to be reverted once badge transfers have been reenabled.

Add a more descriptive error message for badge_transfer

---

uber/automated_emails_server.py

This is a specific request from Ashley, our volunteer coordinator! She wants to be able to give dept heads a little more time to finish up checklist items.

Makes dept checklist email available for sending earlier

---

uber/automated_emails.py
uber/templates/emails/placeholders/dealer.txt
uber/templates/emails/placeholders/guest.txt
uber/templates/emails/placeholders/imported_volunteer.txt
uber/templates/emails/placeholders/panelist.txt
uber/templates/emails/placeholders/regular.txt
uber/templates/emails/placeholders/reminder.txt
uber/templates/emails/placeholders/volunteer.txt

Fixes https://github.com/magfest/ubersystem/issues/2904 by first removing the requirement for placeholder badges to have first and last names, and then modifying all placeholder email templates to only try to print the first name if it in fact exists.

Stop requiring first and last name for placeholder emails

---

alembic/versions/d3da548acd2e_drops_requested_any_dept_column.py
uber/automated_emails_server.py
uber/models/attendee.py
uber/models/department.py
uber/site_sections/departments.py
uber/templates/departments/requests.html
uber/tests/models/test_attendee.py

This pull request reverts the `requested_any_dept` boolean column in favor of using a nullable `department_id` column on the `dept_membership_request` table to indicate a request to help anywhere.
It turns out that a nullable `department_id` column results in far simpler and far more efficient SQL queries when we're trying to get all the unassigned attendees that want to volunteer for a department.
I don't feel bad about spending the time to try the other approach, because I wouldn't have known the technical pros/cons of both designs until trying them :smile:

Reverts requested_any_dept design to use nullable department_id column on dept_membership_request table

---

uber/models/attendee.py
uber/site_sections/registration.py
uber/tests/site_sections/test_registration.py

Added a test to reproduce the bug, and a `_skip_badge_shift_on_delete` flag as described in the comments here: https://github.com/magfest/ubersystem/issues/2823#issuecomment-341485619.
The fix is super short (2 added lines, 1 modified line). Although, I am happy to consider alternative solutions 😄

Fixes #2823: Prevents duplicate badge num error with a _skip_badge_shift_on_delete flag

---

uber/models/__init__.py
uber/models/attendee.py
uber/site_sections/summary.py
uber/templates/summary/departments.html

Fixes this error:
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 330, in with_timing
return func(*args, **kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 345, in with_session …
```

Fixes 500 error in /summary/departments

---

uber/config.py
uber/templates/regform.html

The issue here is that `c.AFTER_SUPPORTER_DEADLINE` has already elapsed, so staffers could no longer change their printed badge name. We want to allow them to change their printed badge name up until `c.PRINTED_BADGE_DEADLINE`.

Allows staffers to change their printed badge name up until c.PRINTED_BADGE_DEADLINE

---

uber/config.py
uber/custom_tags.py
uber/site_sections/accounts.py
uber/site_sections/signups.py
uber/utils.py

- in certain multiple login situations, we were overwriting CSRF tokens
- if you were to go back to other tabs or forms, these would have
caused our CSRF trips to incorrectly tripped
- now we generate the token one time per-session and never overwrite it
- fixes #2934 for certain
I think this might really fix pretty much all of the sporadic CSRF errors we see, more discussion to come in #2919 
#2934 has all the details on why this PR does what it does

fix some/all CSRF token errors

---

uber/server.py

Add new get_verbose_request_context() and log_with_verbose_context(msg)
These allow you to obtain detailed info about the executing request without needing to be in an exception
This is super-useful for armor'ing up chunks of code with as much info about the request/context as possible, without having to be in the context of an exception handler.
(Was originally using this for the CSRF fixing but turned out not to be necessary)
Prints out stuff like:
```Request: POST /uber/registration/form HTTP/1.0
Current admin user is: Test Developer
Request Params:
group_opt: 
assigned_depts_ids: ['', 'ce643801-b1dd-4116-aff5-7eab3ed3eb99']
save: save
found_how: 
first_name: Test
last_name: Developer
got_merch: 0
csrf_token: 8423de5e2e8e4b50b6a50353a1964520
requested_hotel_info: 0
extra_donation: …
```

refactor verbose logging

---

uber/templates/emails/shifts/dept_checklist.txt

Now looks like:
> As a department head for Arcade, Arcade_Crew, Attendee Services, Autographs, and Music we need some information from you about
Instead of:
> As a department head for ArcadeArcade_CrewAttendee ServicesAutographsMusic we need some information from you about

Fixes department list for dept checklist emails

---

uber/server.py
uber/tests/test_exception_handler.py

- convert everything to String type first before doing anything with
- this works fine even with objects that don't convert to string
- will return something like ''<object Part at &ffffff>'
- add some unit tests and mock data to armor this up some more
fixes #2945 
this is tested well in unit tests, but I couldn't run it locally due to an issue with running the DB migrations locally.  should be OK as the unit tests now run this code OK, but, maybe worth a quick test after deploying.
Rob, merge whenever you like

fix error when exception handler context code deals with attachments

---

uber/automated_emails_server.py

- would say 'error while sending email' when it really means
'error while either determining if to send this email or sending it'
- separated these two error states out (so, say, we don't freak people out thinking uber is trying to send thousands of emails when our error handler freaks out and spams us for a while during a deploy)
This one I couldn't test at all due to DB migrations stuff on local box that I'm fixing.  definitely worth a run locally to make sure it's OK before merging.

provide more accurate error handling in email thread

---

uber/config.py
uber/site_sections/departments.py
uber/templates/base.html
uber/templates/departments/form.html

Adds some improvements to departments requested during MAGCon

---

uber/models/__init__.py
uber/tests/models/test_attendee.py

Attendee selection is now based on badge status, in the following order:
- Completed
- New
- Refunded
- Deferred
- Any other status
- Invalid is never returned

Fixes #2969: Session.lookup_attendee() is a little smarter about which attendee it returns

---

uber/automated_emails_server.py
uber/templates/emails/daily_checks/pending_emails.html

We were originally sending this report just to STOPs, which is fine but individual departments are currently unaware that they have pending emails on behalf of their department.
Now, in addition to sending to STOPs, we send a subset of the report the sending email address of the email category. (i.e. we send music@magfest.org info about the music dept's pending emails that need approval)
For the STOPs report, we now group by sender to make it easier to read.
Fixes #2623 for real, phase 2.  Thanks @kitsuta for the great idea to do this, sorry it took a while to get around to :)
Here's an example of the email that would be sent to STOPs which includes all categories, grouped by sender:
Here's an example of the smaller report sent to just one deparment (like music, guests, etc)

send pending email report to individual departments

---

.travis.yml

The `prctl` library added in this [pull request](https://github.com/magfest/sideboard/pull/93) requires new dependencies in each of our `.travis.yml` files to get the builds working again.

Fixes missing libcap development headers on travis builds

---

uber/templates/macros.html
uber/templates/preregistration/stripeForm.html
uber/templates/summary/food_eligible.xml
uber/tests/test_templates.py

Also adds some paranoid whitespace in some template tags due to the new aggressive whitespace stripping.
For example, with the new aggressive whitespace stripping, the following:
```
{% if not label and title %}title="{{ title }}"{% endif %}
{% if is_checked %}checked{% endif %} />
```
would be rendered as:
```
title="The title"checked />
```
With no whitespace before `checked`. I'm pretty sure most browsers will render that just fine, but I _think_ it violates the HTML spec.

Fixes template tests

---

uber/site_sections/dept_checklist.py
uber/templates/dept_checklist/item.html

Super simple feature. Adds a huge bcc mailto link to checklist items for delinquent dept heads.

Fixes #2991: Adds a link to checklist items to email delinquent dept heads

---

uber/models/attendee.py

Allows staffers to sign up for shifts after the shirt deadline if they haven't chosen a second shirt preference.

Fixes broken staff checklist

---

uber/decorators.py
uber/menu.py
uber/site_sections/registration.py

Reverts magfest/ubersystem#2998
This pull request didn't really help, because every reg page has a database feed available in the history 😢

Revert "Fixes #2995, Related to #2909: Restricts database feed to ACCOUNTS permissions"

---

uber/migration.py

lol, @EliAndrewC, this bug is hilarious!
Maybe I should rename the inner recursive function from `_get_plugin_head_revision()` to `_do_get_plugin_head_revision()` or `_recursive_get_plugin_head_revision()`?

Fixes #2911: Makes migration choose correct downrevision

---

uber/models/attendee.py

There's been confusion about the status of the department head ribbon -- we may want to later remove it as a property, but for now we're just automatically adding it to anyone who has the dept_head status. We talked about this a little bit and decided that it's easier to reject a ribbon if you don't want it when you pick up your badge than to ask for a ribbon that's not recorded in the system, so even in the rare case that a department head doesn't want the ribbon, it's okay for the system to force them to have one.
This replaces https://github.com/magfest/ubersystem/pull/2994. It's not been tested yet, it's a simple enough code change but I'll try to get it tested tonight.

Always give department heads a dept_head_ribbon

---

uber/site_sections/preregistration.py

~~Attempts to resolve https://github.com/magfest/ubersystem/issues/3019 by applying ALL the parameters, so that the restricted parameters from the old badge (like base_badge_price) actually get moved over.~~
This code was working just fine, but the way it did things was convoluted enough that it made me think it was broken. This PR is now largely an aesthetic change to make the code's intentions clearer.

Clarify code around assigning new group badges

---

uber/config.py
uber/models/__init__.py
uber/models/department.py
uber/site_sections/jobs.py
uber/site_sections/signups.py
uber/templates/signups/shifts.html

**NOTE**: The new verbiage will only be displayed if there are public shifts shown that wouldn't otherwise be visible to the volunteer.

Adds shift signup ui explaining public shifts

---

uber/migration.py

Just noticed that the panels plugin was ALSO having the same issue with choosing the correct downrevision. Turns out we were not correctly calculating `other_plugins` in this line:
```python
other_plugins = set(plugin_dirs.keys()).difference({plugin_name})
```
What we _really_ want is all the other plugins _not including the ones this plugin has branched from_. Since `panels` was branched from `uber`, we don't want `uber` included in `other_plugins`.
I don't know if that explanation makes sense 😅

Fixes #2911: Correctly calculates downrevision for plugins branched from uber

---

uber/menu.py
uber/site_sections/registration.py

I tried to do this earlier, but I rushed it out and immediately broke the preregistration page (see here https://github.com/magfest/ubersystem/pull/2998).
Now that `renderable_override()` actually works and doesn't disrupt the existing codebase (see here https://github.com/magfest/ubersystem/pull/3049), I wanna restrict access to the feed of database changes.

 I'd like to restrict access to the feed of database changes

---

uber/site_sections/groups.py

This should reset the price of all group badges to the initial attendee price, for all groups that were denied a spot in the Marketplace.

Reset denied group badge price to opening price

---

uber/tests/test_api.py
uber/utils.py

We keep seeing the following error in production. This happens if you load the confirmation page, then click "Clear All Browsing Data" in your browser, then click the "Update My Info" button:
```
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 382, in with_timing
return func(*args, **kwargs)
File …
```

Fixes csrf_token key error

---

uber/models/__init__.py

@kitsuta reminded me at https://github.com/magfest/panels/pull/138#discussion_r157947517 that ``session.lookup_attendee`` is a thing and noted that it should probably be using ``Attendee.normalized_email``.  I've just made this change and tested it locally.

session.lookup_attendee now uses Attendee.normalized_email

---

uber/api.py
uber/site_sections/api.py
uber/templates/preregistration/confirm.html
uber/templates/regform.html
uber/tests/models/test_promo_code.py
uber/tests/models/test_session.py
uber/tests/site_sections/test_preregistration.py
uber/tests/site_sections/test_registration.py
uber/tests/test_api.py

Required by https://github.com/magfest/panels/pull/140
This pull request has a bunch of minor unrelated changes. The following line in `confirm.html` is the only thing required by attractions:
```
{% block panel_top %}{% endblock %}
```

Adds support for attractions tab bar at the top of the prereg confirm form

---

uber/templates/registration/check_in_form_base.html
uber/templates/registration/new_base.html

In order to decrypt badge number barcodes, we first have to accept them in the input field.

Accept badge numbers at checkin besides only numerals

---

uber/templates/emails/dealers/badge_converted.html

Adds emphasized line to clarify recipients will not be a dealer/vendor.
Doing this now so we don't forget next year!

Updated converted e-mail

---

uber/models/attendee.py
uber/site_sections/preregistration.py
uber/templates/preregistration/attendee_donation_form.html
uber/templates/preregistration/confirm.html

Fixes https://github.com/magfest/ubersystem/issues/3082. We had an "I'm not coming" button on the confirmation page, but we were redirecting unpaid attendees to the donation form, thus preventing unpaid attendees outside of a group from using that button. This adds the button to the donation form and converts the prerequisites involved into a property.

Allow unpaid attendees to decline their badges

---

uber/templates/registration/new_base.html

Fixes https://github.com/magfest/ubersystem/issues/3038. We didn't need a full page refresh -- we just needed to add the badge_num field to the function that un-disabled the check-in button.

Remove 'disabled' attr from badge_num field when at-door is paid

---

uber/configspec.ini
uber/templates/base.html
uber/templates/registration/index_base.html
uber/templates/registration/merch.html
uber/templates/registration/new_base.html

Adds the ability to use barcode scanners with automatic decryption on the registration pages. This is hidden behind a new 'reg_uses_barcodes' variable, just in case something goes horribly wrong at-con and we need to turn this off for registration.
Fixes https://github.com/magfest/ubersystem/issues/2867.

Add barcode scanning detection to registration pages

---

uber/models/__init__.py
uber/site_sections/registration.py
uber/templates/registration/watchlist.html

Fixes https://github.com/magfest/ubersystem/issues/3066. This was meant to be a backend-only change to be merged with https://github.com/magfest/ubersystem/pull/3071, but then I ended up going a different direction with the interface. Oops.
This is what this change looks like for an attendee with unconfirmed entries: ![image](https://user-images.githubusercontent.com/7198215/34461819-1bc49dc0-ee03-11e7-8547-c3a97ff00197.png)
If you click any of the blue "Confirm" buttons, this pops up: 
If you confirm the entry, the page then looks like this: ![image](https://user-images.githubusercontent.com/7198215/34461806-e8f5a60a-ee02-11e7-8b3b-8394df10587e.png)
This also makes `guess_attendee_watchentry` able to return active or inactive entries, so that we can display them on this page.

Clean up WatchList page for attendees

---

uber/templates/registration/watchlist_entries.html

Fixes https://github.com/magfest/ubersystem/issues/2942. DataTables can't handle searching input forms very well, so we explicitly tell it our search terms in the `<td>` tags instead.

Fix Watchlist Entries searching

---

alembic/versions/23193b41cfea_added_got_staff_merch.py
uber/config.py
uber/configspec.ini
uber/models/attendee.py
uber/site_sections/groups.py
uber/site_sections/registration.py
uber/templates/registration/form.html
uber/templates/registration/merch.html
uber/tests/models/test_merch.py

This implements everything in #3052 
- There are now two buttons on the Merch page, one for checking for Merch and the other for checking for Staff Merch and the "got merch" states are tracked separately for each.
- This behavior is configurable so other events with a single merch location can turn it off and revert to the original behavior of all merch being combined.
- These two merch sections now reflect the staffer preference given for 2 staff shirts vs 1 event shirt.
- Donation tiers can now be expanded into their component items with a new optional config section called ``[donation_tier_items]``.  (We already have a ``[donation_tier_descriptions]`` section, but it doesn't quite do what we need.)
I still need to make additional PRs in the ``ubersystem-puppet`` and …

split out merch and staff merch

---

uber/config.py
uber/configspec.ini

Requested by registration so they can turn on at-con mode without needing payment stations set up. We do this instead of just changing the door_payment_method opts because it is impossible to take away enum options via puppet.

Add only_prepay_at_door option

---

uber/site_sections/jobs.py
uber/templates/jobs/staffers.html

Several departments have a lot of volunteers assigned to them who don't actually take shifts in that department. We now have a link to only email staffers with shifts in a department, so department heads can send better-targeted emails.

Add a link to email volunteers with shifts in a dept

---

uber/templates/registration/pay.html

We were removing the dropdown options for cash and pay-at-desk, but then bringing attendees to a page that let them select those anyway! This fixes that.

Remove 'fallback' options for at-door if prepay only is set

---

uber/site_sections/registration.py

Note: we also seem to allow changing someone's badge number to something outside the valid range, but I wanted to just fix the checkin side of this, since that's where it's really problematic.

added check for handing someone a badge of the wrong type when checking them in

---

uber/templates/registration/new_base.html

This page is loading super slowly with a lot of attendees, up to 5 minutes. It's because the stripe form is being rendered over and over. Reg can't possibly need the Stripe button that badly.

Remove Stripe forms from Recent At-Door Registrations page

---

alembic/versions/c49ddb5a4845_added_temporary_got_swadge_column.py
uber/config.py
uber/models/attendee.py
uber/site_sections/registration.py
uber/templates/registration/merch.html

Our swadges are late!  But we now have a bunch of people who have already received merch without the swadge.  As a weird on-site fix, I'm temporarily adding swadge logic into the core ``uber`` plugin:
1) People who have already received their merch are marked as not having received their swadge.
2) Until the swadges arrive, instead of the "Give Merch" button, we want "Give Merch Without Swadge" and "Give Merch Including Swadge" buttons.
3) After the "Give Merch With Swadge" button has been pressed for the first time, we want to revert to the single "Give Merch" button, which is assumed to include the Swadge because those have arrived.
4) People who have their merch checked after they've already received merch but NOT received a swadge will show a message allowing you to give them just …

added special swadge handling
